config {
  type: "operations",
  dependencies: ["create_all_table_raw_mastersku"],
  tags: [databuffet.TAG_INITIAL],
}


DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.brand`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.category`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product_category`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product_detail`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product_group`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product_group_cost_group`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.vendor`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.unit`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product_status`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_MASTERSKU}.product_admin_status`;
