config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_CIS360,
    dependencies: ["validated_schema_cis360"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["id"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_CIS360
    const table_id = name()
    const pk_key = ["id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(id) AS STRING), '') as id,
    NULLIF(CAST(TRIM(customer_profile_id) AS STRING), '') as customer_profile_id,
    CAST(address_type_id as INT64) as address_type_id,
    CAST(platform_id as INT64) as platform_id,
    NULLIF(CAST(TRIM(contact_name) AS STRING), '') as contact_name,
    NULLIF(CAST(TRIM(contact_phone_number) AS STRING), '') as contact_phone_number,
    NULLIF(CAST(TRIM(contact_email) AS STRING), '') as contact_email,
    NULLIF(CAST(TRIM(address_detail) AS STRING), '') as address_detail,
    NULLIF(CAST(TRIM(address_name) AS STRING), '') as address_name,
    CAST(branch as INT64) as branch,
    CAST(tax_invoice_juristic_type as INT64) as tax_invoice_juristic_type,
    NULLIF(CAST(TRIM(tax_invoice_juristic_name) AS STRING), '') as tax_invoice_juristic_name,
    NULLIF(CAST(TRIM(tax_invoice_type) AS STRING), '') as tax_invoice_type,
    CAST(tax_invoice_customer_type as INT64) as tax_invoice_customer_type,
    NULLIF(CAST(TRIM(tax_invoice_tax_id) AS STRING), '') as tax_invoice_tax_id,
    NULLIF(CAST(TRIM(parent) AS STRING), '') as parent,
    NULLIF(CAST(TRIM(address_info) AS STRING), '') as address_info,
    NULLIF(CAST(TRIM(street) AS STRING), '') as street,
    CAST(country_id as INT64) as country_id,
    CAST(province_id as INT64) as province_id,
    CAST(district_id as INT64) as district_id,
    CAST(sub_district_id as INT64) as sub_district_id,
    CAST(zipcode_id as INT64) as zipcode_id,
    NULLIF(CAST(TRIM(country_name) AS STRING), '') as country_name,
    NULLIF(CAST(TRIM(province_name) AS STRING), '') as province_name,
    NULLIF(CAST(TRIM(district_name) AS STRING), '') as district_name,
    NULLIF(CAST(TRIM(sub_district_name) AS STRING), '') as sub_district_name,
    NULLIF(CAST(TRIM(zipcode_name) AS STRING), '') as zipcode_name,
    NULLIF(CAST(TRIM(latitude) AS STRING), '') as latitude,
    NULLIF(CAST(TRIM(longitude) AS STRING), '') as longitude,
    CAST(active_status as BOOL) as active_status,
    CAST(is_default as BOOL) as is_default,
    CAST(is_kyc_document as BOOL) as is_kyc_document,
    CAST(is_delete as BOOL) as is_delete,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(create_date, 1, 19)) as create_date,
    NULLIF(CAST(TRIM(create_by) AS STRING), '') as create_by,
    NULLIF(CAST(TRIM(create_by_platform) AS STRING), '') as create_by_platform,
    NULLIF(CAST(TRIM(update_by_platform) AS STRING), '') as update_by_platform,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(update_date, 1, 19)) as update_date,
    NULLIF(CAST(TRIM(update_by) AS STRING), '') AS update_by,
    PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
