config {
    type: "incremental",
    schema: databuffet.VALIDATED_CIS360,
    dependencies: ["validated_schema_cis360", "create_all_table_raw_cis360"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["id"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["id"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_CIS360,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    ${databuffet.cleanString('id')} as id,
    ${databuffet.cleanString('customer_profile_id')} as customer_profile_id,
    ${databuffet.cleanString('related_customer_profile_id')} as related_customer_profile_id,
    ${databuffet.castInt64('relationship_type_id')} as relationship_type_id,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(create_relationship_date, 1, 19)) as create_relationship_date,
    ${databuffet.cleanString('customer_to_customer_role')} as customer_to_customer_role,
    CAST(is_owner as BOOL) as is_owner,
    CAST(is_delete as BOOL) as is_delete,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(create_date, 1, 19)) as create_date,
    ${databuffet.cleanString('create_by')} as create_by,
    ${databuffet.cleanString('create_by_platform')} as create_by_platform,
    ${databuffet.cleanString('update_by_platform')} as update_by_platform,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(update_date, 1, 19)) as update_date,
    ${databuffet.cleanString('update_by')} AS update_by,
    ${databuffet.parseAsatDate()} AS asatdate,

FROM
  `${sourceTableRef}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
