config {
  type: "operations",
  dependencies: ["drop_all_tables_validated_saleout_mdt"],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}` OPTIONS(location="${databuffet.REGION}");
------------------------------------- SCHEMA --------------------------------------


----------------------------------- INCREMENTAL ---------------------------------------
------------------------------------- BT ----------------------------------------------
-- Table: sale_by_branch_detail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.sale_by_branch_detail`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.sale_by_branch_detail`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/sale_by_branch_detail/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/sale_by_branch_detail/'
);

-- Table: sale_by_branch_mch3
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.sale_by_branch_mch3`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.sale_by_branch_mch3`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/sale_by_branch_mch3/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/sale_by_branch_mch3/'
);

-- Table: sales_by_branch
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.sales_by_branch`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.sales_by_branch`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/sales_by_branch/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/sales_by_branch/'
);

-- Table: stock_aging
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.stock_aging`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.stock_aging`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/stock_aging/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/stock_aging/'
);

-- Table: stock_by_branch
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.stock_by_branch`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.stock_by_branch`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/stock_by_branch/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/stock_by_branch/'
);

-- Table: turnover_brand
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.turnover_brand`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.turnover_brand`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/turnover_brand/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/turnover_brand/'
);

-- Table: turnover
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.turnover`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.turnover`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/turnover/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/bt/turnover/'
);
------------------------------------- BT ----------------------------------------------

------------------------------------- GB ----------------------------------------------
-- Table: saleout_mdt_gb
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.saleout_gb`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.saleout_gb`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/gb/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/gb/'
);
------------------------------------- GB ----------------------------------------------

------------------------------------- HP ----------------------------------------------
-- Table: saleout_mdt_hp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.saleout_hp`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.saleout_hp`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/hp/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/hp/'
);
------------------------------------- HP ----------------------------------------------

------------------------------------- TW ----------------------------------------------
-- Table: reportsalesubscription
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.report_sale_subscription`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.report_sale_subscription`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/tw/reportsalesubscription/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_SALEOUT_MDT}/tw/reportsalesubscription/'
);
------------------------------------- TW ----------------------------------------------
----------------------------------- INCREMENTAL ---------------------------------------