config {
  type: "operations",
  dependencies: ["drop_all_tables_validated_cis360"],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}` OPTIONS(location="${databuffet.REGION}");
------------------------------------- SCHEMA --------------------------------------


----------------------------------- INCREMENTAL ------------------------------------
-- Table : juristic_profile
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.juristic_profile`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.juristic_profile`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/juristic_profile/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/juristic_profile/'
);

-- Table : customer_profile_nature_business
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_nature_business`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_nature_business`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_nature_business/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_nature_business/'
);

-- Table : customer_profile
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile/'
);

-- Table : customer_profile_role_business
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_role_business`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_role_business`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_role_business/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_role_business/'
);

-- Table : customer_address
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_address`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_address`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_address/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_address/'
);

-- Table : customer_profile_tag
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_tag`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_tag`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_tag/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_tag/'
);

-- Table : customer_profile_category
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_category`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_category`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_category/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_category/'
);

-- Table : customer_to_platform
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_to_platform`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_to_platform`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_to_platform/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_to_platform/'
);

-- Table : customer_to_transaction
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_to_transaction`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_to_transaction`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_to_transaction/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_to_transaction/'
);

-- Table : customer_to_customer
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_to_customer`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_to_customer`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_to_customer/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_to_customer/'
);

-- Table : role_business
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.role_business`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.role_business`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/role_business/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/role_business/'
);

-- Table : nature_business
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.nature_business`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.nature_business`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/nature_business/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/nature_business/'
);

-- Table : address_type
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.address_type`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.address_type`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/address_type/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/address_type/'
);

-- Table : organize_type
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.organize_type`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.organize_type`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/organize_type/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/organize_type/'
);

-- Table : juristic_type
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.juristic_type`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.juristic_type`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/juristic_type/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/juristic_type/'
);

-- Table : customer_status
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_status`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_status`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_status/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_status/'
);

-- Table : customer_profile_type
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_type`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_profile_type`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_type/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_profile_type/'
);

-- Table : customer_type
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_type`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.customer_type`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_type/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/customer_type/'
);

-- Table : category
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.category`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.category`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/category/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/category/'
);

-- Table : zipcode
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.zipcode`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.zipcode`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/zipcode/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/zipcode/'
);

-- Table : sub_district
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.sub_district`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.sub_district`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/sub_district/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/sub_district/'
);

-- Table : district
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.district`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.district`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/district/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/district/'
);

-- Table : province
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.province`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.province`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/province/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/province/'
);

-- Table : country
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.country`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.country`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/country/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/country/'
);

-- Table : prefix
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.prefix`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_CIS360}.prefix`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/prefix/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_CIS360}/prefix/'
);
----------------------------------- INCREMENTAL ------------------------------------