config {
  type: "operations",
  dependencies: ["create_all_table_raw_cis360"],
  tags: [databuffet.TAG_INITIAL],
}


DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.juristic_profile`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_profile_nature_business`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_profile`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_profile_role_business`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_address`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_profile_tag`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_profile_category`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_to_platform`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_to_transaction`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_to_customer`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.role_business`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.nature_business`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.address_type`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.organize_type`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.juristic_type`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_status`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_profile_type`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.customer_type`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.category`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.zipcode`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.sub_district`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.district`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.province`;
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_CIS360}.country`;