config {
    type: "incremental",
    schema: databuffet.CURATED_MASTERSKU,
    dependencies: [],
    tags: [databuffet.TAG_CURATED],
    uniqueKey: ["prdSku"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["prdSku", "prdUniversalBarcode", "prdVendorId", "prdBrandId"],
        updatePartitionFilter: "asatdate >= CURRENT_DATE('Asia/Bangkok')-7"
    }
}

SELECT
  prd_id as prdId,
  prd_sku as prdSku,
  prd_description as prdDescription,
  prd_d365_sku as prdD365Sku,
  prd_item_text as prdItemText,
  prd_item_code as prdItemCode,
  prd_stopped_sate as prdStoppedSate,
  prd_made_to_order as prdMadeToOrder,
  prd_sale_unite as prdSaleUnite,
  prd_tag as prdTag,
  prd_universal_barcode as prdUniversalBarcode,
  prd_internal_barcode as prdInternalBarcode,
  prd_cat_id as prdCatId,
  prd_filter1 as prdFilter1,
  prd_filter2 as prdFilter2,
  prd_brand_id as prdBrandId,
  prd_size as prdSize,
  prd_line as prdLine,
  prd_color as prdColorTH,
  prd_color as prdColorEN,
  prd_model as prdModel,
  prd_dimension1 as prdDimension1,
  prd_dimension2 as prdDimension2,
  prd_dimension3 as prdDimension3,
  prd_dimension4 as prdDimension4,
  prd_vendor_id as prdVendorId,
  prd_is_active as prdIsActive,
  prd_is_use as prdIsUse,
  prd_created_date as prdCreatedDate,
  prd_created_by as prdCreatedBy,
  prd_updated_date as prdUpdatedDate,
  prd_updated_by as prdUpdatedBy,
  prd_pg_id as prdPgId,
  prd_ps_id as prdPsId,
  prd_id_source as prdIdSource,
  prd_mc_id as prdMcId,
  prd_diminsion_data as prdDiminsionData,
  prd_pas_id as prdPasId,
  prd_barcode as prdBarcode,
  prd_reject_remark as prdRejectRemark,
  prd_ref_mp_id as prdRefMpId,
  prd_is_combo as prdIsCombo,
  prd_combo_price as prdComboPrice,
  prd_is_time as prdIsTime,
  prd_combo_start as prdComboStart,
  prd_combo_end as prdComboEnd,
  prd_total_combo_price as prdTotalComboPrice,
  prd_total_cost_combo_price as prdTotalCostComboPrice,
  prd_barcode_format as prdBarcodeFormat,
  asatdate as asatdate
FROM ${ref(databuffet.VALIDATED_MASTERSKU, "product")}
${ when(incremental(), `WHERE asatdate >= CURRENT_DATE('Asia/Bangkok')-1`) }
QUALIFY row_number() over(partition by prdSku order by prdUpdatedDate desc) = 1


post_operations {
    UPDATE ${self()} as t
    SET 
    t.prdColorTH = src.prdColorTH,
    t.prdColorEN = src.prdColorEN,
    t.prdSize = src.prdSize
    FROM (
        with rows_product as (
            SELECT 
                prdSku,
                JSON_VALUE(dimField, '$.label') as dimField_label,
                NULLIF(TRIM(JSON_VALUE(dimField, '$.value')), '') as dimField_value,
                JSON_VALUE(SpeciFeild, '$.label') as SpeciFeild_label,
                NULLIF(TRIM(JSON_VALUE(SpeciFeild, '$.value')), '') as SpeciFeild_value,
            FROM ${ref(databuffet.VALIDATED_MASTERSKU, "product_detail")} as pd
            LEFT JOIN ${self()} as p
                ON p.prdId = pd.pd_prd_id
            LEFT JOIN UNNEST (JSON_QUERY_ARRAY(prdDiminsionData, '$.dimFeild'))  as dimField
            LEFT JOIN UNNEST (JSON_QUERY_ARRAY(pd_spacific_fields, '$.SpeciFeild'))  as SpeciFeild
            ${ when(incremental(), `WHERE p.asatdate >= CURRENT_DATE('Asia/Bangkok')-1`) }
            -- WHERE p.prdSku in ('MSKU1000091280', 'MSKU0000024500', 'MSKU0000024833')

            ), arge_data as (
            select prdSku, 
                max((case 
                    when lower(dimField_label) in ('ขนาด', 'size') then dimField_value
                    else null
                end)) as dimField_prdSize,
                
                max((case 
                    when lower(dimField_label) in ('สี', 'color') then dimField_value
                    else null
                end)) as dimField_prdColor,
                
                max((case 
                    when lower(SpeciFeild_label) in ('ขนาด', 'size') then SpeciFeild_value
                    else null
                end)) as SpeciFeild_prdSize,
                
                max((case 
                    when lower(SpeciFeild_label) in ('สี', 'color') then SpeciFeild_value
                    else null
                end)) as SpeciFeild_prdColor,
            from rows_product
            group by prdSku
            -- having dimField_prdSize is not null or dimField_prdColor is not null or SpeciFeild_prdSize is not null or SpeciFeild_prdColor is not null
            
            ), cleaning_data as (
            select 
                prdSku,
                IFNULL(dimField_prdSize, SpeciFeild_prdSize) as prdSize,
                IFNULL(dimField_prdColor, SpeciFeild_prdColor) as prdColor
            from arge_data

            )
            SELECT  
                prdSku, 
                prdSize,
                (CASE 
                    WHEN REGEXP_CONTAINS(SPLIT(prdColor, ' ')[SAFE_OFFSET(0)], r'[ก-๙]') 
                        THEN NULLIF(TRIM(REGEXP_EXTRACT(prdColor, r'^([ก-๙\s]+)')), '')
                    ELSE NULL
                END) AS prdColorTH,                
                (CASE 
                    WHEN NOT REGEXP_CONTAINS(SPLIT(prdColor, ' ')[SAFE_OFFSET(0)], r'[ก-๙]') 
                        THEN NULLIF(TRIM(prdColor), '')
                    ELSE NULLIF(TRIM(REGEXP_REPLACE(prdColor, r'^([ก-๙\s]+)', '')), '')
                END) AS prdColorEN
            FROM cleaning_data
    ) src
    WHERE t.prdSku = src.prdSku;

}
