config {
    type: "incremental",
    schema: databuffet.CURATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["curated_mih", "mih2", "mil"],
    tags: [databuffet.TAG_CURATED],
    uniqueKey: ["milDay", "milMonth", "milYear", "milType", "milVnos", "milCus", "milListno"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["milVnos", "milCus", "milType", "milYear"],
        updatePartitionFilter: "asatdate >= CURRENT_DATE('Asia/Bangkok')-7"
    }
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
        name: "mil",
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

}

SELECT
  milday as milDay,
  milmonth as milMonth,
  milyear as milYear,
  miltype as milType,
  milvnos as milVnos,
  milcus as milCus,
  milstk as milStk,
  miljob as milJob,
  mildep as milDep,
  milper as milPer,
  mildoc as milDoc,
  milmec as milMec,
  milsto as milSto,
  milstomt as milStomt,
  millistno as milListno,
  milquan as milQuan,
  milquanp2 as milQuanp2,
  miladisc as milAdisc,
  milcog as milCog,
  milconv as milConv,
  mildisca as milDisca,
  mildisct as milDisct,
  milvat as milVat,
  milsum as milSum,
  milcut as milCut,
  milstype as milStype,
  miluname as milUname,
  mildesc as milDesc,
  milvcol1 as milVcol1,
  milvcol2 as milVcol2,
  milvcol3 as milVcol3,
  milvcol4 as milVcol4,
  milcurc as milCurc,
  milexchg as milExchg,
  milacost as milAcost,
  milpqm as milPqm,
  milpmfrom as milPmfrom,
  milpmto as milPmto,
  miltag as milTag,
  millinkvcno as milLinkvcno,
  millinkvcdate as milLinkvcdate,
  millinkvctype as milLinkvctype,
  millinkvcdeposit as milLinkvcdeposit,
  millinkvcid as milLinkvcid,
  milclearum as milClearum,
  milexpdate as milExpdate,
  milnotes as milNotes,
  milnotkl as milNotkl,
  mildelvdt as milDelvdt,
  mildatesp as milDatesp,
  milnumcsp as milNumcsp,
  milnumisp as milNumisp,
  milcost as milCost,
  milucost as milUcost,
  miluprice as milUprice,
  milusequanp as milUsequanp,
  milvcol5 as milVcol5,
  milfitem as milFitem,
  asatdate as asatdate
FROM ${sourceTableRef}
${ when(incremental(), `WHERE asatdate >= CURRENT_DATE('Asia/Bangkok')-1`) }

post_operations {
  -------- CREATE TEMP TABLE --------
  BEGIN
    CREATE OR REPLACE TEMP TABLE new_data_curated_mil AS
    WITH mih_raw AS (
      SELECT
        mihDay,
        mihMonth,
        mihYear,
        mihType,
        mihVnos,
        mihCus,
        mihRef1,
        mihCancel
      FROM ${ref("mih")}
      WHERE mihType = 'IS'
        AND mihRef1 IS NOT NULL
        AND mihCancel <> -1
        ${ when(incremental(), `AND asatdate >= CURRENT_DATE('Asia/Bangkok')-1`) }
      QUALIFY row_number() over(partition by mihDay, mihMonth, mihYear, mihType, mihVnos, mihCus order by asatdate desc) = 1

    ), mil_raw AS (
      SELECT
        mil.*,
        mih.mihRef1
      FROM ${ref("mil")} AS mil
      INNER JOIN mih_raw AS mih
        ON mih.mihDay = mil.milDay
          AND mih.mihMonth = mil.milMonth
          AND mih.mihYear = mil.milYear
          AND mih.mihType = mil.milType
          AND mih.mihVnos = mil.milVnos
          AND mih.mihCus = mil.milCus
      QUALIFY row_number() over(partition by mil.milDay, mil.milMonth, mil.milYear, mil.milType, mil.milVnos, mil.milCus, mil.milListno order by mil.asatdate desc) = 1

    ), filter_mih2 AS (
      SELECT DISTINCT
        mih2vnos, mih2cus, mih2per2, mih2rev, mih2perpc,
        CAST(NULLIF(REPLACE(REGEXP_REPLACE(mih2perpc, r'[^0-9.%]', ''), '%', ''), '') AS FLOAT64) AS per_sale1,
        CAST(NULLIF(REPLACE(REGEXP_REPLACE(mih2per2pc, r'[^0-9.%]', ''), '%', ''), '') AS FLOAT64) AS per_sale2,
        ROW_NUMBER() OVER(PARTITION BY mih2vnos, mih2cus ORDER BY mih2rev DESC) AS chk_row
      FROM ${ref("mih2")}
      WHERE mih2cus IS NOT NULL
        AND mih2per2 IS NOT NULL
        AND mih2per2pc IS NOT NULL
        AND (mih2perpc <> '100%' AND mih2perpc <> '00%')
        AND mih2type = 'PS'
        AND EXISTS (
          SELECT 1 FROM mil_raw AS mil
          WHERE mih2vnos = mil.mihRef1
            AND mih2cus = mil.milCus
            AND mih2per2 <> mil.milPer
        )

    ), includ_mil AS (
      SELECT
        mil.milDay,
        mil.milMonth,
        mil.milYear,
        mil.milType,
        mil.milVnos,
        mil.milCus,
        mil.milStk,
        mil.milJob,
        mil.milDep,
        (CASE WHEN split_sale = 1 THEN mil.milPer ELSE mih2.mih2per2 END) AS milPer,
        mil.milDoc,
        mil.milMec,
        mil.milSto,
        mil.milStomt,
        mil.milListno,
        (CASE WHEN split_sale = 1 THEN mil.milQuan * (mih2.per_sale1/100) ELSE mil.milQuan * (mih2.per_sale2/100) END) AS milQuan,
        mil.milQuanp2,
        (CASE WHEN split_sale = 1 THEN mil.milAdisc * (mih2.per_sale1/100) ELSE mil.milAdisc * (mih2.per_sale2/100) END) AS milAdisc,
        (CASE WHEN split_sale = 1 THEN mil.milCog * (mih2.per_sale1/100) ELSE mil.milCog * (mih2.per_sale2/100) END) AS milCog,
        mil.milConv,
        (CASE WHEN split_sale = 1 THEN mil.milDisca * (mih2.per_sale1/100) ELSE mil.milDisca * (mih2.per_sale2/100) END) AS milDisca,
        mil.milDisct,
        (CASE WHEN split_sale = 1 THEN mil.milVat * (mih2.per_sale1/100) ELSE mil.milVat * (mih2.per_sale2/100) END) AS milVat,
        (CASE WHEN split_sale = 1 THEN mil.milSum * (mih2.per_sale1/100) ELSE mil.milSum * (mih2.per_sale2/100) END) AS milSum,
        mil.milCut,
        mil.milStype,
        mil.milUname,
        mil.milDesc,
        mil.milVcol1,
        mil.milVcol2,
        mil.milVcol3,
        mil.milVcol4,
        mil.milCurc,
        mil.milExchg,
        mil.milAcost,
        mil.milPqm,
        mil.milPmfrom,
        mil.milPmto,
        mil.milTag,
        mil.milLinkvcno,
        mil.milLinkvcdate,
        mil.milLinkvctype,
        mil.milLinkvcdeposit,
        mil.milLinkvcid,
        mil.milClearum,
        mil.milExpdate,
        mil.milNotes,
        mil.milNotkl,
        mil.milDelvdt,
        mil.milDatesp,
        mil.milNumcsp,
        mil.milNumisp,
        mil.milCost,
        mil.milUcost,
        mil.milUprice,
        mil.milUsequanp,
        mil.milVcol5,
        mil.milFitem,
        mil.mihRef1,
        mil.asatdate
      FROM mil_raw AS mil
      INNER JOIN filter_mih2 AS mih2
        ON mil.mihRef1 = mih2.mih2vnos
          AND mil.milCus = mih2.mih2cus
          AND mih2.chk_row = 1
      CROSS JOIN (
        SELECT 1 AS split_sale
        UNION ALL
        SELECT 2 AS split_sale
      )

    ), exclude_mil AS (
      SELECT
        mil.milDay,
        mil.milMonth,
        mil.milYear,
        mil.milType,
        mil.milVnos,
        mil.milCus,
        mil.milStk,
        mil.milJob,
        mil.milDep,
        mil.milPer,
        mil.milDoc,
        mil.milMec,
        mil.milSto,
        mil.milStomt,
        mil.milListno,
        mil.milQuan,
        mil.milQuanp2,
        mil.milAdisc,
        mil.milCog,
        mil.milConv,
        mil.milDisca,
        mil.milDisct,
        mil.milVat,
        mil.milSum,
        mil.milCut,
        mil.milStype,
        mil.milUname,
        mil.milDesc,
        mil.milVcol1,
        mil.milVcol2,
        mil.milVcol3,
        mil.milVcol4,
        mil.milCurc,
        mil.milExchg,
        mil.milAcost,
        mil.milPqm,
        mil.milPmfrom,
        mil.milPmto,
        mil.milTag,
        mil.milLinkvcno,
        mil.milLinkvcdate,
        mil.milLinkvctype,
        mil.milLinkvcdeposit,
        mil.milLinkvcid,
        mil.milClearum,
        mil.milExpdate,
        mil.milNotes,
        mil.milNotkl,
        mil.milDelvdt,
        mil.milDatesp,
        mil.milNumcsp,
        mil.milNumisp,
        mil.milCost,
        mil.milUcost,
        mil.milUprice,
        mil.milUsequanp,
        mil.milVcol5,
        mil.milFitem,
        mil.mihRef1,
        mil.asatdate
      FROM mil_raw AS mil
      WHERE NOT EXISTS (
        SELECT 1
        FROM includ_mil AS mil2
        WHERE mil.milDay = mil2.milDay
          AND mil.milMonth = mil2.milMonth
          AND mil.milYear = mil2.milYear
          AND mil.milType = mil2.milType
          AND mil.milVnos = mil2.milVnos
          AND mil.milCus = mil2.milCus
          AND mil.milListno = mil2.milListno
      )

    ), final AS (
      SELECT * EXCEPT(mihRef1) FROM exclude_mil
      UNION ALL
      SELECT * EXCEPT(mihRef1) FROM includ_mil
    )

    SELECT *
    FROM final
    ORDER BY milDay, milMonth, milYear, milType, milVnos, milCus, milStk, milDep
    ;
  END;
  -------- CREATE TEMP TABLE --------

  -------- DELETE WITH PK KEY --------
  BEGIN
    DELETE FROM ${self()} AS old_data
    WHERE EXISTS (
      SELECT 1 FROM new_data_curated_mil AS new_data
      WHERE old_data.milDay = new_data.milDay
        AND old_data.milMonth = new_data.milMonth
        AND old_data.milYear = new_data.milYear
        AND old_data.milType = new_data.milType
        AND old_data.milVnos = new_data.milVnos
        AND old_data.milCus = new_data.milCus
        AND old_data.milListno = new_data.milListno
    )
    ;
  END;
  -------- DELETE WITH PK KEY --------

  -------- INSERT DATA --------
  BEGIN
    INSERT INTO ${self()}
    SELECT *
    FROM new_data_curated_mil
    ;
  END;
  -------- INSERT DATA --------
}
