config {
  type: "operations",
  dependencies: ["drop_all_tables_raw_mac5"],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}` OPTIONS(location="${databuffet.REGION}")
;
------------------------------------- SCHEMA --------------------------------------


------------------------------------ INCREMENT ------------------------------------
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mec`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/MEC/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/MEC/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/MIH/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/MIH/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cps/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/cps/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cps_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/cps_dummy/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mie/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mie/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mie_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mie_dummy/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih2`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mih2/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mih2/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mih_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mih_dummy/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mil/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mil/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mil_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mil_dummy/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mir`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mir/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mir/'
);
------------------------------------ INCREMENT ------------------------------------


-------------------------------------- FULL ---------------------------------------
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ap_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/AP_S/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/AR_S/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.doc`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/DOC/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.per`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/PER/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rcv`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/RCV/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rno`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/RNO/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sbl`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/SBL/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.std`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STD/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stf`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STF/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stg`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STG/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STK/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sto`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STO/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.vmp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/VMP/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.apilog`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/apilog/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/ar_s/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cfs`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cfs/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.check_po`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/check_po/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.chq`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/chq/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.comboset`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/comboset/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.combostk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/combostk/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cpp/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpx`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cpx/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cre`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cre/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cst`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cst/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.deb`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/deb/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.dep`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/dep/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.detail_qtspread`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/detail_qtspread/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.grp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/grp/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.log_print_billing`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/log_print_billing/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.main_qtspread`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/main_qtspread/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.maincontract`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/maincontract/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_customer`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/match_customer/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_deb_bot_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/match_deb_bot_re/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_product`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/match_product/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_billing`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mih_billing/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_billing`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mil_billing/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mip`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mip/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mkt_per`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mkt_per/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.order_from_allkon_m`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/order_from_allkon_m/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pathfilestamper`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pathfilestamper/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_ag`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pro_ag/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_crc`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pro_crc/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pro_re/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_bot_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_bot_re/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_detail_bot_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_detail_bot_re/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_promotion`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_promotion/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.qt_spread_to_mih`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/qt_spread_to_mih/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.supcontract`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/supcontract/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tab`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tab/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbcontact`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbcontact/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_apptype`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_apptype/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_givestk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_givestk/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_payin`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_payin/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_profilecomp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_profilecomp/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quodetail`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_quodetail/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quotation`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_quotation/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbpjaddacc`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbpjaddacc/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveorder`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tdis_approveorder/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveqt`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tdis_approveqt/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_mail`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tdis_mail/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_mihstatus`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_mihstatus/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_ap`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_ap/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_frasers`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_frasers/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_pruksa`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_pruksa/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_qh`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_qh/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_sansiri`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_sansiri/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_supalai`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_supalai/*.avro']
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.userloginanyprogram`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/userloginanyprogram/*.avro']
);
-------------------------------------- FULL ---------------------------------------