config {
  type: "operations",
  dependencies: [],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}` OPTIONS(location="${databuffet.REGION}");
------------------------------------- SCHEMA --------------------------------------


------------------------------------ INCREMENT ------------------------------------
-- Table: rcv
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rcv`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rcv`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/RCV/*.avro'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/RCV/'
);

-- Table: cst
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cst`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cst`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cst/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/cst/'
);

-- Table: mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/MIH/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/MIH/'
);

-- Table: cps
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cps/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/cps/'
);

-- Table: cps_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps_dummy`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cps_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/cps_dummy/'
);

-- Table: mie
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mie/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mie/'
);

-- Table: mie_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie_dummy`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mie_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mie_dummy/'
);

-- Table: mih2
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih2`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih2`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mih2/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mih2/'
);

-- Table: mih_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_dummy`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mih_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mih_dummy/'
);

-- Table: mil
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mil/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mil/'
);

-- Table: mil_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_dummy`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_dummy`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mil_dummy/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mil_dummy/'
);

-- Table: mir
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mir`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mir`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mir/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/mir/'
);
------------------------------------ INCREMENT ------------------------------------


-------------------------------------- FULL ---------------------------------------
-- Table: ap_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ap_s`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ap_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/AP_S/*.avro']
);

-- Table: ar_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/AR_S/*.avro']
);

-- Table: doc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.doc`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.doc`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/DOC/*.avro']
);

-- Table: per
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.per`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.per`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/PER/*.avro']
);

-- Table: rno
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rno`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rno`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/RNO/*.avro']
);

-- Table: sbl
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sbl`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sbl`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/SBL/*.avro']
);

-- Table: std
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.std`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.std`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STD/*.avro']
);

-- Table: stf
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stf`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stf`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STF/*.avro']
);

-- Table: stg
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stg`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stg`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STG/*.avro']
);

-- Table: stk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stk`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STK/*.avro']
);

-- Table: sto
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sto`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sto`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/STO/*.avro']
);

-- Table: vmp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.vmp`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.vmp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/VMP/*.avro']
);

-- Table: apilog
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.apilog`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.apilog`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/apilog/*.avro']
);

-- Table: ar_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/ar_s/*.avro']
);

-- Table: cfs
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cfs`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cfs`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cfs/*.avro']
);

-- Table: check_po
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.check_po`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.check_po`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/check_po/*.avro']
);

-- Table: chq
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.chq`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.chq`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/chq/*.avro']
);

-- Table: comboset
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.comboset`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.comboset`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/comboset/*.avro']
);

-- Table: combostk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.combostk`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.combostk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/combostk/*.avro']
);

-- Table: cpp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpp`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cpp/*.avro']
);

-- Table: cpx
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpx`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpx`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cpx/*.avro']
);

-- Table: cre
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cre`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cre`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/cre/*.avro']
);

-- Table: deb
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.deb`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.deb`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/deb/*.avro']
);

-- Table: dep
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.dep`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.dep`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/dep/*.avro']
);

-- Table: detail_qtspread
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.detail_qtspread`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.detail_qtspread`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/detail_qtspread/*.avro']
);

-- Table: grp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.grp`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.grp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/grp/*.avro']
);

-- Table: log_print_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.log_print_billing`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.log_print_billing`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/log_print_billing/*.avro']
);

-- Table: main_qtspread
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.main_qtspread`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.main_qtspread`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/main_qtspread/*.avro']
);

-- Table: maincontract
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.maincontract`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.maincontract`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/maincontract/*.avro']
);

-- Table: match_customer
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_customer`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_customer`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/match_customer/*.avro']
);

-- Table: match_deb_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_deb_bot_re`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_deb_bot_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/match_deb_bot_re/*.avro']
);

-- Table: match_product
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_product`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_product`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/match_product/*.avro']
);

-- Table: mih_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_billing`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_billing`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mih_billing/*.avro']
);

-- Table: mil_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_billing`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_billing`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mil_billing/*.avro']
);

-- Table: mip
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mip`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mip`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mip/*.avro']
);

-- Table: mkt_per
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mkt_per`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mkt_per`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/mkt_per/*.avro']
);

-- Table: order_from_allkon_m
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.order_from_allkon_m`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.order_from_allkon_m`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/order_from_allkon_m/*.avro']
);

-- Table: pathfilestamper
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pathfilestamper`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pathfilestamper`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pathfilestamper/*.avro']
);

-- Table: pro_ag
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_ag`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_ag`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pro_ag/*.avro']
);

-- Table: pro_crc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_crc`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_crc`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pro_crc/*.avro']
);

-- Table: pro_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_re`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/pro_re/*.avro']
);

-- Table: product_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_bot_re`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_bot_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_bot_re/*.avro']
);

-- Table: product_detail_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_detail_bot_re`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_detail_bot_re`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_detail_bot_re/*.avro']
);

-- Table: product_promotion
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_promotion`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_promotion`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_promotion/*.avro']
);

-- Table: qt_spread_to_mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.qt_spread_to_mih`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.qt_spread_to_mih`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/qt_spread_to_mih/*.avro']
);

-- Table: supcontract
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.supcontract`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.supcontract`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/supcontract/*.avro']
);

-- Table: tab
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tab`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tab`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tab/*.avro']
);

-- Table: tbcontact
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbcontact`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbcontact`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbcontact/*.avro']
);

-- Table: tbook_apptype
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_apptype`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_apptype`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_apptype/*.avro']
);

-- Table: tbook_givestk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_givestk`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_givestk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_givestk/*.avro']
);

-- Table: tbook_payin
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_payin`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_payin`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_payin/*.avro']
);

-- Table: tbook_profilecomp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_profilecomp`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_profilecomp`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_profilecomp/*.avro']
);

-- Table: tbook_quodetail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quodetail`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quodetail`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_quodetail/*.avro']
);

-- Table: tbook_quotation
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quotation`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quotation`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbook_quotation/*.avro']
);

-- Table: tbpjaddacc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbpjaddacc`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbpjaddacc`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tbpjaddacc/*.avro']
);

-- Table: tdis_approveorder
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveorder`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveorder`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tdis_approveorder/*.avro']
);

-- Table: tdis_approveqt
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveqt`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveqt`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tdis_approveqt/*.avro']
);

-- Table: tdis_mail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_mail`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_mail`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tdis_mail/*.avro']
);

-- Table: tmp_mihstatus
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_mihstatus`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_mihstatus`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_mihstatus/*.avro']
);

-- Table: tmp_pdf_ap
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_ap`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_ap`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_ap/*.avro']
);

-- Table: tmp_pdf_frasers
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_frasers`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_frasers`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_frasers/*.avro']
);

-- Table: tmp_pdf_pruksa
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_pruksa`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_pruksa`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_pruksa/*.avro']
);

-- Table: tmp_pdf_qh
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_qh`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_qh`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_qh/*.avro']
);

-- Table: tmp_pdf_sansiri
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_sansiri`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_sansiri`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_sansiri/*.avro']
);

-- Table: tmp_pdf_supalai
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_supalai`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_supalai`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/tmp_pdf_supalai/*.avro']
);

-- Table: userloginanyprogram
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.userloginanyprogram`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.userloginanyprogram`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/userloginanyprogram/*.avro']
);

-- Table: stk_mkt
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stk_mkt`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stk_mkt`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/stk_mkt/*.avro']
);

-- Table: mec
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mec`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mec`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/MEC/*.avro']
);
-------------------------------------- FULL ---------------------------------------