config {
  type: "operations",
  dependencies: ["drop_all_tables_raw_mastersku"],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}` OPTIONS(location="${databuffet.REGION}")
;
------------------------------------- SCHEMA --------------------------------------


----------------------------------- INCREMENTAL ------------------------------------
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.brand`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/brand/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/brand/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.category`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/category/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/category/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/product/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_category`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_category/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/product_category/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_detail`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_detail/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/product_detail/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_group`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_group/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/product_group/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_group_cost_group`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/product_group_cost_group/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/product_group_cost_group/'
);

CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.vendor`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/vendor/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/vendor/'
);
----------------------------------- INCREMENTAL ------------------------------------