config {
  type: "operations",
  dependencies: [],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}` OPTIONS(location="${databuffet.REGION}");
------------------------------------- SCHEMA --------------------------------------


----------------------------------- INCREMENTAL ------------------------------------
-- Table: brand
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.brand`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.brand`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/brand/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/brand/'
);

-- Table: category
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.category`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.category`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/category/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/category/'
);

-- Table: product
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product/'
);

-- Table: product_category
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_category`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_category`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_category/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_category/'
);

-- Table: product_detail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_detail`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_detail`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_detail/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_detail/'
);

-- Table: product_group
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_group`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_group`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_group/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_group/'
);

-- Table: product_group_cost_group
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_group_cost_group`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.product_group_cost_group`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_group_cost_group/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/product_group_cost_group/'
);

-- Table: vendor
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.vendor`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MASTERSKU}.vendor`
WITH PARTITION COLUMNS (
    ASATDATE STRING 
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/vendor/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MASTERSKU}/vendor/'
);
----------------------------------- INCREMENTAL ------------------------------------