config {
  type: "operations",
  tags: [databuffet.TAG_INITIAL],
}

-- [1/12] Dropping incremental table: cps
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cps`;


-- [2/12] Dropping incremental table: cps_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cps_dummy`;


-- [3/12] Dropping incremental table: cst
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cst`;


-- [4/12] Dropping incremental table: mie
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mie`;


-- [5/12] Dropping incremental table: mie_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mie_dummy`;


-- [6/12] Dropping incremental table: mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mih`;


-- [7/12] Dropping incremental table: mih2
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mih2`;


-- [8/12] Dropping incremental table: mih_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_dummy`;


-- [9/12] Dropping incremental table: mil
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mil`;


-- [10/12] Dropping incremental table: mil_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_dummy`;


-- [11/12] Dropping incremental table: mip
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mip`;


-- [12/12] Dropping incremental table: rcv
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.rcv`;


-- [13/78] Dropping table: ap_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.ap_s`;


-- [14/78] Dropping table: apilog
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.apilog`;


-- [15/78] Dropping table: ar_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`;


-- [16/78] Dropping table: cfs
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cfs`;


-- [17/78] Dropping table: check_po
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.check_po`;


-- [18/78] Dropping table: chq
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.chq`;


-- [19/78] Dropping table: comboset
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.comboset`;


-- [20/78] Dropping table: combostk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.combostk`;


-- [21/78] Dropping table: cpp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cpp`;


-- [22/78] Dropping table: cpx
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cpx`;


-- [23/78] Dropping table: cre
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.cre`;


-- [24/78] Dropping table: deb
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.deb`;


-- [25/78] Dropping table: dep
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.dep`;


-- [26/78] Dropping table: detail_qtspread
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.detail_qtspread`;


-- [27/78] Dropping table: doc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.doc`;


-- [28/78] Dropping table: grp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.grp`;


-- [29/78] Dropping table: log_print_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.log_print_billing`;


-- [30/78] Dropping table: main_qtspread
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.main_qtspread`;


-- [31/78] Dropping table: maincontract
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.maincontract`;


-- [32/78] Dropping table: match_customer
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.match_customer`;


-- [33/78] Dropping table: match_deb_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.match_deb_bot_re`;


-- [34/78] Dropping table: match_product
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.match_product`;


-- [35/78] Dropping table: mec
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mec`;


-- [36/78] Dropping table: mih_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_billing`;


-- [37/78] Dropping table: mil_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_billing`;


-- [38/78] Dropping table: mir
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.mir`;


-- [39/78] Dropping table: order_from_allkon_m
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.order_from_allkon_m`;


-- [40/78] Dropping table: pathfilestamper
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.pathfilestamper`;


-- [41/78] Dropping table: per
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.per`;


-- [43/78] Dropping table: pro_ag
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_ag`;


-- [44/78] Dropping table: pro_crc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_crc`;


-- [45/78] Dropping table: pro_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_re`;


-- [46/78] Dropping table: product_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.product_bot_re`;


-- [47/78] Dropping table: product_detail_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.product_detail_bot_re`;


-- [48/78] Dropping table: product_promotion
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.product_promotion`;


-- [49/78] Dropping table: qt_spread_to_mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.qt_spread_to_mih`;


-- [50/78] Dropping table: rno
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.rno`;


-- [51/78] Dropping table: sbl
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.sbl`;


-- [52/78] Dropping table: std
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.std`;


-- [53/78] Dropping table: stf
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.stf`;


-- [54/78] Dropping table: stg
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.stg`;


-- [55/78] Dropping table: stk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.stk`;


-- [56/78] Dropping table: sto
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.sto`;


-- [57/78] Dropping table: supcontract
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.supcontract`;


-- [58/78] Dropping table: tab
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tab`;


-- [59/78] Dropping table: tbcontact
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbcontact`;


-- [60/78] Dropping table: tbook_apptype
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_apptype`;


-- [61/78] Dropping table: tbook_givestk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_givestk`;


-- [62/78] Dropping table: tbook_payin
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_payin`;


-- [63/78] Dropping table: tbook_profilecomp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_profilecomp`;


-- [64/78] Dropping table: tbook_quodetail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quodetail`;


-- [65/78] Dropping table: tbook_quotation
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quotation`;


-- [66/78] Dropping table: tbpjaddacc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tbpjaddacc`;


-- [67/78] Dropping table: tdis_approveorder
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveorder`;


-- [68/78] Dropping table: tdis_approveqt
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveqt`;


-- [69/78] Dropping table: tdis_mail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_mail`;


-- [70/78] Dropping table: tmp_mihstatus
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_mihstatus`;


-- [71/78] Dropping table: tmp_pdf_ap
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_ap`;


-- [72/78] Dropping table: tmp_pdf_frasers
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_frasers`;


-- [73/78] Dropping table: tmp_pdf_pruksa
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_pruksa`;


-- [74/78] Dropping table: tmp_pdf_qh
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_qh`;


-- [75/78] Dropping table: tmp_pdf_sansiri
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_sansiri`;


-- [76/78] Dropping table: tmp_pdf_supalai
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_supalai`;


-- [77/78] Dropping table: userloginanyprogram
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.userloginanyprogram`;


-- [78/78] Dropping table: vmp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.VALIDATED_SCHEMA}_${databuffet.SOURCE_MAC5}.vmp`;