config {
  type: "operations",
  tags: [databuffet.TAG_INITIAL],
}

-- DROP ALL TABLES IN MAC5
-- Total tables: 79
-- Generated automatically


-- [1/79] Dropping table: ap_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ap_s`;


-- [2/79] Dropping table: ar_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`;


-- [3/79] Dropping table: doc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.doc`;


-- [4/79] Dropping table: mec
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mec`;


-- [5/79] Dropping table: mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih`;


-- [6/79] Dropping table: per
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.per`;


-- [7/79] Dropping table: rcv
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rcv`;


-- [8/79] Dropping table: rno
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.rno`;


-- [9/79] Dropping table: sbl
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sbl`;


-- [10/79] Dropping table: std
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.std`;


-- [11/79] Dropping table: stf
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stf`;


-- [12/79] Dropping table: stg
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stg`;


-- [13/79] Dropping table: stk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.stk`;


-- [14/79] Dropping table: sto
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.sto`;


-- [15/79] Dropping table: vmp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.vmp`;


-- [16/79] Dropping table: apilog
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.apilog`;


-- [17/79] Dropping table: ar_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.ar_s`;


-- [18/79] Dropping table: cfs
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cfs`;


-- [19/79] Dropping table: check_po
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.check_po`;


-- [20/79] Dropping table: chq
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.chq`;


-- [21/79] Dropping table: comboset
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.comboset`;


-- [22/79] Dropping table: combostk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.combostk`;


-- [23/79] Dropping table: cpp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpp`;


-- [24/79] Dropping table: cps
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps`;


-- [25/79] Dropping table: cps_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cps_dummy`;


-- [26/79] Dropping table: cpx
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cpx`;


-- [27/79] Dropping table: cre
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cre`;


-- [28/79] Dropping table: cst
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.cst`;


-- [29/79] Dropping table: deb
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.deb`;


-- [30/79] Dropping table: dep
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.dep`;


-- [31/79] Dropping table: detail_qtspread
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.detail_qtspread`;


-- [32/79] Dropping table: grp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.grp`;


-- [33/79] Dropping table: log_print_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.log_print_billing`;


-- [34/79] Dropping table: main_qtspread
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.main_qtspread`;


-- [35/79] Dropping table: maincontract
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.maincontract`;


-- [36/79] Dropping table: match_customer
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_customer`;


-- [37/79] Dropping table: match_deb_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_deb_bot_re`;


-- [38/79] Dropping table: match_product
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.match_product`;


-- [39/79] Dropping table: mie
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie`;


-- [40/79] Dropping table: mie_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mie_dummy`;


-- [41/79] Dropping table: mih2
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih2`;


-- [42/79] Dropping table: mih_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_billing`;


-- [43/79] Dropping table: mih_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mih_dummy`;


-- [44/79] Dropping table: mil
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil`;


-- [45/79] Dropping table: mil_billing
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_billing`;


-- [46/79] Dropping table: mil_dummy
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mil_dummy`;


-- [47/79] Dropping table: mip
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mip`;


-- [48/79] Dropping table: mir
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mir`;


-- [49/79] Dropping table: mkt_per
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.mkt_per`;


-- [50/79] Dropping table: order_from_allkon_m
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.order_from_allkon_m`;


-- [51/79] Dropping table: pathfilestamper
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pathfilestamper`;


-- [52/79] Dropping table: pro_ag
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_ag`;


-- [53/79] Dropping table: pro_crc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_crc`;


-- [54/79] Dropping table: pro_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.pro_re`;


-- [55/79] Dropping table: product_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_bot_re`;


-- [56/79] Dropping table: product_detail_bot_re
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_detail_bot_re`;


-- [57/79] Dropping table: product_promotion
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.product_promotion`;


-- [58/79] Dropping table: qt_spread_to_mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.qt_spread_to_mih`;


-- [59/79] Dropping table: supcontract
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.supcontract`;


-- [60/79] Dropping table: tab
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tab`;


-- [61/79] Dropping table: tbcontact
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbcontact`;


-- [62/79] Dropping table: tbook_apptype
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_apptype`;


-- [63/79] Dropping table: tbook_givestk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_givestk`;


-- [64/79] Dropping table: tbook_payin
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_payin`;


-- [65/79] Dropping table: tbook_profilecomp
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_profilecomp`;


-- [66/79] Dropping table: tbook_quodetail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quodetail`;


-- [67/79] Dropping table: tbook_quotation
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbook_quotation`;


-- [68/79] Dropping table: tbpjaddacc
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tbpjaddacc`;


-- [69/79] Dropping table: tdis_approveorder
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveorder`;


-- [70/79] Dropping table: tdis_approveqt
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_approveqt`;


-- [71/79] Dropping table: tdis_mail
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tdis_mail`;


-- [72/79] Dropping table: tmp_mihstatus
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_mihstatus`;


-- [73/79] Dropping table: tmp_pdf_ap
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_ap`;


-- [74/79] Dropping table: tmp_pdf_frasers
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_frasers`;


-- [75/79] Dropping table: tmp_pdf_pruksa
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_pruksa`;


-- [76/79] Dropping table: tmp_pdf_qh
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_qh`;


-- [77/79] Dropping table: tmp_pdf_sansiri
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_sansiri`;


-- [78/79] Dropping table: tmp_pdf_supalai
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.tmp_pdf_supalai`;


-- [79/79] Dropping table: userloginanyprogram
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_SCHEMA}_${databuffet.SOURCE_MAC5}.userloginanyprogram`;


-- All 79 tables have been dropped from MAC5
