config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["dim_invoice", "dim_aging"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_invoice",
    };
    const DimInvoiceTableRef = `${DimInvoiceTable.database}.${DimInvoiceTable.schema}.${DimInvoiceTable.name}`;

    const DimAgingTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_aging",
    };
    const DimAgingTableRef = `${DimAgingTable.database}.${DimAgingTable.schema}.${DimAgingTable.name}`;

    const FnFlagScgTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FUNCTION_DATASET,
        name: "fn_flag_scg",
    };
    const FnFlagScgTableRef = `${FnFlagScgTable.database}.${FnFlagScgTable.schema}.${FnFlagScgTable.name}`;
}

with tab_main as (
  select 
    agi.AgingSK,
    inv.*,
    
    (CASE 
      WHEN inv.mihType in ('BS', 'AS') THEN inv_is.milLinkvcno
      ELSE inv.milLinkvcno
    END) as RefOrder,

  from `${DimInvoiceTableRef}` as inv
  left join `${DimInvoiceTableRef}` as inv_is
    on inv.milLinkVcno = inv_is.mihVnos
    and inv.companyID = inv_is.companyID
    and inv_is.mihType = 'IS'
  left join `${DimAgingTableRef}` as agi
    on agi.CFSvnosID = inv.mihvnos
    and inv.CompanySK = agi.CompanySK

  -- where mih2.mih2pos is not null

  qualify row_number() over(partition by InvoiceSK order by AgingSK) = 1

)
  select 
    *,
    `${FnFlagScgTableRef}`(RefOrder, mihCus) as FlagSCG,
  from tab_main
