config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["view_dim_sale_representative_last", "dim_department_last", "dim_section_last", "dim_region_last"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const ViewDimSaleRepresentativeLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_sale_representative_last",
    };
    const ViewDimSaleRepresentativeLastTableRef = `${ViewDimSaleRepresentativeLastTable.database}.${ViewDimSaleRepresentativeLastTable.schema}.${ViewDimSaleRepresentativeLastTable.name}`;

    const DimDepartmentLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department_last",
    };
    const DimDepartmentLastTableRef = `${DimDepartmentLastTable.database}.${DimDepartmentLastTable.schema}.${DimDepartmentLastTable.name}`;

    const DimSectionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_last",
    };
    const DimSectionLastTableRef = `${DimSectionLastTable.database}.${DimSectionLastTable.schema}.${DimSectionLastTable.name}`;

    const DimRegionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_last",
    };
    const DimRegionLastTableRef = `${DimRegionLastTable.database}.${DimRegionLastTable.schema}.${DimRegionLastTable.name}`;
}

SELECT
  dim_sale.*,
  dim_region.RegionID,
  dim_region.RegionName,
  dim_section.SectionID,
  dim_section.SectionName,
  dim_depart.DepartmentName
FROM `${ViewDimSaleRepresentativeLastTableRef}` as dim_sale
LEFT JOIN `${DimDepartmentLastTableRef}` as dim_depart
  ON dim_depart.DepartmentSK = dim_sale.DepartmentSK
  and dim_depart.CompanySK = dim_sale.CompanySK
LEFT JOIN `${DimSectionLastTableRef}` as dim_section
  ON dim_section.SectionSK = dim_depart.SectionSK
  and dim_section.CompanySK = dim_depart.CompanySK
LEFT JOIN `${DimRegionLastTableRef}` as dim_region
  ON dim_region.RegionSK = dim_depart.RegionSK
  and dim_region.CompanySK = dim_depart.CompanySK
