config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["dim_order"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const FnOrderTypeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FUNCTION_DATASET,
        name: "fn_order_type",
    };
    const FnOrderTypeTableRef = `${FnOrderTypeTable.database}.${FnOrderTypeTable.schema}.${FnOrderTypeTable.name}`;

    const DimOrderTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_order",
    };
    const DimOrderTableRef = `${DimOrderTable.database}.${DimOrderTable.schema}.${DimOrderTable.name}`;
}

SELECT 
  ord.*,
  `${FnOrderTypeTableRef}`(ord.mihref2) as OrderType,
  mih2.mih2pos as CustomerShipTo,

from `${DimOrderTableRef}` as ord
left join ${ref(databuffet.VALIDATED_MAC5, "mih2")} as mih2
  on ord.companyID = mih2.company_id
  and ord.mihDay = mih2.mih2day
  and ord.mihMonth = mih2.mih2month
  and ord.mihYear = mih2.mih2year
  and ord.mihType = mih2.mih2type
  and ord.mihCus = mih2.mih2cus
  and ord.mihVnos = mih2.mih2vnos
  
-- where OrderSK = 1007301

qualify row_number() over(partition by OrderSK order by mih2.mih2pos desc) = 1
