config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["dim_product_mkt", "dim_product_mkt_director"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt",
    };
    const DimProductMktTableRef = `${DimProductMktTable.database}.${DimProductMktTable.schema}.${DimProductMktTable.name}`;

    const DimProductMktDirectorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt_director",
    };
    const DimProductMktDirectorTableRef = `${DimProductMktDirectorTable.database}.${DimProductMktDirectorTable.schema}.${DimProductMktDirectorTable.name}`;
}

SELECT
  mkt.ProductMktSK,
  dir.ProductMktDirectorSK,
  mkt.* except(ProductMktSK)
FROM `${DimProductMktTableRef}` as mkt
LEFT JOIN `${DimProductMktDirectorTableRef}` as dir
  on mkt.TypeMarketingID = dir.TypeMarketingID
  and mkt.CompanyID = dir.CompanyID
