config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["dim_channel", "dim_channel_finance", "dim_channel_sales", "dim_channel_cost"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimChannelTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel",
    };
    const DimChannelTableRef = `${DimChannelTable.database}.${DimChannelTable.schema}.${DimChannelTable.name}`;

    const DimChannelFinanceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel_finance",
    };
    const DimChannelFinanceTableRef = `${DimChannelFinanceTable.database}.${DimChannelFinanceTable.schema}.${DimChannelFinanceTable.name}`;

    const DimChannelSalesTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel_sales",
    };
    const DimChannelSalesTableRef = `${DimChannelSalesTable.database}.${DimChannelSalesTable.schema}.${DimChannelSalesTable.name}`;

    const DimChannelCostTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel_cost",
    };
    const DimChannelCostTableRef = `${DimChannelCostTable.database}.${DimChannelCostTable.schema}.${DimChannelCostTable.name}`;
}

SELECT 
  t1.ChannelSK,
  t2.ChannelFinanceSK,
  t3.ChannelSaleSK,
  t4.ChannelCostSK,
  t1.CompanySK,
  t1.companyID,
  t1.DepCode,
  t1.DepGroup,
  t1.DepDesct,
  t1.DepDesce,
  t1.ChannelGroup,
  t1.ChannelSubGroupName1,
  t1.ChannelSubGroupName2,
  t1.ChannelSubGroupName3,
  t1.ChannelID,
  t1.ChannelName,
  t1.ChannelCostID,
  t1.ChannelCostName,
  t1.ChannelGroupFinance,
  t1.ChannelSubGroupFinance1,
  t1.ChannelSubGroupFinance2,
  t1.ChannelSubGroupFinance3,
  t1.ChannelIDFinance,
  t1.ChannelNameFinance,
  t1.ChannelDSite01,
  t1.ChannelDDepartment02,
  t1.ChannelDDivision03,
  t1.ChannelDSubDivision04,
  t1.DummyChannel,
FROM `${DimChannelTableRef}` as t1
LEFT JOIN `${DimChannelFinanceTableRef}` as t2
  on t1.ChannelIDFinance = t2.ChannelIDFinance
  and t1.CompanySK = t2.CompanySK
LEFT JOIN `${DimChannelSalesTableRef}` as t3
  on t1.ChannelID = t3.ChannelID
  and t1.CompanySK = t3.CompanySK
LEFT JOIN `${DimChannelCostTableRef}` as t4
  on t1.ChannelCostID = t4.ChannelCostID
  and t1.CompanySK = t4.CompanySK
