config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["dim_sale_representative", "dim_department"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimSaleRepresentativeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative",
    };
    const DimSaleRepresentativeTableRef = `${DimSaleRepresentativeTable.database}.${DimSaleRepresentativeTable.schema}.${DimSaleRepresentativeTable.name}`;

    const DimDepartmentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department",
    };
    const DimDepartmentTableRef = `${DimDepartmentTable.database}.${DimDepartmentTable.schema}.${DimDepartmentTable.name}`;
}

select distinct Sales_Rep.*, Department.DepartmentName 
from `${DimSaleRepresentativeTableRef}` as Sales_Rep
left join `${DimDepartmentTableRef}` as Department 
  on Sales_Rep.DepartmentID = Department.DepartmentID
  and Sales_Rep.CompanySK = Department.CompanySK
