config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["dim_sale_representative_last", "dim_department_last"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimSaleRepresentativeLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative_last",
    };
    const DimSaleRepresentativeLastTableRef = `${DimSaleRepresentativeLastTable.database}.${DimSaleRepresentativeLastTable.schema}.${DimSaleRepresentativeLastTable.name}`;

    const DimDepartmentLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department_last",
    };
    const DimDepartmentLastTableRef = `${DimDepartmentLastTable.database}.${DimDepartmentLastTable.schema}.${DimDepartmentLastTable.name}`;
}

select Sales_Rep.*, Department.DepartmentName ,

-------Oat เพิ่ม ไว้ ทำตัว Sort -------
FORMAT('%02d', 
    ROW_NUMBER() OVER (
      -- จัดกลุ่มตาม SectionSK (หากเป็นค่าว่างหรือ Null จะถูกรวบเป็นกลุ่มเดียวกัน)
      PARTITION BY IFNULL(CAST(Sales_Rep.RegionSK AS STRING), '') 
      
      -- เรียงลำดับคิวในการรันเลข โดยดูจาก DepartmentID ก่อน ถ้าไม่มีให้ดู EmployeeID
      ORDER BY 
        IFNULL(Sales_Rep.DepartmentID, ''), 
        EmployeeID
    )
  ) AS Sort
-------Oat เพิ่ม ไว้ ทำตัว Sort -------

from `${DimSaleRepresentativeLastTableRef}` as Sales_Rep
left join `${DimDepartmentLastTableRef}` as Department 
  on Sales_Rep.DepartmentSK = Department.DepartmentSK
  and Sales_Rep.CompanySK = Department.CompanySK
