config {
  type: "view",
  schema: databuffet.DIMENSION_VIEW,
  dependencies: ["view_dim_channel"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimAgingHistoryTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_aging_history",
    };
    const DimAgingHistoryTableRef = `${DimAgingHistoryTable.database}.${DimAgingHistoryTable.schema}.${DimAgingHistoryTable.name}`;

    const ViewDimChannelTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_channel",
    };
    const ViewDimChannelTableRef = `${ViewDimChannelTable.database}.${ViewDimChannelTable.schema}.${ViewDimChannelTable.name}`;
}

select 
  dim_channel.ChannelSK,
  dim_channel.ChannelFinanceSK,
  dim_channel.ChannelSaleSK,
  dim_channel.ChannelCostSK,
  dim_aging.* 
from `${DimAgingHistoryTableRef}` as dim_aging

left join `${ViewDimChannelTableRef}` as dim_channel
  on dim_aging.CompanySK = dim_channel.CompanySK
  and dim_aging.cfsDep = dim_channel.DepCode

where dim_aging.cfsvnosid != 'BFCN020/47'

qualify row_number() over(partition by asatdate, AgingSK order by ChannelSK) = 1
