config {
  type: "operations",
  dependencies: ["drop_all_tables_validated_mac5", "drop_all_tables_curated_mac5"],
  tags: [databuffet.TAG_INITIAL],
}

------------------------------------- SCHEMA --------------------------------------
CREATE SCHEMA IF NOT EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}` OPTIONS(location="${databuffet.REGION}");
------------------------------------- SCHEMA --------------------------------------


------------------------------------ INCREMENT ------------------------------------
-- Table: cql
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.cql`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.cql`
WITH PARTITION COLUMNS (
    ASATDATE STRING
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/cql/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/cql/'
);

-- Table: mih
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mih`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mih`
WITH PARTITION COLUMNS (
    ASATDATE STRING
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/mih/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/mih/'
);

-- Table: mil
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mil`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mil`
WITH PARTITION COLUMNS (
    ASATDATE STRING
)
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/mil/*'],
  hive_partition_uri_prefix = '${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/mil/'
);
------------------------------------ INCREMENT ------------------------------------


-------------------------------------- FULL ---------------------------------------
-- Table: ap_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.ap_s`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.ap_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/ap_s/*.avro']
);

-- Table: ar_s
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.ar_s`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.ar_s`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/ar_s/*.avro']
);

-- Table: chq
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.chq`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.chq`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/chq/*.avro']
);

-- Table: deb
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.deb`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.deb`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/deb/*.avro']
);

-- Table: dep
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.dep`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.dep`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/dep/*.avro']
);

-- Table: per
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.per`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.per`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/per/*.avro']
);

-- Table: stg
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.stg`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.stg`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/stg/*.avro']
);

-- Table: stk
DROP TABLE IF EXISTS `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.stk`;
CREATE OR REPLACE EXTERNAL TABLE `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.stk`
OPTIONS (
  format = 'AVRO',
  uris = ['${databuffet.RAW_BUCKET}/${databuffet.GCS_MAC5_AB01}/stk/*.avro']
);
-------------------------------------- FULL ---------------------------------------
