config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimSectionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimSectionTableRef = `${DimSectionTable.database}.${DimSectionTable.schema}.${DimSectionTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_sales_section_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(SectionSK), 0) FROM `${DimSectionTableRef}`);

  MERGE `${DimSectionTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t3.SectionSK IS NOT NULL THEN t3.SectionSK
        WHEN t2.SectionSK IS NOT NULL THEN t2.SectionSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.SectionSK IS NULL AND t3.SectionSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.companyID")},
            ${databuffet.functionData.cleanString("t1.SectionID")},
            t1.StartDate,
            t1.EndDate
        )
      END) AS SectionSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.cleanString("t1.SectionID")} AS SectionID,
      ${databuffet.functionData.cleanString("t1.SectionName")} AS SectionName,
      t1.StartDate AS StartDate,
      t1.EndDate AS EndDate,
      ${databuffet.functionData.cleanString("t1.id")} as MdsID
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    LEFT JOIN `${DimSectionTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
      AND ${databuffet.functionData.cleanString("t1.SectionID")} = t2.SectionID
      AND t1.StartDate = t2.StartDate
      AND t1.EndDate = t2.EndDate
    LEFT JOIN `${DimSectionTableRef}` AS t3
      ON ${databuffet.functionData.cleanString("t1.id")} = t3.MdsID
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.SectionSK = S.SectionSK

  WHEN MATCHED THEN
    UPDATE SET
      T.SectionName = S.SectionName,
      T.StartDate = S.StartDate,
      T.EndDate = S.EndDate,
      T.MdsID = S.MdsID 

  WHEN NOT MATCHED THEN
    INSERT (
      SectionSK,
      CompanySK,
      companyID,
      SectionID,
      SectionName,
      StartDate,
      EndDate,
      MdsID
    )
    VALUES (
      S.SectionSK,
      S.CompanySK,
      S.companyID,
      S.SectionID,
      S.SectionName,
      S.StartDate,
      S.EndDate,
      S.MdsID
    );

  DELETE FROM `${DimSectionTableRef}`
  WHERE MdsID IN (
    SELECT id FROM `${MdsSourceTableRef}` WHERE is_active = FALSE
  );
END;
