config {
    type: "incremental",
    schema: databuffet.VALIDATED_SALEOUT,
    dependencies: ["validated_schema_saleout", "create_all_table_raw_saleout_mdt"],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: ["crdate", "periodtype", "vendorno", "siteno", "itemno", "mch3", "artno"],
    bigquery: {
        clusterBy: ["crdate", "vendorno", "siteno", "mch3"]
    },
}

js {
    const pk_key = ["crdate", "periodtype", "vendorno", "siteno", "itemno", "mch3", "artno"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    PARSE_DATETIME('%d/%m/%Y %H:%M', TRIM(CRDATE)) AS crdate,
    ${databuffet.cleanString('PERIODTYPE')} AS periodtype,
    PARSE_DATE('%d/%m/%Y', REGEXP_REPLACE(TRIM(PERIODDATE), r'[="]', '')) AS perioddate,
    ${databuffet.cleanString('VENDORNO')} AS vendorno,
    ${databuffet.cleanString('VENDORNAME')} AS vendorname,
    ${databuffet.cleanString('SITENO')} AS siteno,
    ${databuffet.cleanString('SITENAME')} AS sitename,
    ${databuffet.cleanString('ITEMNO')} AS itemno,
    ${databuffet.cleanString('MCH3')} AS mch3,
    ${databuffet.cleanString('MCH2DESC')} AS mch2desc,
    ${databuffet.cleanString('MCH1DESC')} AS mch1desc,
    ${databuffet.cleanString('ARTNO')} AS artno,
    ${databuffet.cleanString('ARTDESC')} AS artdesc,
    NULLIF(CAST(REGEXP_REPLACE(TRIM(ARTEAN), r'[="]', '') AS STRING), '') AS artean,
    NULLIF(CAST(REGEXP_REPLACE(TRIM(VDARTNO), r'[="]', '') AS STRING), '') AS vdartno,
    ${databuffet.cleanString('VDARTDESC')} AS vdartdesc,
    ${databuffet.castFloat64('QTY')} AS qty,
    ${databuffet.castFloat64('VALUE')} AS value,
    ${databuffet.parseAsatDate()} as ASATDATE,
FROM `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.saleout_hp`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
