config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimDoctypeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimDoctypeTableRef = `${DimDoctypeTable.database}.${DimDoctypeTable.schema}.${DimDoctypeTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_document_type_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  -- DECLARE max_sk INT64 DEFAULT 0;

  -- SET max_sk = (SELECT IFNULL(MAX(DoctypeSK), 0) FROM `${DimDoctypeTableRef}`);

  MERGE `${DimDoctypeTableRef}` AS T
  USING (
    SELECT
      -- (CASE
      --   WHEN t2.DoctypeSK IS NOT NULL THEN t2.DoctypeSK
      --   ELSE max_sk + ROW_NUMBER() OVER(
      --     PARTITION BY (CASE WHEN t2.DoctypeSK IS NULL THEN 1 ELSE 0 END)
      --     ORDER BY
      --       ${databuffet.functionData.cleanString("t1.companyID")},
      --       ${databuffet.functionData.cleanString("t1.Code")}
      --   )
      -- END) AS DoctypeSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.cleanString("t1.AccountCategory")} AS AccountCategory,
      ${databuffet.functionData.cleanString("t1.Code")} AS Code,
      ${databuffet.functionData.cleanString("t1.DescriptionEN")} AS DescriptionEN,
      ${databuffet.functionData.cleanString("t1.DescriptionTH")} AS DescriptionTH,
      ${databuffet.functionData.cleanString("t1.id")} as MdsID
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    -- LEFT JOIN `${DimDoctypeTableRef}` AS t2
    --   ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
    --   AND ${databuffet.functionData.cleanString("t1.Code")} = t2.Code
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.companyID = S.companyID
  and T.Code = S.Code

  WHEN MATCHED THEN
    UPDATE SET
      T.AccountCategory = S.AccountCategory,
      T.DescriptionEN = S.DescriptionEN,
      T.DescriptionTH = S.DescriptionTH,
      T.MdsID = S.MdsID

  WHEN NOT MATCHED THEN
    INSERT (
      -- DoctypeSK,
      CompanySK,
      companyID,
      AccountCategory,
      Code,
      DescriptionEN,
      DescriptionTH,
      MdsID
    )
    VALUES (
      -- S.DoctypeSK,
      S.CompanySK,
      S.companyID,
      S.AccountCategory,
      S.Code,
      S.DescriptionEN,
      S.DescriptionTH,
      S.MdsID
    );
END;
