config {
    type: "table",
    schema: databuffet.DIMENSION_TABLE,
    dependencies: [ 
                    "dim_company", "dim_section"
                ],
    tags: [databuffet.TAG_DIM_DAILY],
    uniqueKey: ["SectionSK"],
    bigquery: {
        clusterBy: ["SectionSK"]
    },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimSectionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section",
    };
    const DimSectionTableRef = `${DimSectionTable.database}.${DimSectionTable.schema}.${DimSectionTable.name}`;

}

SELECT
    ROW_NUMBER() OVER (ORDER BY dim_com.CompanySK, t1.SectionID) AS SectionSK,
    NULL AS SectionManagerSK,
    NULL AS RegionSK, 
    NULL AS RegionManagerSK, 
    NULL AS DirectorSK,
    dim_com.CompanySK,
    dim_com.companyID,
    t1.SectionID,
    t1.SectionName,
  FROM (
    SELECT
      *
    FROM `${DimSectionTableRef}`
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CompanyID, SectionID ORDER BY StartDate DESC, EndDate DESC) = 1
  ) as t1
  LEFT JOIN `${DimCompanyTableRef}` as dim_com
    on t1.CompanyID = dim_com.CompanyID


pre_operations {
}

post_operations {
}
