config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["CostStkSK"],
  bigquery: {
    clusterBy: ["CostStkSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_standard_cost_by_product_id_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.cleanString("t1.MilStk")},
      ${databuffet.functionData.cleanString("t1.GaccID")},
      ${databuffet.functionData.cleanString("t1.ChannelCostID")},
      t1.StartDate,
      t1.EndDate
  ) AS CostStkSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.cleanString("t1.MilStk")} AS MilStk,
  ${databuffet.functionData.cleanString("t1.GaccID")} AS GaccID,
  ${databuffet.functionData.cleanString("t1.GAccName")} AS GAccName,
  ${databuffet.functionData.cleanString("t1.ChannelCostID")} AS ChannelCostID,
  ${databuffet.functionData.cleanString("t1.ChannelCostName")} AS ChannelCostName,
  ${databuffet.functionData.castFloat64("t1.Percent")} AS Percent,
  t1.StartDate AS StartDate,
  t1.EndDate AS EndDate,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
