config {
    type: "table",
    schema: databuffet.DIMENSION_TABLE,
    dependencies: [ 
                    "dim_company", "dim_region"
                ],
    tags: [databuffet.TAG_DIM_DAILY],
    uniqueKey: ["RegionSK"],
    bigquery: {
        clusterBy: ["RegionSK"]
    },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimRegionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region",
    };
    const DimRegionTableRef = `${DimRegionTable.database}.${DimRegionTable.schema}.${DimRegionTable.name}`;

}

SELECT
    ROW_NUMBER() OVER (ORDER BY dim_com.CompanySK, t1.RegionID, t1.SubRegionID) AS RegionSK,
    NULL AS RegionManagerSK,
    NULL AS DirectorSK,
    dim_com.CompanySK,
    dim_com.companyID,
    t1.DirectorID,
    t1.RegionID,
    t1.SubRegionID,
    t1.RegionName,
  FROM (
    SELECT
      *
    FROM `${DimRegionTableRef}`
    -- WHERE CURRENT_DATE('Asia/Bangkok') between StartDate and EndDate
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CompanyID, RegionID, SubRegionID ORDER BY StartDate DESC, EndDate DESC) = 1
  ) as t1
  LEFT JOIN `${DimCompanyTableRef}` as dim_com
    on t1.CompanyID = dim_com.CompanyID


pre_operations {
}

post_operations {
}
