config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimGradeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimGradeTableRef = `${DimGradeTable.database}.${DimGradeTable.schema}.${DimGradeTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_custgrade_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(GradeSK), 0) FROM `${DimGradeTableRef}`);

  MERGE `${DimGradeTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t3.GradeSK IS NOT NULL THEN t3.GradeSK
        WHEN t2.GradeSK IS NOT NULL THEN t2.GradeSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.GradeSK IS NULL AND t3.GradeSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.companyID")},
            ${databuffet.functionData.castFloat64("t1.Percentmin")},
            ${databuffet.functionData.castFloat64("t1.Percentmax")},
            t1.StartDate,
            t1.EndDate
        )
      END) AS GradeSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.castFloat64("t1.Percentmin")} AS Percentmin,
      ${databuffet.functionData.castFloat64("t1.Percentmax")} AS Percentmax,
      ${databuffet.functionData.cleanString("t1.Grade")} AS Grade,
      t1.StartDate,
      t1.EndDate,
      ${databuffet.functionData.cleanString("t1.id")} as MdsID
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    LEFT JOIN `${DimGradeTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
      AND ${databuffet.functionData.castFloat64("t1.Percentmin")} = t2.Percentmin
      AND ${databuffet.functionData.castFloat64("t1.Percentmax")} = t2.Percentmax
      AND t1.StartDate = t2.StartDate
      AND t1.EndDate = t2.EndDate
    LEFT JOIN `${DimGradeTableRef}` AS t3
      ON ${databuffet.functionData.cleanString("t1.id")} = t3.MdsID
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.GradeSK = S.GradeSK

  WHEN MATCHED THEN
    UPDATE SET
      T.Percentmin = S.Percentmin,
      T.Percentmax = S.Percentmax,
      T.Grade = S.Grade,
      T.StartDate = S.StartDate,
      T.EndDate = S.EndDate,
      T.MdsID = S.MdsID

  WHEN NOT MATCHED THEN
    INSERT (
      GradeSK, 
      CompanySK, 
      CompanyID, 
      Percentmin, 
      Percentmax, 
      Grade, 
      StartDate, 
      EndDate,
      MdsID
    )
    VALUES (
      S.GradeSK, 
      S.CompanySK, 
      S.CompanyID, 
      S.Percentmin, 
      S.Percentmax, 
      S.Grade, 
      S.StartDate, 
      S.EndDate,
      S.MdsID
    );
END;
