config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimCostStkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimCostStkTableRef = `${DimCostStkTable.database}.${DimCostStkTable.schema}.${DimCostStkTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_standard_cost_by_product_id_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(CostStkSK), 0) FROM `${DimCostStkTableRef}`);

  MERGE `${DimCostStkTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t3.CostStkSK IS NOT NULL THEN t3.CostStkSK
        WHEN t2.CostStkSK IS NOT NULL THEN t2.CostStkSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.CostStkSK IS NULL AND t3.CostStkSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.companyID")},
            ${databuffet.functionData.cleanString("t1.MilStk")},
            ${databuffet.functionData.cleanString("t1.GaccID")},
            ${databuffet.functionData.cleanString("t1.ChannelCostID")},
            t1.StartDate,
            t1.EndDate
        )
      END) AS CostStkSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.cleanString("t1.MilStk")} AS MilStk,
      ${databuffet.functionData.cleanString("t1.GaccID")} AS GaccID,
      ${databuffet.functionData.cleanString("t1.GAccName")} AS GAccName,
      ${databuffet.functionData.cleanString("t1.ChannelCostID")} AS ChannelCostID,
      ${databuffet.functionData.cleanString("t1.ChannelCostName")} AS ChannelCostName,
      ${databuffet.functionData.castFloat64("t1.Percent")} AS Percent,
      t1.StartDate AS StartDate,
      t1.EndDate AS EndDate,
      ${databuffet.functionData.cleanString("t1.id")} as MdsID
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    LEFT JOIN `${DimCostStkTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
      AND ${databuffet.functionData.cleanString("t1.MilStk")} = t2.MilStk
      AND ${databuffet.functionData.cleanString("t1.GaccID")} = t2.GaccID
      AND ${databuffet.functionData.cleanString("t1.ChannelCostID")} = t2.ChannelCostID
      AND t1.StartDate = t2.StartDate
      AND t1.EndDate = t2.EndDate
    LEFT JOIN `${DimCostStkTableRef}` AS t3
      ON ${databuffet.functionData.cleanString("t1.id")} = t3.MdsID
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.CostStkSK = S.CostStkSK

  WHEN MATCHED THEN
    UPDATE SET
      T.GAccName = S.GAccName,
      T.ChannelCostName = S.ChannelCostName,
      T.Percent = S.Percent,
      T.StartDate = S.StartDate,
      T.EndDate = S.EndDate,
      T.MdsID = S.MdsID

  WHEN NOT MATCHED THEN
    INSERT (
      CostStkSK,
      CompanySK,
      companyID,
      MilStk,
      GaccID,
      GAccName,
      ChannelCostID,
      ChannelCostName,
      Percent,
      StartDate,
      EndDate,
      MdsID
    )
    VALUES (
      S.CostStkSK,
      S.CompanySK,
      S.companyID,
      S.MilStk,
      S.GaccID,
      S.GAccName,
      S.ChannelCostID,
      S.ChannelCostName,
      S.Percent,
      S.StartDate,
      S.EndDate,
      S.MdsID
    );
END;
