config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["TargetProductGroupSK"],
  bigquery: {
    clusterBy: ["TargetProductGroupSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_sales_target_by_product_group_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.castInt64("t1.Year")},
      ${databuffet.functionData.castInt64("t1.Month")},
      ${databuffet.functionData.cleanString("t1.MarketingGroupID")},
      ${databuffet.functionData.cleanString("t1.SubMarketingID")},
      ${databuffet.functionData.cleanString("t1.SegmentID")},
      ${databuffet.functionData.cleanString("t1.ChannelTargetGroup")},
      ${databuffet.functionData.cleanString("t1.TargetID")}
  ) AS TargetProductGroupSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.castInt64("t1.Year")} AS Year,
  ${databuffet.functionData.castInt64("t1.Month")} AS Month,
  ${databuffet.functionData.cleanString("t1.MarketingGroupID")} AS MarketingGroupID,
  ${databuffet.functionData.cleanString("t1.MarketingGroupName")} AS MarketingGroupName,
  ${databuffet.functionData.cleanString("t1.SubMarketingID")} AS SubMarketingID,
  ${databuffet.functionData.cleanString("t1.SubMarketingName")} AS SubMarketingName,
  ${databuffet.functionData.cleanString("t1.SegmentID")} AS SegmentID,
  ${databuffet.functionData.cleanString("t1.SegmentName")} AS SegmentName,
  ${databuffet.functionData.cleanString("t1.ChannelTargetGroup")} AS ChannelTargetGroup,
  ${databuffet.functionData.cleanString("t1.TargetID")} AS TargetID,
  ${databuffet.functionData.castFloat64("t1.Amt")} AS Amt,
  ${databuffet.functionData.castFloat64("t1.Qty")} AS Qty,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
