config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: [],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_holiday_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  t1.HolidayDate AS HolidayDate,
  ${databuffet.functionData.cleanString("t1.HolidayNameTH")} AS HolidayNameTH,
  ${databuffet.functionData.cleanString("t1.HolidayNameEN")} AS HolidayNameEN,
  ${databuffet.functionData.castInt64("t1.LongWeekEndFlag")} AS LongWeekEndFlag,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
