config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["NotReceiveSK"],
  bigquery: {
    clusterBy: ["NotReceiveSK"],
  },
}

js {
    /*
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;
    */

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_payment_status_not_receive_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.CompanyID")},
      ${databuffet.functionData.castInt64("t1.StatusID")}
  ) AS NotReceiveSK,
  -- dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.CompanyID")} AS CompanyID,
  ${databuffet.functionData.castInt64("t1.StatusID")} AS StatusID,
  ${databuffet.functionData.cleanString("t1.StatusNameTH")} AS StatusNameTH,
  ${databuffet.functionData.cleanString("t1.StatusNameENG")} AS StatusNameENG,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
-- LEFT JOIN `${DimCompanyTableRef}` AS dim_com
--   ON ${databuffet.functionData.cleanString("t1.CompanyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
