config {
  type: "operations",
  dependencies: [],
  tags: [databuffet.TAG_DIM_DAILY],
  hasOutput: true
}

js {
    // Define table references
    const DimProjectTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimProjectTableRef = `${DimProjectTable.database}.${DimProjectTable.schema}.${DimProjectTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;
  SET max_sk = (SELECT IFNULL(MAX(ProjectSK), 0) FROM `${DimProjectTableRef}`);

  -- เริ่มกระบวนการ MERGE
  MERGE `${DimProjectTableRef}` AS T
  USING (
    WITH raw_data AS (
      SELECT
        dim_com.CompanySK,
        dim_com.companyID,
        projectcode as projectCode,
        docno as docNo,
        compname as companyName,
        typecomp as companyType,
        statuscomp as companyStatus,
        compgroup as companyGroup,
        history,
        place,
        district,
        province,
        profilecomp as profileComp,
        projectname as projectName,
        projectfrom as projectFrom,
        pjstart as projectStart,
        pjend as projectEnd,
        (CASE
          WHEN SAFE_CAST(pjstart AS DATE) IS NULL THEN 0
          WHEN SAFE_CAST(pjend AS DATE) IS NULL THEN DATE_DIFF(CURRENT_DATE(), SAFE_CAST(pjstart AS DATE), DAY)
          ELSE DATE_DIFF(SAFE_CAST(pjend AS DATE), SAFE_CAST(pjstart AS DATE), DAY)
        END) as projectDay
      FROM ${ref(databuffet.VALIDATED_MAC5, 'tbook_profilecomp')} as pj
      left join `${DimCompanyTableRef}` as dim_com
        on pj.company_id = dim_com.companyID
      -- WHERE pj.company_id = 'ag01'
    )
    SELECT
      (CASE
        WHEN t2.ProjectSK IS NOT NULL THEN t2.ProjectSK
        ELSE max_sk + ROW_NUMBER() OVER(PARTITION BY (CASE WHEN t2.projectCode IS NULL THEN 1 ELSE 0 END) ORDER BY t1.CompanySK, t1.projectCode)
      END) AS ProjectSK,
      t1.CompanySK,
      t1.companyID,
      t1.projectCode,
      t1.docNo,
      t1.companyName,
      t1.companyType,
      t1.companyStatus,
      t1.companyGroup,
      t1.history,
      t1.place,
      t1.district,
      t1.province,
      t1.profileComp,
      t1.projectName,
      t1.projectFrom,
      t1.projectStart,
      t1.projectEnd,
      t1.projectDay
    FROM raw_data AS t1
    LEFT JOIN `${DimProjectTableRef}` AS t2
      ON t1.projectCode = t2.projectCode
      AND t1.CompanySK = t2.CompanySK
  ) AS S
  ON T.ProjectSK = S.ProjectSK

  -- กรณีเจอข้อมูลเดิม (Update)
  WHEN MATCHED THEN
    UPDATE SET
      T.docNo = S.docNo,
      T.profileComp = S.profileComp,
      T.companyName = S.companyName,
      T.projectName = S.projectName,
      T.companyType = S.companyType,
      T.companyStatus = S.companyStatus,
      T.projectFrom = S.projectFrom,
      T.companyGroup = S.companyGroup,
      T.history = S.history,
      T.place = S.place,
      T.district = S.district,
      T.province = S.province,
      T.projectStart = S.projectStart,
      T.projectEnd = S.projectEnd,
      T.projectDay = S.projectDay

  -- กรณีข้อมูลใหม่ (Insert)
  WHEN NOT MATCHED THEN
    INSERT (
      ProjectSK, CompanySK,
      companyID,
      projectCode, docNo, profileComp, companyName, projectName,
      companyType, companyStatus, projectFrom, companyGroup, history,
      place, district, province, projectStart, projectEnd, projectDay
    )
    VALUES (
      S.ProjectSK, S.CompanySK,
      S.companyID,
      S.projectCode, S.docNo, S.profileComp, S.companyName, S.projectName,
      S.companyType, S.companyStatus, S.projectFrom, S.companyGroup, S.history,
      S.place, S.district, S.province, S.projectStart, S.projectEnd, S.projectDay
    );
END;
