config {
  type: "operations",
  // deb_address_data คือตารางที่อยู่หลัง view_deb_address_data ที่ไฟล์นี้อ่าน
  dependencies: ["dim_company", "deb_address_data"],
  tags: [databuffet.TAG_DIM_DAILY],
  hasOutput: true
}

js {
    // Define table references
    const DimCustomerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimCustomerTableRef = `${DimCustomerTable.database}.${DimCustomerTable.schema}.${DimCustomerTable.name}`;

    const DebAddressTable = {
        database: databuffet.DATABASE,
        schema: databuffet.PROCESS_DATASET,
        name: "view_deb_address_data",
    };
    const DebAddressTableRef = `${DebAddressTable.database}.${DebAddressTable.schema}.${DebAddressTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;
  SET max_sk = (SELECT IFNULL(MAX(CustomerSK), 0) FROM `${DimCustomerTableRef}`);

  -- เริ่มกระบวนการ MERGE
  MERGE `${DimCustomerTableRef}` AS T
  USING (
    WITH match_customer AS (
        SELECT company_id, customer_allkon, customer_mac5
        FROM (
            SELECT
                a.customer_allkon,
                a.customer_mac5,
                a.company_id,
                ROW_NUMBER() OVER(PARTITION BY a.customer_mac5 ORDER BY a.customer_allkon DESC) as rn
            FROM ${ref(databuffet.VALIDATED_MAC5, 'match_customer')} as a
            INNER JOIN (
                SELECT DISTINCT customer_code
                FROM ${ref(databuffet.VALIDATED_CIS360, 'customer_profile')}
            ) b
                ON a.customer_allkon = b.customer_code
        WHERE a.company_id = 'ag01'
        )
        WHERE rn = 1
    ),
    Customer_360 AS (
        SELECT
            cp.*,
            cs.customer_status_name,
            nb.nature_business_code,
            nb.nature_business_name,
            nb.nature_business_name_en,
            ct.customer_type_name,
            ct.customer_type_name_en
        FROM ${ref(databuffet.VALIDATED_CIS360, 'customer_profile')} as cp
        LEFT JOIN ${ref(databuffet.VALIDATED_CIS360, 'customer_status')} as cs
            ON cp.customer_status_id = cs.id
        LEFT JOIN ${ref(databuffet.VALIDATED_CIS360, 'customer_profile_nature_business')} as cpnb
            ON cp.id = cpnb.customer_profile_id
        LEFT JOIN ${ref(databuffet.VALIDATED_CIS360, 'nature_business')} as nb
            ON cpnb.nature_business_id = nb.id
        LEFT JOIN ${ref(databuffet.VALIDATED_CIS360, 'customer_type')} as ct
            ON cp.customer_type_id = ct.id
    ),
    source_data AS (
        SELECT
            deb_address.ProvinceSK as InvoiceProvinceSK,
            deb_address.DistrictSK as InvoiceDistrictSK,
            deb_address.SubDistrictSK as InvoiceSubDistrictSK,
            dim_com.CompanySK,
            dim_com.companyID,
            deb.debcode,
            deb.debdate,
            cp.customer_code,
            cp.prefix_id,
            deb.debnamet,
            cp.first_name,
            cp.last_name,
            deb.debtaxclass,
            cp.full_name,
            cp.customer_status_name,
            deb.debsalesp,
            deb.debxxxx,
            deb.debgrade,
            cp.nature_business_code,
            cp.nature_business_name,
            cp.nature_business_name_en,
            cp.customer_type_name,
            cp.customer_type_name_en,
            deb.debbranch,
            deb.deblimit,
            deb.debgroup,
            deb.DEBcreditTerm,
            deb.debmemo,
            CAST(NULL as STRING) as Customer_CM_Grade,
            DATE_DIFF(CURRENT_DATE(), deb.debdate, YEAR) as Total_contact_time_Year
        FROM ${ref(databuffet.VALIDATED_MAC5, 'deb')} as deb
        LEFT JOIN `${DebAddressTableRef}` as deb_address
            ON deb.debcode = deb_address.debcode
            and deb.company_id = deb_address.company_id
        LEFT JOIN match_customer as mc
            ON deb.debcode = mc.customer_mac5
            and deb.company_id = mc.company_id
        LEFT JOIN Customer_360 as cp
            ON mc.customer_allkon = cp.customer_code
        LEFT JOIN `${DimCompanyTableRef}` as dim_com
            ON deb.company_id = dim_com.companyID
        -- WHERE deb.company_id = 'ag01'
    )

    -- จัดการรัน CustomerSK ต่อจากของเดิม
    SELECT
        (CASE
            WHEN t2.CustomerSK IS NOT NULL THEN t2.CustomerSK
            ELSE max_sk + ROW_NUMBER() OVER(PARTITION BY (CASE WHEN t2.debcode IS NULL THEN 1 ELSE 0 END) ORDER BY t1.CompanySK, t1.debcode)
        END) AS CustomerSK,
        t1.InvoiceProvinceSK,
        t1.InvoiceDistrictSK,
        t1.InvoiceSubDistrictSK,
        t1.CompanySK,
        t1.companyID,
        t1.debcode,
        t1.debdate,
        t1.customer_code,
        t1.prefix_id,
        t1.debnamet,
        t1.first_name,
        t1.last_name,
        t1.debtaxclass,
        t1.full_name,
        t1.customer_status_name,
        t1.debsalesp,
        t1.debxxxx,
        t1.debgrade,
        t1.nature_business_code,
        t1.nature_business_name,
        t1.nature_business_name_en,
        t1.customer_type_name,
        t1.customer_type_name_en,
        t1.debbranch,
        t1.deblimit,
        t1.debgroup,
        t1.DEBcreditTerm,
        t1.debmemo,
        t1.Customer_CM_Grade,
        t1.Total_contact_time_Year
    FROM source_data AS t1
    LEFT JOIN `${DimCustomerTableRef}` AS t2
        ON t1.debcode = t2.debcode
        AND t1.CompanySK = t2.CompanySK

  ) AS S
  ON T.CustomerSK = S.CustomerSK

  WHEN MATCHED THEN
    UPDATE SET
      InvoiceProvinceSK = S.InvoiceProvinceSK,
      InvoiceDistrictSK = S.InvoiceDistrictSK,
      InvoiceSubDistrictSK = S.InvoiceSubDistrictSK,
      debdate = S.debdate,
      customer_code = S.customer_code,
      prefix_id = S.prefix_id,
      debnamet = S.debnamet,
      first_name = S.first_name,
      last_name = S.last_name,
      debtaxclass = S.debtaxclass,
      full_name = S.full_name,
      customer_status_name = S.customer_status_name,
      debsalesp = S.debsalesp,
      debxxxx = S.debxxxx,
      debgrade = S.debgrade,
      nature_business_code = S.nature_business_code,
      nature_business_name = S.nature_business_name,
      nature_business_name_en = S.nature_business_name_en,
      customer_type_name = S.customer_type_name,
      customer_type_name_en = S.customer_type_name_en,
      debbranch = S.debbranch,
      deblimit = S.deblimit,
      debgroup = S.debgroup,
      DEBcreditTerm = S.DEBcreditTerm,
      debmemo = S.debmemo,
      Customer_CM_Grade = S.Customer_CM_Grade,
      Total_contact_time_Year = S.Total_contact_time_Year

  WHEN NOT MATCHED THEN
    INSERT (
      CustomerSK, InvoiceProvinceSK, InvoiceDistrictSK, InvoiceSubDistrictSK, CompanySK,
      companyID, debcode, debdate, customer_code, prefix_id, debnamet,
      first_name, last_name, debtaxclass, full_name, customer_status_name,
      debsalesp, debxxxx, debgrade, nature_business_code, nature_business_name,
      nature_business_name_en, customer_type_name, customer_type_name_en,
      debbranch, deblimit, debgroup, DEBcreditTerm, debmemo, Customer_CM_Grade, Total_contact_time_Year
    )
    VALUES (
      S.CustomerSK, S.InvoiceProvinceSK, S.InvoiceDistrictSK, S.InvoiceSubDistrictSK, S.CompanySK,
      S.companyID, S.debcode, S.debdate, S.customer_code, S.prefix_id, S.debnamet,
      S.first_name, S.last_name, S.debtaxclass, S.full_name, S.customer_status_name,
      S.debsalesp, S.debxxxx, S.debgrade, S.nature_business_code, S.nature_business_name,
      S.nature_business_name_en, S.customer_type_name, S.customer_type_name_en,
      S.debbranch, S.deblimit, S.debgroup, S.DEBcreditTerm, S.debmemo, S.Customer_CM_Grade, S.Total_contact_time_Year
    );
END;
