config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["RebateSK"],
  bigquery: {
    clusterBy: ["RebateSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsRebateTable = {
        database: databuffet.DATABASE,
        schema: databuffet.MDS_DATASET,
        name: "mds_data_sales_kpi_condition_master",
    };
    const MdsRebateTableRef = `${MdsRebateTable.database}.${MdsRebateTable.schema}.${MdsRebateTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString('t1.companyID')},
      ${databuffet.functionData.cleanString('t1.rebate')},
      ${databuffet.functionData.cleanString('t1.status')}
  ) AS RebateSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString('t1.companyID')}  AS companyID,
  ${databuffet.functionData.cleanString('t1.rebate')}     AS rebate,
  ${databuffet.functionData.cleanString('t1.rebateName')} AS rebateName,
  ${databuffet.functionData.cleanString('t1.status')}     AS status,
  ${databuffet.functionData.cleanString('t1.type')}       AS type,
  ${databuffet.functionData.cleanString('t1.salesExc')}   AS salesExc,
  ${databuffet.functionData.cleanString('t1.accExc')}     AS accExc,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsRebateTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString('t1.companyID')} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
