config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["CollectSK"],
  bigquery: {
    clusterBy: ["CollectSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_collection_status_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.CompanyID")},
      ${databuffet.functionData.castInt64("t1.Year")},
      ${databuffet.functionData.castInt64("t1.Month")},
      ${databuffet.functionData.castInt64("t1.CustomerID")}
  ) AS CollectSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.CompanyID")} AS CompanyID,
  ${databuffet.functionData.castInt64("t1.Year")} AS Year,
  ${databuffet.functionData.castInt64("t1.Month")} AS Month,
  ${databuffet.functionData.castInt64("t1.CustomerID")} AS CustomerID,
  ${databuffet.functionData.cleanString("t1.CustomerName")} AS CustomerName,
  ${databuffet.functionData.cleanString("t1.Actions")} AS Actions,
  ${databuffet.functionData.cleanString("t1.Justification")} AS Justification,
  ${databuffet.functionData.cleanString("t1.Responsible")} AS Responsible,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.CompanyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
