config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company", "dim_department_last", "dim_director_last", "update_sk_sale_rep_group"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["RateTargetSK"],
  bigquery: {
    clusterBy: ["RateTargetSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_target_rate_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;

    const DimDepartmentLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department_last",
    };
    const DimDepartmentLastTableRef = `${DimDepartmentLastTable.database}.${DimDepartmentLastTable.schema}.${DimDepartmentLastTable.name}`;

    const DimDirectorLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director_last",
    };
    const DimDirectorLastTableRef = `${DimDirectorLastTable.database}.${DimDirectorLastTable.schema}.${DimDirectorLastTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.castInt64("t1.Year")},
      ${databuffet.functionData.castInt64("t1.Month")},
      ${databuffet.functionData.cleanString("t1.ProductGroupID")},
      ${databuffet.functionData.cleanString("t1.TargetID")},
      ${databuffet.functionData.cleanString("t1.TargetDepartmentID")},
      ${databuffet.functionData.cleanString("t1.DepartmentID")},
      ${databuffet.functionData.cleanString("t1.EmployeeID")}
  ) AS RateTargetSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.castInt64("t1.Year")} AS Year,
  ${databuffet.functionData.castInt64("t1.Month")} AS Month,
  t1.startdate as StartDate,
  t1.enddate as EndDate,
  ${databuffet.functionData.cleanString("t1.ProductGroupID")} AS ProductGroupID,
  ${databuffet.functionData.cleanString("t1.ProductGroupName")} AS ProductGroupName,
  ${databuffet.functionData.cleanString("t1.TargetID")} AS TargetID,
  ${databuffet.functionData.cleanString("t1.TargetName")} AS TargetName,
  ${databuffet.functionData.cleanString("t1.TargetDepartmentID")} AS TargetDepartmentID,
  ${databuffet.functionData.cleanString("t1.TargetDepartmentName")} AS TargetDepartmentName,
  ${databuffet.functionData.cleanString("t1.DepartmentID")} AS DepartmentID,
  ${databuffet.functionData.cleanString("t1.EmployeeID")} AS EmployeeID,
  ${databuffet.functionData.cleanString("t1.EmployeeName")} AS EmployeeName,
  ${databuffet.functionData.castFloat64("t1.Percent")} AS Percent,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {
  BEGIN
    -- DECLARE static_count BIGNUMERIC;
    DECLARE max_total_employee BIGNUMERIC;

    -- 1. สร้าง Temp Table หลักสำหรับ MDT เท่านั้น
    CREATE OR REPLACE TEMP TABLE mdt_base_data AS
    SELECT
      rate.year,
      rate.month,
      rate.targetid,
      rate.employeeid,
      rate.departmentid,
    FROM ${self()} AS rate
    INNER JOIN `${DimDepartmentLastTableRef}` AS dep
      ON rate.DepartmentID = dep.DepartmentID
    INNER JOIN `${DimDirectorLastTableRef}` AS dir
      ON dep.DirectorSK = dir.DirectorSK
    WHERE dir.DirectorName = 'MDT';

    -- หาค่า count ของเดือนที่เป็น NULL
    -- SET static_count = (
    --   SELECT (CAST(COUNT(DISTINCT CONCAT(employeeid, '-', departmentid)) AS BIGNUMERIC) / CAST(6 AS BIGNUMERIC))
    --   FROM mdt_base_data
    --   WHERE month IS NULL
    -- );

    -- 2. คำนวณค่ารายเดือนและหาค่า MAX
    CREATE OR REPLACE TEMP TABLE monthly_summary AS
    SELECT
      year,
      month,
      targetid,
      ( CAST( COUNT( DISTINCT CONCAT(employeeid, '-', departmentid) ) AS BIGNUMERIC ) ) AS total_val
    FROM mdt_base_data
    WHERE month IS NOT NULL
    GROUP BY 1, 2, 3;

    -- อัปเดตรายเดือน
    UPDATE ${self()} AS target
    SET target.Percent = (CAST(100 AS BIGNUMERIC) / CAST(src.total_val AS BIGNUMERIC))
    FROM monthly_summary AS src
    WHERE target.year = src.year
      AND target.month = src.month
      AND target.TargetID = src.targetid;

    -- หาค่า max ของของทุกเดือน
    -- SET max_total_employee = (SELECT MAX(total_val) FROM monthly_summary);

    -- อัปเดตแถว NULL (ใช้ค่า MAX)
    -- UPDATE ${self()} AS target
    -- SET target.Percent = (CAST(100 AS BIGNUMERIC) / max_total_employee)
    -- WHERE target.month IS NULL
    --   AND target.DepartmentID IN (SELECT DISTINCT departmentid FROM mdt_base_data);

    -- 3. ล้าง Temp Tables
    DROP TABLE IF EXISTS mdt_base_data;
    DROP TABLE IF EXISTS monthly_summary;
  END;
}
