config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["ChannelSK"],
  bigquery: {
    clusterBy: ["ChannelSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_channel_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.cleanString("t1.DepCode")}
  ) AS ChannelSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.cleanString("t1.DepCode")} AS DepCode,
  ${databuffet.functionData.cleanString("t1.DepGroup")} AS DepGroup,
  ${databuffet.functionData.cleanString("t1.DepDesct")} AS DepDesct,
  ${databuffet.functionData.cleanString("t1.DepDesce")} AS DepDesce,
  ${databuffet.functionData.cleanString("t1.ChannelGroup")} AS ChannelGroup,
  ${databuffet.functionData.cleanString("t1.ChannelSubGroupName1")} AS ChannelSubGroupName1,
  ${databuffet.functionData.cleanString("t1.ChannelSubGroupName2")} AS ChannelSubGroupName2,
  ${databuffet.functionData.cleanString("t1.ChannelSubGroupName3")} AS ChannelSubGroupName3,
  ${databuffet.functionData.cleanString("t1.ChannelID")} AS ChannelID,
  ${databuffet.functionData.cleanString("t1.ChannelName")} AS ChannelName,
  ${databuffet.functionData.cleanString("t1.ChannelCostID")} AS ChannelCostID,
  ${databuffet.functionData.cleanString("t1.ChannelCostName")} AS ChannelCostName,
  ${databuffet.functionData.cleanString("t1.ChannelGroupFinance")} AS ChannelGroupFinance,
  ${databuffet.functionData.cleanString("t1.ChannelSubGroupFinance1")} AS ChannelSubGroupFinance1,
  ${databuffet.functionData.cleanString("t1.ChannelSubGroupFinance2")} AS ChannelSubGroupFinance2,
  ${databuffet.functionData.cleanString("t1.ChannelSubGroupFinance3")} AS ChannelSubGroupFinance3,
  ${databuffet.functionData.cleanString("t1.ChannelIDFinance")} AS ChannelIDFinance,
  ${databuffet.functionData.cleanString("t1.ChannelNameFinance")} AS ChannelNameFinance,
  ${databuffet.functionData.cleanString("t1.ChannelDSite01")} AS ChannelDSite01,
  ${databuffet.functionData.cleanString("t1.ChannelDDepartment02")} AS ChannelDDepartment02,
  ${databuffet.functionData.cleanString("t1.ChannelDDivision03")} AS ChannelDDivision03,
  ${databuffet.functionData.cleanString("t1.ChannelDSubDivision04")} AS ChannelDSubDivision04,
  ${databuffet.functionData.cleanString("t1.DummyChannel")} AS DummyChannel,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
