config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["BounceChequeSK"],
  bigquery: {
    clusterBy: ["BounceChequeSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_custgrade_cheque_score_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.castFloat64("t1.BouncedChequeMin")},
      ${databuffet.functionData.castFloat64("t1.BouncedChequeMax")},
      t1.StartDate,
      t1.EndDate
  ) AS BounceChequeSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.castFloat64("t1.BouncedChequeMin")} AS BouncedChequeMin,
  ${databuffet.functionData.castFloat64("t1.BouncedChequeMax")} AS BouncedChequeMax,
  ${databuffet.functionData.castFloat64("t1.Score")} AS Score,
  t1.StartDate,
  t1.EndDate,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
