config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["ProductMasterFcSK"],
  bigquery: {
    clusterBy: ["ProductMasterFcSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_product_finance_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.cleanString("t1.Barcode")}
  ) AS ProductMasterFcSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.cleanString("t1.ProductIDOldMac5")} AS ProductIDOldMac5,
  ${databuffet.functionData.cleanString("t1.ProductNameOldMac5")} AS ProductNameOldMac5,
  ${databuffet.functionData.cleanString("t1.ProductIDNewD365")} AS ProductIDNewD365,
  ${databuffet.functionData.cleanString("t1.ProductNameNewD365")} AS ProductNameNewD365,
  ${databuffet.functionData.cleanString("t1.SerchName")} AS SerchName,
  ${databuffet.functionData.cleanString("t1.Size")} AS Size,
  ${databuffet.functionData.cleanString("t1.SizeDescription")} AS SizeDescription,
  ${databuffet.functionData.cleanString("t1.Color")} AS Color,
  ${databuffet.functionData.cleanString("t1.ColorDescription")} AS ColorDescription,
  ${databuffet.functionData.cleanString("t1.Style")} AS Style,
  ${databuffet.functionData.cleanString("t1.StyleDescription")} AS StyleDescription,
  ${databuffet.functionData.cleanString("t1.Config")} AS Config,
  ${databuffet.functionData.cleanString("t1.ConfigDescription")} AS ConfigDescription,
  ${databuffet.functionData.cleanString("t1.ProductNumber")} AS ProductNumber,
  ${databuffet.functionData.cleanString("t1.ProductDescription")} AS ProductDescription,
  ${databuffet.functionData.cleanString("t1.Unit")} AS Unit,
  ${databuffet.functionData.cleanString("t1.NetWeight")} AS NetWeight,
  ${databuffet.functionData.cleanString("t1.GrossWeight")} AS GrossWeight,
  ${databuffet.functionData.cleanString("t1.DeepMM")} AS DeepMM,
  ${databuffet.functionData.cleanString("t1.WideMM")} AS WideMM,
  ${databuffet.functionData.cleanString("t1.HeightMM")} AS HeightMM,
  ${databuffet.functionData.castInt64("t1.DoNotStackOverLayer")} AS DoNotStackOverLayer,
  ${databuffet.functionData.cleanString("t1.Barcode")} AS Barcode,
  ${databuffet.functionData.cleanString("t1.ItemGroup")} AS ItemGroup,
  ${databuffet.functionData.cleanString("t1.ItemGroupName")} AS ItemGroupName,
  ${databuffet.functionData.cleanString("t1.TM1Category")} AS TM1Category,
  ${databuffet.functionData.cleanString("t1.TM2Brand")} AS TM2Brand,
  ${databuffet.functionData.cleanString("t1.TM3Series")} AS TM3Series,
  ${databuffet.functionData.cleanString("t1.TM4FactorySection")} AS TM4FactorySection,
  ${databuffet.functionData.cleanString("t1.TM5Material")} AS TM5Material,
  ${databuffet.functionData.cleanString("t1.TM6PackageShape")} AS TM6PackageShape,
  ${databuffet.functionData.cleanString("t1.Remark")} AS Remark,
  ${databuffet.functionData.cleanString("t1.PurchaseUnit")} AS PurchaseUnit,
  ${databuffet.functionData.cleanString("t1.UnitConversions")} AS UnitConversions,
  ${databuffet.functionData.cleanString("t1.ToUnit")} AS ToUnit,
  ${databuffet.functionData.cleanString("t1.SalesUnit")} AS SalesUnit,
  ${databuffet.functionData.cleanString("t1.PackSize")} AS PackSize,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
