config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["RegionManagerSK"],
  bigquery: {
    clusterBy: ["RegionManagerSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_sales_region_manager_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.cleanString("t1.RegionID")},
      ${databuffet.functionData.cleanString("t1.SubRegionID")},
      t1.StartDate,
      t1.EndDate
  ) AS RegionManagerSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.cleanString("t1.RegionID")} AS RegionID,
  ${databuffet.functionData.cleanString("t1.SubRegionID")} AS SubRegionID,
  ${databuffet.functionData.cleanString("t1.RegionName")} AS RegionName,
  ${databuffet.functionData.cleanString("t1.RegionManagerEmployeeID")} AS RegionManagerEmployeeID,
  ${databuffet.functionData.cleanString("t1.RegionManagerName")} AS RegionManagerName,
  ${databuffet.functionData.cleanString("t1.RegionManagerSurname")} AS RegionManagerSurname,
  ${databuffet.functionData.cleanString("t1.RegionManagerNickname")} AS RegionManagerNickname,
  t1.StartDate AS StartDate,
  t1.EndDate AS EndDate,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
