config {
  type: "operations",
  dependencies: ["dim_company", "dim_customer", "dim_invoice"],
  tags: [databuffet.TAG_DIM_DAILY],
  hasOutput: true
}

js {
    const DimAgingTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimAgingTableRef = `${DimAgingTable.database}.${DimAgingTable.schema}.${DimAgingTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimCustomerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_customer",
    };
    const DimCustomerTableRef = `${DimCustomerTable.database}.${DimCustomerTable.schema}.${DimCustomerTable.name}`;

    const DimInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_invoice",
    };
    const DimInvoiceTableRef = `${DimInvoiceTable.database}.${DimInvoiceTable.schema}.${DimInvoiceTable.name}`;

    const DimAgingHistoryTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_aging_history",
    };
    const DimAgingHistoryTableRef = `${DimAgingHistoryTable.database}.${DimAgingHistoryTable.schema}.${DimAgingHistoryTable.name}`;

    const DimAgingView = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_aging",
    };
    const DimAgingViewRef = `${DimAgingView.database}.${DimAgingView.schema}.${DimAgingView.name}`;

    const FactBillingTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: "fact_mir_vs",
    };
    const FactBillingTableRef = `${FactBillingTable.database}.${FactBillingTable.schema}.${FactBillingTable.name}`;

    const DimStatusNotReceiveTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_status_not_receive",
    };
    const DimStatusNotReceiveTableRef = `${DimStatusNotReceiveTable.database}.${DimStatusNotReceiveTable.schema}.${DimStatusNotReceiveTable.name}`;

    const CfsClose2024Table = {
        database: databuffet.DATABASE,
        schema: databuffet.ONETIME,
        name: "cfsinvclose2024",
    };
    const CfsClose2024TableRef = `${CfsClose2024Table.database}.${CfsClose2024Table.schema}.${CfsClose2024Table.name}`;

}

create or replace table `${DimAgingTableRef}`
cluster by AgingSK
as
with chq as (
  SELECT
    cql.company_id, cql.cqlvnos,
    max(ex.extract_date) as extract_date, 
    sum(ex.extract_amount) as extract_amount
  FROM ${ref(databuffet.VALIDATED_MAC5, "chq")} as chq
  , UNNEST(extract_value) as ex
  INNER JOIN (
    select distinct company_id, cqlno, cqlvnos, 
    from ${ref(databuffet.VALIDATED_MAC5, "cql")}
  ) as cql 
    ON chq.chqno = cql.cqlno 
    and chq.company_id = cql.company_id
  WHERE ex.extract_date is not null
    and ex.extract_date <= CURRENT_DATE('Asia/Bangkok')
  group by 1,2

), normal_mir_summary AS (
  SELECT 
    company_id,
    mirbinvno,
    SUM(mirsum) as total_normal_paid
  FROM ${ref(databuffet.VALIDATED_MAC5, "mir")}
  WHERE mirtype = 'RS'
    AND (company_id, mirvnos) NOT IN (
       SELECT AS STRUCT company_id, cqlvnos 
       FROM chq
    )
    AND PARSE_DATE('%Y%m%d', CONCAT(CAST(miryear AS STRING), FORMAT('%02d', mirmonth), FORMAT('%02d', mirday))) <= CURRENT_DATE('Asia/Bangkok')
  GROUP BY 1,2

), edit_mir_raw AS (
  SELECT 
    mir.company_id,
    mir.mirbinvno, 
    mir.mirbinvdate,
    mir.mirvnos, 
    (COALESCE(mih.mihnetsum, 0) - COALESCE(norm.total_normal_paid, 0)) as adjusted_mihnetsum,
    ri.extract_date, 
    ri.extract_amount
  FROM ${ref(databuffet.VALIDATED_MAC5, "mir")} as mir
  INNER JOIN chq as ri 
    ON mir.company_id = ri.company_id 
    and mir.mirvnos = ri.cqlvnos
  LEFT JOIN ${ref(databuffet.CURATED_MAC5, "curated_mih")} as mih
    ON mir.company_id = mih.company_id
    AND mir.mirbinvno = mih.mihvnos
    AND mir.mirbinvtype = mih.mihtype
  LEFT JOIN normal_mir_summary as norm
    ON mir.company_id = norm.company_id
    AND mir.mirbinvno = norm.mirbinvno
  WHERE mir.mirtype = 'RS'
    AND PARSE_DATE('%Y%m%d', CONCAT(CAST(mir.miryear AS STRING), FORMAT('%02d', mir.mirmonth), FORMAT('%02d', mir.mirday))) <= CURRENT_DATE('Asia/Bangkok')

), running_calculations AS (
  SELECT 
    *,
    SUM(adjusted_mihnetsum) OVER (PARTITION BY company_id, mirvnos ORDER BY mirbinvdate, mirbinvno) as accum_mihnetsum,
    COALESCE(SUM(adjusted_mihnetsum) OVER (PARTITION BY company_id, mirvnos ORDER BY mirbinvdate, mirbinvno 
              ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) as cut_accum_amount
  FROM edit_mir_raw

), edit_mir as (
  SELECT
    company_id,
    mirbinvno,
    mirvnos,
    extract_date,
    ROUND(
      GREATEST(0, LEAST(adjusted_mihnetsum, extract_amount - cut_accum_amount)), 
      2
    ) as mirsum,

    -- company_id,
    -- mirbinvno,
    -- mirbinvdate,
    -- mirvnos,
    -- ปรับปัดเศษ 2 ตำแหน่งในส่วนแสดงผล
    -- ROUND(adjusted_mihnetsum, 2) as adjusted_mihnetsum,
    -- extract_date,
    -- ROUND(extract_amount, 2) as extract_amount,
    -- ROUND(accum_mihnetsum, 2) as accum_mihnetsum,
    -- ROUND(cut_accum_amount, 2) as cut_accum_amount,
    
    -- คำนวณยอดจ่ายและปัดเศษ
    -- ROUND(
    --   GREATEST(0, LEAST(adjusted_mihnetsum, extract_amount - cut_accum_amount)), 
    --   2
    -- ) as mirsum,
    
    -- คำนวณยอดคงเหลือและปัดเศษ
    -- ROUND(
    --   adjusted_mihnetsum - GREATEST(0, LEAST(adjusted_mihnetsum, extract_amount - cut_accum_amount)), 
    --   2
    -- ) as new_outstanding
  FROM running_calculations

), mir as (
  select 
    mir.company_id,
    mir.mirbinvno,
    SUM( IF(e_mir.mirvnos is not null, e_mir.mirsum, IFNULL(mir.mirsum, 0.00)) ) as mirsum,
    MIN( IF(e_mir.mirvnos is not null, e_mir.extract_date, PARSE_DATE('%Y%m%d', CONCAT(CAST(mir.miryear AS STRING), FORMAT('%02d', mir.mirmonth), FORMAT('%02d', mir.mirday)))) ) as MinReceiveDate,
    MAX( IF(e_mir.mirvnos is not null, e_mir.extract_date, PARSE_DATE('%Y%m%d', CONCAT(CAST(mir.miryear AS STRING), FORMAT('%02d', mir.mirmonth), FORMAT('%02d', mir.mirday)))) ) as MaxReceiveDate,
    COUNT(DISTINCT IF(mir.miryear <= 2023 and exc_status.CompanyID is not null, TRUE, NULL)) as status_complete,
  from ${ref(databuffet.VALIDATED_MAC5, "mir")} as mir
  inner join ${ref(databuffet.CURATED_MAC5, "curated_mih")} as mih
    on mir.company_id = mih.company_id
    and mir.mirvnos = mih.mihvnos
    and mir.mirtype = mih.mihtype
    and mih.mihcancel = 0
  left join edit_mir as e_mir
    on mir.company_id = e_mir.company_id
    and mir.mirvnos = e_mir.mirvnos
    and mir.mirbinvno = e_mir.mirbinvno
left join `${DimStatusNotReceiveTableRef}` as exc_status
    on mir.company_id = exc_status.CompanyID
    and mih.mihstatus = exc_status.StatusID
  where mir.mirtype = 'RS'
    and (
      -- (mir.miryear <= 2022 and mih.mihstatus = 7)
      ( mir.miryear <= 2023 and exc_status.CompanyID is not null )
      or 
      ( exc_status.CompanyID is null )
    )
    and PARSE_DATE('%Y%m%d', CONCAT(CAST(mir.miryear AS STRING), FORMAT('%02d', mir.mirmonth), FORMAT('%02d', mir.mirday))) <= CURRENT_DATE('Asia/Bangkok')
  group by 1,2

), mie as (
  select 
    company_id, mietype, mievnos, 
    MAX(COALESCE(
      SAFE.PARSE_DATE('%d/%m/%Y', SUBSTR(mie.MIEctermDX, 1, 10)),
      SAFE.PARSE_DATE('%d/%m/%Y', SUBSTR(mie.MIEctermDX, 1, 9)),
      SAFE.PARSE_DATE('%d/%m/%y', SUBSTR(mie.MIEctermDX, 1, 7))
    )) as DueDate
  from ${ref(databuffet.VALIDATED_MAC5, "mie")} as mie
  group by 1,2,3

), main_is_raw as (
  select 
    mih.company_id as CompanyID, 
    mih.mihVnos as InvoiceNo,
    mih.mihType as InvoiceType,
    mih.mihCus as CustomerID,
    PARSE_DATE('%Y%m%d', CONCAT(mih.mihYear, FORMAT("%02d", mih.mihMonth),  mih.mihDay)) as InvoiceDate, 
    mih.mihJob,
    mih.mihDep,
    mih.mihPer,
    mih.mihNotes,
    mih.mihstanding as TransCreditTerm,
    mih.mihNetSum as TotalAmount,
  from ${ref(databuffet.CURATED_MAC5, "curated_mih")} as mih
  where mih.mihType = 'IS'
    and mih.mihcancel = 0
    and PARSE_DATE('%Y%m%d', CONCAT(CAST(mih.mihyear AS STRING), FORMAT('%02d', mih.mihmonth), FORMAT('%02d', mih.mihday))) <= CURRENT_DATE('Asia/Bangkok')
    and not exists (select 1 from `${CfsClose2024TableRef}` as fix where mih.mihVnos = fix.cfsvnosid and mih.company_id = 'ag01')

), main_bs_as_raw as (
  select 
    mih.company_id as CompanyID, 
    mih.mihVnos as InvoiceNo,
    IF(skip_inv.cfsvnosid is null, mil.milLinkVcno, null) as InvoiceRef,
    mih.mihType as InvoiceType,
    mih.mihCus as CustomerID,
    PARSE_DATE('%Y%m%d', CONCAT(mih.mihYear, FORMAT("%02d", mih.mihMonth),  mih.mihDay)) as InvoiceDate, 
    mih.mihJob,
    mih.mihDep,
    mih.mihPer,
    mih.mihNotes,
    mih.mihstanding as TransCreditTerm,
    mih.mihNetSum as TotalAmount,
    (mil.milSum * 1.07) as InvoiceAmount
  from ${ref(databuffet.CURATED_MAC5, "curated_mih")} as mih
  left join ${ref(databuffet.CURATED_MAC5, "curated_mil")} as mil
    on mih.company_id = mil.company_id
    and mih.mihDay = mil.milDay
    and mih.mihMonth = mil.milMonth
    and mih.mihYear = mil.milYear
    and mih.mihVnos = mil.milVnos
    and mih.mihCus = mil.milCus
  left join `${CfsClose2024TableRef}` as skip_inv
    on mih.company_id = 'ag01'
    and mil.milLinkVcno = skip_inv.cfsvnosid
  where mih.mihType in ('BS', 'AS')
    and (mih.company_id, mih.mihStatus) not in (
        select DISTINCT AS STRUCT company_id, ar_scode
        from ${ref(databuffet.VALIDATED_MAC5, "ar_s")}
        where ar_snamet in ('เงินมัดจำรับล่วงหน้า', 'ยกเลิกใบกำกับภาษี', 'ยกเลิกลดหนี้', 'ยกเลิก', 'เงินมัดจำรับล่วงหน้า 214025')
      )
    and PARSE_DATE('%Y%m%d', CONCAT(CAST(mih.mihyear AS STRING), FORMAT('%02d', mih.mihmonth), FORMAT('%02d', mih.mihday))) <= CURRENT_DATE('Asia/Bangkok')
    and not exists (select 1 from `${CfsClose2024TableRef}` as fix where mih.mihVnos = fix.cfsvnosid and mih.company_id = 'ag01')

), main_bs_as as (
  select 
    CompanyID, 
    InvoiceNo,
    STRING_AGG(DISTINCT InvoiceRef, '|') as InvoiceRef,
    InvoiceType,
    CustomerID,
    InvoiceDate, 
    mihJob,
    mihDep,
    mihPer,
    mihNotes,
    MAX(TransCreditTerm) as TransCreditTerm,
    ROUND(MAX(IFNULL(TotalAmount, 0.00)), 2) as TotalAmount,
    ROUND(SUM(IF(InvoiceType = 'BS', IFNULL(InvoiceAmount, 0.00), 0.00)), 2) as CnAmount,
    ROUND(SUM(IF(InvoiceType = 'AS', IFNULL(InvoiceAmount, 0.00), 0.00)), 2) as DnAmount
  from main_bs_as_raw
  group by 1,2,4,5,6,7,8,9,10

), main_is AS (
  SELECT 
    t_is.CompanyID, 
    t_is.InvoiceNo,
    STRING_AGG(DISTINCT t_bs_as.InvoiceNo, '|') as InvoiceRef,
    t_is.InvoiceType,
    t_is.CustomerID,
    t_is.InvoiceDate,
    t_is.mihJob,
    t_is.mihDep,
    t_is.mihPer,
    t_is.mihNotes,
    MAX(t_is.TransCreditTerm) as TransCreditTerm,
    ROUND(MAX(IFNULL(t_is.TotalAmount, 0.00)), 2) as TotalAmount,
    ROUND(SUM(IF(t_bs_as.InvoiceType = 'BS' and mir.MinReceiveDate is null, IFNULL(t_bs_as.InvoiceAmount, 0.00), 0.00)), 2) as CnAmount,
    ROUND(SUM(IF(t_bs_as.InvoiceType = 'AS' and mir.MinReceiveDate is null, IFNULL(t_bs_as.InvoiceAmount, 0.00), 0.00)), 2) as DnAmount,
  FROM main_is_raw as t_is
  LEFT JOIN main_bs_as_raw as t_bs_as
    on t_is.CompanyID = t_bs_as.CompanyID
    and t_is.InvoiceNo = t_bs_as.InvoiceRef
  LEFT JOIN mir as mir
    on t_bs_as.CompanyID = mir.company_id
    and t_bs_as.InvoiceNo = mir.mirbinvno
  group by 1,2,4,5,6,7,8,9,10

), final_main_mix as (
  select distinct
    main.* except(TotalAmount, CnAmount, DnAmount), 
    COALESCE(mie.DueDate, (main.InvoiceDate + main.TransCreditTerm)) as DueDate,
    (main.InvoiceDate + main.TransCreditTerm) as RealDueDate,
    main.TransCreditTerm as CalCreditTerm,
    mir.MinReceiveDate,
    mir.MaxReceiveDate,
    main.TotalAmount,
    (CASE 
      WHEN mir.status_complete = 1 THEN main.TotalAmount
      ELSE IFNULL(mir.mirsum, 0.00)
    END) as RiAmount,
    main.CnAmount,	
    main.DnAmount,
    (CASE 
      WHEN mir.status_complete = 1 THEN 0 
      ELSE ROUND(
                main.TotalAmount
                - (CASE 
                    WHEN mir.status_complete = 1 THEN main.TotalAmount
                    ELSE IFNULL(mir.mirsum, 0.00)
                  END)
                + main.CnAmount
                + main.DnAmount
              , 2)
    END) as OutStanding,

  from main_is as main
  left join mie as mie
    on main.CompanyID = mie.company_id
    and main.InvoiceType = mie.mietype
    and main.InvoiceNo = mie.mievnos
  left join mir as mir
    on main.CompanyID = mir.company_id
    and main.InvoiceNo = mir.mirbinvno
  -- where not exists (select 1 from `${CfsClose2024TableRef}` as fix where main.InvoiceNo = fix.cfsvnosid and main.CompanyID = 'ag01')

  union all
  select distinct
    main.* except(TotalAmount, CnAmount, DnAmount), 
    COALESCE(mie.DueDate, (main.InvoiceDate + main.TransCreditTerm)) as DueDate,
    (main.InvoiceDate + main.TransCreditTerm) as RealDueDate,
    main.TransCreditTerm as CalCreditTerm,
    mir.MinReceiveDate,
    mir.MaxReceiveDate,
    main.TotalAmount,
    (CASE 
      WHEN mir.MinReceiveDate is not null THEN main.TotalAmount
      ELSE 0.00
    END) as RiAmount,
    0.00 as CnAmount,	
    0.00 as DnAmount,
    (CASE 
      WHEN mir.status_complete = 1 THEN 0
      WHEN mir.MinReceiveDate is not null THEN 0.00
      WHEN main.InvoiceRef is null THEN main.TotalAmount
      ELSE ROUND(
              main.TotalAmount
              - IF(InvoiceType = 'BS', main.CnAmount, 0.00)
              - IF(InvoiceType = 'AS', main.DnAmount, 0.00)
            , 2)
    END) as OutStanding,

  from main_bs_as as main
  left join mie as mie
    on main.CompanyID = mie.company_id
    and main.InvoiceType = mie.mietype
    and main.InvoiceNo = mie.mievnos
  left join mir as mir
    on main.CompanyID = mir.company_id
    and main.InvoiceNo = mir.mirbinvno
  -- where not exists (select 1 from `${CfsClose2024TableRef}` as fix where main.InvoiceNo = fix.cfsvnosid and main.CompanyID = 'ag01')

), group_data as (
  select distinct
    companyID, InvoiceNo,
    IF(InvoiceType = 'IS', InvoiceNo, InvoiceRefValue) as invoiceIS, 
    IF(InvoiceType in ('BS', 'AS'), InvoiceNo, InvoiceRefValue) as invoiceBSAS,
  from final_main_mix
  left join unnest(SPLIT(InvoiceRef, '|')) as InvoiceRefValue

), base_pairs AS (
  -- 1. เตรียมข้อมูลพื้นฐาน ล็อคด้วย companyID
  SELECT DISTINCT companyID, invoiceIS AS a, invoiceBSAS AS b FROM group_data
  UNION DISTINCT
  SELECT DISTINCT companyID, invoiceBSAS AS a, invoiceIS AS b FROM group_data

), hop_2 AS (
  -- hop_2: ระยะ 2 ทอด
  SELECT 
    t1.companyID, t1.a, 
    MIN(LEAST(t1.a, t1.b, t2.b)) as min_node
  FROM base_pairs as t1
  INNER JOIN base_pairs as t2 
    ON t1.b = t2.a 
    AND t1.companyID = t2.companyID
  GROUP BY 1, 2

), hop_4 AS (
  -- hop_4: ระยะ 4 ทอด
  SELECT 
    t1.companyID, t1.a, 
    MIN(LEAST(t1.a, t1.min_node, t2.min_node)) as final_group_id
  FROM hop_2 as t1
  INNER JOIN hop_2 as t2 
    ON t1.min_node = t2.a 
    AND t1.companyID = t2.companyID
  GROUP BY 1, 2

), hop_8 AS (
  -- hop_8: ระยะ 8 ทอด
  SELECT 
    t1.companyID, t1.a, 
    MIN(LEAST(t1.a, t1.final_group_id, t2.final_group_id)) as super_group_id
  FROM hop_4 as t1
  INNER JOIN hop_4 as t2 
    ON t1.final_group_id = t2.a 
    AND t1.companyID = t2.companyID
  GROUP BY 1, 2

), group_data_final as (
  SELECT 
    t.companyID, 
    t.InvoiceNo,
    -- หาค่าที่น้อยที่สุดจากทุก "ทางเชื่อม" ที่ Invoice นี้มี
    MIN(COALESCE(g.super_group_id, t.invoiceIS, t.InvoiceNo)) as group_id
  FROM group_data as t
  LEFT JOIN hop_8 as g 
    ON  t.invoiceIS = g.a 
    AND t.companyID = g.companyID
  GROUP BY 1, 2

), dim_invoice as (
  select InvoiceSK, CompanySK, mihVnos
  from `${DimInvoiceTableRef}`
  qualify row_number() over(partition by CompanySK, mihVnos order by InvoiceSK) = 1

), final as (
  select
    row_number() over(order by dim_com.CompanySK, final.InvoiceNo, final.InvoiceDate) as AgingSK,
    vs.BillingSK,
    dim_cus.CustomerSK,
    inv.InvoiceSK,
    dim_com.CompanySK,
    dim_com.companyID,
    final.DueDate as dueDate,
    final.RealDueDate as realDueDate,
    final.InvoiceDate as invoiceDate,

    final.InvoiceNo as cfsVnosID,
    final.InvoiceType as cfsTypeID,

    final.mihJob as cfsJob,
    final.mihDep as cfsDep,
    final.mihPer as cfsPer,

    final.CustomerID as debCode,
    dim_cus.debnamet as debName,
    final.CalCreditTerm as calCreditTerm,
    dim_cus.DEBcreditTerm as debCreditTerm,
    final.TransCreditTerm as transCreditTerm,
    dim_cus.debLimit,
    dim_cus.debMemo,

    CAST(NULL AS STRING) as channel,
    CAST(NULL AS STRING) as mihRef2,
    final.mihNotes as mihNote,
    final.InvoiceRef as mihRef1,

    final.TotalAmount,
    final.RiAmount as PaymentAmount,
    final.CnAmount as CreditNoteAmount,
    final.DnAmount as DebitNoteAmount,
    final.OutStanding,

    (CASE 
      WHEN EXTRACT(YEAR FROM final.InvoiceDate) < 2023
        and IF(OutStanding between -1 and 1, 'Completed', 'Non-Completed') = 'Non-Completed'
          THEN IF( 
                  IFNULL(
                    (select 
                      min(PARSE_DATE('%Y%m%d', CONCAT(CAST(miryear AS STRING), FORMAT('%02d', mirmonth), FORMAT('%02d', mirday)))) as min_date
                      from ${ref(databuffet.VALIDATED_MAC5, "mir")}
                      where mirtype = 'RS'
                        and company_id = final.companyid
                        and mirbinvno = final.InvoiceNo), 
                    DATE('2000-01-01')
                  ) <= CURRENT_DATE('Asia/Bangkok')
                  and (select 1
                    from ${ref(databuffet.VALIDATED_MAC5, "cfs")}
                    where cfsclearsum = -1
                      and cfsclearall = -1
                      and company_id = final.companyid
                      and cfsvnosid = final.InvoiceNo) = 1, 
                  'Completed', 'Non-Completed'
                )
      ELSE IF(OutStanding between -1 and 1, 'Completed', 'Non-Completed')
    END) as flagComplete,

    final.MinReceiveDate,
    final.MaxReceiveDate,
  from final_main_mix as final
  left join `${DimCompanyTableRef}` as dim_com
    on final.CompanyID = dim_com.companyID
  left join `${DimCustomerTableRef}` as dim_cus
    on final.CustomerID = dim_cus.debcode
    and dim_com.CompanySK = dim_cus.CompanySK
  left join dim_invoice as inv
    on final.InvoiceNo = inv.mihVnos
    and dim_com.CompanySK = inv.CompanySK
  left join `${FactBillingTableRef}` as vs
    on final.InvoiceNo = vs.mirbinvno
    and final.CompanyID = vs.company_id

)
  select distinct
    final.*,
    groupdata.group_id as GroupID,
    IF( LOGICAL_AND(final.flagComplete = 'Completed') OVER(PARTITION BY final.CompanyID, groupdata.group_id),
      'Completed',
      'Non-Completed'
    ) as GroupFlagComplete
  from final as final
  left join group_data_final as groupdata
    on final.CompanyID = groupdata.CompanyID
    and final.cfsVnosID = groupdata.InvoiceNo
;




BEGIN
    DECLARE run_date DATE DEFAULT CURRENT_DATE('Asia/Bangkok')-1;

    --- delete data before daily process
    DELETE FROM `${DimAgingHistoryTableRef}`
    WHERE asatdate >= run_date
    ;

    --- insert data for daily process
    INSERT INTO `${DimAgingHistoryTableRef}`
    SELECT run_date as asatdate, * except(ChannelSK, ChannelFinanceSK, ChannelSaleSK, ChannelCostSK)
    FROM `${DimAgingViewRef}`
    WHERE GroupFlagComplete = 'Non-Completed' 
    ;

    --- delete data for daily process
    DELETE FROM `${DimAgingHistoryTableRef}`
    WHERE (
        DATE_TRUNC(asatdate, MONTH) = DATE_TRUNC(run_date, MONTH)
        AND asatdate < run_date
    )
    OR 
    (
        DATE_TRUNC(asatdate, MONTH) < DATE_TRUNC(run_date, MONTH)
        AND asatdate != LAST_DAY(asatdate)
    );
END;
