config {
  type: "operations",
  dependencies: [],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    // Define table references
    const DimProductTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimProductTableRef = `${DimProductTable.database}.${DimProductTable.schema}.${DimProductTable.name}`;
    
    const DimHolidayTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_holiday",
    };
    const DimHolidayTableRef = `${DimHolidayTable.database}.${DimHolidayTable.schema}.${DimHolidayTable.name}`;

    const DimProductRebateTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_rebate",
    };
    const DimProductRebateTableRef = `${DimProductRebateTable.database}.${DimProductRebateTable.schema}.${DimProductRebateTable.name}`;

    const DimStkMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_stk_mkt",
    };
    const DimStkMktTableRef = `${DimStkMktTable.database}.${DimStkMktTable.schema}.${DimStkMktTable.name}`;

    const DimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt",
    };
    const DimProductMktTableRef = `${DimProductMktTable.database}.${DimProductMktTable.schema}.${DimProductMktTable.name}`;

}

BEGIN
  -- 1. หาค่า Max ของ ProductSK เดิมเพื่อรันเลขต่อสำหรับของใหม่
  DECLARE max_sk INT64;
  SET max_sk = (SELECT IFNULL(MAX(ProductSK), 0) FROM `${DimProductTableRef}`);

  -- 2. รัน MERGE กระบวนการ Upsert
  MERGE `${DimProductTableRef}` T
  USING (
    WITH raw_data AS (
      select
--   row_number() over(order by a.stkcode) as ProductSK,
        stk_mkt_sk.StkMktSK,
        product_mk_sk.ProductMktSK,
        a.stkcode as ProductCode ,
        a.stkcode2 as ProductCode1,
        a.stkdesct1 as ProductMac5Description,
        g.stgcode as ProductGroupMAC5, 
        g.stgdesct as ProductGroupMac5Description,
        g.stgdesce as ProductGroupMAC5Type,
        g.gacccode as ProductGroupACC,
        g.gaccname as ProductGroupACCName,
        pd.pd_product_name as ProductName,
        p.prd_description as ProductDescription,
        p.prd_dimension1 as ProductDimension1 ,
        p.prd_dimension2 as ProductDimension2,
        p.prd_dimension3 as ProductDimension3,
        p.prd_dimension4 as ProductDimension4,
        pd.pd_garantee as ProductGarantee,
        pd.pd_garantee_detail as ProductGaranteeDetail,
        (case 
            when 
            pd.pd_certificate is not null 
            and pd.pd_certificate <> '' 
            and pd.pd_certificate <> 'โปรดระบุ' 
            and pd.pd_certificate <> '-' 
            and pd.pd_certificate <> 'None' 
            and pd.pd_certificate <> 'No'
            then 'Yes' 
            else 'No' 
        end) as ThaiIndustrialStandardFlag,
        -- (case
        --     when pdr.salesExc is not null then pdr.salesExc
        --     else 'No'
        -- end) as ProductSaleExcFlag,
        -- (case
        --     when pdr.accExc is not null then pdr.accExc
        --     else 'No'
        -- end) as ProductFCExcFlag,
        pd.pd_certificate as ThaiIndustrialSatandardDetail,
        p.prd_brand_id as BrandID,
        p.prd_vendor_id as VendorID,
        a.stksto as WarehouseID,
        a.STKcode885 as Barcode

        from ${ref(databuffet.VALIDATED_MAC5, "stk")} as a
        left join ${ref(databuffet.VALIDATED_MAC5, "stg")} as g on a.STKgroup = g.STGcode AND a.company_id = g.company_id
        left join ${ref(databuffet.VALIDATED_MASTERSKU, "product")} as p on a.STKcode885 = p.prd_barcode
        left join ${ref(databuffet.VALIDATED_MASTERSKU, "product_detail")} as pd on p.prd_id = pd.pd_prd_id
        -- left join `${DimProductRebateTableRef}` as pdr on a.stkcode = pdr.rebate and pdr.status = 'Product'
        --left join `${databuffet.DATABASE}.validated_mastersku.brand` brand on p.prd_brand_id = brand.bra_id
        --left join `${databuffet.DATABASE}.validated_mastersku.vendor` vendor on p.prd_vendor_id = vendor.vd_id
        
        left join `${DimStkMktTableRef}` as stk_mkt_sk
          on a.stkcode = stk_mkt_sk.StkCode
        left join `${DimProductMktTableRef}` as product_mk_sk
          on stk_mkt_sk.MarketingGroupID = product_mk_sk.MarketingGroupID
            and stk_mkt_sk.SubMarketingID = product_mk_sk.SubMarketingID
            and stk_mkt_sk.SegmentID = product_mk_sk.SegmentID
        where a.company_id = 'ag01'
        --and a.STKcode885 is not null and a.STKcode885 <> ''
        qualify row_number() over(partition by ProductCode, Barcode order by prd_updated_date desc) = 1
    )
    SELECT
      S.*,
      -- เช็คว่ามีอยู่แล้วในตาราง Target หรือไม่
      ROW_NUMBER() OVER(PARTITION BY T.ProductSK IS NULL ORDER BY S.ProductCode) as ProductSK
    FROM raw_data S
    LEFT JOIN `${DimProductTableRef}` T
      ON S.ProductCode = T.ProductCode
      AND IFNULL(S.Barcode, '') = IFNULL(T.Barcode, '')
  ) S
  ON T.ProductCode = S.ProductCode 
    AND IFNULL(T.Barcode, '') = IFNULL(S.Barcode, '')

  WHEN MATCHED THEN
    UPDATE SET
      T.StkMktSK = S.StkMktSK,
      T.ProductMktSK = S.ProductMktSK,
      T.ProductCode1 = S.ProductCode1,
      T.ProductMac5Description = S.ProductMac5Description,
      T.ProductGroupMAC5 = S.ProductGroupMAC5,
      T.ProductGroupMac5Description = S.ProductGroupMac5Description,
      T.ProductGroupMAC5Type = S.ProductGroupMAC5Type,
      T.ProductGroupACC = S.ProductGroupACC,
      T.ProductGroupACCName = S.ProductGroupACCName,
      T.ProductName = S.ProductName,
      T.ProductDescription = S.ProductDescription,
      T.ProductDimension1 = S.ProductDimension1,
      T.ProductDimension2 = S.ProductDimension2,
      T.ProductDimension3 = S.ProductDimension3,
      T.ProductDimension4 = S.ProductDimension4,
      T.ProductGarantee = S.ProductGarantee,
      T.ProductGaranteeDetail = S.ProductGaranteeDetail,
      T.ThaiIndustrialStandardFlag = S.ThaiIndustrialStandardFlag,
      T.ThaiIndustrialSatandardDetail = S.ThaiIndustrialSatandardDetail,
      T.BrandID = S.BrandID,
      T.VendorID = S.VendorID,
      T.WarehouseID = S.WarehouseID

  WHEN NOT MATCHED THEN
    INSERT (
      ProductSK, StkMktSK, ProductMktSK,
      ProductCode, ProductCode1, ProductMac5Description,
      ProductGroupMAC5, ProductGroupMac5Description, ProductGroupMAC5Type,
      ProductGroupACC, ProductGroupACCName, ProductName, ProductDescription,
      ProductDimension1, ProductDimension2, ProductDimension3, ProductDimension4,
      ProductGarantee, ProductGaranteeDetail, ThaiIndustrialStandardFlag,
      ThaiIndustrialSatandardDetail, BrandID, VendorID,
      WarehouseID, Barcode
    )
    VALUES (
      max_sk + ProductSK, S.StkMktSK, S.ProductMktSK,
      S.ProductCode, S.ProductCode1, S.ProductMac5Description,
      S.ProductGroupMAC5, S.ProductGroupMac5Description, S.ProductGroupMAC5Type,
      S.ProductGroupACC, S.ProductGroupACCName, S.ProductName, S.ProductDescription,
      S.ProductDimension1, S.ProductDimension2, S.ProductDimension3, S.ProductDimension4,
      S.ProductGarantee, S.ProductGaranteeDetail, S.ThaiIndustrialStandardFlag,
      S.ThaiIndustrialSatandardDetail, S.BrandID, S.VendorID,
      S.WarehouseID, S.Barcode
    );

END;

-- BEGIN
--   drop table if exists `${DimProductTableRef}`;
  
--   create or replace table `${DimProductTableRef}`
--   cluster by ProductSK, ProductCode, ProductGroupMAC5Type
--   as
--   select
--   row_number() over(order by a.stkcode) as ProductSK,
--   a.stkcode as ProductCode ,
--   a.stkcode2 as ProductCode1,
--   a.stkdesct1 as ProductMac5Description,
--   g.stgcode as ProductGroupMAC5, 
--   g.stgdesct as ProductGroupMac5Description,
--   g.stgdesce as ProductGroupMAC5Type,
--   g.gacccode as ProductGroupACC,
--   g.gaccname as ProductGroupACCName,
--   pd.pd_product_name as ProductName,
--   p.prd_description as ProductDescription,
--   p.prd_dimension1 as ProductDimension1 ,
--   p.prd_dimension2 as ProductDimension2,
--   p.prd_dimension3 as ProductDimension3,
--   p.prd_dimension4 as ProductDimension4,
--   pd.pd_garantee as ProductGarantee,
--   pd.pd_garantee_detail as ProductGaranteeDetail,
--   (case 
--     when 
--       pd.pd_certificate is not null 
--       and pd.pd_certificate <> '' 
--       and pd.pd_certificate <> 'โปรดระบุ' 
--       and pd.pd_certificate <> '-' 
--       and pd.pd_certificate <> 'None' 
--       and pd.pd_certificate <> 'No'
--     then 'Yes' 
--     else 'No' 
--   end) as ThaiIndustrialStandardFlag,
--   (case
--     when pdr.Rebate is not null then 'Yes'
--     else 'No'
--   end) as ProductFCExcFlag,
--   pd.pd_certificate as ThaiIndustrialSatandardDetail,
--   p.prd_brand_id as BrandID,
--   p.prd_vendor_id as VendorID,
--   a.stksto as WarehouseID,
--   a.STKcode885 as Barcode

--   from ${ref(databuffet.VALIDATED_MAC5, "stk")} as a  
--   left join ${ref(databuffet.VALIDATED_MAC5, "stg")} as g on a.STKgroup = g.STGcode
--   left join ${ref(databuffet.VALIDATED_MASTERSKU, "product")} as p on a.STKcode885 = p.prd_barcode
--   left join ${ref(databuffet.VALIDATED_MASTERSKU, "product_detail")} as pd on p.prd_id = pd.pd_prd_id
--   left join `${DimProductRebateTableRef}` as pdr on a.stkcode = pdr.Rebate
--   --left join `${databuffet.DATABASE}.validated_mastersku.brand` brand on p.prd_brand_id = brand.bra_id
--   --left join `${databuffet.DATABASE}.validated_mastersku.vendor` vendor on p.prd_vendor_id = vendor.vd_id
--   --where a.STKcode885 is not null and a.STKcode885 <> '' 
--   qualify row_number() over(partition by ProductCode, Barcode order by prd_updated_date desc) = 1
--   ;
  
-- END;
