config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["SectionManagerSK"],
  bigquery: {
    clusterBy: ["SectionManagerSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_sales_section_manager_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.cleanString("t1.SectionID")},
      t1.StartDate,
      t1.EndDate
  ) AS SectionManagerSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.cleanString("t1.SectionID")} AS SectionID,
  ${databuffet.functionData.cleanString("t1.SectionName")} AS SectionName,
  ${databuffet.functionData.cleanString("t1.SectionManagerEmployeeID")} AS SectionManagerEmployeeID,
  ${databuffet.functionData.cleanString("t1.SectionManagerName")} AS SectionManagerName,
  ${databuffet.functionData.cleanString("t1.SectionManagerSurname")} AS SectionManagerSurname,
  ${databuffet.functionData.cleanString("t1.SectionManagerNickname")} AS SectionManagerNickname,
  t1.StartDate AS StartDate,
  t1.EndDate AS EndDate,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
