config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimAgingRangTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimAgingRangTableRef = `${DimAgingRangTable.database}.${DimAgingRangTable.schema}.${DimAgingRangTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_aging_rang_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(AgingRangSK), 0) FROM `${DimAgingRangTableRef}`);

  MERGE `${DimAgingRangTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t3.AgingRangSK IS NOT NULL THEN t3.AgingRangSK
        WHEN t2.AgingRangSK IS NOT NULL THEN t2.AgingRangSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.AgingRangSK IS NULL AND t3.AgingRangSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.companyID")},
            ${databuffet.functionData.castInt64("t1.AgingDayMin")},
            ${databuffet.functionData.castInt64("t1.AgingDayMax")}
        )
      END) AS AgingRangSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.castInt64("t1.AgingDayMin")} AS AgingDayMin,
      ${databuffet.functionData.castInt64("t1.AgingDayMax")} AS AgingDayMax,
      ${databuffet.functionData.cleanString("t1.ReportName")} AS ReportName,
      ${databuffet.functionData.cleanString("t1.id")} as MdsID
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    LEFT JOIN `${DimAgingRangTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
      AND ${databuffet.functionData.castInt64("t1.AgingDayMin")} = t2.AgingDayMin
      AND ${databuffet.functionData.castInt64("t1.AgingDayMax")} = t2.AgingDayMax
    LEFT JOIN `${DimAgingRangTableRef}` AS t3
      ON ${databuffet.functionData.cleanString("t1.id")} = t3.MdsID
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.AgingRangSK = S.AgingRangSK

  WHEN MATCHED THEN
    UPDATE SET
      T.AgingDayMin = S.AgingDayMin,
      T.AgingDayMax = S.AgingDayMax,
      T.ReportName = S.ReportName,
      T.MdsID = S.MdsID

  WHEN NOT MATCHED THEN
    INSERT (
      AgingRangSK,
      CompanySK,
      companyID,
      AgingDayMin,
      AgingDayMax,
      ReportName,
      MdsID
    )
    VALUES (
      S.AgingRangSK,
      S.CompanySK,
      S.companyID,
      S.AgingDayMin,
      S.AgingDayMax,
      S.ReportName,
      S.MdsID
    );

  DELETE FROM `${DimAgingRangTableRef}`
  WHERE MdsID IN (
    SELECT id FROM `${MdsSourceTableRef}` WHERE is_active = FALSE
  );
END;
