config {
  type: "table",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY]
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_change_section_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
    dim_com.CompanySK,
    ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
    ${databuffet.functionData.cleanString("t1.customerCode")} AS customerCode,
    ${databuffet.functionData.cleanString("t1.CustomerName")} AS CustomerName,
    ${databuffet.functionData.cleanString("t1.province")} AS province,
    ${databuffet.functionData.cleanString("t1.oldSectionID")} AS oldSectionID,
    ${databuffet.functionData.cleanString("t1.newSectionID")} AS newSectionID,
    t1.startDate AS startDate,
    t1.endDate AS endDate,
    ${databuffet.functionData.cleanString("t1.id")} AS MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
    ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = true