config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["PaymentSK"],
  bigquery: {
    clusterBy: ["PaymentSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_payment_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.companyID")},
      ${databuffet.functionData.cleanString("t1.CodeMemo")}
  ) AS PaymentSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
  ${databuffet.functionData.cleanString("t1.CodeMemo")} AS CodeMemo,
  ${databuffet.functionData.cleanString("t1.PaymentID")} AS PaymentID,
  ${databuffet.functionData.cleanString("t1.PaymentName")} AS PaymentName,
  ${databuffet.functionData.cleanString("t1.PaymentMethodEN")} AS PaymentMethodEN,
  ${databuffet.functionData.cleanString("t1.PaymentMethodTH")} AS PaymentMethodTH,
  ${databuffet.functionData.cleanString("t1.PaymentType")} AS PaymentType,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
