config {
    type: "table",
    schema: databuffet.DIMENSION_TABLE,
    dependencies: [ 
                    "dim_company", "dim_director"
                ],
    tags: [databuffet.TAG_DIM_DAILY],
    uniqueKey: ["DirectorSK"],
    bigquery: {
        clusterBy: ["DirectorSK"]
    },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimDirectorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director",
    };
    const DimDirectorTableRef = `${DimDirectorTable.database}.${DimDirectorTable.schema}.${DimDirectorTable.name}`;

}

SELECT
    ROW_NUMBER() OVER (ORDER BY dim_com.CompanySK, t1.DirectorID) AS DirectorSK,
    dim_com.CompanySK,
    dim_com.companyID,
    t1.DirectorID,
    t1.DirectorName, 
    t1.DirectorOfSalesID, 
    t1.DirectorOfSalesName, 
    t1.StartDate, 
    t1.EndDate,
  FROM (
    SELECT
      *
    FROM `${DimDirectorTableRef}`
    -- WHERE CURRENT_DATE('Asia/Bangkok') between StartDate and EndDate
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CompanyID, DirectorID ORDER BY EndDate DESC, StartDate DESC) = 1
  ) as t1
  LEFT JOIN `${DimCompanyTableRef}` as dim_com
    on t1.CompanyID = dim_com.CompanyID


pre_operations {
}

post_operations {
}
