config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimChannelFinanceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimChannelFinanceTableRef = `${DimChannelFinanceTable.database}.${DimChannelFinanceTable.schema}.${DimChannelFinanceTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_channel_finance_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(ChannelFinanceSK), 0) FROM `${DimChannelFinanceTableRef}`);

  MERGE `${DimChannelFinanceTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t2.ChannelFinanceSK IS NOT NULL THEN t2.ChannelFinanceSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.ChannelFinanceSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.companyID")},
            ${databuffet.functionData.cleanString("t1.ChannelIDFinance")}
        )
      END) AS ChannelFinanceSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.cleanString("t1.ChannelIDFinance")} AS ChannelIDFinance,
      ${databuffet.functionData.cleanString("t1.ChannelNameFinance")} AS ChannelNameFinance
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    LEFT JOIN `${DimChannelFinanceTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
      AND ${databuffet.functionData.cleanString("t1.ChannelIDFinance")} = t2.ChannelIDFinance
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.ChannelFinanceSK = S.ChannelFinanceSK

  WHEN MATCHED THEN
    UPDATE SET
      T.ChannelNameFinance = S.ChannelNameFinance

  WHEN NOT MATCHED THEN
    INSERT (
      ChannelFinanceSK,
      CompanySK,
      companyID,
      ChannelIDFinance,
      ChannelNameFinance
    )
    VALUES (
      S.ChannelFinanceSK,
      S.CompanySK,
      S.companyID,
      S.ChannelIDFinance,
      S.ChannelNameFinance
    );
END;
