config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["GuaranteeSK"],
  bigquery: {
    clusterBy: ["GuaranteeSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_guarantee_document_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.CompanyID")},
      ${databuffet.functionData.cleanString("t1.CustomerCode")},
      ${databuffet.functionData.cleanString("t1.BankName")}
  ) AS GuaranteeSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.CompanyID")} AS CompanyID,
  ${databuffet.functionData.cleanString("t1.Region")} AS Region,
  ${databuffet.functionData.cleanString("t1.CustomerCode")} AS CustomerCode,
  ${databuffet.functionData.cleanString("t1.CustomerName")} AS CustomerName,
  t1.ExpiryDate AS ExpiryDate,
  ${databuffet.functionData.cleanString("t1.BankName")} AS BankName,
  ${databuffet.functionData.castFloat64("t1.BG_Limit")} AS BG_Limit,
  ${databuffet.functionData.cleanString("t1.Renewal")} AS Renewal,
  ${databuffet.functionData.cleanString("t1.Remarks")} AS Remarks,
  ${databuffet.functionData.cleanString("t1.Address")} AS Address,
  ${databuffet.functionData.cleanString("t1.PhoneNumber")} AS PhoneNumber,
  ${databuffet.functionData.cleanString("t1.FAX")} AS FAX,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.CompanyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
