config {
  type: "table",
  schema: databuffet.DIMENSION_TABLE,
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
  uniqueKey: ["ProductMktSK"],
  bigquery: {
    clusterBy: ["ProductMktSK"],
  },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_product_marketing_name_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

SELECT
  ROW_NUMBER() OVER(
    ORDER BY
      ${databuffet.functionData.cleanString("t1.CompanyID")},
      ${databuffet.functionData.cleanString("t1.TypeMarketingID")},
      ${databuffet.functionData.cleanString("t1.MarketingGroupID")},
      ${databuffet.functionData.cleanString("t1.SubMarketingID")},
      ${databuffet.functionData.cleanString("t1.SegmentID")}
  ) AS ProductMktSK,
  dim_com.CompanySK,
  ${databuffet.functionData.cleanString("t1.CompanyID")} AS CompanyID,
  ${databuffet.functionData.cleanString("t1.TypeMarketingID")} AS TypeMarketingID,
  ${databuffet.functionData.cleanString("t1.TypeMarketing")} AS TypeMarketing,
  ${databuffet.functionData.cleanString("t1.MarketingGroupID")} AS MarketingGroupID,
  ${databuffet.functionData.cleanString("t1.MarketingGroup")} AS MarketingGroup,
  ${databuffet.functionData.cleanString("t1.SubMarketingID")} AS SubMarketingID,
  ${databuffet.functionData.cleanString("t1.SubMarketing")} AS SubMarketing,
  ${databuffet.functionData.cleanString("t1.SegmentID")} AS SegmentID,
  ${databuffet.functionData.cleanString("t1.Segment")} AS Segment,
  ${databuffet.functionData.cleanString("t1.id")} as MdsID
FROM `${MdsSourceTableRef}` AS t1
LEFT JOIN `${DimCompanyTableRef}` AS dim_com
  ON ${databuffet.functionData.cleanString("t1.CompanyID")} = dim_com.companyID
WHERE t1.is_active = TRUE

pre_operations {}

post_operations {}
