config {
    type: "table",
    schema: databuffet.DIMENSION_TABLE,
    dependencies: [ 
                    "dim_company", "dim_sale_representative"
                  ],
    tags: [databuffet.TAG_DIM_DAILY],
    uniqueKey: ["SaleRepSK"],
    bigquery: {
        clusterBy: ["SaleRepSK"]
    },
}

js {
    const DimSaleRepLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimSaleRepLastTableRef = `${DimSaleRepLastTable.database}.${DimSaleRepLastTable.schema}.${DimSaleRepLastTable.name}`;


    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimSaleRepTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative",
    };
    const DimSaleRepTableRef = `${DimSaleRepTable.database}.${DimSaleRepTable.schema}.${DimSaleRepTable.name}`;

}

SELECT
    ROW_NUMBER() OVER (ORDER BY dim_com.CompanySK, t1.DepartmentID, t1.EmployeeID, t1.DepCode, t1.CostChannelID, t1.ProvinceID) AS SaleRepSK,
    NULL AS DepartmentSK,
    NULL AS SectionSK,
    NULL AS SectionManagerSK,
    NULL AS RegionSK,
    NULL AS RegionManagerSK,
    NULL AS DirectorSK,
    dim_com.CompanySK,
    dim_com.companyID,

    t1.DepartmentID,
    t1.EmployeeID,
    t1.EmployeeName,
    t1.EmployeeSurname,
    t1.EmployeeNickname,
    t1.DepCode,
    t1.CostChannelID,
    t1.ProvinceID,
    t1.ChangeSectionFlag,
    t1.CustomerFlag
  FROM (
    SELECT
      *
    FROM `${DimSaleRepTableRef}`
    -- WHERE CURRENT_DATE('Asia/Bangkok') between StartDate and EndDate
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CompanyID, DepartmentID, EmployeeID, DepCode, CostChannelID, ProvinceID ORDER BY StartDate DESC, EndDate DESC) = 1
  ) as t1
  LEFT JOIN `${DimCompanyTableRef}` as dim_com
    on t1.CompanyID = dim_com.CompanyID


pre_operations {
}

post_operations {
BEGIN
  DECLARE max_sk INT64 DEFAULT 0;
  SET max_sk = (SELECT IFNULL(MAX(SaleRepSK), 0) FROM `${DimSaleRepLastTableRef}`);

  MERGE `${DimSaleRepLastTableRef}` AS T
  USING (
    WITH raw_per AS (
        SELECT DISTINCT
            company_id,
            percode as EmployeeID,
            TRIM(REGEXP_REPLACE(pernamet, r'\s+', ' ')) as pernamet
        FROM ${ref(databuffet.VALIDATED_MAC5, 'per')} as per
        -- WHERE per.company_id = 'ag01'

    ),
    source_combined AS (
        SELECT
            dim_com.CompanySK,
            dim_com.companyID,
            EmployeeID,
            REGEXP_EXTRACT(pernamet, r'^([^\s]+)') AS EmployeeName,
            REGEXP_EXTRACT(pernamet, r'\s([^\s(]+)') AS EmployeeSurname,
            REGEXP_EXTRACT(pernamet, r'\((.*?)\)') AS EmployeeNickname,
            CAST(NULL AS STRING) AS DepartmentID,
            CAST(NULL AS STRING) AS DepCode,
            CAST(NULL AS STRING) AS CostChannelID,
            CAST(NULL AS STRING) AS ProvinceID,
            CAST(NULL AS STRING) AS ChangeSectionFlag
        FROM raw_per
        LEFT JOIN `${DimCompanyTableRef}` as dim_com
            on raw_per.company_id = dim_com.companyID

    )

    SELECT
        (CASE
            WHEN t2.SaleRepSK IS NOT NULL THEN t2.SaleRepSK
            ELSE max_sk + ROW_NUMBER() OVER(PARTITION BY (CASE WHEN t2.EmployeeID IS NULL THEN 1 ELSE 0 END) ORDER BY t1.CompanySK, t1.EmployeeID)
        END) AS SaleRepSK,
        t1.CompanySK,
        t1.companyID,
        t1.EmployeeID,
        t1.EmployeeName,
        t1.EmployeeSurname,
        t1.EmployeeNickname,
        t1.DepartmentID,
        t1.DepCode,
        t1.CostChannelID,
        t1.ProvinceID,
        t1.ChangeSectionFlag
    FROM source_combined AS t1
    LEFT JOIN `${DimSaleRepLastTableRef}` AS t2
        ON t1.EmployeeID = t2.EmployeeID
          AND t2.DepartmentID IS NULL
          AND t1.CompanySK = t2.CompanySK

  ) AS S
  ON T.SaleRepSK = S.SaleRepSK

  WHEN MATCHED THEN
    UPDATE SET
      T.EmployeeName = S.EmployeeName,
      T.EmployeeSurname = S.EmployeeSurname,
      T.EmployeeNickname = S.EmployeeNickname

  WHEN NOT MATCHED THEN
    INSERT (
      SaleRepSK, DepartmentSK, SectionSK, SectionManagerSK, RegionSK,
      RegionManagerSK, DirectorSK, CompanySK, companyID, DepartmentID, EmployeeID, EmployeeName,
      EmployeeSurname, EmployeeNickname, DepCode, CostChannelID,
      ProvinceID, ChangeSectionFlag
    )
    VALUES (
      S.SaleRepSK, NULL, NULL, NULL, NULL,
      NULL, NULL, S.CompanySK, S.companyID, S.DepartmentID, S.EmployeeID, S.EmployeeName,
      S.EmployeeSurname, S.EmployeeNickname, S.DepCode, S.CostChannelID,
      S.ProvinceID, S.ChangeSectionFlag
    );
END;

}
