config {
  type: "operations",
  dependencies: ["stk", "stg", "product", "product_detail"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    // Define table references
    const DimProductTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_master",
    };
    const DimProductTableRef = `${DimProductTable.database}.${DimProductTable.schema}.${DimProductTable.name}`;
    
    const DimHolidayTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_holiday",
    };
    const DimHolidayTableRef = `${DimHolidayTable.database}.${DimHolidayTable.schema}.${DimHolidayTable.name}`;

    const DimProductRebateTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_rebate",
    };
    const DimProductRebateTableRef = `${DimProductRebateTable.database}.${DimProductRebateTable.schema}.${DimProductRebateTable.name}`;

}

BEGIN
  drop table if exists `${DimProductTableRef}`;
  
  create or replace table `${DimProductTableRef}`
  cluster by ProductCode, ProductGroupMAC5, ProductGroupACC, ProductGroupMAC5Type
  as
  select
  a.stkcode as ProductCode ,
  a.stkcode2 as ProductCode1,
  a.stkdesct1 as ProductMac5Description,
  g.stgcode as ProductGroupMAC5, 
  g.stgdesct as ProductGroupMac5Description,
  g.stgdesce as ProductGroupMAC5Type,
  g.gacccode as ProductGroupACC,
  g.gaccname as ProductGroupACCName,
  pd.pd_product_name as ProductName,
  p.prd_description as ProductDescription,
  p.prd_dimension1 as ProductDimension1 ,
  p.prd_dimension2 as ProductDimension2,
  p.prd_dimension3 as ProductDimension3,
  p.prd_dimension4 as ProductDimension4,
  pd.pd_garantee as ProductGarantee,
  pd.pd_garantee_detail as ProductGaranteeDetail,
  (case 
    when 
      pd.pd_certificate is not null 
      and pd.pd_certificate <> '' 
      and pd.pd_certificate <> 'โปรดระบุ' 
      and pd.pd_certificate <> '-' 
      and pd.pd_certificate <> 'None' 
      and pd.pd_certificate <> 'No'
    then 'Yes' 
    else 'No' 
  end) as ThaiIndustrialStandardFlag,
  (case
    when pdr.Rebate is not null then 'Yes'
    else 'No'
  end) as ProductFCExcFlag,
  pd.pd_certificate as ThaiIndustrialSatandardDetail,
  p.prd_brand_id as BrandID,
  p.prd_vendor_id as VendorID,
  a.stksto as WarehouseID,
  a.STKcode885 as Barcode

  from ${ref(databuffet.VALIDATED_MAC5, "stk")} as a  
  left join ${ref(databuffet.VALIDATED_MAC5, "stg")} as g on a.STKgroup = g.STGcode
  left join ${ref(databuffet.VALIDATED_MASTERSKU, "product")} as p on a.STKcode885 = p.prd_barcode
  left join ${ref(databuffet.VALIDATED_MASTERSKU, "product_detail")} as pd on p.prd_id = pd.pd_prd_id
  left join `${DimProductRebateTableRef}` as pdr on a.stkcode = pdr.Rebate
  --left join `${databuffet.DATABASE}.validated_mastersku.brand` brand on p.prd_brand_id = brand.bra_id
  --left join `${databuffet.DATABASE}.validated_mastersku.vendor` vendor on p.prd_vendor_id = vendor.vd_id
  --where a.STKcode885 is not null and a.STKcode885 <> '' 
  qualify row_number() over(partition by Barcode order by prd_updated_date desc) = 1
  ;
  
END;
