config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimStatusNotReceiveTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimStatusNotReceiveTableRef = `${DimStatusNotReceiveTable.database}.${DimStatusNotReceiveTable.schema}.${DimStatusNotReceiveTable.name}`;

    /*
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;
    */

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_payment_status_not_receive_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(NotReceiveSK), 0) FROM `${DimStatusNotReceiveTableRef}`);

  MERGE `${DimStatusNotReceiveTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t2.NotReceiveSK IS NOT NULL THEN t2.NotReceiveSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.NotReceiveSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.CompanyID")},
            ${databuffet.functionData.castInt64("t1.StatusID")}
        )
      END) AS NotReceiveSK,
      -- dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.CompanyID")} AS CompanyID,
      ${databuffet.functionData.castInt64("t1.StatusID")} AS StatusID,
      ${databuffet.functionData.cleanString("t1.StatusNameTH")} AS StatusNameTH,
      ${databuffet.functionData.cleanString("t1.StatusNameENG")} AS StatusNameENG
    FROM `${MdsSourceTableRef}` AS t1
    -- LEFT JOIN `${DimCompanyTableRef}` AS dim_com
    --   ON ${databuffet.functionData.cleanString("t1.CompanyID")} = dim_com.companyID
    LEFT JOIN `${DimStatusNotReceiveTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.CompanyID")} = t2.CompanyID
      AND ${databuffet.functionData.castInt64("t1.StatusID")} = t2.StatusID
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.NotReceiveSK = S.NotReceiveSK

  WHEN MATCHED THEN
    UPDATE SET
      T.StatusNameTH = S.StatusNameTH,
      T.StatusNameENG = S.StatusNameENG

  WHEN NOT MATCHED THEN
    INSERT (
      NotReceiveSK,
      -- CompanySK,
      CompanyID,
      StatusID,
      StatusNameTH,
      StatusNameENG
    )
    VALUES (
      S.NotReceiveSK,
      -- S.CompanySK,
      S.CompanyID,
      S.StatusID,
      S.StatusNameTH,
      S.StatusNameENG
    );
END;
