config {
    type: "table",
    schema: databuffet.DIMENSION_TABLE,
    dependencies: [ 
                    "dim_company", "dim_section_manager"
                ],
    tags: [databuffet.TAG_DIM_DAILY],
    uniqueKey: ["SectionManagerSK"],
    bigquery: {
        clusterBy: ["SectionManagerSK"]
    },
}

js {
    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimSectionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_manager",
    };
    const DimSectionManagerTableRef = `${DimSectionManagerTable.database}.${DimSectionManagerTable.schema}.${DimSectionManagerTable.name}`;

}

SELECT
    ROW_NUMBER() OVER (ORDER BY dim_com.CompanySK, t1.SectionID) AS SectionManagerSK,
    dim_com.CompanySK,
    dim_com.companyID,
    t1.SectionID,
    t1.SectionName,
    t1.SectionManagerEmployeeID,
    t1.SectionManagerName,
    t1.SectionManagerSurname,
    t1.SectionManagerNickname,
    t1.StartDate, 
    t1.EndDate,
  FROM (
    SELECT
      *
    FROM `${DimSectionManagerTableRef}`
    WHERE CURRENT_DATE('Asia/Bangkok') between StartDate and EndDate
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CompanyID, SectionID ORDER BY EndDate DESC, StartDate DESC) = 1
  ) as t1
  LEFT JOIN `${DimCompanyTableRef}` as dim_com
    on t1.CompanyID = dim_com.CompanyID


pre_operations {
}

post_operations {
}
