config {
  type: "operations",
  dependencies: ["dim_company"],
  tags: [databuffet.TAG_DIM_DAILY],
}

js {
    const DimCostGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: name(),
    };
    const DimCostGroupTableRef = `${DimCostGroupTable.database}.${DimCostGroupTable.schema}.${DimCostGroupTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const MdsSourceTable = {
        database: databuffet.DATABASE,
        schema: "mds_dataset",
        name: "mds_data_standard_cost_by_product_group_master",
    };
    const MdsSourceTableRef = `${MdsSourceTable.database}.${MdsSourceTable.schema}.${MdsSourceTable.name}`;
}

BEGIN
  DECLARE max_sk INT64 DEFAULT 0;

  SET max_sk = (SELECT IFNULL(MAX(CostGroupSK), 0) FROM `${DimCostGroupTableRef}`);

  MERGE `${DimCostGroupTableRef}` AS T
  USING (
    SELECT
      (CASE
        WHEN t3.CostGroupSK IS NOT NULL THEN t3.CostGroupSK
        WHEN t2.CostGroupSK IS NOT NULL THEN t2.CostGroupSK
        ELSE max_sk + ROW_NUMBER() OVER(
          PARTITION BY (CASE WHEN t2.CostGroupSK IS NULL AND t3.CostGroupSK IS NULL THEN 1 ELSE 0 END)
          ORDER BY
            ${databuffet.functionData.cleanString("t1.companyID")},
            ${databuffet.functionData.cleanString("t1.GAccID")},
            ${databuffet.functionData.cleanString("t1.ChannelCostID")},
            t1.StartDate,
            t1.EndDate
        )
      END) AS CostGroupSK,
      dim_com.CompanySK,
      ${databuffet.functionData.cleanString("t1.companyID")} AS companyID,
      ${databuffet.functionData.cleanString("t1.GAccID")} AS GAccID,
      ${databuffet.functionData.cleanString("t1.GAccName")} AS GAccName,
      ${databuffet.functionData.cleanString("t1.ChannelCostID")} AS ChannelCostID,
      ${databuffet.functionData.cleanString("t1.ChannelCostName")} AS ChannelCostName,
      ${databuffet.functionData.castFloat64("t1.Percent")} AS Percent,
      t1.StartDate AS StartDate,
      t1.EndDate AS EndDate,
      ${databuffet.functionData.cleanString("t1.id")} as MdsID
    FROM `${MdsSourceTableRef}` AS t1
    LEFT JOIN `${DimCompanyTableRef}` AS dim_com
      ON ${databuffet.functionData.cleanString("t1.companyID")} = dim_com.companyID
    LEFT JOIN `${DimCostGroupTableRef}` AS t2
      ON ${databuffet.functionData.cleanString("t1.companyID")} = t2.companyID
      AND ${databuffet.functionData.cleanString("t1.GAccID")} = t2.GAccID
      AND ${databuffet.functionData.cleanString("t1.ChannelCostID")} = t2.ChannelCostID
      AND t1.StartDate = t2.StartDate
      AND t1.EndDate = t2.EndDate
    LEFT JOIN `${DimCostGroupTableRef}` AS t3
      ON ${databuffet.functionData.cleanString("t1.id")} = t3.MdsID
    WHERE t1.is_active = TRUE
      AND DATE(t1.updated_at) >= DATE_SUB(
            CURRENT_DATE("Asia/Bangkok"),
            INTERVAL ${databuffet.MDS_BACKFILL_DAYS} DAY
          )
  ) AS S
  ON T.CostGroupSK = S.CostGroupSK

  WHEN MATCHED THEN
    UPDATE SET
      T.GAccName = S.GAccName,
      T.ChannelCostName = S.ChannelCostName,
      T.Percent = S.Percent,
      T.StartDate = S.StartDate,
      T.EndDate = S.EndDate,
      T.MdsID = S.MdsID

  WHEN NOT MATCHED THEN
    INSERT (
      CostGroupSK,
      CompanySK,
      companyID,
      GAccID,
      GAccName,
      ChannelCostID,
      ChannelCostName,
      Percent,
      StartDate,
      EndDate,
      MdsID
    )
    VALUES (
      S.CostGroupSK,
      S.CompanySK,
      S.companyID,
      S.GAccID,
      S.GAccName,
      S.ChannelCostID,
      S.ChannelCostName,
      S.Percent,
      S.StartDate,
      S.EndDate,
      S.MdsID
    );
END;
