config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ap_s"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ap_s"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ap_s"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ap_snamet DESC, ap_snamee DESC) = 1`
        : ""

}

SELECT
  CAST(ap_scode AS INT64) AS ap_scode,
  CAST(ap_snamet AS STRING) AS ap_snamet,
  CAST(ap_snamee AS STRING) AS ap_snamee,
  CAST(ap_scolf AS INT64) AS ap_scolf,
  CAST(ap_scolb AS INT64) AS ap_scolb,
  CAST(rowguid AS STRING) AS rowguid
FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}
  -- pre_operations {}
  -- post_operations {}
