config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ap_s"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ap_s"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ap_s"]

}

SELECT
    CAST(ap_scode AS INT64) as ap_scode,
    CAST(ap_snamet AS STRING) as ap_snamet,
    CAST(ap_snamee AS STRING) as ap_snamee,
    CAST(ap_scolf AS INT64) as ap_scolf,
    CAST(ap_scolb AS INT64) as ap_scolb,
    CAST(rowguid AS STRING) as rowguid
  
FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ap_snamet desc, ap_snamee desc) = 1

  -- pre_operations {}
  -- post_operations {}
