config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ar_s"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ar_s"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["ar_s"]

}

SELECT
    CAST(ar_scode AS INT64) as ar_scode,
    CAST(ar_snamet AS STRING) as ar_snamet,
    CAST(ar_snamee AS STRING) as ar_snamee,
    CAST(ar_scolf AS INT64) as ar_scolf,
    CAST(ar_scolb AS INT64) as ar_scolb,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ar_snamet desc, ar_snamee desc) = 1

  -- pre_operations {}
  -- post_operations {}
