config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cfs"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cfs"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cfs"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cfsjob desc, cfsdep desc) = 1`
        : ""

}

SELECT
    CAST(cfsvnosid AS STRING) as cfsvnosid,
    CAST(cfsdateid AS DATETIME) as cfsdateid,
    CAST(cfscusid AS STRING) as cfscusid,
    CAST(cfstypeid AS STRING) as cfstypeid,
    CAST(cfsjob AS STRING) as cfsjob,
    CAST(cfsdep AS STRING) as cfsdep,
    CAST(cfsper AS STRING) as cfsper,
    CAST(cfsdoc AS STRING) as cfsdoc,
    CAST(cfsmec AS STRING) as cfsmec,
    CAST(cfssumreq AS FLOAT64) as cfssumreq,
    CAST(cfssumcut1 AS FLOAT64) as cfssumcut1,
    CAST(cfssumcut2 AS FLOAT64) as cfssumcut2,
    CAST(cfsclearsum AS INT64) as cfsclearsum,
    CAST(cfsclearuser AS INT64) as cfsclearuser,
    CAST(cfsclearall AS INT64) as cfsclearall,
    CAST(cfscurc AS INT64) as cfscurc,
    CAST(cfsexchg AS FLOAT64) as cfsexchg,
    CAST(cfsbillcut AS FLOAT64) as cfsbillcut,
    CAST(cfsbillclr AS INT64) as cfsbillclr,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
