config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"]

}

SELECT
    CAST(chqno AS STRING) as chqno,
    CAST(chqbank AS STRING) as chqbank,
    CAST(chqacode AS STRING) as chqacode,
    CAST(chqcus AS STRING) as chqcus,
    CAST(chqdatec AS DATETIME) as chqdatec,
    CAST(chqdater AS DATETIME) as chqdater,
    CAST(chqdatep AS DATETIME) as chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    CAST(chqmemo AS STRING) as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    CAST(chqjob AS STRING) as chqjob,
    CAST(chqdep AS STRING) as chqdep,
    CAST(chqper AS STRING) as chqper,
    CAST(chqzon AS STRING) as chqzon,
    CAST(chqrcode AS STRING) as chqrcode,
    CAST(chqeditlk AS DATETIME) as chqeditlk,
    CAST(chqkeyuser AS STRING) as chqkeyuser,
    CAST(chqkeydate AS DATETIME) as chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    CAST(chqecode AS STRING) as chqecode,
    CAST(chqbranch AS STRING) as chqbranch,
    CAST(chqmec AS STRING) as chqmec,
    CAST(chqdatev AS DATETIME) as chqdatev

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY chqacode desc, chqcus desc) = 1

  -- pre_operations {}
  -- post_operations {}
