config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY chqacode desc, chqcus desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(chqno AS STRING) as chqno,
    CAST(chqbank AS STRING) as chqbank,
    CAST(chqacode AS STRING) as chqacode,
    CAST(chqcus AS STRING) as chqcus,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19)) AS chqdatec,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19)) AS chqdater,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19)) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    CAST(chqmemo AS STRING) as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    CAST(chqjob AS STRING) as chqjob,
    CAST(chqdep AS STRING) as chqdep,
    CAST(chqper AS STRING) as chqper,
    CAST(chqzon AS STRING) as chqzon,
    CAST(chqrcode AS STRING) as chqrcode,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19)) AS chqeditlk,
    CAST(chqkeyuser AS STRING) as chqkeyuser,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19)) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    CAST(chqecode AS STRING) as chqecode,
    CAST(chqbranch AS STRING) as chqbranch,
    CAST(chqmec AS STRING) as chqmec,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19)) AS chqdatev

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
