config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["comboset"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["comboset"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["comboset"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY combostk desc, stkcode desc) = 1`
        : ""

}

SELECT
    CAST(id AS INT64) as id,
    CAST(combostk AS STRING) as combostk,
    CAST(stkcode AS STRING) as stkcode,
    CAST(date AS DATETIME) as date,
    CAST(uinsert AS STRING) as uinsert,
    CAST(uupdate AS STRING) as uupdate,
    CAST(status AS INT64) as status,
    CAST(quantity AS INT64) as quantity,
    CAST(price AS FLOAT64) as price,
    CAST(lp AS FLOAT64) as lp

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
