config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cpp"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cpp"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cpp"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cppstkid desc, cpplinkid desc) = 1`
        : ""

}

SELECT
    CAST(cppstkid AS STRING) as cppstkid,
    CAST(cpplinkid AS INT64) as cpplinkid,
    CAST(cppvnosid AS STRING) as cppvnosid,
    CAST(cppdateid AS DATETIME) as cppdateid,
    CAST(cppcusid AS STRING) as cppcusid,
    CAST(cppjob AS STRING) as cppjob,
    CAST(cppdep AS STRING) as cppdep,
    CAST(cppper AS STRING) as cppper,
    CAST(cppdoc AS STRING) as cppdoc,
    CAST(cppmec AS STRING) as cppmec,
    CAST(cppsto AS STRING) as cppsto,
    CAST(cppstkreq AS FLOAT64) as cppstkreq,
    CAST(cppstkcut1 AS FLOAT64) as cppstkcut1,
    CAST(cppstkcut2 AS FLOAT64) as cppstkcut2,
    CAST(cppsumreq AS FLOAT64) as cppsumreq,
    CAST(cppsumcut1 AS FLOAT64) as cppsumcut1,
    CAST(cppsumcut2 AS FLOAT64) as cppsumcut2,
    CAST(cppclearstk AS INT64) as cppclearstk,
    CAST(cppclearsum AS INT64) as cppclearsum,
    CAST(cppclearuser AS INT64) as cppclearuser,
    CAST(cppclearall AS INT64) as cppclearall,
    CAST(cppcurc AS INT64) as cppcurc,
    CAST(cppexchg AS FLOAT64) as cppexchg,
    CAST(cppcut AS INT64) as cppcut,
    CAST(cppdelvdate AS DATETIME) as cppdelvdate,
    CAST(cpplistno AS INT64) as cpplistno,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
