config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cps"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cps"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(CPSstkID AS STRING) AS cpsstkid,
  CAST(CPSlinkID AS INT64) AS cpslinkid,
  CAST(CPSvnosID AS STRING) AS cpsvnosid,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(CPSdateID, 1, 19)) AS cpsdateid,
  CAST(CPScusID AS STRING) AS cpscusid,
  CAST(CPSjob AS STRING) AS cpsjob,
  CAST(CPSdep AS STRING) AS cpsdep,
  CAST(CPSper AS STRING) AS cpsper,
  CAST(CPSdoc AS STRING) AS cpsdoc,
  CAST(CPSmec AS STRING) AS cpsmec,
  CAST(CPSsto AS STRING) AS cpssto,
  CAST(CPSstkREQ AS FLOAT64) AS cpsstkreq,
  CAST(CPSstkCUT1 AS FLOAT64) AS cpsstkcut1,
  CAST(CPSstkCUT2 AS FLOAT64) AS cpsstkcut2,
  CAST(CPSsumREQ AS FLOAT64) AS cpssumreq,
  CAST(CPSsumCUT1 AS FLOAT64) AS cpssumcut1,
  CAST(CPSsumCUT2 AS FLOAT64) AS cpssumcut2,
  CAST(CPSclearSTK AS INT64) AS cpsclearstk,
  CAST(CPSclearSUM AS INT64) AS cpsclearsum,
  CAST(CPSclearUSER AS INT64) AS cpsclearuser,
  CAST(CPSclearALL AS INT64) AS cpsclearall,
  CAST(CPScurC AS INT64) AS cpscurc,
  CAST(CPSexchg AS FLOAT64) AS cpsexchg,
  CAST(CPScut AS INT64) AS cpscut,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(CPSdelvDate, 1, 19)) AS cpsdelvdate,
  CAST(CPSlistNo AS INT64) AS cpslistno,
  CAST(rowguid AS STRING) AS rowguid,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
