config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cpx"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cpx"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cpxjob desc, cpxdep desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(cpxstkid AS STRING) as cpxstkid,
    CAST(cpxlinkid AS INT64) as cpxlinkid,
    CAST(cpxvnosid AS STRING) as cpxvnosid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cpxdateid, 1, 19)) AS cpxdateid,
    CAST(cpxjob AS STRING) as cpxjob,
    CAST(cpxdep AS STRING) as cpxdep,
    CAST(cpxper AS STRING) as cpxper,
    CAST(cpxdoc AS STRING) as cpxdoc,
    CAST(cpxmec AS STRING) as cpxmec,
    CAST(cpxsto AS STRING) as cpxsto,
    CAST(cpxstkreq AS FLOAT64) as cpxstkreq,
    CAST(cpxstkcut AS FLOAT64) as cpxstkcut,
    CAST(cpxclearstk AS INT64) as cpxclearstk,
    CAST(cpxclearuser AS INT64) as cpxclearuser,
    CAST(cpxclearall AS INT64) as cpxclearall,
    CAST(cpxstatus AS INT64) as cpxstatus,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
