config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cre"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cre"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY crenamet desc, crenamee desc, credate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(crecode AS STRING) as crecode,
    CAST(cregroup AS STRING) as cregroup,
    CAST(crenamet AS STRING) as crenamet,
    CAST(crenamee AS STRING) as crenamee,
    CAST(crecontactt AS STRING) as crecontactt,
    CAST(crecontacte AS STRING) as crecontacte,
    CAST(creadd1at AS STRING) as creadd1at,
    CAST(creadd2at AS STRING) as creadd2at,
    CAST(creadd3at AS STRING) as creadd3at,
    CAST(creadd1ae AS STRING) as creadd1ae,
    CAST(creadd2ae AS STRING) as creadd2ae,
    CAST(creadd3ae AS STRING) as creadd3ae,
    CAST(cretel AS STRING) as cretel,
    CAST(cretaxnos AS STRING) as cretaxnos,
    CAST(crezone AS STRING) as crezone,
    CAST(cregrade AS STRING) as cregrade,
    CAST(crelimit AS FLOAT64) as crelimit,
    CAST(cretaxclass AS FLOAT64) as cretaxclass,
    CAST(cregoodsdef AS INT64) as cregoodsdef,
    CAST(crecreditterm AS INT64) as crecreditterm,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(credate, 1, 19)) AS credate,
    CAST(crehide AS INT64) as crehide,
    CAST(crefax AS STRING) as crefax,
    CAST(creemail AS STRING) as creemail,
    CAST(cretarget AS FLOAT64) as cretarget,
    CAST(crememo AS STRING) as crememo,
    CAST(creac AS STRING) as creac,
    CAST(crelock AS INT64) as crelock,
    CAST(creoname AS STRING) as creoname,
    CAST(creprice AS STRING) as creprice,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(creeditlk, 1, 19)) AS creeditlk,
    CAST(crerefwe AS STRING) as crerefwe,
    CAST(cresortnt AS STRING) as cresortnt,
    CAST(cresortne AS STRING) as cresortne,
    CAST(crecardid AS STRING) as crecardid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(creeditdt, 1, 19)) AS creeditdt,
    CAST(creeditmf AS STRING) as creeditmf,
    CAST(cretaxtype AS INT64) as cretaxtype,
    CAST(creinex AS INT64) as creinex,
    CAST(crebranch AS STRING) as crebranch

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
