config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cst"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cst"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(CSTdate, 1, 19)) AS cstdate,
  CAST(CSTtype AS STRING) AS csttype,
  CAST(CSTvnos AS STRING) AS cstvnos,
  CAST(CSTcus AS STRING) AS cstcus,
  CAST(CSTstk AS STRING) AS cststk,
  CAST(CSTjob AS STRING) AS cstjob,
  CAST(CSTdep AS STRING) AS cstdep,
  CAST(CSTper AS STRING) AS cstper,
  CAST(CSTdoc AS STRING) AS cstdoc,
  CAST(CSTmec AS STRING) AS cstmec,
  CAST(CSTsto AS STRING) AS cststo,
  CAST(CSTquan AS FLOAT64) AS cstquan,
  CAST(CSTquanP2 AS FLOAT64) AS cstquanp2,
  CAST(CSTcogSP AS FLOAT64) AS cstcogsp,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(CSTexpDATE, 1, 19)) AS cstexpdate,
  CAST(CSTlinkVC AS STRING) AS cstlinkvc,
  CAST(CSTlinkVCid AS INT64) AS cstlinkvcid,
  CAST(CSTio AS INT64) AS cstio,
  CAST(CSTioZW AS INT64) AS cstiozw,
  CAST(CSTlist AS INT64) AS cstlist,
  CAST(CSTcostA AS FLOAT64) AS cstcosta,
  CAST(CSTcostF AS FLOAT64) AS cstcostf,
  CAST(CSTcostL AS FLOAT64) AS cstcostl,
  CAST(rowguid AS STRING) AS rowguid,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
