config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["deb"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["deb"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY debnamet desc, debnamee desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(debcode AS STRING) as debcode,
    CAST(debgroup AS STRING) as debgroup,
    CAST(debnamet AS STRING) as debnamet,
    CAST(debnamee AS STRING) as debnamee,
    CAST(debcontactt AS STRING) as debcontactt,
    CAST(debcontacte AS STRING) as debcontacte,
    CAST(debadd1at AS STRING) as debadd1at,
    CAST(debadd2at AS STRING) as debadd2at,
    CAST(debadd3at AS STRING) as debadd3at,
    CAST(debadd1ae AS STRING) as debadd1ae,
    CAST(debadd2ae AS STRING) as debadd2ae,
    CAST(debadd3ae AS STRING) as debadd3ae,
    CAST(debtel AS STRING) as debtel,
    CAST(debtaxnos AS STRING) as debtaxnos,
    CAST(debzone AS STRING) as debzone,
    CAST(debgrade AS STRING) as debgrade,
    CAST(deblimit AS FLOAT64) as deblimit,
    CAST(debtaxclass AS FLOAT64) as debtaxclass,
    CAST(debgoodsdef AS FLOAT64) as debgoodsdef,
    CAST(debcreditterm AS INT64) as debcreditterm,
    CAST(debpaytype AS INT64) as debpaytype,
    CAST(debpayday AS INT64) as debpayday,
    CAST(debpayon1 AS INT64) as debpayon1,
    CAST(debpayon2 AS INT64) as debpayon2,
    CAST(debpayon3 AS INT64) as debpayon3,
    CAST(debpayon4 AS INT64) as debpayon4,
    CAST(debpayon5 AS INT64) as debpayon5,
    CAST(debpayn1 AS INT64) as debpayn1,
    CAST(debpayn2 AS INT64) as debpayn2,
    CAST(debbgrtype AS INT64) as debbgrtype,
    CAST(debbgrday AS INT64) as debbgrday,
    CAST(debbgron1 AS INT64) as debbgron1,
    CAST(debbgron2 AS INT64) as debbgron2,
    CAST(debbgron3 AS INT64) as debbgron3,
    CAST(debbgron4 AS INT64) as debbgron4,
    CAST(debbgron5 AS INT64) as debbgron5,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(debdate, 1, 19)) AS debdate,
    CAST(debhide AS INT64) as debhide,
    CAST(debfax AS STRING) as debfax,
    CAST(debemail AS STRING) as debemail,
    CAST(debtarget AS FLOAT64) as debtarget,
    CAST(debmemo AS STRING) as debmemo,
    CAST(debac AS STRING) as debac,
    CAST(deblock AS INT64) as deblock,
    CAST(deboname AS STRING) as deboname,
    CAST(debcm1 AS STRING) as debcm1,
    CAST(debcm2 AS STRING) as debcm2,
    CAST(debcm3 AS STRING) as debcm3,
    CAST(debcm4 AS STRING) as debcm4,
    CAST(debcm5 AS STRING) as debcm5,
    CAST(debcm6 AS STRING) as debcm6,
    CAST(debcm7 AS STRING) as debcm7,
    CAST(debcm8 AS STRING) as debcm8,
    CAST(debcm9 AS STRING) as debcm9,
    CAST(debcm10 AS STRING) as debcm10,
    CAST(debprice AS STRING) as debprice,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(debeditlk, 1, 19)) AS debeditlk,
    CAST(debrefwe AS STRING) as debrefwe,
    CAST(debbillad AS INT64) as debbillad,
    CAST(debsortnt AS STRING) as debsortnt,
    CAST(debsortne AS STRING) as debsortne,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(debeditdt, 1, 19)) AS debeditdt,
    CAST(debeditmf AS STRING) as debeditmf,
    CAST(debinex AS INT64) as debinex,
    CAST(debsalesp AS STRING) as debsalesp,
    CAST(debbranch AS STRING) as debbranch,
    CAST(rowguid AS STRING) as rowguid,
    CAST(debxxxx AS STRING) as debxxxx,
    CAST(debbusinesstype AS STRING) as debbusinesstype,
    CAST(debbusinessdesc AS STRING) as debbusinessdesc,
    CAST(debactive AS INT64) as debactive,
    CAST(debstatus AS INT64) as debstatus,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(debexpiredate, 1, 19)) AS debexpiredate

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
