config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["dep"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["dep"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["dep"]

}

SELECT
    CAST(depcode AS STRING) as depcode,
    CAST(depgroup AS STRING) as depgroup,
    CAST(depdesct AS STRING) as depdesct,
    CAST(depdesce AS STRING) as depdesce,
    CAST(dephide AS INT64) as dephide,
    CAST(deplock AS INT64) as deplock,
    CAST(depeditdt AS DATETIME) as depeditdt,
    CAST(depeditmf AS STRING) as depeditmf,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY depdesct desc, depdesce desc) = 1

  -- pre_operations {}
  -- post_operations {}
