config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["detail_qtspread"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["detail_qtspread"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ref_id desc, qtid desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(ref_id AS INT64) as ref_id,
    CAST(qtid AS INT64) as qtid,
    CAST(quodeid AS STRING) as quodeid,
    CAST(stkcode AS STRING) as stkcode,
    CAST(quantity AS FLOAT64) as quantity,
    CAST(price AS FLOAT64) as price,
    CAST(total AS STRING) as total,
    CAST(uinsert AS STRING) as uinsert,
    CAST(uupdate AS STRING) as uupdate,
    CAST(dinsert AS STRING) as dinsert,
    CAST(dupdate AS STRING) as dupdate,
    CAST(status AS STRING) as status,
    CAST(link AS STRING) as link,
    CAST(type AS STRING) as type,
    CAST(fandex AS STRING) as fandex,
    CAST(itemsize AS STRING) as itemsize

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
