config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["doc"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["doc"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["doc"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY docdesct desc, docdesce desc) = 1`
        : ""

}

SELECT
    CAST(doccode AS STRING) as doccode,
    CAST(docgroup AS STRING) as docgroup,
    CAST(docdesct AS STRING) as docdesct,
    CAST(docdesce AS STRING) as docdesce,
    CAST(doclock AS INT64) as doclock,
    CAST(docacc AS STRING) as docacc,
    CAST(docdebit AS INT64) as docdebit,
    CAST(docrefwe AS STRING) as docrefwe,
    CAST(dochide AS INT64) as dochide,
    CAST(doceditdt AS DATETIME) as doceditdt,
    CAST(doceditmf AS STRING) as doceditmf,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
