config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["doc"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["doc"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY doceditdt desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(doccode AS STRING) as doccode,
    CAST(docgroup AS STRING) as docgroup,
    CAST(docdesct AS STRING) as docdesct,
    CAST(docdesce AS STRING) as docdesce,
    CAST(doclock AS INT64) as doclock,
    CAST(docacc AS STRING) as docacc,
    CAST(docdebit AS INT64) as docdebit,
    CAST(docrefwe AS STRING) as docrefwe,
    CAST(dochide AS INT64) as dochide,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(doceditdt, 1, 19)) AS doceditdt,
    CAST(doceditmf AS STRING) as doceditmf,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
