config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["log_print_billing"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["log_print_billing"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["log_print_billing"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(ref1 AS STRING) as ref1,
    CAST(ref2 AS STRING) as ref2,
    CAST(order_no AS STRING) as order_no,
    CAST(amount AS FLOAT64) as amount,
    CAST(status AS INT64) as status,
    CAST(dinsert AS DATE) as dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ref1 desc, ref2 desc) = 1

  -- pre_operations {}
  -- post_operations {}
