config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["maincontract"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["maincontract"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["maincontract"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY dateinsert desc, status desc) = 1`
        : ""

}

SELECT
    CAST(mcontractid AS INT64) as mcontractid,
    CAST(dateinsert AS DATETIME) as dateinsert,
    CAST(status AS INT64) as status,
    CAST(uinsert AS STRING) as uinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
