config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["match_deb_bot_re"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["match_deb_bot_re"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["match_deb_bot_re"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(deb_code AS STRING) as deb_code,
    CAST(vendor_name AS STRING) as vendor_name,
    CAST(channel AS STRING) as channel

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY vendor_name desc) = 1

  -- pre_operations {}
  -- post_operations {}
