config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mie"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mie"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(MIEday AS INT64) AS mieday,
  CAST(MIEmonth AS INT64) AS miemonth,
  CAST(MIEyear AS INT64) AS mieyear,
  CAST(MIEtype AS STRING) AS mietype,
  CAST(MIEvnos AS STRING) AS mievnos,
  CAST(MIEcus AS STRING) AS miecus,
  CAST(MIErecDT3 AS NUMERIC) AS mierecdt3,
  CAST(MIErecDT53 AS NUMERIC) AS mierecdt53,
  CAST(MIErecDRND AS NUMERIC) AS mierecdrnd,
  CAST(MIErecDEXG AS NUMERIC) AS mierecdexg,
  CAST(MIErecDCSH AS NUMERIC) AS mierecdcsh,
  CAST(MIErecDOTH AS NUMERIC) AS mierecdoth,
  CAST(MIErecPLUS AS NUMERIC) AS mierecplus,
  CAST(MIErecCASH AS NUMERIC) AS miereccash,
  CAST(MIErecCQRD AS NUMERIC) AS miereccqrd,
  CAST(MIEctermCX AS STRING) AS miectermcx,
  CAST(MIEctermPX AS STRING) AS miectermpx,
  CAST(MIEctermAX AS STRING) AS miectermax,
  CAST(MIEctermDX AS STRING) AS miectermdx,
  CAST(MIEtag AS INT64) AS mietag,
  CAST(MIEbaseDT3 AS NUMERIC) AS miebasedt3,
  CAST(MIEbaseDT53 AS NUMERIC) AS miebasedt53,
  CAST(MIEdescDT3 AS STRING) AS miedescdt3,
  CAST(MIEdescDT53 AS STRING) AS miedescdt53,
  CAST(MIEconDT3 AS INT64) AS miecondt3,
  CAST(MIEconDT53 AS INT64) AS miecondt53,
  CAST(MIErecFC AS STRING) AS mierecfc,
  CAST(MIErecDT32 AS NUMERIC) AS mierecdt32,
  CAST(MIErecDT532 AS NUMERIC) AS mierecdt532,
  CAST(MIEbaseDT32 AS NUMERIC) AS miebasedt32,
  CAST(MIEbaseDT532 AS NUMERIC) AS miebasedt532,
  CAST(MIEdescDT32 AS STRING) AS miedescdt32,
  CAST(MIEdescDT532 AS STRING) AS miedescdt532,
  CAST(MIEconDT32 AS INT64) AS miecondt32,
  CAST(MIEconDT532 AS INT64) AS miecondt532,
  CAST(MIEperDT3 AS NUMERIC) AS mieperdt3,
  CAST(MIEperDT32 AS NUMERIC) AS mieperdt32,
  CAST(MIEperDT53 AS NUMERIC) AS mieperdt53,
  CAST(MIEperDT532 AS NUMERIC) AS mieperdt532,
  CAST(MIEtaxpayNo AS STRING) AS mietaxpayno,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
