config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mih_billing"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mih_billing"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mih_billing"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY mihdesc desc) = 1`
        : ""

}

SELECT
    CAST(mihday AS INT64) as mihday,
    CAST(mihmonth AS INT64) as mihmonth,
    CAST(mihyear AS INT64) as mihyear,
    CAST(mihtype AS STRING) as mihtype,
    CAST(mihvnos AS STRING) as mihvnos,
    CAST(mihcus AS STRING) as mihcus,
    CAST(mihjob AS STRING) as mihjob,
    CAST(mihdep AS STRING) as mihdep,
    CAST(mihper AS STRING) as mihper,
    CAST(mihdoc AS STRING) as mihdoc,
    CAST(mihmec AS STRING) as mihmec,
    CAST(mihvatno AS STRING) as mihvatno,
    CAST(mihdesc AS STRING) as mihdesc,
    CAST(mihmemo AS STRING) as mihmemo,
    CAST(mihnotes AS STRING) as mihnotes,
    CAST(mihref1 AS STRING) as mihref1,
    CAST(mihref2 AS STRING) as mihref2,
    CAST(mihref3 AS STRING) as mihref3,
    CAST(mihdischt1 AS STRING) as mihdischt1,
    CAST(mihdischt2 AS STRING) as mihdischt2,
    CAST(mihdelvsite AS STRING) as mihdelvsite,
    CAST(mihdelvdate AS DATETIME) as mihdelvdate,
    CAST(mihstanding AS INT64) as mihstanding,
    CAST(mihlinkgl AS INT64) as mihlinkgl,
    CAST(mihnouplink AS INT64) as mihnouplink,
    CAST(mihnolist AS INT64) as mihnolist,
    CAST(mihcurc AS INT64) as mihcurc,
    CAST(mihvatinlist AS INT64) as mihvatinlist,
    CAST(mihlock AS INT64) as mihlock,
    CAST(mihprintn AS INT64) as mihprintn,
    CAST(mihcheque AS INT64) as mihcheque,
    CAST(mihcancel AS INT64) as mihcancel,
    CAST(mihstatus AS INT64) as mihstatus,
    CAST(mihclearum AS INT64) as mihclearum,
    CAST(mihctermno AS INT64) as mihctermno,
    CAST(mihcog AS FLOAT64) as mihcog,
    CAST(mihvatsum AS FLOAT64) as mihvatsum,
    CAST(mihnetsum AS FLOAT64) as mihnetsum,
    CAST(mihdisclst AS FLOAT64) as mihdisclst,
    CAST(mihdischf1 AS FLOAT64) as mihdischf1,
    CAST(mihdischf2 AS FLOAT64) as mihdischf2,
    CAST(mihexchg AS FLOAT64) as mihexchg,
    CAST(mihextrasum AS FLOAT64) as mihextrasum,
    CAST(mihextravat AS FLOAT64) as mihextravat,
    CAST(mihextracut AS INT64) as mihextracut,
    CAST(mihextramem AS STRING) as mihextramem,
    CAST(mihrecno AS STRING) as mihrecno,
    CAST(mihrecdate AS DATETIME) as mihrecdate,
    CAST(mihsavetag AS STRING) as mihsavetag,
    CAST(mihkeyuser AS STRING) as mihkeyuser,
    CAST(mihkeydate AS DATETIME) as mihkeydate,
    CAST(mihdocrunno AS STRING) as mihdocrunno,
    CAST(mihdategl AS DATETIME) as mihdategl,
    CAST(mihduepo AS DATETIME) as mihduepo,
    CAST(miheditlk AS DATETIME) as miheditlk,
    CAST(mihiscf AS INT64) as mihiscf,
    CAST(mihissp AS INT64) as mihissp,
    CAST(mihdates1 AS DATETIME) as mihdates1,
    CAST(mihdates2 AS DATETIME) as mihdates2,
    CAST(mihnumsi AS INT64) as mihnumsi,
    CAST(mihnumsc AS FLOAT64) as mihnumsc,
    CAST(mihvatpc AS FLOAT64) as mihvatpc,
    CAST(mihincluded AS INT64) as mihincluded,
    CAST(mihtaxvnos AS STRING) as mihtaxvnos,
    CAST(mihtaxdate AS DATETIME) as mihtaxdate,
    CAST(mihtaxsum AS FLOAT64) as mihtaxsum,
    CAST(mihload AS INT64) as mihload,
    CAST(mihpaiddate AS DATETIME) as mihpaiddate,
    CAST(mihbookordernum AS STRING) as mihbookordernum,
    CAST(mihsenddate AS DATETIME) as mihsenddate,
    CAST(mihbl AS INT64) as mihbl,
    CAST(mihrpv AS INT64) as mihrpv,
    CAST(mihclearcut AS INT64) as mihclearcut,
    CAST(mihsettlecut AS INT64) as mihsettlecut,
    CAST(rowguid AS STRING) as rowguid,
    CAST(mihdebbranch AS STRING) as mihdebbranch,
    CAST(mihdebtaxnos AS STRING) as mihdebtaxnos

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
