config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mir"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mir"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY mirdesc desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(mirday AS INT64) as mirday,
    CAST(mirmonth AS INT64) as mirmonth,
    CAST(miryear AS INT64) as miryear,
    CAST(mirtype AS STRING) as mirtype,
    CAST(mirvnos AS STRING) as mirvnos,
    CAST(mircus AS STRING) as mircus,
    CAST(mirlistno AS INT64) as mirlistno,
    CAST(mirbinvno AS STRING) as mirbinvno,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mirbinvdate, 1, 19)) AS mirbinvdate,
    CAST(mirbinvtype AS STRING) as mirbinvtype,
    CAST(mirdesc AS STRING) as mirdesc,
    CAST(mircog AS FLOAT64) as mircog,
    CAST(mirvat AS FLOAT64) as mirvat,
    CAST(mirsum AS FLOAT64) as mirsum,
    CAST(mircurc AS INT64) as mircurc,
    CAST(mirexchg AS FLOAT64) as mirexchg,
    CAST(mirtag AS INT64) as mirtag,
    CAST(mirnotes AS STRING) as mirnotes,
    CAST(miraccount AS STRING) as miraccount

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
