config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mir"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mir"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mir"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY mirdesc desc) = 1`
        : ""

}

SELECT
    CAST(mirday AS INT64) as mirday,
    CAST(mirmonth AS INT64) as mirmonth,
    CAST(miryear AS INT64) as miryear,
    CAST(mirtype AS STRING) as mirtype,
    CAST(mirvnos AS STRING) as mirvnos,
    CAST(mircus AS STRING) as mircus,
    CAST(mirlistno AS INT64) as mirlistno,
    CAST(mirbinvno AS STRING) as mirbinvno,
    CAST(mirbinvdate AS DATETIME) as mirbinvdate,
    CAST(mirbinvtype AS STRING) as mirbinvtype,
    CAST(mirdesc AS STRING) as mirdesc,
    CAST(mircog AS FLOAT64) as mircog,
    CAST(mirvat AS FLOAT64) as mirvat,
    CAST(mirsum AS FLOAT64) as mirsum,
    CAST(mircurc AS INT64) as mircurc,
    CAST(mirexchg AS FLOAT64) as mirexchg,
    CAST(mirtag AS INT64) as mirtag,
    CAST(mirnotes AS STRING) as mirnotes,
    CAST(miraccount AS STRING) as miraccount

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
