config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["order_from_allkon_m"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["order_from_allkon_m"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["order_from_allkon_m"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(order_no AS STRING) as order_no,
    CAST(status AS STRING) as status,
    CAST(create_date AS DATETIME) as create_date,
    CAST(promotion_type AS STRING) as promotion_type,
    CAST(notes AS STRING) as notes,
    CAST(sub_order AS STRING) as sub_order,
    CAST(made_from AS STRING) as made_from,
    CAST(datetime AS DATETIME) as datetime,
    CAST(deliverystatus AS STRING) as deliverystatus,
    CAST(cancelstatus AS STRING) as cancelstatus,
    CAST(confirmstatus AS STRING) as confirmstatus,
    CAST(order_source AS STRING) as order_source,
    CAST(is_complete AS INT64) as is_complete,
    CAST(update_date AS DATETIME) as update_date

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY order_no desc, status desc) = 1

  -- pre_operations {}
  -- post_operations {}
