config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["per"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["per"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY pernamet desc, pernamee desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(percode AS STRING) as percode,
    CAST(perdep AS STRING) as perdep,
    CAST(pertaxnos AS STRING) as pertaxnos,
    CAST(pernamet AS STRING) as pernamet,
    CAST(pernamee AS STRING) as pernamee,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(perbdate, 1, 19)) AS perbdate,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(perworks, 1, 19)) AS perworks,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(perworkf, 1, 19)) AS perworkf,
    CAST(peradd1 AS STRING) as peradd1,
    CAST(peradd2 AS STRING) as peradd2,
    CAST(peradd3 AS STRING) as peradd3,
    CAST(pertel AS STRING) as pertel,
    CAST(perpositn AS STRING) as perpositn,
    CAST(perstatus AS INT64) as perstatus,
    CAST(pernchild AS INT64) as pernchild,
    CAST(percisstudy AS INT64) as percisstudy,
    CAST(pernotstudy AS INT64) as pernotstudy,
    CAST(persalary AS FLOAT64) as persalary,
    CAST(perhide AS INT64) as perhide,
    CAST(perlock AS INT64) as perlock,
    CAST(permemo AS STRING) as permemo,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pereditlk, 1, 19)) AS pereditlk,
    CAST(perrefwe AS STRING) as perrefwe,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pereditdt, 1, 19)) AS pereditdt,
    CAST(pereditmf AS STRING) as pereditmf,
    CAST(rowguid AS STRING) as rowguid,
    CAST(perzone AS STRING) as perzone

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
