config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["per"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["per"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["per"]

}

SELECT
    CAST(percode AS STRING) as percode,
    CAST(perdep AS STRING) as perdep,
    CAST(pertaxnos AS STRING) as pertaxnos,
    CAST(pernamet AS STRING) as pernamet,
    CAST(pernamee AS STRING) as pernamee,
    CAST(perbdate AS DATETIME) as perbdate,
    CAST(perworks AS DATETIME) as perworks,
    CAST(perworkf AS DATETIME) as perworkf,
    CAST(peradd1 AS STRING) as peradd1,
    CAST(peradd2 AS STRING) as peradd2,
    CAST(peradd3 AS STRING) as peradd3,
    CAST(pertel AS STRING) as pertel,
    CAST(perpositn AS STRING) as perpositn,
    CAST(perstatus AS INT64) as perstatus,
    CAST(pernchild AS INT64) as pernchild,
    CAST(percisstudy AS INT64) as percisstudy,
    CAST(pernotstudy AS INT64) as pernotstudy,
    CAST(persalary AS FLOAT64) as persalary,
    CAST(perhide AS INT64) as perhide,
    CAST(perlock AS INT64) as perlock,
    CAST(permemo AS STRING) as permemo,
    CAST(pereditlk AS DATETIME) as pereditlk,
    CAST(perrefwe AS STRING) as perrefwe,
    CAST(pereditdt AS DATETIME) as pereditdt,
    CAST(pereditmf AS STRING) as pereditmf,
    CAST(rowguid AS STRING) as rowguid,
    CAST(perzone AS STRING) as perzone

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY pernamet desc, pernamee desc) = 1

  -- pre_operations {}
  -- post_operations {}
