config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["price_product_bot"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["price_product_bot"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["price_product_bot"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(product_bot_re_id AS INT64) as product_bot_re_id,
    CAST(price AS FLOAT64) as price,
    CAST(channel AS STRING) as channel,
    CAST(type AS STRING) as type,
    CAST(start_date AS DATETIME) as start_date,
    CAST(end_date AS DATETIME) as end_date,
    CAST(create_date AS DATETIME) as create_date

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY product_bot_re_id desc, price desc) = 1

  -- pre_operations {}
  -- post_operations {}
