config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_ag"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_ag"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_ag"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY proagsttcode desc, proagstt desc) = 1`
        : ""

}

SELECT
    CAST(proagid AS INT64) as proagid,
    CAST(proagstkcode AS STRING) as proagstkcode,
    CAST(proagsttcode AS STRING) as proagsttcode,
    CAST(proagstt AS STRING) as proagstt,
    CAST(proagstrdate AS DATE) as proagstrdate,
    CAST(proagenddate AS DATE) as proagenddate,
    CAST(proagregion AS STRING) as proagregion,
    CAST(dinsert AS DATETIME) as dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
