config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_re"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_re"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_re"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY proresttcode desc, prorestt desc) = 1`
        : ""

}

SELECT
    CAST(proreid AS INT64) as proreid,
    CAST(prorestkcode AS STRING) as prorestkcode,
    CAST(proresttcode AS STRING) as proresttcode,
    CAST(prorestt AS STRING) as prorestt,
    CAST(prorestrdate AS DATE) as prorestrdate,
    CAST(proreenddate AS DATE) as proreenddate,
    CAST(proreregion AS STRING) as proreregion,
    CAST(dinsert AS DATETIME) as dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
