config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_crc"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_crc"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["pro_crc"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(procrcstkcode AS STRING) as procrcstkcode,
    CAST(procrcsttcode AS STRING) as procrcsttcode,
    CAST(procrcstt AS STRING) as procrcstt,
    CAST(procrcstrdate AS DATE) as procrcstrdate,
    CAST(procrcenddate AS DATE) as procrcenddate,
    CAST(procrcregion AS STRING) as procrcregion,
    CAST(dinsert AS DATETIME) as dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY procrcsttcode desc, procrcstt desc) = 1

  -- pre_operations {}
  -- post_operations {}
