config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["product_bot_re"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["product_bot_re"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["product_bot_re"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(sku_id AS STRING) as sku_id,
    CAST(qty AS FLOAT64) as qty,
    CAST(price AS FLOAT64) as price,
    CAST(channel AS STRING) as channel,
    CAST(type_product AS STRING) as type_product,
    CAST(create_date AS DATETIME) as create_date

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY sku_id desc, qty desc) = 1

  -- pre_operations {}
  -- post_operations {}
