config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["qt_spread_to_mih"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["qt_spread_to_mih"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["qt_spread_to_mih"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(qt_spread_ref_id AS INT64) as qt_spread_ref_id,
    CAST(qtid AS STRING) as qtid,
    CAST(mihvnos AS STRING) as mihvnos,
    CAST(status AS INT64) as status,
    CAST(rdysendtomac5 AS INT64) as rdysendtomac5,
    CAST(sto AS STRING) as sto

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY qt_spread_ref_id desc, qtid desc) = 1

  -- pre_operations {}
  -- post_operations {}
