config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["rcv"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["rcv"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(serial AS STRING) AS serial,
  CAST(rcvdate AS STRING) AS rcvdate,
  CAST(rcvtype AS INT64) AS rcvtype,
  CAST(rcvvnos AS STRING) AS rcvvnos,
  CAST(rcvstk AS STRING) AS rcvstk,
  CAST(descT1 AS STRING) AS desct1,
  CAST(qty AS STRING) AS qty,
  CAST(unit AS STRING) AS unit,
  CAST(rcvsto AS STRING) AS rcvsto,
  CAST(username AS STRING) AS username,
  CAST(remark AS STRING) AS remark,
  CAST(rcvtime AS STRING) AS rcvtime,
  CAST(Fdatetime2 AS STRING) AS fdatetime2,
  CAST(rcvStatus AS STRING) AS rcvstatus,
  CAST(rcvtypeFG AS STRING) AS rcvtypefg,
  CAST(rcvstatusMR AS STRING) AS rcvstatusmr,
  CAST(rcvzone AS STRING) AS rcvzone,
  CAST(rcvOrder AS STRING) AS rcvorder,
  CAST(rcvCommand AS STRING) AS rcvcommand,
  CAST(rcvExtCode AS STRING) AS rcvextcode,
  CAST(mixVnos AS STRING) AS mixvnos,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mixDate, 1, 19)) AS mixdate,
  CAST(rcvTranCode AS STRING) AS rcvtrancode,
  CAST(rcvCancel AS INT64) AS rcvcancel,
  CAST(rcvOrder_Pack AS STRING) AS rcvorder_pack,
  CAST(adjVnos AS STRING) AS adjvnos,
  CAST(PackDate AS STRING) AS packdate,
  CAST(PackTime AS STRING) AS packtime,
  CAST(rcvConvert AS INT64) AS rcvconvert,
  CAST(Odate AS STRING) AS odate,
  CAST(Ouser AS STRING) AS ouser,
  CAST(FMIL2LISTNO AS INT64) AS fmil2listno,
  CAST(Ostatus AS STRING) AS ostatus,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
