config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["rno"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["rno"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["rno"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY rnoid desc, rnoprefix desc) = 1`
        : ""

}

SELECT
    CAST(rnoid AS INT64) as rnoid,
    CAST(rnoprefix AS STRING) as rnoprefix,
    CAST(rnoyear AS STRING) as rnoyear,
    CAST(rnomonth AS STRING) as rnomonth,
    CAST(rnorunning AS INT64) as rnorunning,
    CAST(rnorunno AS STRING) as rnorunno,
    CAST(rnocrdate AS DATETIME) as rnocrdate,
    CAST(rnoupdatedate AS DATETIME) as rnoupdatedate

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
