config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["sbl"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["sbl"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY sblquan desc, sblquanp2 desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(sblstk AS STRING) as sblstk,
    CAST(sblsto AS STRING) as sblsto,
    CAST(sblquan AS FLOAT64) as sblquan,
    CAST(sblquanp2 AS FLOAT64) as sblquanp2,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
