config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["stk"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["stk"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stkdesct1 desc, stkdesct2 desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(stkcode AS STRING) as stkcode,
    CAST(stkgroup AS STRING) as stkgroup,
    CAST(stkcode2 AS STRING) as stkcode2,
    CAST(stkdesct1 AS STRING) as stkdesct1,
    CAST(stkdesct2 AS STRING) as stkdesct2,
    CAST(stkdesct3 AS STRING) as stkdesct3,
    CAST(stkdesce1 AS STRING) as stkdesce1,
    CAST(stkdesce2 AS STRING) as stkdesce2,
    CAST(stkdesce3 AS STRING) as stkdesce3,
    CAST(stkmax AS FLOAT64) as stkmax,
    CAST(stkmin AS FLOAT64) as stkmin,
    CAST(stkunit1 AS INT64) as stkunit1,
    CAST(stkunit2 AS INT64) as stkunit2,
    CAST(stkconv1 AS FLOAT64) as stkconv1,
    CAST(stkconv2 AS FLOAT64) as stkconv2,
    CAST(stksnsv AS INT64) as stksnsv,
    CAST(stkuname0 AS STRING) as stkuname0,
    CAST(stkuname1 AS STRING) as stkuname1,
    CAST(stkuname2 AS STRING) as stkuname2,
    CAST(stkuname3 AS STRING) as stkuname3,
    CAST(stkuname4 AS STRING) as stkuname4,
    CAST(stkuname5 AS STRING) as stkuname5,
    CAST(stkqu1 AS FLOAT64) as stkqu1,
    CAST(stkqu2 AS FLOAT64) as stkqu2,
    CAST(stkqu3 AS FLOAT64) as stkqu3,
    CAST(stkqu4 AS FLOAT64) as stkqu4,
    CAST(stkqu5 AS FLOAT64) as stkqu5,
    CAST(stkqe1 AS FLOAT64) as stkqe1,
    CAST(stkqe2 AS FLOAT64) as stkqe2,
    CAST(stkqe3 AS FLOAT64) as stkqe3,
    CAST(stkqe4 AS FLOAT64) as stkqe4,
    CAST(stkqe5 AS FLOAT64) as stkqe5,
    CAST(stkqn1 AS INT64) as stkqn1,
    CAST(stkqn2 AS INT64) as stkqn2,
    CAST(stkqn3 AS INT64) as stkqn3,
    CAST(stkqn4 AS INT64) as stkqn4,
    CAST(stkqn5 AS INT64) as stkqn5,
    CAST(stkvat AS FLOAT64) as stkvat,
    CAST(stkexpire AS INT64) as stkexpire,
    CAST(stkhide AS INT64) as stkhide,
    CAST(stkuse2 AS INT64) as stkuse2,
    CAST(stku2name AS STRING) as stku2name,
    CAST(stkfx AS INT64) as stkfx,
    CAST(stkacp AS STRING) as stkacp,
    CAST(stkacs AS STRING) as stkacs,
    CAST(stkacc AS STRING) as stkacc,
    CAST(stklock AS INT64) as stklock,
    CAST(stkmemo AS STRING) as stkmemo,
    CAST(stkacc1 AS STRING) as stkacc1,
    CAST(stkacc2 AS STRING) as stkacc2,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(stkeditlk, 1, 19)) AS stkeditlk,
    CAST(stkrefwe AS STRING) as stkrefwe,
    CAST(stkbarc1 AS STRING) as stkbarc1,
    CAST(stkbarc2 AS STRING) as stkbarc2,
    CAST(stkbarc3 AS STRING) as stkbarc3,
    CAST(stksortnt AS STRING) as stksortnt,
    CAST(stksortne AS STRING) as stksortne,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(stkeditdt, 1, 19)) AS stkeditdt,
    CAST(stkstatus AS INT64) as stkstatus,
    CAST(stksto AS STRING) as stksto,
    CAST(stkeditmf AS STRING) as stkeditmf,
    CAST(rowguid AS STRING) as rowguid,
    CAST(stkcode885 AS STRING) as stkcode885,
    CAST(stktype AS STRING) as stktype,
    CAST(stksalegrp AS STRING) as stksalegrp,
    CAST(stksaletype AS STRING) as stksaletype,
    CAST(stksalesup AS STRING) as stksalesup,
    CAST(stksalegrps1 AS STRING) as stksalegrps1,
    CAST(stksalegrps2 AS STRING) as stksalegrps2,
    CAST(stksub1 AS STRING) as stksub1,
    CAST(stksub2 AS STRING) as stksub2,
    CAST(stksub3 AS STRING) as stksub3,
    CAST(stkbrand AS STRING) as stkbrand,
    CAST(stkexpand AS STRING) as stkexpand,
    CAST(stklggrp AS STRING) as stklggrp,
    CAST(stkgroup_dge AS STRING) as stkgroup_dge,
    CAST(stkgroup1_dge_report AS STRING) as stkgroup1_dge_report,
    CAST(stkgroup2_dge_report AS STRING) as stkgroup2_dge_report,
    CAST(stkgroup3_dge_report AS STRING) as stkgroup3_dge_report,
    CAST(part_dge AS STRING) as part_dge,
    CAST(stkfpass AS STRING) as stkfpass

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
