config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["supcontract"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["supcontract"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["supcontract"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(mcontractid AS INT64) as mcontractid,
    CAST(scontractid AS STRING) as scontractid,
    CAST(dateinsert AS DATETIME) as dateinsert,
    CAST(status AS INT64) as status,
    CAST(uinsert AS STRING) as uinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY mcontractid desc, scontractid desc) = 1

  -- pre_operations {}
  -- post_operations {}
