config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tab"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tab"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tab"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY tablinktype desc, tablinkvno desc) = 1`
        : ""

}

SELECT
    CAST(tabvnosid AS STRING) as tabvnosid,
    CAST(tabdateid AS DATETIME) as tabdateid,
    CAST(tabcusid AS STRING) as tabcusid,
    CAST(tabtypeid AS STRING) as tabtypeid,
    CAST(tablinktype AS STRING) as tablinktype,
    CAST(tablinkvno AS STRING) as tablinkvno,
    CAST(tablinkvdate AS DATETIME) as tablinkvdate,
    CAST(tablinkvcus AS STRING) as tablinkvcus,
    CAST(tablinkvtype AS STRING) as tablinkvtype,
    CAST(tablinkvid AS INT64) as tablinkvid,
    CAST(tabstk AS STRING) as tabstk,
    CAST(tabquan AS FLOAT64) as tabquan,
    CAST(tabquanp2 AS FLOAT64) as tabquanp2,
    CAST(tabsum AS FLOAT64) as tabsum,
    CAST(tabcurc AS INT64) as tabcurc,
    CAST(tabexchg AS FLOAT64) as tabexchg,
    CAST(tablistno AS INT64) as tablistno,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
