config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quotation"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quotation"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY extradesc desc, cname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(running AS STRING) as running,
    CAST(atten AS STRING) as atten,
    CAST(address AS STRING) as address,
    CAST(sdate AS STRING) as sdate,
    CAST(project AS STRING) as project,
    CAST(tel AS STRING) as tel,
    CAST(sale AS STRING) as sale,
    CAST(price_validity AS STRING) as price_validity,
    CAST(termdelivery AS STRING) as termdelivery,
    CAST(termpayment AS STRING) as termpayment,
    CAST(uinsert AS STRING) as uinsert,
    CAST(dinsert AS STRING) as dinsert,
    CAST(uupdate AS STRING) as uupdate,
    CAST(dupdate AS STRING) as dupdate,
    CAST(agent1 AS STRING) as agent1,
    CAST(agent2 AS STRING) as agent2,
    CAST(period AS STRING) as period,
    CAST(pos AS STRING) as pos,
    CAST(vat AS INT64) as vat,
    CAST(disc AS INT64) as disc,
    CAST(extrasum AS INT64) as extrasum,
    CAST(extradesc AS STRING) as extradesc,
    CAST(date1st AS STRING) as date1st,
    CAST(date1end AS STRING) as date1end,
    CAST(date2st AS STRING) as date2st,
    CAST(date2end AS STRING) as date2end,
    CAST(cashstatus AS INT64) as cashstatus,
    CAST(note AS STRING) as note,
    CAST(noteforapp AS STRING) as noteforapp,
    CAST(memoforapp AS STRING) as memoforapp,
    CAST(rev AS INT64) as rev,
    CAST(typecus AS INT64) as typecus,
    CAST(channel AS STRING) as channel,
    CAST(channel2 AS STRING) as channel2,
    CAST(typeprice AS INT64) as typeprice,
    CAST(fob AS INT64) as fob,
    CAST(cancel AS INT64) as cancel,
    CAST(apptype AS INT64) as apptype,
    CAST(typedeb AS STRING) as typedeb,
    CAST(saledep AS STRING) as saledep,
    CAST(typeproject AS STRING) as typeproject,
    CAST(selectstatus AS INT64) as selectstatus,
    CAST(conpostatus AS INT64) as conpostatus,
    CAST(lat AS STRING) as lat,
    CAST(long AS STRING) as long,
    CAST(mapnote AS STRING) as mapnote,
    CAST(fileupload AS STRING) as fileupload,
    CAST(city AS STRING) as city,
    CAST(rdosend AS INT64) as rdosend,
    CAST(cname AS STRING) as cname,
    CAST(ctel AS STRING) as ctel,
    CAST(caddress AS STRING) as caddress,
    CAST(checknote AS STRING) as checknote,
    CAST(textnote AS STRING) as textnote,
    CAST(statusspread AS INT64) as statusspread,
    CAST(chkbox AS INT64) as chkbox,
    CAST(fobstt AS INT64) as fobstt,
    CAST(quotation_ref AS INT64) as quotation_ref,
    CAST(customer_id AS INT64) as customer_id,
    CAST(customer_group AS INT64) as customer_group,
    CAST(quotation_id AS INT64) as quotation_id,
    CAST(estatus AS INT64) as estatus,
    CAST(area AS STRING) as area,
    CAST(district AS STRING) as district,
    CAST(postcode AS STRING) as postcode,
    CAST(qtstepprice AS INT64) as qtstepprice,
    CAST(extradis AS STRING) as extradis

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
