config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_profilecomp"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_profilecomp"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY projectname desc, compname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(docno AS INT64) as docno,
    CAST(projectcode AS INT64) as projectcode,
    CAST(projectname AS STRING) as projectname,
    CAST(statuscomp AS STRING) as statuscomp,
    CAST(compname AS STRING) as compname,
    CAST(register AS STRING) as register,
    CAST(addresscomp AS STRING) as addresscomp,
    CAST(province AS STRING) as province,
    CAST(district AS STRING) as district,
    CAST(country AS STRING) as country,
    CAST(status AS STRING) as status,
    CAST(capital AS STRING) as capital,
    CAST(place AS STRING) as place,
    CAST(tel AS STRING) as tel,
    CAST(mobile AS STRING) as mobile,
    CAST(fax AS STRING) as fax,
    CAST(mail AS STRING) as mail,
    CAST(namedirector AS STRING) as namedirector,
    CAST(nickname AS STRING) as nickname,
    CAST(teldirector AS STRING) as teldirector,
    CAST(profilecomp AS STRING) as profilecomp,
    CAST(typecomp AS STRING) as typecomp,
    CAST(startdate AS STRING) as startdate,
    CAST(history AS STRING) as history,
    CAST(pjstart AS STRING) as pjstart,
    CAST(pjend AS STRING) as pjend,
    CAST(pjval AS STRING) as pjval,
    CAST(pjfor AS STRING) as pjfor,
    CAST(compgroup AS STRING) as compgroup,
    CAST(acccode AS STRING) as acccode,
    CAST(accname AS STRING) as accname,
    CAST(closedby AS STRING) as closedby,
    CAST(projectfrom AS STRING) as projectfrom,
    CAST(ptype AS STRING) as ptype,
    CAST(ppc AS STRING) as ppc,
    CAST(pecom AS STRING) as pecom,
    CAST(uinsert AS STRING) as uinsert,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert,
    CAST(insertby AS STRING) as insertby,
    CAST(uupdate AS STRING) as uupdate,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)) AS dupdate,
    CAST(meccode AS STRING) as meccode,
    CAST(contactdebcode AS STRING) as contactdebcode,
    CAST(refallkon AS STRING) as refallkon

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
