config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quodetail"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quodetail"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stkdesc desc, cname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(linkid AS INT64) as linkid,
    CAST(stkcode AS STRING) as stkcode,
    CAST(stkdesc AS STRING) as stkdesc,
    CAST(quantity AS FLOAT64) as quantity,
    CAST(lp AS FLOAT64) as lp,
    CAST(nd AS FLOAT64) as nd,
    CAST(sd1 AS FLOAT64) as sd1,
    CAST(sd2 AS FLOAT64) as sd2,
    CAST(sd3 AS FLOAT64) as sd3,
    CAST(dispercent AS FLOAT64) as dispercent,
    CAST(crc AS FLOAT64) as crc,
    CAST(price AS FLOAT64) as price,
    CAST(total AS FLOAT64) as total,
    CAST(priceforag AS FLOAT64) as priceforag,
    CAST(com AS FLOAT64) as com,
    CAST(setcb AS INT64) as setcb,
    CAST(type AS STRING) as type,
    CAST(status AS STRING) as status,
    CAST(sent AS STRING) as sent,
    CAST(datepart AS STRING) as datepart,
    CAST(fg AS STRING) as fg,
    CAST(pic AS STRING) as pic,
    CAST(productcp AS STRING) as productcp,
    CAST(pricecp AS FLOAT64) as pricecp,
    CAST(uinsert AS STRING) as uinsert,
    CAST(uupdate AS STRING) as uupdate,
    CAST(dinsert AS STRING) as dinsert,
    CAST(dupdate AS STRING) as dupdate,
    CAST(giveaway AS STRING) as giveaway,
    CAST(givestk AS STRING) as givestk,
    CAST(bgcount AS FLOAT64) as bgcount,
    CAST(orderno AS INT64) as orderno,
    CAST(lat AS STRING) as lat,
    CAST(long AS STRING) as long,
    CAST(mapnote AS STRING) as mapnote,
    CAST(fileupload AS STRING) as fileupload,
    CAST(city AS STRING) as city,
    CAST(rdosend AS INT64) as rdosend,
    CAST(cname AS STRING) as cname,
    CAST(ctel AS STRING) as ctel,
    CAST(caddress AS STRING) as caddress,
    CAST(checknote AS STRING) as checknote,
    CAST(textnote AS STRING) as textnote,
    CAST(ref_quodetail AS INT64) as ref_quodetail,
    CAST(productgrade AS INT64) as productgrade,
    CAST(fobprice AS FLOAT64) as fobprice,
    CAST(isshow AS INT64) as isshow

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
