config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_givestk"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_givestk"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_givestk"]

}

SELECT
    CAST(id AS INT64) as id,
    CAST(qtid AS INT64) as qtid,
    CAST(qtspread_ref_id AS INT64) as qtspread_ref_id,
    CAST(quodeid AS INT64) as quodeid,
    CAST(quolinkdel AS INT64) as quolinkdel,
    CAST(stkcode AS STRING) as stkcode,
    CAST(stkgive AS STRING) as stkgive,
    CAST(quantity AS INT64) as quantity,
    CAST(datetimekey AS DATETIME) as datetimekey,
    CAST(status AS INT64) as status

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY qtid desc, qtspread_ref_id desc) = 1

  -- pre_operations {}
  -- post_operations {}
