config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY accname desc, conname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(pjid AS STRING) as pjid,
    CAST(accid AS STRING) as accid,
    CAST(accname AS STRING) as accname,
    CAST(acctype AS STRING) as acctype,
    CAST(acctype2 AS STRING) as acctype2,
    CAST(accpow AS STRING) as accpow,
    CAST(conid AS STRING) as conid,
    CAST(conname AS STRING) as conname,
    CAST(contel AS STRING) as contel,
    CAST(condetail AS STRING) as condetail,
    CAST(uinsert AS STRING) as uinsert,
    PARSE_DATE('%Y-%m-%d', SUBSTR(insertdate, 1, 10)) AS insertdate,
    CAST(textnote AS STRING) as textnote,
    CAST(nickname AS STRING) as nickname,
    CAST(religion AS STRING) as religion,
    PARSE_DATE('%Y-%m-%d', SUBSTR(birthdate, 1, 10)) AS birthdate,
    CAST(lineidper AS STRING) as lineidper,
    CAST(emailper AS STRING) as emailper,
    CAST(idcardper AS STRING) as idcardper,
    CAST(addressper AS STRING) as addressper,
    CAST(country AS STRING) as country,
    CAST(province AS STRING) as province,
    CAST(district AS STRING) as district,
    CAST(sub_district AS STRING) as sub_district,
    CAST(zipcode AS STRING) as zipcode,
    CAST(spousefullname AS STRING) as spousefullname,
    PARSE_DATE('%Y-%m-%d', SUBSTR(birthdatespouse, 1, 10)) AS birthdatespouse,
    CAST(numberofchildren AS STRING) as numberofchildren,
    CAST(favoriteactivity AS STRING) as favoriteactivity,
    CAST(unfavoriteactivity AS STRING) as unfavoriteactivity,
    CAST(trait AS STRING) as trait

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
