config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY accname desc, conname desc) = 1`
        : ""

}

SELECT
    CAST(id AS INT64) as id,
    CAST(pjid AS STRING) as pjid,
    CAST(accid AS STRING) as accid,
    CAST(accname AS STRING) as accname,
    CAST(acctype AS STRING) as acctype,
    CAST(acctype2 AS STRING) as acctype2,
    CAST(accpow AS STRING) as accpow,
    CAST(conid AS STRING) as conid,
    CAST(conname AS STRING) as conname,
    CAST(contel AS STRING) as contel,
    CAST(condetail AS STRING) as condetail,
    CAST(uinsert AS STRING) as uinsert,
    CAST(insertdate AS DATE) as insertdate,
    CAST(textnote AS STRING) as textnote,
    CAST(nickname AS STRING) as nickname,
    CAST(religion AS STRING) as religion,
    CAST(birthdate AS DATE) as birthdate,
    CAST(lineidper AS STRING) as lineidper,
    CAST(emailper AS STRING) as emailper,
    CAST(idcardper AS STRING) as idcardper,
    CAST(addressper AS STRING) as addressper,
    CAST(country AS STRING) as country,
    CAST(province AS STRING) as province,
    CAST(district AS STRING) as district,
    CAST(sub_district AS STRING) as sub_district,
    CAST(zipcode AS STRING) as zipcode,
    CAST(spousefullname AS STRING) as spousefullname,
    CAST(birthdatespouse AS DATE) as birthdatespouse,
    CAST(numberofchildren AS STRING) as numberofchildren,
    CAST(favoriteactivity AS STRING) as favoriteactivity,
    CAST(unfavoriteactivity AS STRING) as unfavoriteactivity,
    CAST(trait AS STRING) as trait

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
