config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["userloginanyprogram"],
    bigquery: {
        clusterBy: databuffet.primaryKeys[databuffet.SOURCE_MAC5]["userloginanyprogram"],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["userloginanyprogram"]

    // สร้าง partition clause เฉพาะเมื่อมี pk_key
    const partition_statement = pk_key && pk_key.length > 0
        ? `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY username desc, name desc) = 1`
        : ""

}

SELECT
    CAST(id AS INT64) as id,
    CAST(username AS STRING) as username,
    CAST(password AS STRING) as password,
    CAST(actionapp AS STRING) as actionapp,
    CAST(name AS STRING) as name,
    CAST(notes AS STRING) as notes,
    CAST(department AS STRING) as department,
    CAST(levelaction AS STRING) as levelaction,
    CAST(email AS STRING) as email,
    CAST(token AS STRING) as token,
    CAST(tokenexpiry AS DATETIME) as tokenexpiry,
    CAST(istokenvalid AS INT64) as istokenvalid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
  -- post_operations {}
