config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["vmp"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["vmp"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY vmgltotal desc, vmglb1 desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(vmmonth AS INT64) as vmmonth,
    CAST(vmyear AS INT64) as vmyear,
    CAST(vmgltotal AS INT64) as vmgltotal,
    CAST(vmglb1 AS INT64) as vmglb1,
    CAST(vmglb2 AS INT64) as vmglb2,
    CAST(vmglb3 AS INT64) as vmglb3,
    CAST(vmglb4 AS INT64) as vmglb4,
    CAST(vmglb5 AS INT64) as vmglb5,
    CAST(vmglb6 AS INT64) as vmglb6,
    CAST(vmglb7 AS INT64) as vmglb7,
    CAST(vmglb8 AS INT64) as vmglb8,
    CAST(vmglb9 AS INT64) as vmglb9,
    CAST(vmglb10 AS INT64) as vmglb10,
    CAST(vmglb11 AS INT64) as vmglb11,
    CAST(vmglb12 AS INT64) as vmglb12,
    CAST(vmglb13 AS INT64) as vmglb13,
    CAST(vmglb14 AS INT64) as vmglb14,
    CAST(vmglb15 AS INT64) as vmglb15,
    CAST(vmglb16 AS INT64) as vmglb16,
    CAST(vmglb17 AS INT64) as vmglb17,
    CAST(vmglb18 AS INT64) as vmglb18,
    CAST(vmglb19 AS INT64) as vmglb19,
    CAST(vmglb20 AS INT64) as vmglb20,
    CAST(vmglb21 AS INT64) as vmglb21,
    CAST(vmglb22 AS INT64) as vmglb22,
    CAST(vmglb23 AS INT64) as vmglb23,
    CAST(vmglb24 AS INT64) as vmglb24,
    CAST(vmglb25 AS INT64) as vmglb25,
    CAST(vmglb26 AS INT64) as vmglb26,
    CAST(vmglb27 AS INT64) as vmglb27,
    CAST(vmglb28 AS INT64) as vmglb28,
    CAST(vmglb29 AS INT64) as vmglb29,
    CAST(vmglb30 AS INT64) as vmglb30,
    CAST(vmglb31 AS INT64) as vmglb31,
    CAST(vmglb32 AS INT64) as vmglb32,
    CAST(vmglb33 AS INT64) as vmglb33,
    CAST(vmglb34 AS INT64) as vmglb34,
    CAST(vmglb35 AS INT64) as vmglb35,
    CAST(vmglb36 AS INT64) as vmglb36,
    CAST(vmglb37 AS INT64) as vmglb37,
    CAST(vmglb38 AS INT64) as vmglb38,
    CAST(vmglb39 AS INT64) as vmglb39,
    CAST(vmglb40 AS INT64) as vmglb40,
    CAST(vmglb41 AS INT64) as vmglb41,
    CAST(vmglb42 AS INT64) as vmglb42,
    CAST(vmglb43 AS INT64) as vmglb43,
    CAST(vmglb44 AS INT64) as vmglb44,
    CAST(vmglb45 AS INT64) as vmglb45,
    CAST(vmglb46 AS INT64) as vmglb46,
    CAST(vmglb47 AS INT64) as vmglb47,
    CAST(vmglb48 AS INT64) as vmglb48,
    CAST(vmglb49 AS INT64) as vmglb49,
    CAST(vmglb50 AS INT64) as vmglb50,
    CAST(vmartotal AS INT64) as vmartotal,
    CAST(vmarquo AS INT64) as vmarquo,
    CAST(vmarpo AS INT64) as vmarpo,
    CAST(vmardel AS INT64) as vmardel,
    CAST(vmarbil AS INT64) as vmarbil,
    CAST(vmarinv AS INT64) as vmarinv,
    CAST(vmardrn AS INT64) as vmardrn,
    CAST(vmarcrn AS INT64) as vmarcrn,
    CAST(vmarcash AS INT64) as vmarcash,
    CAST(vmarlease AS INT64) as vmarlease,
    CAST(vmarrec AS INT64) as vmarrec,
    CAST(vmaptotal AS INT64) as vmaptotal,
    CAST(vmapquo AS INT64) as vmapquo,
    CAST(vmappo AS INT64) as vmappo,
    CAST(vmapdel AS INT64) as vmapdel,
    CAST(vmapbil AS INT64) as vmapbil,
    CAST(vmapinv AS INT64) as vmapinv,
    CAST(vmapdrn AS INT64) as vmapdrn,
    CAST(vmapcrn AS INT64) as vmapcrn,
    CAST(vmapcash AS INT64) as vmapcash,
    CAST(vmaplease AS INT64) as vmaplease,
    CAST(vmaprec AS INT64) as vmaprec,
    CAST(vmictotal AS INT64) as vmictotal,
    CAST(vmicgin AS INT64) as vmicgin,
    CAST(vmicgout AS INT64) as vmicgout,
    CAST(vmicgrt AS INT64) as vmicgrt,
    CAST(vmicgrf AS INT64) as vmicgrf,
    CAST(vmicjour AS INT64) as vmicjour,
    CAST(vmicmstr AS INT64) as vmicmstr,
    CAST(vmicpr AS INT64) as vmicpr,
    CAST(vmprtotal AS INT64) as vmprtotal,
    CAST(vmprsalary AS INT64) as vmprsalary,
    CAST(vmprmemo AS INT64) as vmprmemo,
    CAST(rowguid AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
