config {
  type: "operations",
  dependencies: ["dim_invoice", "fact_order"],
  tags: [databuffet.TAG_FACT_DAILY],
}

js {
    // Define table references
    const FactInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: name(),
    };
    const FactInvoiceTableRef = `${FactInvoiceTable.database}.${FactInvoiceTable.schema}.${FactInvoiceTable.name}`;

    const FactOrderTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: "fact_order",
    };
    const FactOrderTableRef = `${FactOrderTable.database}.${FactOrderTable.schema}.${FactOrderTable.name}`;

    const DimInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_invoice",
    };
    const DimInvoiceTableRef = `${DimInvoiceTable.database}.${DimInvoiceTable.schema}.${DimInvoiceTable.name}`;

    const DimCustomerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_customer",
    };
    const DimCustomerTableRef = `${DimCustomerTable.database}.${DimCustomerTable.schema}.${DimCustomerTable.name}`;

}

BEGIN
  -- drop table if exists `${FactInvoiceTableRef}`;
  
  -- create or replace table `${FactInvoiceTableRef}`
  -- partition by asatdate
  -- cluster by FactInvoiceSK
  -- as  
  create or replace temp table temp_invoice_table as
  with mil as (
    select
      milYear, milMonth, milDay,
      t.InvoiceSk,
      mil.milType,
      mil.milvnos,
      mil.milCus,
      mil.milLinkVcno, 
      mil.milStk,
      sum(mil.milQuan) as milQuan,
      sum(mil.milAdisc) as milAdisc,
      sum(mil.milCog) as milCog,
      sum(mil.milDisca) as milDisca,
      sum(mil.milSum) as milSum,
    FROM ${ref('curated_mil')} as mil
    INNER JOIN `${DimInvoiceTableRef}` as t 
      on t.mihYear = mil.milYear
        and t.mihMonth = mil.milMonth
        and t.mihDay = mil.milDay
        and t.mihType = mil.milType
        and t.mihVnos = mil.milVnos
        and t.mihCus = mil.milCus
        and IFNULL(t.milLinkVcno, '') = IFNULL(mil.milLinkVcno, '')
    where mil.asatdate >= current_date('Asia/Bangkok')-1
    group by 1,2,3,4,5,6,7,8,9

  )
  select 
    row_number() over(order by mil.milVnos, mil.milLinkVcno, mil.milStk) as FactInvoiceSK,
    mil.InvoiceSK,
    fact_ord.OrderSK,
    fact_ord.FactOrderSK,
    fact_ord.QuotationSK,
    fact_ord.FactQuotationSK,
    dim_cust.CustomerSK,
    
    PARSE_DATE('%Y%m%d', CONCAT(mil.milYear, FORMAT("%02d", mil.milMonth),  mil.milDay)) as mix_date,
    mil.* except(InvoiceSk),
    current_date('Asia/Bangkok') as asatdate
  from mil as mil
  LEFT JOIN `${FactOrderTableRef}` AS fact_ord
    ON IFNULL(mil.milLinkVcno, '') = IFNULL(fact_ord.milVnos, '')
    AND mil.milStk = fact_ord.milStk
  LEFT JOIN `${DimCustomerTableRef}` as dim_cust
    ON mil.milCus = dim_cust.debcode
  ;

  BEGIN    
    DELETE FROM `${FactInvoiceTableRef}` AS T
    WHERE EXISTS (
        SELECT 1 
        FROM temp_invoice_table AS S 
        WHERE T.milYear = S.milYear
          AND T.milMonth = S.milMonth
          AND T.milDay = S.milDay
          AND T.milType = S.milType
          AND T.milVnos = S.milVnos
          AND T.milCus = S.milCus
          AND IFNULL(T.milLinkVcno, '') = IFNULL(S.milLinkVcno, '')
          AND T.milStk = S.milStk
    );

    INSERT INTO `${FactInvoiceTableRef}` 
    SELECT * FROM temp_invoice_table;
  END;

  BEGIN
    DROP TABLE IF EXISTS temp_invoice_table;
  END;

  BEGIN
    DELETE FROM ${FactInvoiceTableRef}
    WHERE PARSE_DATE('%Y%m%d', CONCAT(milYear, FORMAT("%02d", milMonth), FORMAT("%02d", milDay))) < DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 4 YEAR), YEAR);
  END;

END;