config {
  type: "operations",
  dependencies: ["curated_mih", "curated_mil", "dim_product_master"],
  tags: [databuffet.TAG_FACT_DAILY],
}

js {
    // Define table references
    const FactTranscationTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: name(),
    };
    const FactTranscationTableRef = `${FactTranscationTable.database}.${FactTranscationTable.schema}.${FactTranscationTable.name}`;

    const DimProductTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_master",
    };
    const DimProductTableRef = `${DimProductTable.database}.${DimProductTable.schema}.${DimProductTable.name}`;
    
    const DimPaymentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_payment",
    };
    const DimPaymentTableRef = `${DimPaymentTable.database}.${DimPaymentTable.schema}.${DimPaymentTable.name}`;
    
    const DimChannelTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel",
    };
    const DimChannelTableRef = `${DimChannelTable.database}.${DimChannelTable.schema}.${DimChannelTable.name}`;
    
    const DimCostStkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_cost_stk",
    };
    const DimCostStkTableRef = `${DimCostStkTable.database}.${DimCostStkTable.schema}.${DimCostStkTable.name}`;
    
    const DimCostGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_cost_group",
    };
    const DimCostGroupTableRef = `${DimCostGroupTable.database}.${DimCostGroupTable.schema}.${DimCostGroupTable.name}`;
    
    const DimSaleRepGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative",
    };
    const DimSaleRepGroupTableRef = `${DimSaleRepGroupTable.database}.${DimSaleRepGroupTable.schema}.${DimSaleRepGroupTable.name}`;
    
    const DimDepartmentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department",
    };
    const DimDepartmentTableRef = `${DimDepartmentTable.database}.${DimDepartmentTable.schema}.${DimDepartmentTable.name}`;
    
    const DimRegionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region",
    };
    const DimRegionTableRef = `${DimRegionTable.database}.${DimRegionTable.schema}.${DimRegionTable.name}`;
    
    const DimRegionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_manager",
    };
    const DimRegionManagerTableRef = `${DimRegionManagerTable.database}.${DimRegionManagerTable.schema}.${DimRegionManagerTable.name}`;

    const DimSectionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section",
    };
    const DimSectionTableRef = `${DimSectionTable.database}.${DimSectionTable.schema}.${DimSectionTable.name}`;

    const DimSectionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_manager",
    };
    const DimSectionManagerTableRef = `${DimSectionManagerTable.database}.${DimSectionManagerTable.schema}.${DimSectionManagerTable.name}`;

    const DimDirectorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director",
    };
    const DimDirectorTableRef = `${DimDirectorTable.database}.${DimDirectorTable.schema}.${DimDirectorTable.name}`;

    const DimChannelCostTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel_cost",
    };
    const DimChannelCostTableRef = `${DimChannelCostTable.database}.${DimChannelCostTable.schema}.${DimChannelCostTable.name}`;

    const DimStkMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_stk_mkt",
    };
    const DimStkMktTableRef = `${DimStkMktTable.database}.${DimStkMktTable.schema}.${DimStkMktTable.name}`;

    const DimProductGroupBySaleDayofworkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_target_product_group_by_sale_dayofwork",
    };
    const DimProductGroupBySaleDayofworkTableRef = `${DimProductGroupBySaleDayofworkTable.database}.${DimProductGroupBySaleDayofworkTable.schema}.${DimProductGroupBySaleDayofworkTable.name}`;
    
    const DimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt",
    };
    const DimProductMktTableRef = `${DimProductMktTable.database}.${DimProductMktTable.schema}.${DimProductMktTable.name}`;

}

BEGIN
  CREATE OR REPLACE TEMP TABLE temp_fact_transcation 
  AS
  WITH raw_transction as (
    SELECT 
      channel_sk.ChannelSK,
      channel_sk.ChannelCostID,
      channel_sk.ChannelFinanceSK,
      channel_sk.ChannelSaleSK,
      channel_sk.ChannelCostSK,
      payment_sk.PaymentSK,

      PARSE_DATE('%Y%m%d', CONCAT(trans.milYear, FORMAT("%02d", trans.milMonth), FORMAT("%02d", trans.milDay))) as mix_date,
      
      -- productmaster.ProductCode,
      productmaster.ProductGroupACC,
      trans.*
    FROM ${databuffet.DATABASE}.onetime.Transaction_Data_Mart as trans
    
    -- Product Master
    LEFT JOIN `${DimProductTableRef}` AS productmaster
      ON trans.milstk = productmaster.ProductCode

    -- PaymentSK
    LEFT JOIN `${DimPaymentTableRef}` as payment_sk
      ON trans.memoextract = payment_sk.CodeMemo

    -- ChannelSK
    LEFT JOIN `${DimChannelTableRef}` AS channel_sk
      ON IFNULL(trans.milDep, 'N/A') = channel_sk.DepCode
      
    WHERE asatdate BETWEEN DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 4 YEAR), YEAR) AND CURRENT_DATE('Asia/Bangkok')
      -- AND milVnos = '6901003086'
      -- AND trans.milPer = '1065043'

), final_part1 as (
  SELECT 
    -- Surrogate Key
    sale_sk.SaleRepSK,
    dep_sk.DepartmentSK,
    reg_sk.RegionSK,
    reg_m_sk.RegionManagerSK,
    sec_sk.SectionSK,
    sec_m_sk.SectionManagerSK,
    dir_sk.DirectorSK,
    coststk_sk.CostStkSk,
    costgroup_sk.CostGroupSK,

    trans.ChannelSK,
    trans.ChannelFinanceSK,
    trans.ChannelSaleSK,
    trans.ChannelCostSK,

    -- DATA
    trans.* except(ChannelSK, ChannelFinanceSK, ChannelSaleSK, ChannelCostSK, milPer_raw),

    -- FOR USE THIS PROCESS
    dep_sk.DepartmentID
  FROM raw_transction as trans

  -- CostStkSk
  LEFT JOIN `${DimCostStkTableRef}` AS coststk_sk
      ON trans.milStk = coststk_sk.MilStk
      AND trans.ChannelCostID = coststk_sk.ChannelCostID
      AND trans.mix_date BETWEEN coststk_sk.StartDate AND coststk_sk.EndDate

  -- CostGroupSK
  LEFT JOIN `${DimCostGroupTableRef}` AS costgroup_sk
      ON trans.ProductGroupACC = costgroup_sk.GAccID
      AND trans.ChannelCostID = costgroup_sk.ChannelCostID 
      AND trans.mix_date BETWEEN costgroup_sk.StartDate AND costgroup_sk.EndDate

  -- SaleRepSK
  LEFT JOIN (
    select *,
      (CASE 
        WHEN TRIM(CAST(EmployeeID as STRING)) is not null and TRIM(DepCode) is not null and CostChannelID is not null 
          THEN 1
        WHEN TRIM(CAST(EmployeeID as STRING)) is not null and CostChannelID is not null 
          THEN 2
        ELSE 3
      END) as seq_condition
    from `${DimSaleRepGroupTableRef}`
  ) as sale_sk
    ON trans.mix_date between sale_sk.StartDate and sale_sk.EndDate
      and (CASE 
            WHEN sale_sk.DepCode IS NOT NULL and sale_sk.CostChannelID IS NOT NULL
              THEN TRIM(trans.milPer_raw) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and TRIM(trans.milDep) = TRIM(sale_sk.DepCode)
                and trans.ChannelCostID = sale_sk.CostChannelID
            WHEN sale_sk.ProvinceID IS NOT NULL
              THEN TRIM(trans.milPer_raw) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and CAST(trans.ProvinceSK as STRING) IN  UNNEST(SPLIT(sale_sk.ProvinceID, '|'))
            WHEN sale_sk.DepCode IS NULL and sale_sk.CostChannelID IS NOT NULL
              THEN TRIM(trans.milPer_raw) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and trans.ChannelCostID = sale_sk.CostChannelID
            ELSE TRIM(trans.milPer_raw) = TRIM(CAST(sale_sk.EmployeeID as STRING))
          END)

  -- DepartmentSK
  LEFT JOIN `${DimDepartmentTableRef}` as dep_sk
    ON trans.mix_date between dep_sk.StartDate and dep_sk.EndDate
      and sale_sk.DepartmentID = dep_sk.DepartmentID

  -- RegionSK
  LEFT JOIN `${DimRegionTableRef}` as reg_sk
    ON trans.mix_date between reg_sk.StartDate and reg_sk.EndDate
      and (CASE 
        WHEN reg_sk.RegionID != reg_sk.SubRegionID
          THEN dep_sk.RegionID = reg_sk.RegionID and dep_sk.SectionID = reg_sk.SubRegionID
        ELSE dep_sk.RegionID = reg_sk.RegionID
      END)

  -- RegionManagerSK
  LEFT JOIN `${DimRegionManagerTableRef}` as reg_m_sk
    ON trans.mix_date between reg_m_sk.StartDate and reg_m_sk.EndDate
      and (CASE 
        WHEN reg_m_sk.RegionID != reg_m_sk.SubRegionID
          THEN reg_sk.RegionID = reg_m_sk.RegionID and dep_sk.SectionID = reg_m_sk.SubRegionID
        ELSE reg_sk.RegionID = reg_m_sk.RegionID
      END)

  -- SectionSK
  LEFT JOIN `${DimSectionTableRef}` as sec_sk
    ON trans.mix_date between sec_sk.StartDate and sec_sk.EndDate
      and dep_sk.SectionID = sec_sk.SectionID

  -- SectionManagerSK
  LEFT JOIN `${DimSectionManagerTableRef}` as sec_m_sk
    ON trans.mix_date between sec_m_sk.StartDate and sec_m_sk.EndDate
      and sec_sk.SectionID = sec_m_sk.SectionID

  -- DirectorSK
  LEFT JOIN `${DimDirectorTableRef}` as dir_sk
    ON trans.mix_date between dir_sk.StartDate and dir_sk.EndDate
      and reg_sk.DirectorID = dir_sk.DirectorID

  WHERE IFNULL(trans.ChannelCostID, '') != 'COST99999'
  qualify row_number() over(partition by trans.milType,trans.milVnos,trans.milCus,trans.milStk,trans.milPer,trans.milListno order by sale_sk.seq_condition) = 1
  
), final_part2 as (
  SELECT 
    -- Surrogate Key
    sale_sk.SaleRepSK,
    dep_sk.DepartmentSK,
    reg_sk.RegionSK,
    reg_m_sk.RegionManagerSK,
    sec_sk.SectionSK,
    sec_m_sk.SectionManagerSK,
    dir_sk.DirectorSK,
    coststk_sk.CostStkSk,
    costgroup_sk.CostGroupSK,

    trans.ChannelSK,
    trans.ChannelFinanceSK,
    trans.ChannelSaleSK,
    channel_cost.ChannelCostSK,

    -- DATA
    trans.* except(ChannelSK, ChannelFinanceSK, ChannelSaleSK, ChannelCostSK, milPer_raw),

    -- FOR USE THIS PROCESS
    dep_sk.DepartmentID
  FROM raw_transction as trans

  -- SaleRepSK
  LEFT JOIN (
    select *,
      (CASE 
        WHEN TRIM(CAST(EmployeeID as STRING)) is not null and TRIM(DepCode) is not null and CostChannelID is not null 
          THEN 1
        WHEN TRIM(CAST(EmployeeID as STRING)) is not null and CostChannelID is not null 
          THEN 2
        ELSE 3
      END) as seq_condition
    from `${DimSaleRepGroupTableRef}`
  ) as sale_sk
    ON trans.mix_date between sale_sk.StartDate and sale_sk.EndDate
      and sale_sk.DepCode is null and sale_sk.CostChannelID is null
      and TRIM(trans.milPer_raw) = TRIM(CAST(sale_sk.EmployeeID as STRING))

  -- DepartmentSK
  LEFT JOIN `${DimDepartmentTableRef}` as dep_sk
    ON trans.mix_date between dep_sk.StartDate and dep_sk.EndDate
      and sale_sk.DepartmentID = dep_sk.DepartmentID

  -- RegionSK
  LEFT JOIN `${DimRegionTableRef}` as reg_sk
    ON trans.mix_date between reg_sk.StartDate and reg_sk.EndDate
      and (CASE 
        WHEN reg_sk.RegionID != reg_sk.SubRegionID
          THEN dep_sk.RegionID = reg_sk.RegionID and dep_sk.SectionID = reg_sk.SubRegionID
        ELSE dep_sk.RegionID = reg_sk.RegionID
      END)

  -- RegionManagerSK
  LEFT JOIN `${DimRegionManagerTableRef}` as reg_m_sk
    ON trans.mix_date between reg_m_sk.StartDate and reg_m_sk.EndDate
      and (CASE 
        WHEN reg_m_sk.RegionID != reg_m_sk.SubRegionID
          THEN reg_sk.RegionID = reg_m_sk.RegionID and dep_sk.SectionID = reg_m_sk.SubRegionID
        ELSE reg_sk.RegionID = reg_m_sk.RegionID
      END)

  -- SectionSK
  LEFT JOIN `${DimSectionTableRef}` as sec_sk
    ON trans.mix_date between sec_sk.StartDate and sec_sk.EndDate
      and dep_sk.SectionID = sec_sk.SectionID

  -- SectionManagerSK
  LEFT JOIN `${DimSectionManagerTableRef}` as sec_m_sk
    ON trans.mix_date between sec_m_sk.StartDate and sec_m_sk.EndDate
      and sec_sk.SectionID = sec_m_sk.SectionID

  -- DirectorSK
  LEFT JOIN `${DimDirectorTableRef}` as dir_sk
    ON trans.mix_date between dir_sk.StartDate and dir_sk.EndDate
      and reg_sk.DirectorID = dir_sk.DirectorID
  
  -- Join เพื่อหา ChannelCostID ใหม่ในกรณีที่เป็น COST99999
  LEFT JOIN `${DimChannelCostTableRef}` AS channel_cost
    ON sec_sk.SectionID = channel_cost.ChannelCostName

  -- CostStkSk
  LEFT JOIN `${DimCostStkTableRef}` AS coststk_sk
    ON trans.milStk = coststk_sk.MilStk
      AND coststk_sk.ChannelCostID = channel_cost.ChannelCostID
      AND trans.mix_date BETWEEN coststk_sk.StartDate AND coststk_sk.EndDate

  -- CostGroupSK
  LEFT JOIN `${DimCostGroupTableRef}` AS costgroup_sk
    ON trans.ProductGroupACC = costgroup_sk.GAccID
      AND costgroup_sk.ChannelCostID = channel_cost.ChannelCostID
      AND trans.mix_date BETWEEN costgroup_sk.StartDate AND costgroup_sk.EndDate

  WHERE trans.ChannelCostID = 'COST99999'
  qualify row_number() over(partition by trans.milType,trans.milVnos,trans.milCus,trans.milStk,trans.milPer,trans.milListno order by sale_sk.seq_condition) = 1

), mix_table as (
  select * except(ProductGroupACC)
  from final_part1
  -- where mildep is null
  union all
  select * except(ProductGroupACC)
  from final_part2
  -- where mildep is null
)
  select 
    -- SK
    stk_mkt.StkMktSK,
    product_mkt.ProductMktSK,
    tg_dayofwork.TargetBySaleDayofworkSK,
    tg_dayofwork.TargetProductGroupSK, 
    tg_dayofwork.RateTargetSK,

    -- DATA
    mix_table.* except(DepartmentID)
  from mix_table
  left join `${DimStkMktTableRef}` as stk_mkt
    on mix_table.milStk = stk_mkt.StkCode
  left join `${DimProductMktTableRef}` as product_mkt
    on stk_mkt.MarketingGroupID = product_mkt.MarketingGroupID
        and stk_mkt.SubMarketingID = product_mkt.SubMarketingID
        and stk_mkt.SegmentID = product_mkt.SegmentID
  left join `${DimProductGroupBySaleDayofworkTableRef}` as tg_dayofwork
    on mix_table.milyear = tg_dayofwork.year
        and mix_table.milmonth = tg_dayofwork.month
        and mix_table.milday = CAST(tg_dayofwork.day AS INT64)
        and mix_table.DepartmentID = tg_dayofwork.DepartmentID
        and stk_mkt.MarketingGroupID = tg_dayofwork.MarketingGroupID
        and stk_mkt.SubMarketingID = tg_dayofwork.SubMarketingID
        and stk_mkt.SegmentID = tg_dayofwork.SegmentID
  ;

--   -- 1767567
--   -- ALL : 2388305

  BEGIN    
    DELETE FROM `${FactTranscationTableRef}` AS T
    WHERE EXISTS (
        SELECT 1 
        FROM temp_fact_transcation AS S 
        WHERE T.milVnos = S.milVnos
          AND T.milType = S.milType
          AND T.milPer = S.milPer
          AND T.milListno = S.milListno
    )
    ;
  END;

  BEGIN
    INSERT INTO `${FactTranscationTableRef}` 
    SELECT * FROM temp_fact_transcation;
  END;

END;

BEGIN
  DELETE FROM ${FactTranscationTableRef}
  WHERE mix_date < DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 4 YEAR), YEAR);
END;