config {
  type: "operations",
  dependencies: ["curated_mih", "curated_mil", "dim_product_master"],
  tags: [databuffet.TAG_FACT_DAILY],
}

js {
    // Define table references
    const DimProductTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_master",
    };
    const DimProductTableRef = `${DimProductTable.database}.${DimProductTable.schema}.${DimProductTable.name}`;
    
    const DimPaymentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_payment",
    };
    const DimPaymentTableRef = `${DimPaymentTable.database}.${DimPaymentTable.schema}.${DimPaymentTable.name}`;
    
    const DimChannelTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel",
    };
    const DimChannelTableRef = `${DimChannelTable.database}.${DimChannelTable.schema}.${DimChannelTable.name}`;
    
    const DimCostStkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_cost_stk",
    };
    const DimCostStkTableRef = `${DimCostStkTable.database}.${DimCostStkTable.schema}.${DimCostStkTable.name}`;
    
    const DimCostGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_cost_group",
    };
    const DimCostGroupTableRef = `${DimCostGroupTable.database}.${DimCostGroupTable.schema}.${DimCostGroupTable.name}`;
    
    const DimSaleRepGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative",
    };
    const DimSaleRepGroupTableRef = `${DimSaleRepGroupTable.database}.${DimSaleRepGroupTable.schema}.${DimSaleRepGroupTable.name}`;
    
    const DimDepartmentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department",
    };
    const DimDepartmentTableRef = `${DimDepartmentTable.database}.${DimDepartmentTable.schema}.${DimDepartmentTable.name}`;
    
    const DimRegionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region",
    };
    const DimRegionTableRef = `${DimRegionTable.database}.${DimRegionTable.schema}.${DimRegionTable.name}`;
    
    const DimRegionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_manager",
    };
    const DimRegionManagerTableRef = `${DimRegionManagerTable.database}.${DimRegionManagerTable.schema}.${DimRegionManagerTable.name}`;

    const DimSectionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section",
    };
    const DimSectionTableRef = `${DimSectionTable.database}.${DimSectionTable.schema}.${DimSectionTable.name}`;

    const DimSectionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_manager",
    };
    const DimSectionManagerTableRef = `${DimSectionManagerTable.database}.${DimSectionManagerTable.schema}.${DimSectionManagerTable.name}`;

    const DimDirectorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director",
    };
    const DimDirectorTableRef = `${DimDirectorTable.database}.${DimDirectorTable.schema}.${DimDirectorTable.name}`;

    const DimChannelCostTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel_cost",
    };
    const DimChannelCostTableRef = `${DimChannelCostTable.database}.${DimChannelCostTable.schema}.${DimChannelCostTable.name}`;
}

BEGIN
  CREATE OR REPLACE TEMP TABLE temp_fact_transcation 
  AS
  WITH raw_transction as (
    SELECT 
      channel_sk.ChannelSK,
      channel_sk.ChannelCostID,
      channel_sk.ChannelFinanceSK,
      channel_sk.ChannelSaleSK,
      channel_sk.ChannelCostSK,
      payment_sk.PaymentSK,

      PARSE_DATE('%Y%m%d', CONCAT(trans.milYear, FORMAT("%02d", trans.milMonth), FORMAT("%02d", trans.milDay))) as mix_date,
      
      -- productmaster.ProductCode,
      productmaster.ProductGroupACC,
      trans.*
    FROM ${databuffet.DATABASE}.onetime.Transaction_Data_Mart as trans
    
    -- Product Master
    LEFT JOIN `${DimProductTableRef}` AS productmaster
      ON trans.milstk = productmaster.ProductCode

    -- PaymentSK
    LEFT JOIN ${DimPaymentTableRef} as payment_sk
      ON trans.memoextract = payment_sk.CodeMemo

    -- ChannelSK
    LEFT JOIN `${DimChannelTableRef}` AS channel_sk
      ON IFNULL(trans.milDep, 'N/A') = channel_sk.DepCode
      
    WHERE asatdate BETWEEN DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 4 YEAR), YEAR) AND CURRENT_DATE('Asia/Bangkok')
      -- AND milVnos = '6901003086'
      -- AND trans.milPer = '1065043'

), final_part1 as (
  SELECT 
    -- Surrogate Key
    sale_sk.SaleRepSK,
    dep_sk.DepartmentSK,
    reg_sk.RegionSK,
    reg_m_sk.RegionManagerSK,
    sec_sk.SectionSK,
    sec_m_sk.SectionManagerSK,
    dir_sk.DirectorSK,
    coststk_sk.CostStkSk,
    costgroup_sk.CostGroupSK,

    trans.ChannelSK,
    trans.ChannelFinanceSK,
    trans.ChannelSaleSK,
    trans.ChannelCostSK,

    -- DATA
    trans.* except(ChannelSK, ChannelFinanceSK, ChannelSaleSK, ChannelCostSK)
  FROM raw_transction as trans

  -- CostStkSk
  LEFT JOIN `${DimCostStkTableRef}` AS coststk_sk
      ON trans.milStk = coststk_sk.MilStk
      AND trans.ChannelCostID = coststk_sk.ChannelCostID
      AND trans.mix_date BETWEEN coststk_sk.StartDate AND coststk_sk.EndDate

  -- CostGroupSK
  LEFT JOIN `${DimCostGroupTable}` AS costgroup_sk
      ON trans.ProductGroupACC = costgroup_sk.GAccID
      AND trans.ChannelCostID = costgroup_sk.ChannelCostID 
      AND trans.mix_date BETWEEN costgroup_sk.StartDate AND costgroup_sk.EndDate

  -- SaleRepSK
  LEFT JOIN `${DimSaleRepGroupTable}` as sale_sk
    ON trans.mix_date between sale_sk.StartDate and sale_sk.EndDate
      and (CASE 
            WHEN sale_sk.DepCode IS NOT NULL and sale_sk.CostChannelID IS NOT NULL
              THEN TRIM(trans.milPer) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and TRIM(trans.milDep) = TRIM(sale_sk.DepCode)
                and trans.ChannelCostID = sale_sk.CostChannelID
            WHEN sale_sk.DepCode IS NULL and sale_sk.CostChannelID IS NOT NULL
              THEN TRIM(trans.milPer) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and trans.ChannelCostID = sale_sk.CostChannelID
            ELSE TRIM(trans.milPer) = TRIM(CAST(sale_sk.EmployeeID as STRING))
          END)

  -- DepartmentSK
  LEFT JOIN ${DimDepartmentTableRef} as dep_sk
    ON trans.mix_date between dep_sk.StartDate and dep_sk.EndDate
      and sale_sk.DepartmentID = dep_sk.DepartmentID

  -- RegionSK
  LEFT JOIN ${DimRegionTableRef} as reg_sk
    ON trans.mix_date between reg_sk.StartDate and reg_sk.EndDate
      and (CASE 
        WHEN reg_sk.RegionID != reg_sk.SubRegionID
          THEN dep_sk.RegionID = reg_sk.RegionID and dep_sk.SectionID = reg_sk.SubRegionID
        ELSE dep_sk.RegionID = reg_sk.RegionID
      END)

  -- RegionManagerSK
  LEFT JOIN ${DimRegionManagerTableRef} as reg_m_sk
    ON trans.mix_date between reg_m_sk.StartDate and reg_m_sk.EndDate
      and (CASE 
        WHEN reg_m_sk.RegionID != reg_m_sk.SubRegionID
          THEN reg_sk.RegionID = reg_m_sk.RegionID and dep_sk.SectionID = reg_m_sk.SubRegionID
        ELSE reg_sk.RegionID = reg_m_sk.RegionID
      END)

  -- SectionSK
  LEFT JOIN ${DimSectionTableRef} as sec_sk
    ON trans.mix_date between sec_sk.StartDate and sec_sk.EndDate
      and dep_sk.SectionID = sec_sk.SectionID

  -- SectionManagerSK
  LEFT JOIN ${DimSectionManagerTableRef} as sec_m_sk
    ON trans.mix_date between sec_m_sk.StartDate and sec_m_sk.EndDate
      and sec_sk.SectionID = sec_m_sk.SectionID

  -- DirectorSK
  LEFT JOIN ${DimDirectorTableRef} as dir_sk
    ON trans.mix_date between dir_sk.StartDate and dir_sk.EndDate
      and reg_sk.DirectorID = dir_sk.DirectorID

  WHERE IFNULL(trans.ChannelCostID, '') != 'COST99999'
  
), final_part2 as (
  SELECT 
    -- Surrogate Key
    sale_sk.SaleRepSK,
    dep_sk.DepartmentSK,
    reg_sk.RegionSK,
    reg_m_sk.RegionManagerSK,
    sec_sk.SectionSK,
    sec_m_sk.SectionManagerSK,
    dir_sk.DirectorSK,
    coststk_sk.CostStkSk,
    costgroup_sk.CostGroupSK,

    trans.ChannelSK,
    trans.ChannelFinanceSK,
    trans.ChannelSaleSK,
    channel_cost.ChannelCostSK,

    -- DATA
    trans.* except(ChannelSK, ChannelFinanceSK, ChannelSaleSK, ChannelCostSK)
  FROM raw_transction as trans

  -- SaleRepSK
  LEFT JOIN `${DimSaleRepGroupTable}` as sale_sk
    ON trans.mix_date between sale_sk.StartDate and sale_sk.EndDate
      and sale_sk.DepCode is null and sale_sk.CostChannelID is null
      and TRIM(trans.milPer) = TRIM(CAST(sale_sk.EmployeeID as STRING))

  -- DepartmentSK
  LEFT JOIN ${DimDepartmentTableRef} as dep_sk
    ON trans.mix_date between dep_sk.StartDate and dep_sk.EndDate
      and sale_sk.DepartmentID = dep_sk.DepartmentID

  -- RegionSK
  LEFT JOIN ${DimRegionTableRef} as reg_sk
    ON trans.mix_date between reg_sk.StartDate and reg_sk.EndDate
      and (CASE 
        WHEN reg_sk.RegionID != reg_sk.SubRegionID
          THEN dep_sk.RegionID = reg_sk.RegionID and dep_sk.SectionID = reg_sk.SubRegionID
        ELSE dep_sk.RegionID = reg_sk.RegionID
      END)

  -- RegionManagerSK
  LEFT JOIN ${DimRegionManagerTableRef} as reg_m_sk
    ON trans.mix_date between reg_m_sk.StartDate and reg_m_sk.EndDate
      and (CASE 
        WHEN reg_m_sk.RegionID != reg_m_sk.SubRegionID
          THEN reg_sk.RegionID = reg_m_sk.RegionID and dep_sk.SectionID = reg_m_sk.SubRegionID
        ELSE reg_sk.RegionID = reg_m_sk.RegionID
      END)

  -- SectionSK
  LEFT JOIN ${DimSectionTableRef} as sec_sk
    ON trans.mix_date between sec_sk.StartDate and sec_sk.EndDate
      and dep_sk.SectionID = sec_sk.SectionID

  -- SectionManagerSK
  LEFT JOIN ${DimSectionManagerTableRef} as sec_m_sk
    ON trans.mix_date between sec_m_sk.StartDate and sec_m_sk.EndDate
      and sec_sk.SectionID = sec_m_sk.SectionID

  -- DirectorSK
  LEFT JOIN ${DimDirectorTableRef} as dir_sk
    ON trans.mix_date between dir_sk.StartDate and dir_sk.EndDate
      and reg_sk.DirectorID = dir_sk.DirectorID
  
  -- Join เพื่อหา ChannelCostID ใหม่ในกรณีที่เป็น COST99999
  LEFT JOIN ${DimChannelCostTableRef} AS channel_cost
    ON sec_sk.SectionID = channel_cost.ChannelCostName

  -- CostStkSk
  LEFT JOIN `${DimCostStkTableRef}` AS coststk_sk
    ON trans.milStk = coststk_sk.MilStk
      AND coststk_sk.ChannelCostID = channel_cost.ChannelCostID
      AND trans.mix_date BETWEEN coststk_sk.StartDate AND coststk_sk.EndDate

  -- CostGroupSK
  LEFT JOIN `${DimCostGroupTable}` AS costgroup_sk
    ON trans.ProductGroupACC = costgroup_sk.GAccID
      AND costgroup_sk.ChannelCostID = channel_cost.ChannelCostID
      AND trans.mix_date BETWEEN costgroup_sk.StartDate AND costgroup_sk.EndDate

  WHERE trans.ChannelCostID = 'COST99999'

), mix_table as (
  select * except(ProductGroupACC)
  from final_part1
  -- where mildep is null
  union all
  select * except(ProductGroupACC)
  from final_part2
  -- where mildep is null
)
  select *
  from mix_table
  ;

--   -- 1767567
--   -- ALL : 2388305

  BEGIN    
    DELETE FROM `${databuffet.DATABASE}.fact_table.fact_transcation` AS T
    WHERE EXISTS (
        SELECT 1 
        FROM temp_fact_transcation AS S 
        WHERE T.milVnos = S.milVnos
          AND T.milType = S.milType
          AND T.milPer = S.milPer
          AND T.milListno = S.milListno
    )
    ;
  END;

  BEGIN
    INSERT INTO `${databuffet.DATABASE}.fact_table.fact_transcation` 
    SELECT * FROM temp_fact_transcation;
  END;

END;

BEGIN
  DELETE FROM ${databuffet.DATABASE}.fact_table.fact_transcation
  WHERE mix_date < DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 4 YEAR), YEAR);
END;