config {
    type: "incremental",
    schema: databuffet.VALIDATED_SALEOUT,
    dependencies: ["validated_schema_saleout", "create_all_table_raw_saleout_mdt"],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: ["Store", "Cat", "Sub_Cat", "Brand", "SKU"],
    bigquery: {
        clusterBy: ["Store", "Cat", "Sub_Cat", "Brand"]
    },
}

js {
    const pk_key = ["Store", "Cat", "Sub_Cat", "Brand", "SKU"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    ${databuffet.cleanString('Store')} as Store,
    ${databuffet.cleanString('Cat')} as Cat,
    ${databuffet.cleanString('Sub_Cat')} as Sub_Cat,
    ${databuffet.cleanString('Brand')} as Brand,
    ${databuffet.cleanString('SKU')} as SKU,
    ${databuffet.cleanString('Barcode')} as Barcode,
    ${databuffet.cleanString('Description')} as Description,
    ${databuffet.cleanString('Product_Type')} as Product_Type,
    CAST(Sales_Amount as FLOAT64) as Sales_Amount,
    CAST(Sales_Qty as INT64) as Sales_Qty,
    CAST(Stock_On_Hand as FLOAT64) as Stock_On_Hand,
    CAST(Stock_On_Order as INT64) as Stock_On_Order,
    PARSE_DATE('%Y-%m-%d', TRIM(Last_Sold_Date)) as Last_Sold_Date,
    PARSE_DATE('%Y-%m-%d', TRIM(Last_Receive_Date)) as Last_Receive_Date,
    ${databuffet.parseAsatDate()} as ASATDATE,
FROM `${databuffet.DATABASE}.${databuffet.RAW_SALEOUT_MDT}.report_sale_subscription`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
