config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["curated_tbook_quotation"],
  tags: [databuffet.TAG_VIEW],
}

select 
  ID,
  Running, 
  SDate,
  EXTRACT(YEAR FROM CAST(SDate AS DATE)) Year,
  EXTRACT(MONTH FROM CAST(SDate AS DATE)) Month,
  EXTRACT(DAY FROM CAST(SDate AS DATE)) Day,
  Atten,
  Project,
  UInsert,
  PriceValidity,
  TermDelivery,
  TermPayment 
from `${databuffet.DATABASE}.${databuffet.CURATED_MAC5}.curated_tbook_quotation`
