config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["curated_tbook_quotation"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const CuratedTbookQuotationTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_tbook_quotation",
    };
    const CuratedTbookQuotationTableRef = `${CuratedTbookQuotationTable.database}.${CuratedTbookQuotationTable.schema}.${CuratedTbookQuotationTable.name}`;
}

select 
  ID,
  Running, 
  SDate,
  EXTRACT(YEAR FROM CAST(SDate AS DATE)) Year,
  EXTRACT(MONTH FROM CAST(SDate AS DATE)) Month,
  EXTRACT(DAY FROM CAST(SDate AS DATE)) Day,
  Atten,
  Project,
  UInsert,
  PriceValidity,
  TermDelivery,
  TermPayment 
from `${CuratedTbookQuotationTableRef}`
