config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["curated_mih", "ar_s"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const CuratedMihTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_mih",
    };
    const CuratedMihTableRef = `${CuratedMihTable.database}.${CuratedMihTable.schema}.${CuratedMihTable.name}`;

    const ArSTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "ar_s",
    };
    const ArSTableRef = `${ArSTable.database}.${ArSTable.schema}.${ArSTable.name}`;
}

SELECT  
  mihYear, 
  mihMonth, 
  mihDay,
  mihVnos, 
  mihJob, 
  mihRef1, 
  mihRef2, 
  mihRef3, 
  mihCancel, 
  mihStatus ,
  ar.ar_snamet as Status_Name ,
  memoExtract,
  mihMemoNew,
  mihstatus_desc 
FROM `${CuratedMihTableRef}` mih
  left join `${ArSTableRef}` ar on mih.mihStatus = ar.ar_scode
WHERE mihType = 'PS'
