config {
  type: "view",
  schema: databuffet.ONETIME,
  tags: [databuffet.TAG_VIEW],
}

SELECT  
  mihYear, 
  mihMonth, 
  mihDay,
  mihVnos, 
  mihJob, 
  mihRef1, 
  mihRef2, 
  mihRef3, 
  mihCancel, 
  mihStatus ,
  ar.ar_snamet as Status_Name ,
  memoExtract,
  mihMemoNew,
  mihstatus_desc 
FROM ${ref(databuffet.CURATED_MAC5, "curated_mih")} mih
  left join ${ref(databuffet.VALIDATED_MAC5, "ar_s")} ar on mih.mihStatus = ar.ar_scode
WHERE mihType = 'PS'
