config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["ttrip_document", "ttrip", "curated_mil", "tdelivery", "curated_mih", "deb"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const TtripDocumentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "ttrip_document",
    };
    const TtripDocumentTableRef = `${TtripDocumentTable.database}.${TtripDocumentTable.schema}.${TtripDocumentTable.name}`;

    const TtripTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "ttrip",
    };
    const TtripTableRef = `${TtripTable.database}.${TtripTable.schema}.${TtripTable.name}`;

    const CuratedMilTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_mil",
    };
    const CuratedMilTableRef = `${CuratedMilTable.database}.${CuratedMilTable.schema}.${CuratedMilTable.name}`;

    const TdeliveryTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "tdelivery",
    };
    const TdeliveryTableRef = `${TdeliveryTable.database}.${TdeliveryTable.schema}.${TdeliveryTable.name}`;

    const CuratedMihTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_mih",
    };
    const CuratedMihTableRef = `${CuratedMihTable.database}.${CuratedMihTable.schema}.${CuratedMihTable.name}`;

    const DebTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "deb",
    };
    const DebTableRef = `${DebTable.database}.${DebTable.schema}.${DebTable.name}`;
}

select td.fdocument,d.fserial_no,t.fcode,t.fvehicle
  ,PARSE_DATE('%Y%m%d', LEFT(CAST(td.fdatetime AS STRING), 8)) as Date, mh.mihCus, deb.debnamet
  ,d.flattitude, d.flongtitude ,d.fzone ,d.fpoi
  ,td.fitem
  ,td.fitem2
  ,(case 
      when IFNULL(td.fdocument,'0') = '0' then 'ยังไม่จัดของ' 
      else 'จัดของขึ้นรถ' 
    end) S1 
  ,(case 
      when IFNULL(t.fpass_Date,'0') = '0' then 'ไม่ปล่อยรถ' 
      else 'ปล่อยรถแล้ว' 
    end) S2  
  ,(case 
      when IFNULL(d.fserial_no,'0') = '0' then 'ยังไม่ส่งของ' 
      else (case when td.fcancel = '0' then 'รับสินค้าแล้ว' else 'ลูกค้าไม่รับ' end) 
    end) S3
  ,count(td.fitem) qty2  
  
from `${TtripDocumentTableRef}` as td  
inner join `${TtripTableRef}` as t 
  on t.frun = td.fmaster  
inner join (select distinct milvnos from `${CuratedMilTableRef}` where miltype = 'IS') as milIS 
  on td.fdocument = milIS.milvnos
left join (         
  select fserial_no ,fmaster ,flattitude,flongtitude,fzone,fpoi ,fdatetime  
  from `${TdeliveryTableRef}` as dl 
  inner join (
    select distinct milvnos from `${CuratedMilTableRef}` where miltype = 'IS'
  ) as milIS2 
    on dl.fserial_no = milIS2.milvnos
) d 
  on td.fmaster = d.fmaster   

left join `${CuratedMihTableRef}` as mh 
  on td.fdocument = mh.mihvnos
left join `${DebTableRef}` as deb 
  on mh.mihCus = deb.debcode

where td.fdocument like (case when IFNULL(d.fserial_no,'0') = '0' then '%' else  d.fserial_no end)  
group by td.fdocument,t.fcode,t.fvehicle,td.fitem,td.fitem2  ,d.flattitude , d.flongtitude ,d.fzone ,d.fpoi
  ,(case when IFNULL(td.fdocument,'0') = '0' then 'ยังไม่จัดของ' else 'จัดของขึ้นรถ' end)   
  ,(case when IFNULL(t.fpass_Date,'0') = '0' then 'ไม่ปล่อยรถ' else 'ปล่อยรถแล้ว' end)  
  ,(case 
    when IFNULL(d.fserial_no,'0') = '0' then 'ยังไม่ส่งของ'
    else (case when td.fcancel = '0' then 'รับสินค้าแล้ว' else 'ลูกค้าไม่รับ' end)
  end)  
  ,d.fserial_no
  ,PARSE_DATE('%Y%m%d', LEFT(CAST(td.fdatetime AS STRING), 8))
  ,mh.mihCus,deb.debnamet
