config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["dim_target_product_group_by_sale_dayofwork", "dim_sale_representative_last", "dim_department_last", "dim_section_last", "dim_section_manager_last", "dim_region_manager_last", "dim_region_last", "dim_director_last", "dim_product_mkt", "dim_target_product_group", "dim_report"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimTargetProductGroupBySaleDayofworkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_target_product_group_by_sale_dayofwork",
    };
    const DimTargetProductGroupBySaleDayofworkTableRef = `${DimTargetProductGroupBySaleDayofworkTable.database}.${DimTargetProductGroupBySaleDayofworkTable.schema}.${DimTargetProductGroupBySaleDayofworkTable.name}`;

    const DimSaleRepresentativeLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative_last",
    };
    const DimSaleRepresentativeLastTableRef = `${DimSaleRepresentativeLastTable.database}.${DimSaleRepresentativeLastTable.schema}.${DimSaleRepresentativeLastTable.name}`;

    const DimDepartmentLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department_last",
    };
    const DimDepartmentLastTableRef = `${DimDepartmentLastTable.database}.${DimDepartmentLastTable.schema}.${DimDepartmentLastTable.name}`;

    const DimSectionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_last",
    };
    const DimSectionLastTableRef = `${DimSectionLastTable.database}.${DimSectionLastTable.schema}.${DimSectionLastTable.name}`;

    const DimSectionManagerLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_manager_last",
    };
    const DimSectionManagerLastTableRef = `${DimSectionManagerLastTable.database}.${DimSectionManagerLastTable.schema}.${DimSectionManagerLastTable.name}`;

    const DimRegionManagerLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_manager_last",
    };
    const DimRegionManagerLastTableRef = `${DimRegionManagerLastTable.database}.${DimRegionManagerLastTable.schema}.${DimRegionManagerLastTable.name}`;

    const DimRegionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_last",
    };
    const DimRegionLastTableRef = `${DimRegionLastTable.database}.${DimRegionLastTable.schema}.${DimRegionLastTable.name}`;

    const DimDirectorLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director_last",
    };
    const DimDirectorLastTableRef = `${DimDirectorLastTable.database}.${DimDirectorLastTable.schema}.${DimDirectorLastTable.name}`;

    const DimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt",
    };
    const DimProductMktTableRef = `${DimProductMktTable.database}.${DimProductMktTable.schema}.${DimProductMktTable.name}`;

    const DimTargetProductGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_target_product_group",
    };
    const DimTargetProductGroupTableRef = `${DimTargetProductGroupTable.database}.${DimTargetProductGroupTable.schema}.${DimTargetProductGroupTable.name}`;

    const DimReportTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_report",
    };
    const DimReportTableRef = `${DimReportTable.database}.${DimReportTable.schema}.${DimReportTable.name}`;
}

select 
      Target_Work.TargetBySaleDayofworkSK
      -- ,FORMAT('%d-%02d-%02d', CAST(Target_Work.Year AS INT64),CAST(Target_Work.Month AS INT64),CAST(Target_Work.Day AS INT64)) as TargetDate
      ,PARSE_DATE('%Y%m%d', CONCAT(Target_Work.Year, FORMAT("%02d", Target_Work.Month), CAST(Target_Work.Day AS INT64))) as TargetDate
      ,Target_Work.Year as TargetYear
      ,Target_Work.Month as TargetMonth
      ,Target_Work.Day as TargetDay
      ,SalesPer.EmployeeID as SalesRepID
      ,CONCAT(IFNULL(SalesPer.EmployeeName,''),' ',IFNULL(SalesPer.EmployeeSurname,'')) as SalesRepNameSurname
      ,SalesPer.DepartmentID as TeamID
      ,SalesPer.DepartmentName as TeamName
      ,Section.SectionID
      ,Section.SectionName
      ,CONCAT(IFNULL(SectionM.SectionManagerName,''),' ',IFNULL(SectionM.SectionManagerSurname,'')) as SectionManagerNameSurname
      ,Region.RegionID
      ,Region.RegionName 
      ,CONCAT(IFNULL(RegionM.RegionManagerName,''), ' ', IFNULL(RegionM.RegionManagerSurname,'')) as RegionManagerNameSurname
      ,director.DirectorID
      ,director.DirectorName
      ,director.DirectorOfSalesName as DirectorSalesNameSurname
      ,ProductMkt.MarketingGroupID
      ,ProductMkt.MarketingGroup as MarketingGroupName
      ,ProductMkt.SubMarketingID
      ,ProductMkt.SubMarketing as SubMarketingName
      ,ProductMkt.SegmentID
      ,ProductMkt.Segment as SegmentName
      ,Target_Work.ChannelTargetGroup
      ,Target_Work.Amt_New as TargetAmount
      ,Target_Work.Qty_New as TargetQuantity
      ,Report.ReportID 
      ,Report.ReportName1
      ,Report.ReportName2
      
from `${DimTargetProductGroupBySaleDayofworkTableRef}` as Target_Work
left join (
      select Sales_Rep.*, Department.DepartmentName 
      from `${DimSaleRepresentativeLastTableRef}` as Sales_Rep
      left join `${DimDepartmentLastTableRef}` as Department 
            on Sales_Rep.DepartmentSK = Department.DepartmentSK
            and Sales_Rep.CompanySK = Department.CompanySK
) SalesPer 
      on Target_Work.SaleRepSK = SalesPer.SaleRepSK
      and Target_Work.CompanySK = SalesPer.CompanySK
left join `${DimSectionLastTableRef}` as Section 
      on Target_Work.SectionSK = Section.SectionSK
      and Target_Work.CompanySK = Section.CompanySK
left join `${DimSectionManagerLastTableRef}` as SectionM 
      on Target_Work.SectionManagerSK = SectionM.SectionManagerSK
      and Target_Work.CompanySK = SectionM.CompanySK
left join `${DimRegionManagerLastTableRef}` as RegionM 
      on Target_Work.RegionManagerSK = RegionM.RegionManagerSK
      and Target_Work.CompanySK = RegionM.CompanySK
left join `${DimRegionLastTableRef}` as Region 
      on Target_Work.RegionSK = Region.RegionSK
      and Target_Work.CompanySK = Region.CompanySK
left join `${DimDirectorLastTableRef}` as director 
      on Target_Work.DirectorSK = director.DirectorSK
      and Target_Work.CompanySK = director.CompanySK
left join `${DimProductMktTableRef}` as ProductMkt 
      on Target_Work.ProductMktSK = ProductMkt.ProductMktSK
      and Target_Work.CompanySK = ProductMkt.CompanySK
left join `${DimTargetProductGroupTableRef}` as TargetGroup 
      on Target_Work.TargetProductGroupSK = TargetGroup.TargetProductGroupSK
      and Target_Work.CompanySK = TargetGroup.CompanySK
left join `${DimReportTableRef}` as Report 
      on Target_Work.ReportSK = Report.ReportSK
      and Target_Work.CompanySK = Report.CompanySK
where Target_Work.CompanySK = 4
