config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["view_fact_transcation", "dim_sale_representative_last", "dim_department_last", "dim_section_last", "dim_section_manager_last", "dim_region_manager_last", "dim_region_last", "dim_director_last", "dim_product_master", "dim_product_mkt", "view_dim_customer", "dim_invoice", "dim_payment", "dim_doctype", "dim_channel", "dim_channel_cost", "dim_report"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const ViewFactTranscationTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_VIEW,
        name: "view_fact_transcation",
    };
    const ViewFactTranscationTableRef = `${ViewFactTranscationTable.database}.${ViewFactTranscationTable.schema}.${ViewFactTranscationTable.name}`;

    const DimSaleRepresentativeLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative_last",
    };
    const DimSaleRepresentativeLastTableRef = `${DimSaleRepresentativeLastTable.database}.${DimSaleRepresentativeLastTable.schema}.${DimSaleRepresentativeLastTable.name}`;

    const DimDepartmentLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department_last",
    };
    const DimDepartmentLastTableRef = `${DimDepartmentLastTable.database}.${DimDepartmentLastTable.schema}.${DimDepartmentLastTable.name}`;

    const DimSectionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_last",
    };
    const DimSectionLastTableRef = `${DimSectionLastTable.database}.${DimSectionLastTable.schema}.${DimSectionLastTable.name}`;

    const DimSectionManagerLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_manager_last",
    };
    const DimSectionManagerLastTableRef = `${DimSectionManagerLastTable.database}.${DimSectionManagerLastTable.schema}.${DimSectionManagerLastTable.name}`;

    const DimRegionManagerLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_manager_last",
    };
    const DimRegionManagerLastTableRef = `${DimRegionManagerLastTable.database}.${DimRegionManagerLastTable.schema}.${DimRegionManagerLastTable.name}`;

    const DimRegionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_last",
    };
    const DimRegionLastTableRef = `${DimRegionLastTable.database}.${DimRegionLastTable.schema}.${DimRegionLastTable.name}`;

    const DimDirectorLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director_last",
    };
    const DimDirectorLastTableRef = `${DimDirectorLastTable.database}.${DimDirectorLastTable.schema}.${DimDirectorLastTable.name}`;

    const DimProductMasterTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_master",
    };
    const DimProductMasterTableRef = `${DimProductMasterTable.database}.${DimProductMasterTable.schema}.${DimProductMasterTable.name}`;

    const DimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt",
    };
    const DimProductMktTableRef = `${DimProductMktTable.database}.${DimProductMktTable.schema}.${DimProductMktTable.name}`;

    const ViewDimCustomerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_customer",
    };
    const ViewDimCustomerTableRef = `${ViewDimCustomerTable.database}.${ViewDimCustomerTable.schema}.${ViewDimCustomerTable.name}`;

    const DimInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_invoice",
    };
    const DimInvoiceTableRef = `${DimInvoiceTable.database}.${DimInvoiceTable.schema}.${DimInvoiceTable.name}`;

    const DimPaymentTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_payment",
    };
    const DimPaymentTableRef = `${DimPaymentTable.database}.${DimPaymentTable.schema}.${DimPaymentTable.name}`;

    const DimDoctypeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_doctype",
    };
    const DimDoctypeTableRef = `${DimDoctypeTable.database}.${DimDoctypeTable.schema}.${DimDoctypeTable.name}`;

    const DimChannelTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel",
    };
    const DimChannelTableRef = `${DimChannelTable.database}.${DimChannelTable.schema}.${DimChannelTable.name}`;

    const DimChannelCostTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel_cost",
    };
    const DimChannelCostTableRef = `${DimChannelCostTable.database}.${DimChannelCostTable.schema}.${DimChannelCostTable.name}`;

    const DimReportTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_report",
    };
    const DimReportTableRef = `${DimReportTable.database}.${DimReportTable.schema}.${DimReportTable.name}`;
}

select      
      Sales_Tran.mix_date as InvoiceDate
      ,Sales_Tran.milYear as InvoiceYear
      ,Sales_Tran.milMonth as InvoiceMonth
      ,Sales_Tran.milday as InvoiceDay
      ,Sales_Tran.milvnos as InvoiceNo
      ,DocType.Code as InvoiceType
      ,DocType.DescriptionEN as InvoiceTypeName
      ,inv.mihStatus as InvoiceStatusID
      ,inv.StatusDesc as InvoiceStatusName
      ,case when inv.mihCancel = -1 then 'Yes' else 'No' end as InvoiceCancel 
      ,Payment.PaymentID
      ,Payment.PaymentName
      ,Payment.PaymentType
      ,Channel.ChannelCostID
      ,Channel.ChannelCostName
      ,Channel.ChannelID as ChannelSaleID
      ,Channel.ChannelName as ChannelSaleName
      ,Channel.ChannelGroup as ChannelSaleGroup
      ,Channel.ChannelSubGroupName1 as ChannelSaleSubGroup1
      ,Channel.ChannelSubGroupName2 as ChannelSaleSubGroup2
      ,Channel.ChannelIDFinance as ChannelFinanceID
      ,Channel.ChannelNameFinance as ChannelFinanceName
      ,Channel.ChannelGroupFinance as ChannelFinanceGroup
      ,Channel.ChannelSubGroupFinance1 as ChannelFinanceSubGroup1
      ,Channel.ChannelSubGroupFinance2 as ChannelFinanceSubGroup2
      ,Channel.ChannelSubGroupFinance3 as ChannelFinanceSubGroup3
      ,Channel.ChannelDSite01 as ChannelD01Site
      ,Channel.ChannelDDepartment02 as ChannelD02Department
      ,Channel.ChannelDDivision03 as ChannelD03Division
      ,Channel.ChannelDSubDivision04 as ChannelD04SubDivision
      ,Sales_Tran.milJob as Job
      ,SalesPer.EmployeeID as SalesRepID
      ,CONCAT(IFNULL(SalesPer.EmployeeName,''),' ',IFNULL(SalesPer.EmployeeSurname,'')) as SalesRepNameSurname
      ,Sales_Tran.milDep as DepartmentCode
      ,SalesPer.DepartmentID as TeamID
      ,SalesPer.DepartmentName as TeamName
      ,Section.SectionID
      ,Section.SectionName
      ,CONCAT(IFNULL(SectionM.SectionManagerName,''),' ',IFNULL(SectionM.SectionManagerSurname,'')) as SectionManagerNameSurname
      ,Region.RegionID
      ,Region.RegionName 
      ,CONCAT(IFNULL(RegionM.RegionManagerName,''), ' ', IFNULL(RegionM.RegionManagerSurname,'')) as RegionManagerNameSurname
      ,director.DirectorID
      ,director.DirectorName
      ,director.DirectorOfSalesName as DirectorSalesNameSurname
      ,Sales_Tran.FlagSaleExc as FlagSaleKPIExclude
      ,Sales_Tran.FlagAccExc as FlagSalesFiananceExclude
      ,Sales_Tran.FlagSCG as SCGSalesType
      ,Sales_Tran.milstk as Product
      ,ProductMaster.ProductMac5Description as ProductName
      ,ProductMkt.MarketingGroupID
      ,ProductMkt.MarketingGroup as MarketingGroupName
      ,ProductMkt.SubMarketingID
      ,ProductMkt.SubMarketing as SubMarketingName
      ,ProductMkt.SegmentID
      ,ProductMkt.Segment as SegmentName
      ,Sales_Tran.milsum as NetSalesExcVat
      ,Sales_Tran.milsum_incvat as NetSalesIncVat
      ,Sales_Tran.milQuan as Quantity
      ,Sales_Tran.milDisca as DiscountAmountExcVat
      ,Sales_Tran.mildisca_incvat as DiscountAmountIncVat
      ,Sales_Tran.milCog as GrossAmountExcVat
      ,Sales_Tran.milcog_incvat as GrossAmountIncVat
      ,Sales_Tran.productpercent as ProductCostPercent
      ,Sales_Tran.DepositExcVat
      ,Sales_Tran.DepositIncVat
      ,Sales_Tran.milcus as CustomerID
      ,Customer.debnamet as CustomerName
      ,Customer.SubDistrict
      ,Customer.District
      ,Customer.Province
      ,Report.ReportID
      ,Report.ReportName1
      ,Report.ReportName2
      ,Sales_Tran.TargetBySaleDayofworkSK

      
      from `${ViewFactTranscationTableRef}` Sales_Tran

left join (
      select Sales_Rep.*, Department.DepartmentName 
      from `${DimSaleRepresentativeLastTableRef}` as Sales_Rep
      left join `${DimDepartmentLastTableRef}` as Department 
            on Sales_Rep.DepartmentSK = Department.DepartmentSK
            and Sales_Rep.CompanySK = Department.CompanySK
) SalesPer on Sales_Tran.SaleRepSKLast = SalesPer.SaleRepSK
      and Sales_Tran.CompanySK = SalesPer.CompanySK

left join `${DimSectionLastTableRef}` as Section 
      on Sales_Tran.ChangeSectionSKLast = Section.SectionSK
      and Sales_Tran.CompanySK = Section.CompanySK
left join `${DimSectionManagerLastTableRef}` as SectionM 
      on  Sales_Tran.SectionManagerSKLast = SectionM.SectionManagerSK
      and Sales_Tran.CompanySK = SectionM.CompanySK
left join `${DimRegionManagerLastTableRef}` as RegionM 
      on  Sales_Tran.RegionManagerSKLast = RegionM.RegionManagerSK
      and Sales_Tran.CompanySK = RegionM.CompanySK
left join `${DimRegionLastTableRef}` as Region 
      on  Sales_Tran.RegionSKLast = Region.RegionSK
      and Sales_Tran.CompanySK = Region.CompanySK
left join `${DimDirectorLastTableRef}` as director 
      on  Sales_Tran.DirectorSKLast = director.DirectorSK
      and Sales_Tran.CompanySK = director.CompanySK

left join `${DimProductMasterTableRef}` as ProductMaster 
      on  Sales_Tran.milstk = ProductMaster.ProductCode
      and Sales_Tran.CompanySK = ProductMaster.CompanySK
left join `${DimProductMktTableRef}` as ProductMkt 
      on  Sales_Tran.ProductMktSK = ProductMkt.ProductMktSK
      and Sales_Tran.CompanySK = ProductMkt.CompanySK

left join `${ViewDimCustomerTableRef}` as Customer 
      on  Sales_Tran.milCus = Customer.debcode
      and Sales_Tran.CompanySK = Customer.CompanySK
left join `${DimInvoiceTableRef}` as inv 
      on Sales_Tran.invoiceSK = inv.InvoiceSK
      and Sales_Tran.CompanySK = inv.CompanySK
left join `${DimPaymentTableRef}` as Payment 
      on Sales_Tran.PaymentSK = Payment.PaymentSK
      and Sales_Tran.CompanySK = Payment.CompanySK
left join `${DimDoctypeTableRef}` as DocType 
      on Sales_Tran.milType = DocType.Code
      and Sales_Tran.CompanySK = DocType.CompanySK
left join `${DimChannelTableRef}` as Channel 
      on Sales_Tran.ChannelSK = Channel.ChannelSK
      and Sales_Tran.CompanySK = Channel.CompanySK
left join `${DimChannelCostTableRef}` as ChannelCost 
      on Sales_Tran.ChannelCostSK = ChannelCost.ChannelCostSK
      and Sales_Tran.CompanySK = ChannelCost.CompanySK

left join `${DimReportTableRef}` as Report
      on Sales_Tran.ReportSK = Report.ReportSK
      and Sales_Tran.CompanySK = Report.CompanySK

where Sales_Tran.milYear in (2024,2025,2026) and Sales_Tran.milvnos is not null
      and Sales_Tran.CompanySK = 4
