config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["dim_target_product_group_by_sale_dayofwork", "dim_sale_representative_last", "dim_department_last", "dim_section_last", "dim_section_manager_last", "dim_region_manager_last", "dim_region_last", "dim_director_last", "dim_product_mkt", "dim_target_product_group", "dim_report"],
  tags: [databuffet.TAG_VIEW],
}

select 
      Target_Work.TargetBySaleDayofworkSK
      -- ,FORMAT('%d-%02d-%02d', CAST(Target_Work.Year AS INT64),CAST(Target_Work.Month AS INT64),CAST(Target_Work.Day AS INT64)) as TargetDate
      ,PARSE_DATE('%Y%m%d', CONCAT(Target_Work.Year, FORMAT("%02d", Target_Work.Month), CAST(Target_Work.Day AS INT64))) as TargetDate
      ,Target_Work.Year as TargetYear
      ,Target_Work.Month as TargetMonth
      ,Target_Work.Day as TargetDay
      ,SalesPer.EmployeeID as SalesRepID
      ,CONCAT(IFNULL(SalesPer.EmployeeName,''),' ',IFNULL(SalesPer.EmployeeSurname,'')) as SalesRepNameSurname
      ,SalesPer.DepartmentID as TeamID
      ,SalesPer.DepartmentName as TeamName
      ,Section.SectionID
      ,Section.SectionName
      ,CONCAT(IFNULL(SectionM.SectionManagerName,''),' ',IFNULL(SectionM.SectionManagerSurname,'')) as SectionManagerNameSurname
      ,Region.RegionID
      ,Region.RegionName 
      ,CONCAT(IFNULL(RegionM.RegionManagerName,''), ' ', IFNULL(RegionM.RegionManagerSurname,'')) as RegionManagerNameSurname
      ,director.DirectorID
      ,director.DirectorName
      ,director.DirectorOfSalesName as DirectorSalesNameSurname
      ,ProductMkt.MarketingGroupID
      ,ProductMkt.MarketingGroup as MarketingGroupName
      ,ProductMkt.SubMarketingID
      ,ProductMkt.SubMarketing as SubMarketingName
      ,ProductMkt.SegmentID
      ,ProductMkt.Segment as SegmentName
      ,Target_Work.ChannelTargetGroup
      ,Target_Work.Amt_New as TargetAmount
      ,Target_Work.Qty_New as TargetQuantity
      ,Report.ReportID 
      ,Report.ReportName1
      ,Report.ReportName2
      
from `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_target_product_group_by_sale_dayofwork` as Target_Work
left join (
      select Sales_Rep.*, Department.DepartmentName 
      from `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_sale_representative_last` as Sales_Rep
      left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_department_last` as Department 
            on Sales_Rep.DepartmentSK = Department.DepartmentSK
            and Sales_Rep.CompanySK = Department.CompanySK
) SalesPer 
      on Target_Work.SaleRepSK = SalesPer.SaleRepSK
      and Target_Work.CompanySK = SalesPer.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_section_last` as Section 
      on Target_Work.SectionSK = Section.SectionSK
      and Target_Work.CompanySK = Section.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_section_manager_last` as SectionM 
      on Target_Work.SectionManagerSK = SectionM.SectionManagerSK
      and Target_Work.CompanySK = SectionM.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_region_manager_last` as RegionM 
      on Target_Work.RegionManagerSK = RegionM.RegionManagerSK
      and Target_Work.CompanySK = RegionM.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_region_last` as Region 
      on Target_Work.RegionSK = Region.RegionSK
      and Target_Work.CompanySK = Region.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_director_last` as director 
      on Target_Work.DirectorSK = director.DirectorSK
      and Target_Work.CompanySK = director.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_product_mkt` as ProductMkt 
      on Target_Work.ProductMktSK = ProductMkt.ProductMktSK
      and Target_Work.CompanySK = ProductMkt.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_target_product_group` as TargetGroup 
      on Target_Work.TargetProductGroupSK = TargetGroup.TargetProductGroupSK
      and Target_Work.CompanySK = TargetGroup.CompanySK
left join `${databuffet.DATABASE}.${databuffet.DIMENSION_TABLE}.dim_report` as Report 
      on Target_Work.ReportSK = Report.ReportSK
      and Target_Work.CompanySK = Report.CompanySK
where Target_Work.CompanySK = 4
