config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["dim_product_master", "view_dim_product_mkt", "Product_Attribute", "dim_product_mkt_director"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimProductMasterTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_master",
    };
    const DimProductMasterTableRef = `${DimProductMasterTable.database}.${DimProductMasterTable.schema}.${DimProductMasterTable.name}`;

    const ViewDimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_product_mkt",
    };
    const ViewDimProductMktTableRef = `${ViewDimProductMktTable.database}.${ViewDimProductMktTable.schema}.${ViewDimProductMktTable.name}`;

    const ProductAttributeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.ONETIME,
        name: "Product_Attribute",
    };
    const ProductAttributeTableRef = `${ProductAttributeTable.database}.${ProductAttributeTable.schema}.${ProductAttributeTable.name}`;

    const DimProductMktDirectorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt_director",
    };
    const DimProductMktDirectorTableRef = `${DimProductMktDirectorTable.database}.${DimProductMktDirectorTable.schema}.${DimProductMktDirectorTable.name}`;
}

SELECT
  product.ProductCode,
  product.ProductCode1,
  product.ProductMac5Description,
  product.ProductGroupMAC5,
  product.ProductGroupMac5Description,
  product.ProductGroupMAC5Type,
  product.ProductGroupACC,
  product.ProductGroupACCName,
  product.ProductName,
  product.ProductDescription,
  product.ProductDimension1,
  product.ProductDimension2,
  product.ProductDimension3,
  product.ProductDimension4,
  product.ProductGarantee,
  product.ProductGaranteeDetail,
  product.ThaiIndustrialStandardFlag,
  product.ThaiIndustrialSatandardDetail,
  product.Barcode,
  mkt.MarketingGroupID,
  mkt.MarketingGroup,
  mkt.SubMarketingID,
  mkt.SubMarketing,
  mkt.SegmentID,
  mkt.Segment,
  mkt.TypeMarketingID,
  mkt.TypeMarketing,
  director.name as DirectorMarketingName,
  director.Surname as DirectorMarketingSurname,
  CONCAT(director.name,' ',director.Surname) as DirectorMarketingNameSurname,
  attr.ProductColor,
  attr.ProductShape,
  attr.ProductGrossWeight,
  attr.ProductNetWeight,
  attr.ProductSeries,
  attr.ProductSize,
  attr.ProductSizeHight,
  attr.ProductSizeLong,
  attr.ProductSizeWide,
  attr.ProductUnit,
  attr.ProductMaterials,
  attr.ProductModel
FROM `${DimProductMasterTableRef}` product
LEFT JOIN `${ViewDimProductMktTableRef}` mkt
  ON product.ProductMktSK = mkt.ProductMktSK and product.CompanySK = mkt.CompanySK

LEFT JOIN `${ProductAttributeTableRef}` attr
  ON product.ProductSK = attr.ProductSK and product.CompanySK = attr.CompanySK

LEFT JOIN `${DimProductMktDirectorTableRef}` director
  ON mkt.ProductMktDirectorSK = director.ProductMktDirectorSK and mkt.CompanySK = director.CompanySK

where product.companyID = 'ag01'
