config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["per", "dim_sale_representative"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const PerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "per",
    };
    const PerTableRef = `${PerTable.database}.${PerTable.schema}.${PerTable.name}`;

    const DimSaleRepresentativeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative",
    };
    const DimSaleRepresentativeTableRef = `${DimSaleRepresentativeTable.database}.${DimSaleRepresentativeTable.schema}.${DimSaleRepresentativeTable.name}`;
}

SELECT
  t2.percode AS EmployeeID,
  CASE WHEN INSTR(t2.pernamet, ' ') > 0 THEN TRIM(SUBSTR(t2.pernamet, 1, INSTR(t2.pernamet, ' ') - 1)) ELSE t2.pernamet END AS EmployeeName,
  CASE WHEN INSTR(t2.pernamet, ' ') > 0 THEN  TRIM(SUBSTR(t2.pernamet, INSTR(t2.pernamet, ' ') + 1)) ELSE NULL END AS EmployeeSurname,
  REGEXP_EXTRACT(t2.pernamet, r'\(([^)]*)\)') AS EmployeeNickname
FROM
  `${PerTableRef}` AS t2
WHERE
  CAST(t2.percode AS STRING) NOT IN (
  SELECT
    DISTINCT CAST(t1.EmployeeID AS STRING)
  FROM
    `${DimSaleRepresentativeTableRef}` AS t1
  WHERE
    t1.EmployeeID IS NOT NULL )
