config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["stk", "curated_mih", "curated_tbook_quotation", "curated_mil", "view_deb_address_data", "dim_company"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const StkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "stk",
    };
    const StkTableRef = `${StkTable.database}.${StkTable.schema}.${StkTable.name}`;

    const CuratedMihTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_mih",
    };
    const CuratedMihTableRef = `${CuratedMihTable.database}.${CuratedMihTable.schema}.${CuratedMihTable.name}`;

    const CuratedTbookQuotationTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_tbook_quotation",
    };
    const CuratedTbookQuotationTableRef = `${CuratedTbookQuotationTable.database}.${CuratedTbookQuotationTable.schema}.${CuratedTbookQuotationTable.name}`;

    const FnFlagSalesKpiTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FUNCTION_DATASET,
        name: "fn_flag_sales_kpi",
    };
    const FnFlagSalesKpiTableRef = `${FnFlagSalesKpiTable.database}.${FnFlagSalesKpiTable.schema}.${FnFlagSalesKpiTable.name}`;

    const CuratedMilTable = {
        database: databuffet.DATABASE,
        schema: databuffet.CURATED_MAC5,
        name: "curated_mil",
    };
    const CuratedMilTableRef = `${CuratedMilTable.database}.${CuratedMilTable.schema}.${CuratedMilTable.name}`;

    const DimProductRebateTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_rebate",
    };
    const DimProductRebateTableRef = `${DimProductRebateTable.database}.${DimProductRebateTable.schema}.${DimProductRebateTable.name}`;

    const ViewDebAddressDataTable = {
        database: databuffet.DATABASE,
        schema: databuffet.PROCESS_DATASET,
        name: "view_deb_address_data",
    };
    const ViewDebAddressDataTableRef = `${ViewDebAddressDataTable.database}.${ViewDebAddressDataTable.schema}.${ViewDebAddressDataTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;
}

WITH stk as (
  SELECT DISTINCT
    company_id,
    stkcode,
    stkvat,
    (stkvat / 100) + 1 AS vat,
    stkcode885,
    stkgroup
  FROM `${StkTableRef}`
  -- where company_id = 'ag01'

), mih_ps as (
  select 
    mihps.company_id,
    mihVnos,
    qt.id as QuotationID ,
    qt.running as QuotationCode 
  from `${CuratedMihTableRef}` as mihps
  left join `${CuratedTbookQuotationTableRef}` as qt  
    on mihps.mihref1 = qt.running
    and mihps.company_id = qt.company_id
  where mihps.mihType = 'PS'
    -- and mihps.company_id = 'ag01'

), raw_transcation as (
  SELECT
    -- `${FnFlagSalesKpiTableRef}`(a.mihcancel, a.mihstatus, product_rebate.rebate) as FlagSalesKPI,
    dim_com.CompanySK,
    dim_com.companyID,
    a.mihvatno,
    a.mihdesc,
    a.mihmemo,
    a.memoextract,
    a.mihmemonew,
    a.mihCancel,
    a.mihStatus,
    mih_ps.QuotationID,
    mih_ps.QuotationCode,
    b.* except(company_id),

    s.stkcode885,
    s.vat as stkVat,
    s.stkgroup as stkGroup,
    a.mihVatsum,
    a.mihExtrasum,
    a.mihExtravat,
    aidata.ProvinceSK as OrderProvinceSK,
    aidata.DistrictSK as OrderDistrictSK,
    aidata.SubDistrictSK as OrderSubDistrictSK,
    SUM(milSum) OVER (PARTITION BY b.milDay, b.milMonth, b.milYear, b.milType, b.milCus, b.milVnos) as over_milsum,

  FROM `${CuratedMihTableRef}` as a
  INNER JOIN `${CuratedMilTableRef}` as b
    ON a.mihYear = b.milYear
      AND a.mihMonth = b.milMonth
      AND a.mihDay = b.milDay
      AND a.mihType = b.milType
      AND a.mihVnos = b.milVnos
      AND a.mihCus = b.milCus
      AND a.company_id = b.company_id
  LEFT JOIN mih_ps as mih_ps
    ON b.milLinkvcno = mih_ps.mihVnos
    and b.company_id = mih_ps.company_id
  LEFT JOIN stk AS s
    ON s.stkcode = b.milstk
    and s.company_id = b.company_id
  -- LEFT JOIN `${DimProductRebateTableRef}` as product_rebate 
  --   ON b.milstk = product_rebate.Rebate
  LEFT JOIN `${ViewDebAddressDataTableRef}` as aidata
    ON a.mihCus = aidata.debcode
    AND a.company_id = aidata.company_id
  LEFT JOIN `${DimCompanyTableRef}` as dim_com
    ON a.company_id = dim_com.companyID
  WHERE a.mihtype IN ('IS', 'AS', 'BS', 'QS') 
    -- and a.company_id = 'ag01'

), transcation as (
  SELECT *,
    (CASE 
      WHEN milType = 'BS' 
        THEN 
          IF(
            IFNULL(over_milsum, 0) <> 0, 
            (milSum / over_milsum)*-1 * mihVatsum,
          0) *-1
      ELSE 
        IF(
          IFNULL(over_milsum, 0) <> 0,
          (milSum / over_milsum) * mihVatsum,
        0)
    END) as Vat,

  FROM raw_transcation

)
  SELECT 
    * EXCEPT(mihVatsum, stkVat, stkcode885, mihExtrasum, mihExtravat, over_milsum),
    --------- Oat Edit --------------
    /*(CASE
      WHEN milType = 'BS' and milsum < 0 THEN 0
      ELSE milsum + Vat 
    END) AS milsum_incvat,*/
    --------- End Oat Edit --------------
    milsum + Vat AS milsum_incvat,

    (CASE
      WHEN IFNULL(mihVatsum, 0.0) <> 0.0 THEN mildisca * stkVat
      ELSE mildisca
    END) AS mildisca_incvat,

    (CASE 
      WHEN IFNULL(mihVatsum, 0.0) <> 0.0 THEN milcog * stkVat
      ELSE milcog
    END) AS milcog_incvat,

    stkcode885 AS Barcode,
    IF(
      IFNULL(over_milsum, 0) <> 0,
      ((milSum / over_milsum) * mihExtrasum),
    0) AS DepositExcVat,
    IF(
      IFNULL(over_milsum, 0) <> 0,
      (((milSum / over_milsum) * mihExtrasum) + (milSum / over_milsum) * mihExtravat),
    0) AS DepositIncVat,
    IF(
      IFNULL(over_milsum, 0) <> 0,
      ((milSum / over_milsum) * mihExtravat),
    0) AS DepositVat,

  FROM transcation
