config {
  type: "view",
  schema: databuffet.ONETIME,
  dependencies: ["stk", "stk_mkt", "stg", "product", "product_detail", "brand", "vendor"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const StkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "stk",
    };
    const StkTableRef = `${StkTable.database}.${StkTable.schema}.${StkTable.name}`;

    const StkMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "stk_mkt",
    };
    const StkMktTableRef = `${StkMktTable.database}.${StkMktTable.schema}.${StkMktTable.name}`;

    const StgTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MAC5,
        name: "stg",
    };
    const StgTableRef = `${StgTable.database}.${StgTable.schema}.${StgTable.name}`;

    const ProductTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MASTERSKU,
        name: "product",
    };
    const ProductTableRef = `${ProductTable.database}.${ProductTable.schema}.${ProductTable.name}`;

    const CategoryTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MASTERSKU,
        name: "category",
    };
    const CategoryTableRef = `${CategoryTable.database}.${CategoryTable.schema}.${CategoryTable.name}`;

    const ProductDetailTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MASTERSKU,
        name: "product_detail",
    };
    const ProductDetailTableRef = `${ProductDetailTable.database}.${ProductDetailTable.schema}.${ProductDetailTable.name}`;

    const BrandTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MASTERSKU,
        name: "brand",
    };
    const BrandTableRef = `${BrandTable.database}.${BrandTable.schema}.${BrandTable.name}`;

    const VendorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.VALIDATED_MASTERSKU,
        name: "vendor",
    };
    const VendorTableRef = `${VendorTable.database}.${VendorTable.schema}.${VendorTable.name}`;
}

select 
a.stkcode,
a.stkgroup,
g.stgdesct,
g.stgdesce,
a.stkcode2,
a.stkdesct1,
a.stksortnt,
a.stksto,
a.stksalegrp,
a.stkcode885 ,
a.stkvat,
b.zgroup3 as Group_1 ,
b.zgroup4 as Shipping ,
p.prd_sku ,
p.prd_description ,
p.prd_model ,
p.prd_is_active,
p.prd_barcode ,
p.prd_brand_id ,
brand.bra_name,
p.prd_cat_id ,
pc.cat_code ,
pc.cat_level ,
pd.pd_material,
p.prd_vendor_id,
vendor.vd_name,
pd.pd_certificate,
pd.pd_garantee
from `${StkTableRef}` a  
left join `${StkMktTableRef}` b on a.STKcode = b.stkcode
left join `${StgTableRef}` g on a.STKgroup = g.STGcode
left join `${ProductTableRef}` p on a.STKcode885 = p.prd_barcode
left join `${CategoryTableRef}` pc on p.prd_cat_id = pc.cat_id
left join `${ProductDetailTableRef}` pd on p.prd_id = pd.pd_prd_id
left join `${BrandTableRef}` brand on p.prd_brand_id = brand.bra_id
left join `${VendorTableRef}` vendor on p.prd_vendor_id = vendor.vd_id
--where a.STKcode885 is not null and a.STKcode885 <> ''
