config {
  type: "view",
  schema: databuffet.FACT_VIEW,
  dependencies: ["dim_calendar", "dim_product_mkt", "dim_rebate", "dim_report", "fact_transcation", "dim_guarantee", "dim_section_last", "dim_section", "dim_sale_representative", "dim_channel", "dim_sale_representative_last", "dim_department_last", "dim_director_last", "dim_change_district", "dim_cost_stk", "dim_cost_group", "dim_stk_mkt", "dim_region_last", "dim_product_master", "fact_invoice", "view_dim_aging", "fact_order", "view_dim_invoice", "dim_region", "dim_company", "dim_director", "dim_region_manager", "dim_section_manager"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const DimCalendarTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_calendar",
    };
    const DimCalendarTableRef = `${DimCalendarTable.database}.${DimCalendarTable.schema}.${DimCalendarTable.name}`;

    const DimChangeDistrictTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_change_district",
    };
    const DimChangeDistrictTableRef = `${DimChangeDistrictTable.database}.${DimChangeDistrictTable.schema}.${DimChangeDistrictTable.name}`;

    const DimChannelTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_channel",
    };
    const DimChannelTableRef = `${DimChannelTable.database}.${DimChannelTable.schema}.${DimChannelTable.name}`;

    const DimCompanyTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_company",
    };
    const DimCompanyTableRef = `${DimCompanyTable.database}.${DimCompanyTable.schema}.${DimCompanyTable.name}`;

    const DimCostGroupTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_cost_group",
    };
    const DimCostGroupTableRef = `${DimCostGroupTable.database}.${DimCostGroupTable.schema}.${DimCostGroupTable.name}`;

    const DimCostStkTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_cost_stk",
    };
    const DimCostStkTableRef = `${DimCostStkTable.database}.${DimCostStkTable.schema}.${DimCostStkTable.name}`;

    const DimDepartmentLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_department_last",
    };
    const DimDepartmentLastTableRef = `${DimDepartmentLastTable.database}.${DimDepartmentLastTable.schema}.${DimDepartmentLastTable.name}`;

    const DimDirectorTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director",
    };
    const DimDirectorTableRef = `${DimDirectorTable.database}.${DimDirectorTable.schema}.${DimDirectorTable.name}`;

    const DimDirectorLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_director_last",
    };
    const DimDirectorLastTableRef = `${DimDirectorLastTable.database}.${DimDirectorLastTable.schema}.${DimDirectorLastTable.name}`;

    const DimGuaranteeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_guarantee",
    };
    const DimGuaranteeTableRef = `${DimGuaranteeTable.database}.${DimGuaranteeTable.schema}.${DimGuaranteeTable.name}`;

    const DimProductMasterTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_master",
    };
    const DimProductMasterTableRef = `${DimProductMasterTable.database}.${DimProductMasterTable.schema}.${DimProductMasterTable.name}`;

    const DimProductMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_product_mkt",
    };
    const DimProductMktTableRef = `${DimProductMktTable.database}.${DimProductMktTable.schema}.${DimProductMktTable.name}`;

    const DimRebateTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_rebate",
    };
    const DimRebateTableRef = `${DimRebateTable.database}.${DimRebateTable.schema}.${DimRebateTable.name}`;

    const DimRegionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region",
    };
    const DimRegionTableRef = `${DimRegionTable.database}.${DimRegionTable.schema}.${DimRegionTable.name}`;

    const DimRegionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_last",
    };
    const DimRegionLastTableRef = `${DimRegionLastTable.database}.${DimRegionLastTable.schema}.${DimRegionLastTable.name}`;

    const DimRegionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_region_manager",
    };
    const DimRegionManagerTableRef = `${DimRegionManagerTable.database}.${DimRegionManagerTable.schema}.${DimRegionManagerTable.name}`;

    const DimReportTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_report",
    };
    const DimReportTableRef = `${DimReportTable.database}.${DimReportTable.schema}.${DimReportTable.name}`;

    const DimSaleRepresentativeTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative",
    };
    const DimSaleRepresentativeTableRef = `${DimSaleRepresentativeTable.database}.${DimSaleRepresentativeTable.schema}.${DimSaleRepresentativeTable.name}`;

    const DimSaleRepresentativeLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_sale_representative_last",
    };
    const DimSaleRepresentativeLastTableRef = `${DimSaleRepresentativeLastTable.database}.${DimSaleRepresentativeLastTable.schema}.${DimSaleRepresentativeLastTable.name}`;

    const DimSectionTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section",
    };
    const DimSectionTableRef = `${DimSectionTable.database}.${DimSectionTable.schema}.${DimSectionTable.name}`;

    const DimSectionLastTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_last",
    };
    const DimSectionLastTableRef = `${DimSectionLastTable.database}.${DimSectionLastTable.schema}.${DimSectionLastTable.name}`;

    const DimSectionManagerTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_section_manager",
    };
    const DimSectionManagerTableRef = `${DimSectionManagerTable.database}.${DimSectionManagerTable.schema}.${DimSectionManagerTable.name}`;

    const DimStkMktTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_stk_mkt",
    };
    const DimStkMktTableRef = `${DimStkMktTable.database}.${DimStkMktTable.schema}.${DimStkMktTable.name}`;

    const ViewDimAgingTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_aging",
    };
    const ViewDimAgingTableRef = `${ViewDimAgingTable.database}.${ViewDimAgingTable.schema}.${ViewDimAgingTable.name}`;

    const ViewDimInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_VIEW,
        name: "view_dim_invoice",
    };
    const ViewDimInvoiceTableRef = `${ViewDimInvoiceTable.database}.${ViewDimInvoiceTable.schema}.${ViewDimInvoiceTable.name}`;

    const FactInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: "fact_invoice",
    };
    const FactInvoiceTableRef = `${FactInvoiceTable.database}.${FactInvoiceTable.schema}.${FactInvoiceTable.name}`;

    const FactOrderTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: "fact_order",
    };
    const FactOrderTableRef = `${FactOrderTable.database}.${FactOrderTable.schema}.${FactOrderTable.name}`;

    const FactTranscationTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: "fact_transcation",
    };
    const FactTranscationTableRef = `${FactTranscationTable.database}.${FactTranscationTable.schema}.${FactTranscationTable.name}`;

    const FnFlagExcTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FUNCTION_DATASET,
        name: "fn_flag_exc",
    };
    const FnFlagExcTableRef = `${FnFlagExcTable.database}.${FnFlagExcTable.schema}.${FnFlagExcTable.name}`;

    const FnFlagScgTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FUNCTION_DATASET,
        name: "fn_flag_scg",
    };
    const FnFlagScgTableRef = `${FnFlagScgTable.database}.${FnFlagScgTable.schema}.${FnFlagScgTable.name}`;

    const MdsDataChangeMarketinggroupMasterTable = {
        database: databuffet.DATABASE,
        schema: databuffet.MDS_DATASET,
        name: "mds_data_change_marketinggroup_master",
    };
    const MdsDataChangeMarketinggroupMasterTableRef = `${MdsDataChangeMarketinggroupMasterTable.database}.${MdsDataChangeMarketinggroupMasterTable.schema}.${MdsDataChangeMarketinggroupMasterTable.name}`;

    const MappingInvoiceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.ONETIME,
        name: "mapping_invoice",
    };
    const MappingInvoiceTableRef = `${MappingInvoiceTable.database}.${MappingInvoiceTable.schema}.${MappingInvoiceTable.name}`;
}

with dim_calendar as (
  select cal.Date, comp.CompanySK
  from `${DimCalendarTableRef}` as cal
  cross join `${DimCompanyTableRef}` as comp
  where Date between DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 4 YEAR), YEAR) AND CURRENT_DATE('Asia/Bangkok')-1 
 
), mds_change_mktgroup as (
  SELECT 
    chg.companyid, chg.depcodeaction, chg.depcode, 
    chg.jobaction, chg.job, 
    chg.productaction, chg.productid, 
    chg.productgroupaction, chg.productgroup, 
    chg.salesregionaction, chg.salesregion, 
    chg.salesamtaction, chg.salesamt, 
    chg.productdescriptionaction, chg.productdescription, 
    chg.remarkaction, chg.remark, 
    chg.marketingaction, 
    oldmarketinggroupid, oldsubmarketinggroupid, oldsegmentid, 
    new_mktgroup.ProductMktSK as NewProductMktSK,
    newmarketinggroupid, newsubmarketinggroupid, newsegmentid
  FROM `${MdsDataChangeMarketinggroupMasterTableRef}` as chg
  LEFT JOIN `${DimProductMktTableRef}` as new_mktgroup
    on chg.companyid = new_mktgroup.CompanyID
    and chg.newmarketinggroupid = new_mktgroup.MarketingGroupID
    and chg.newsubmarketinggroupid = new_mktgroup.SubMarketingID
    and chg.newsegmentid = new_mktgroup.SegmentID
  WHERE chg.is_active = TRUE

), dim_rebate as (
  select * 
  from `${DimRebateTableRef}`
  where lower(trim(status)) in ('cutomer', 'sales', 'product', 'textsplit')
    -- and companyID = 'ag01'

), dim_report as (
  SELECT 
    *, 
    (CASE 
      WHEN COUNT(*) OVER(PARTITION BY RegionID) = 1 THEN 1
      WHEN COUNT(*) OVER(PARTITION BY RegionID) > 1 
            AND MarketingGroupID IS NULL THEN 3
      ELSE 2
    END) AS Segment
  FROM `${DimReportTableRef}`
  -- where companyID = 'ag01'
  
), fact_transaction as (
  select
    (CASE 
      WHEN trans.companyID not in ('ag01', 'ab01') THEN null
      WHEN trans.companyID in ('ag01', 'ab01') and map_inv.FlagMustUser = True THEN 'Yes'
      WHEN trans.companyID in ('ag01', 'ab01') and cast(format_date('%Y%m', trans.mix_date) as int64) > 202601 THEN null
      WHEN trans.companyID in ('ag01', 'ab01') and map_inv.SectionID is not null THEN 'Yes'
      ELSE 'No'
    END) as FlagMappingInvoice, 
    map_inv.SectionID as SectionMappingID,
    deb.debgroup,
    
    -- gur.GuaranteeSK,

    trans.*
  from `${FactTranscationTableRef}` as trans

  -- deb
  left join ${ref(databuffet.VALIDATED_MAC5, "deb")} as deb
    on trans.milCus = deb.debcode
    and trans.companyID = deb.company_id

  -- mapping invoice
  left join `${MappingInvoiceTableRef}` as map_inv
    on trans.milPer = TRIM(map_inv.milPer)
    and trans.milVnos = TRIM(map_inv.milVnos)
    and trans.companyID = TRIM(map_inv.CompanyID)

  -- guarantee
  -- left join `${DimGuaranteeTableRef}` as gur
  --   on gur.CustomerID = trans.milCus
  --   and gur.CompanySK = trans.CompanySK

  -- where trans.companyID = 'ag01'

), raw_table as (
  select 
    trans.FlagMappingInvoice,
    dim_report.ReportSK,
    sale_sk.SaleRepSK as SaleRepSKLast,
    (CASE 
      WHEN FlagMappingInvoice is null THEN dep_sk.DepartmentSK
      WHEN FlagMappingInvoice = 'Yes' THEN null
      ELSE null
    END) as DepartmentSKLast,
    (CASE 
      WHEN FlagMappingInvoice is null THEN sec_sk.RegionSK
      WHEN FlagMappingInvoice = 'Yes' THEN sec_map_sk.RegionSK
      ELSE null
    END) as RegionSKLast,
    (CASE 
      WHEN FlagMappingInvoice is null THEN sec_sk.RegionManagerSK
      WHEN FlagMappingInvoice = 'Yes' THEN sec_map_sk.RegionManagerSK
      ELSE null
    END) as RegionManagerSKLast,
    (CASE 
      WHEN FlagMappingInvoice is null THEN sec_sk.SectionSK
      WHEN FlagMappingInvoice = 'Yes' THEN sec_map_sk.SectionSK
      ELSE null
    END) as SectionSKLast,
    (CASE 
      WHEN FlagMappingInvoice is null THEN sec_sk.SectionManagerSK
      WHEN FlagMappingInvoice = 'Yes' THEN sec_map_sk.SectionManagerSK
      ELSE null
    END) as SectionManagerSKLast,
    (CASE 
      WHEN FlagMappingInvoice is null THEN sec_sk.DirectorSK
      WHEN FlagMappingInvoice = 'Yes' THEN sec_map_sk.DirectorSK
      ELSE null
    END) as DirectorSKLast,

    (CASE
      WHEN UPPER(dir_map.DirectorName) = UPPER('Agent') THEN change_sec_map_sk.SectionSK
      ELSE (CASE 
              WHEN UPPER(dir_map.DirectorName) LIKE 'PS%' and UPPER(LEFT(trans.SectionMappingID, 3)) = UPPER(LEFT(chg_dis_map.newSectionID, 3))
                THEN change_sec_map_sk.SectionSK
              ELSE (CASE 
                    WHEN FlagMappingInvoice is null THEN 
                      (CASE 
                        WHEN IFNULL(sale_sk.ChangeSectionFlag, 'No') = 'Yes' 
                          THEN COALESCE(change_sec_sk.SectionSK, (SELECT SectionSK FROM `${DimSectionLastTableRef}` WHERE SectionID = 'Dummy999990'))
                        ELSE sec_sk.SectionSK -- COALESCE(change_sec_sk.SectionSK, sec_sk.SectionSK)
                      END)
                    WHEN FlagMappingInvoice = 'Yes' THEN sec_map_sk.SectionSK
                    ELSE null
                  END) 
            END)
    END) as ChangeSectionSKLast,

    ----  change transaction
    (CASE 
      WHEN IFNULL(dim_salerep.ChangeSectionFlag, 'No') = 'Yes' 
        THEN COALESCE(trans.ChangeSectionSK, dummy_sec.SectionSK)
      ELSE COALESCE(trans.ChangeSectionSK, trans.SectionSK)
    END) as ChangeSectionSK,

    (CASE 
      WHEN IFNULL(dim_salerep.ChangeSectionFlag, 'No') = 'Yes' 
        THEN COALESCE(trans.ChangeSectionManagerSK, dummy_sec_mgr.SectionManagerSK)
      ELSE COALESCE(trans.ChangeSectionManagerSK, trans.SectionManagerSK)
    END) as ChangeSectionManagerSK,

    (CASE 
      WHEN IFNULL(dim_salerep.ChangeSectionFlag, 'No') = 'Yes' 
        THEN COALESCE(trans.ChangeRegionSK, dummy_reg.RegionSK)
      ELSE COALESCE(trans.ChangeRegionSK, trans.RegionSK)
    END) as ChangeRegionSK,

    (CASE 
      WHEN IFNULL(dim_salerep.ChangeSectionFlag, 'No') = 'Yes' 
        THEN COALESCE(trans.ChangeRegionManagerSK, dummy_reg_mgr.RegionManagerSK)
      ELSE COALESCE(trans.ChangeRegionManagerSK, trans.RegionManagerSK)
    END) as ChangeRegionManagerSK,

    (CASE 
      WHEN IFNULL(dim_salerep.ChangeSectionFlag, 'No') = 'Yes' 
        THEN COALESCE(trans.ChangeDirectorSK, dummy_dir.DirectorSK)
      ELSE COALESCE(trans.ChangeDirectorSK, trans.DirectorSK)
    END) as ChangeDirectorSK,

    trans.* except(ChangeSectionSK, ChangeRegionSK, ChangeDirectorSK,
      ChangeSectionManagerSK, ChangeRegionManagerSK,
      SectionMappingID, debgroup, FlagMappingInvoice),

    (CASE
      WHEN sale_sk.seq_condition = 3 and trans.ChannelCostID = sale_sk.CostChannelID THEN 3.1
      WHEN sale_sk.seq_condition = 3 and trans.debgroup in ('HP', 'HPEXPO') and lower(sale_sk.DepartmentID) like 'hp_%'THEN 3.2
      WHEN sale_sk.seq_condition = 3 and trans.debgroup in ('TW', 'TWEXPO') and lower(sale_sk.DepartmentID) like 'tw_%'THEN 3.3
      WHEN sale_sk.seq_condition = 3 and trans.debgroup in ('BT', 'BT.C') and lower(sale_sk.DepartmentID) like 'bt_%' THEN 3.4
      WHEN sale_sk.seq_condition = 3 and trans.debgroup in ('GB') and lower(sale_sk.DepartmentID) like 'gb_%' THEN 3.5
      WHEN sale_sk.seq_condition = 3 and trans.debgroup in ('MH') and lower(sale_sk.DepartmentID) like 'mh_%' THEN 3.6
      WHEN sale_sk.seq_condition = 3 and trans.debgroup in ('DOHOME') and lower(sale_sk.DepartmentID) like 'dh_%' THEN 3.7
      ELSE sale_sk.seq_condition
    END) as seq_condition,

    (CASE 
      WHEN trans.CostStkSk is not null THEN ROUND(cost_stk_sk.Percent/100, 4)
      WHEN trans.CostGroupSk is not null THEN ROUND(cost_group_sk.Percent/100, 4)
      ELSE NULL
    END) as ProductPercent,
    (CASE 
      WHEN trans.CostStkSk is not null THEN '% Stk'
      WHEN trans.CostGroupSk is not null THEN '% Group'
      ELSE NULL
    END) as FlagProductPercent,

    `${FnFlagScgTableRef}`(milLinkvcno, milCus) as FlagSCG,

  from fact_transaction as trans

  left join `${DimSaleRepresentativeTableRef}` as dim_salerep
    on trans.SaleRepSk = dim_salerep.SaleRepSk
    and trans.CompanySK = dim_salerep.CompanySK

  -- dim_channel
  left join (
      select 
        * except(DummyChannel),
        IF(DummyChannel <> 'not calculated', DummyChannel, CAST(NULL AS STRING)) as DummyChannel
      from `${DimChannelTableRef}`
  ) as channel_sk
    on trans.ChannelSK = channel_sk.ChannelSK
    and trans.CompanySK = channel_sk.CompanySK

  -- SaleRepSK
  left join (
    select *,
      (CASE 
        WHEN NULLIF(TRIM(CAST(EmployeeID as STRING)), '') is not null 
          and NULLIF(TRIM(CAST(DepCode as STRING)), '') is not null 
          and NULLIF(TRIM(CAST(CostChannelID as STRING)), '') is not null 
          THEN 1
        WHEN NULLIF(TRIM(CAST(EmployeeID as STRING)), '') is not null and NULLIF(TRIM(CAST(ProvinceID as STRING)), '') is not null
          THEN 2
        WHEN NULLIF(TRIM(CAST(EmployeeID as STRING)), '') is not null and NULLIF(TRIM(CAST(CostChannelID as STRING)), '') is not null 
          THEN 3
        WHEN NULLIF(TRIM(CAST(EmployeeID as STRING)), '') is not null and NULLIF(TRIM(CAST(DepartmentID as STRING)), '') is not null
          THEN 4
        ELSE 5
      END) as seq_condition
    from `${DimSaleRepresentativeLastTableRef}`
  ) as sale_sk
    on trans.CompanySK = sale_sk.CompanySK
    and (CASE 
            WHEN IFNULL(TRIM(sale_sk.DepCode), '') != '' and IFNULL(TRIM(sale_sk.CostChannelID), '') != ''
              THEN TRIM(IFNULL(trans.DummyChannel, trans.milPer)) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and TRIM(trans.milDep) = TRIM(sale_sk.DepCode)
                and trans.ChannelCostID = sale_sk.CostChannelID
            WHEN IFNULL(TRIM(sale_sk.DepCode), '') = '' and IFNULL(TRIM(sale_sk.CostChannelID), '') != ''
              THEN TRIM(IFNULL(trans.DummyChannel, trans.milPer)) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and (CASE
                      WHEN trans.ChannelCostID = sale_sk.CostChannelID THEN TRUE
                      WHEN trans.debgroup in ('HP', 'HPEXPO') THEN lower(sale_sk.DepartmentID) like 'hp_%'
                      WHEN trans.debgroup in ('TW', 'TWEXPO') THEN lower(sale_sk.DepartmentID) like 'tw_%'
                      WHEN trans.debgroup in ('BT', 'BT.C') THEN lower(sale_sk.DepartmentID) like 'bt_%'
                      WHEN trans.debgroup in ('GB') THEN lower(sale_sk.DepartmentID) like 'gb_%'
                      WHEN trans.debgroup in ('MH') THEN lower(sale_sk.DepartmentID) like 'mh_%'
                      WHEN trans.debgroup in ('DOHOME') THEN lower(sale_sk.DepartmentID) like 'dh_%'
                    END)
            WHEN IFNULL(TRIM(sale_sk.ProvinceID), '') != ''
              THEN TRIM(IFNULL(trans.DummyChannel, trans.milPer)) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and CAST(trans.OrderProvinceSK as STRING) IN  UNNEST(SPLIT(sale_sk.ProvinceID, '|'))
            WHEN IFNULL(TRIM(sale_sk.DepartmentID), '') != '' 
              THEN TRIM(IFNULL(trans.DummyChannel, trans.milPer)) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and sale_sk.DepartmentID is not null
            WHEN IFNULL(TRIM(sale_sk.DepartmentID), '') = '' 
              THEN TRIM(IFNULL(trans.DummyChannel, trans.milPer)) = TRIM(CAST(sale_sk.EmployeeID as STRING))
                and sale_sk.DepartmentID is null
          END)

  -- DepartmentSK
  left join `${DimDepartmentLastTableRef}` as dep_sk
    on sale_sk.DepartmentSK = dep_sk.DepartmentSK
    and trans.CompanySK = dep_sk.CompanySK

  -- SectionSK
  left join `${DimSectionLastTableRef}` as sec_sk
    on dep_sk.SectionSK = sec_sk.SectionSK
    and trans.CompanySK = sec_sk.CompanySK
    
  -- Change Section
  left join `${DimSectionTableRef}` as change_sec
    on COALESCE(trans.ChangeSectionSK, trans.SectionSK) = change_sec.SectionSK
    and trans.CompanySK = change_sec.CompanySK

  -- ChangeSectionSK
  left join `${DimSectionLastTableRef}` as change_sec_sk
    on change_sec.SectionID = change_sec_sk.SectionID
    and trans.CompanySK = change_sec_sk.CompanySK
    
  -- SectionForMapping
  left join `${DimSectionLastTableRef}` as sec_map_sk
    on trans.SectionMappingID = sec_map_sk.SectionID
    and trans.CompanySK = sec_map_sk.CompanySK

  -- DirectorForMapping
  left join `${DimDirectorLastTableRef}` as dir_map
    on sec_map_sk.DirectorSK = dir_map.DirectorSK
    and trans.CompanySK = dir_map.CompanySK
    
  -- ChangeDistrictForMapping
  left join `${DimChangeDistrictTableRef}` as chg_dis_map
    on trans.milCus = chg_dis_map.customerCode
    and trans.CompanySK = chg_dis_map.CompanySK

  -- ChangeSectionForMapping
  left join `${DimSectionLastTableRef}` as change_sec_map_sk
    on trans.SectionMappingID = change_sec_map_sk.SectionID
    and trans.CompanySK = change_sec_map_sk.CompanySK

  -- CostStkSk
  left join `${DimCostStkTableRef}` as cost_stk_sk
    on trans.CostStkSk = cost_stk_sk.CostStkSk
    and trans.CompanySK = cost_stk_sk.CompanySK

  -- CostGroupSK
  left join `${DimCostGroupTableRef}` as cost_group_sk
    on trans.CostGroupSK = cost_group_sk.CostGroupSK
    and trans.CompanySK = cost_group_sk.CompanySK

  -- StkMkt
  left join `${DimStkMktTableRef}` as stk_mkt
    on trans.StkMktSK = stk_mkt.StkMktSK
    and trans.CompanySK = stk_mkt.CompanySK

  -- Region Last
  left join `${DimRegionLastTableRef}` as region_last
    on sec_sk.RegionSK = region_last.RegionSK
    and trans.CompanySK = region_last.CompanySK

  -- RegionMapping Last
  left join `${DimRegionLastTableRef}` as region_map_last
    on sec_map_sk.RegionSK = region_map_last.RegionSK
    and trans.CompanySK = region_map_last.CompanySK

  -- ReportSk
  left join dim_report as dim_report
    on trans.CompanySK = dim_report.CompanySK
    and (CASE 
      WHEN dim_report.Segment = 1 
        THEN (CASE
            WHEN FlagMappingInvoice is null THEN region_last.RegionID
            WHEN FlagMappingInvoice = 'Yes' THEN region_map_last.RegionID
            ELSE null
          END) = dim_report.RegionID
      WHEN dim_report.Segment = 2
        THEN (CASE
          WHEN FlagMappingInvoice is null THEN region_last.RegionID
          WHEN FlagMappingInvoice = 'Yes' THEN region_map_last.RegionID
          ELSE null
        END) = dim_report.RegionID
          and stk_mkt.MarketingGroupID = dim_report.MarketingGroupID
      WHEN dim_report.Segment = 3
        THEN (CASE
          WHEN FlagMappingInvoice is null THEN region_last.RegionID
          WHEN FlagMappingInvoice = 'Yes' THEN region_map_last.RegionID
          ELSE null
        END) = dim_report.RegionID
          and dim_report.MarketingGroupID is null
    END)

    LEFT JOIN `${DimSectionTableRef}` as dummy_sec
      ON dummy_sec.SectionID = 'Dummy999990'
      AND trans.CompanySK = dummy_sec.CompanySK
      AND trans.mix_date BETWEEN dummy_sec.StartDate AND dummy_sec.EndDate

    LEFT JOIN `${DimSectionManagerTableRef}` as dummy_sec_mgr
      ON dummy_sec_mgr.SectionID = 'Dummy999990'
      AND trans.CompanySK = dummy_sec_mgr.CompanySK
      AND trans.mix_date BETWEEN dummy_sec_mgr.StartDate AND dummy_sec_mgr.EndDate

    LEFT JOIN `${DimRegionTableRef}` dummy_reg
      ON dummy_reg.RegionID = 'Dummy999990'
      AND dummy_reg.SubRegionID = 'Dummy999990'
      AND trans.CompanySK = dummy_reg.CompanySK
      AND trans.mix_date BETWEEN dummy_reg.StartDate AND dummy_reg.EndDate

    LEFT JOIN `${DimRegionManagerTableRef}` as dummy_reg_mgr
      ON dummy_reg_mgr.RegionID = 'Dummy999990'
      AND dummy_reg_mgr.SubRegionID = 'Dummy999990'
      AND trans.CompanySK = dummy_reg_mgr.CompanySK
      AND trans.mix_date BETWEEN dummy_reg_mgr.StartDate AND dummy_reg_mgr.EndDate

    LEFT JOIN `${DimDirectorTableRef}` as dummy_dir
      ON dummy_dir.DirectorID = 'Non Director'
      AND trans.CompanySK = dummy_dir.CompanySK
      AND trans.mix_date BETWEEN dummy_dir.StartDate AND dummy_dir.EndDate

  -- where UPPER(left(milLinkvcno,3)) = 'CRC'

  qualify row_number() over(partition by trans.CompanySK, trans.milType,trans.milVnos,trans.milCus,trans.milStk,trans.milPer,trans.milListno order by seq_condition, dim_report.Segment, sale_sk.SaleRepSK desc) = 1

), final as (
  select 
    -- SK
    t2.FactInvoiceSK,
    t2.InvoiceSK,
    dim_aging.AgingSK,
    dim_aging.AgingRangSK,
    COALESCE(t2.OrderSK, t3.OrderSK) as OrderSK,
    COALESCE(t2.FactOrderSK, t3.FactOrderSK) as FactOrderSK,
    COALESCE(t2.QuotationSK, t3.QuotationSK) as QuotationSK,
    COALESCE(t2.FactQuotationSK, t3.FactQuotationSK) as FactQuotationSK,
  
    `${FnFlagExcTableRef}`(
      t1.mihCancel, 
      t1.mihStatus, 
      (CASE 
        WHEN ( (t5.RefOrder is null and t6.RefOrder is null) or (t5.mihVnos = '0001' or t6.mihVnos = '0001') or (LEFT(t5.mihVnos, 3) = 'PRE' or LEFT(t6.mihVnos, 3) = 'PRE') ) THEN 'Yes'
        WHEN 'Yes' IN (rebate_customer.salesExc, rebate_sale.salesExc, rebate_product.salesExc, rebate_textsplit.salesExc, rebate_dep.salesExc) THEN 'Yes'
        ELSE 'No'
      END)
    ) as FlagSaleExc,
  
    `${FnFlagExcTableRef}`(
      t1.mihCancel, 
      t1.mihstatus, 
      (CASE 
        WHEN 'Yes' IN (rebate_customer.accExc, rebate_sale.accExc, rebate_product.accExc, rebate_textsplit.accExc, rebate_dep.accExc) THEN 'Yes'
        ELSE 'No'
      END)
    ) as FlagAccExc,
    
    -- DATA
    t1.* except(mihCancel, mihStatus, seq_condition)
  from raw_table as t1
  left join `${DimProductMasterTableRef}` as t4
    ON t1.milstk = t4.ProductCode
    and t1.CompanySK = t4.CompanySK
  left join dim_rebate as rebate_customer
    on t1.milCus = TRIM(rebate_customer.rebate)
    and lower(trim(rebate_customer.status)) = 'cutomer'
    and t1.CompanySK = rebate_customer.CompanySK
  left join dim_rebate as rebate_sale
    on t1.milPer = TRIM(rebate_sale.rebate)
    and lower(trim(rebate_sale.status)) = 'sales'
    and t1.CompanySK = rebate_sale.CompanySK
  left join dim_rebate as rebate_product
    on t1.milStk = TRIM(rebate_product.rebate)
    and lower(trim(rebate_product.status)) = 'product'
    and t1.CompanySK = rebate_product.CompanySK
  left join dim_rebate as rebate_dep
    on t1.milDep = TRIM(rebate_dep.rebate)
    and lower(trim(rebate_product.status)) = 'dep'
    and t1.CompanySK = rebate_product.CompanySK
  left join dim_rebate as rebate_textsplit
    on (
        replace(t1.milDesc,' ', '') LIKE CONCAT('%', replace(rebate_textsplit.rebate,' ', ''), '%')
        or replace(t4.ProductMac5Description, ' ', '') LIKE CONCAT('%', replace(rebate_textsplit.rebate, ' ', ''), '%')
        or replace(t1.milDep, ' ', '') LIKE CONCAT('%', replace(rebate_textsplit.rebate, ' ', ''), '%')
      ) 
    and lower(trim(rebate_textsplit.status)) = 'textsplit'
    and t1.CompanySK = rebate_textsplit.CompanySK

  left join `${FactInvoiceTableRef}` as t2
    on t1.milYear = t2.milYear
    and t1.milMonth = t2.milMonth
    and t1.milDay = t2.milDay
    and t1.milType = t2.milType
    and t1.milVnos = t2.milVnos
    and t1.milCus = t2.milCus
    and IFNULL(t1.milLinkVcno, '') = IFNULL(t2.milLinkVcno, '')
    and IFNULL(t1.milStk, '') = IFNULL(t2.milStk, '')
    and t1.CompanySK = t2.CompanySK

  -- aging
  left join `${ViewDimAgingTableRef}` as dim_aging
    on t2.CompanySK = dim_aging.CompanySK
    and t2.milVnos = dim_aging.cfsVnosID
  
  left join `${FactOrderTableRef}` as t3
    on t1.milYear = t3.milYear
    and t1.milMonth = t3.milMonth
    and t1.milDay = t3.milDay
    and t1.milType = t3.milType
    and t1.milVnos = t3.milVnos
    and t1.milCus = t3.milCus
    and t1.milStk = t3.milStk
    and t1.CompanySK = t3.CompanySK

  left join (
    SELECT CompanySK, mihType, mihVnos, MAX(OrderSK) as OrderSK, MAX(RefOrder) as RefOrder
    FROM `${ViewDimInvoiceTableRef}`
    GROUP BY 1,2,3
  ) as t5
    on t1.CompanySK = t5.CompanySK
    and t1.miltype = t5.mihType
    and t1.milvnos = t5.mihVnos
  
  left join (
    SELECT CompanySK, mihType, mihVnos, MAX(OrderSK) as OrderSK, MAX(RefOrder) as RefOrder
    FROM `${ViewDimInvoiceTableRef}`
    GROUP BY 1,2,3
  ) as t6
    on t1.CompanySK = t6.CompanySK
    and t1.millinkvcno = t6.mihVnos
    
), final2 as (
  select 
    -- mds.NewProductMktSK,
    COALESCE(mds.NewProductMktSK, fn.ProductMktSk) as NewProductMktSK,
    fn.*
  from final as fn
  -- get product mkt
  left join `${DimProductMktTableRef}` as prd_mkt
    on fn.ProductMktSK = prd_mkt.ProductMktSK

  -- get sale region
  left join `${DimRegionTableRef}` as reg
    on fn.RegionSKLast = reg.RegionSK

  -- get product master
  left join `${DimProductMasterTableRef}` as prd
    on fn.ProductSK = prd.ProductSK

  -- get mihnotes
  left join ${ref(databuffet.CURATED_MAC5, "curated_mih")} as mih
    on fn.companyid = mih.company_id
    and fn.milday = mih.mihday
    and fn.milmonth = mih.mihmonth
    and fn.milyear = mih.mihyear
    and fn.miltype = mih.mihtype
    and fn.milvnos = mih.mihvnos
    and fn.milcus = mih.mihcus
    
  -- change productmktsk
  left join mds_change_mktgroup as mds
    on fn.companyid = mds.companyid
    and (
      (
        -- กลุ่มที่ 1: เช็คจาก Depcode และ ProductID (milstk) เช่น บ-0124
        (
          lower(mds.DepcodeAction) = 'startwith' AND lower(mds.ProductAction) = 'exc' 
          AND fn.mildep LIKE CONCAT(mds.Depcode, '%') 
          AND fn.milstk <> mds.ProductID
        )
      )
      OR 
      (
        -- กลุ่มที่ 2 & 3: เช็คจาก ID เดิม และ Job (miljob) = LITETITE
        (
          lower(mds.JobAction) = 'inc' AND lower(MarketingAction) = 'inc'
          AND fn.miljob = mds.Job           
          AND (
            (
              prd_mkt.MarketingGroupID = mds.OLDMarketingGroupID
              and ifnull(trim(mds.OLDSubMarketingGroupID), '') = ''
              and ifnull(trim(mds.OLDSegmentID), '') = ''
            ) 
            OR (
              prd_mkt.MarketingGroupID = mds.OLDMarketingGroupID
              and prd_mkt.SubMarketingID = mds.OLDSubMarketingGroupID
              and prd_mkt.SegmentID = mds.OLDSegmentID
            )
          )
        )
      )
      OR 
      (
        -- กลุ่มที่ 4-11: เช็คจาก SalesReging, ยอดขาย (SalesAmt) และ ID เดิม
        (
          lower(mds.SalesRegionAction) = 'inc' AND lower(mds.SalesAmtAction) = 'inc'
          AND reg.RegionID = mds.SalesRegion 
          AND fn.milSum = mds.SalesAmt 
          AND prd_mkt.MarketingGroupID = mds.OLDMarketingGroupID
          AND prd_mkt.SubMarketingID = mds.OLDSubMarketingGroupID
          AND prd_mkt.SegmentID = mds.OLDSegmentID
        )
      )
      OR 
      (
        -- กลุ่มที่ 12-13: เช็คจาก Product Group (LT-DFS) และคำค้นหาในชื่อสินค้า (mildesc)
        (
          lower(mds.ProductGroupAction) = 'inc' AND lower(mds.ProductDescriptionAction) = 'contains'
          AND prd.ProductGroupMac5Description = mds.ProductGroup
          AND REGEXP_CONTAINS(fn.mildesc, mds.ProductDescription)
        )
      )
      OR 
      (
        -- กลุ่มที่ 14-18: เช็คจาก ProductID และคำค้นหาในหมายเหตุ (mihnotes) หรือชื่อสินค้า (mildesc)
        (
          lower(mds.ProductAction) = 'inc' AND lower(mds.ProductDescriptionAction) = 'contains' AND lower(RemarkAction) = 'contains'
          AND fn.milstk = mds.ProductID 
          AND (REGEXP_CONTAINS(fn.mildesc, mds.ProductDescription) OR REGEXP_CONTAINS(mih.mihnotes, mds.Remark) OR REGEXP_CONTAINS(mih.mihdesc, mds.Remark))
        )
      )
      OR 
      (
        -- กลุ่มที่ 19: เช็คจาก ProductID และชื่อสินค้า (mildesc)
        (
          lower(mds.ProductAction) = 'inc' AND lower(mds.ProductDescriptionAction) = 'contains'
          AND fn.milstk = mds.ProductID 
          AND REGEXP_CONTAINS(fn.mildesc, mds.ProductDescription)
        )
      )
    )

)
  select distinct
    trans.* except(
      mix_date, milDay, milMonth, milYear, 
      milQuan, milQuanp2, milAdisc, milCog, milConv, milDisca, milDisct, milVat, milSum,
      milExchg, milAcost, milCost, milUcost, milUprice, 
      Vat, milsum_incvat, mildisca_incvat, milcog_incvat,
      DepositExcVat, DepositIncVat, DepositVat, CompanySK
    ),
    IF(trans.mix_date is not null, trans.CompanySK, calendar.CompanySK) as CompanySK,
    IF(trans.mix_date is not null, trans.mix_date, calendar.Date) as mix_date,
    IF(trans.mix_date is not null, trans.milDay, EXTRACT(DAY FROM calendar.Date) ) as milDay,
    IF(trans.mix_date is not null, trans.milMonth, EXTRACT(MONTH FROM calendar.Date) ) as milMonth,
    IF(trans.mix_date is not null, trans.milYear, EXTRACT(YEAR FROM calendar.Date) ) as milYear,
    
    IF(trans.mix_date is not null, trans.milQuan, 0.0) as milQuan,
    IF(trans.mix_date is not null, trans.milQuanp2, 0.0) as milQuanp2,
    IF(trans.mix_date is not null, trans.milAdisc, 0.0) as milAdisc,
    IF(trans.mix_date is not null, trans.milCog, 0.0) as milCog,
    IF(trans.mix_date is not null, trans.milConv, 0.0) as milConv,
    IF(trans.mix_date is not null, trans.milDisca, 0.0) as milDisca,
    IF(trans.mix_date is not null, trans.milDisct, NULL) as milDisct,
    IF(trans.mix_date is not null, trans.milVat, 0.0) as milVat,
    IF(trans.mix_date is not null, trans.milSum, 0.0) as milSum,
    
    IF(trans.mix_date is not null, trans.milExchg, 0.0) as milExchg,
    IF(trans.mix_date is not null, trans.milAcost, 0.0) as milAcost,
    
    IF(trans.mix_date is not null, trans.milCost, 0.0) as milCost,
    IF(trans.mix_date is not null, trans.milUcost, 0.0) as milUcost,
    IF(trans.mix_date is not null, trans.milUprice, 0.0) as milUprice,
    
    IF(trans.mix_date is not null, trans.Vat, 0.0) as Vat,
    IF(trans.mix_date is not null, trans.milsum_incvat, 0.0) as milsum_incvat,
    IF(trans.mix_date is not null, trans.mildisca_incvat, 0.0) as mildisca_incvat,
    IF(trans.mix_date is not null, trans.milcog_incvat, 0.0) as milcog_incvat,

    IF(trans.mix_date is not null, trans.DepositExcVat, 0.0) as DepositExcVat,
    IF(trans.mix_date is not null, trans.DepositIncVat, 0.0) as DepositIncVat,
    IF(trans.mix_date is not null, trans.DepositVat, 0.0) as DepositVat,

  from dim_calendar as calendar
  left join final2 as trans
    on calendar.Date = trans.mix_date
    and calendar.CompanySK = trans.CompanySK
  left join `${DimProductMktTableRef}` as new_prd
    on trans.NewProductMktSK = new_prd.ProductMktSK
  left join `${DimProductMktTableRef}` as prd
    on trans.ProductMktSK = prd.ProductMktSK
  
  -- where NewProductMktSK is not null
