config {
  type: "view",
  schema: databuffet.FACT_VIEW,
  dependencies: ["fact_mir_vs", "dim_aging"],
  tags: [databuffet.TAG_VIEW],
}

js {
    const FactMirVsTable = {
        database: databuffet.DATABASE,
        schema: databuffet.FACT_TABLE,
        name: "fact_mir_vs",
    };
    const FactMirVsTableRef = `${FactMirVsTable.database}.${FactMirVsTable.schema}.${FactMirVsTable.name}`;

    const DimAgingTable = {
        database: databuffet.DATABASE,
        schema: databuffet.DIMENSION_TABLE,
        name: "dim_aging",
    };
    const DimAgingTableRef = `${DimAgingTable.database}.${DimAgingTable.schema}.${DimAgingTable.name}`;
}

select t2.AgingSK, t1.*
from `${FactMirVsTableRef}` as t1
left join `${DimAgingTableRef}` as t2
  on t1.mirbinvno = t2.cfsvnosid
  and t1.company_id = t2.CompanyID


-- 509185
