config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: ["validated_schema_mastersku", "create_all_table_raw_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["bra_id"],
    bigquery: {
        partitionBy : "asatdate",
        clusterBy: ["bra_id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = ["bra_id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    -- Retry loop
    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            -- ลอง ALTER TABLE
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            -- ถ้า error ให้ retry
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(bra_id) AS STRING), '') AS bra_id,
  NULLIF(CAST(TRIM(bra_name) AS STRING), '') AS bra_name,
  NULLIF(CAST(TRIM(bra_name_th) AS STRING), '') AS bra_name_th,
  NULLIF(CAST(TRIM(bra_detail) AS STRING), '') AS bra_detail,
  NULLIF(CAST(TRIM(bra_vendor_id) AS STRING), '') AS bra_vendor_id,
  NULLIF(CAST(TRIM(bra_logo_name) AS STRING), '') AS bra_logo_name,
  NULLIF(CAST(TRIM(bra_logo_path) AS STRING), '') AS bra_logo_path,
  CAST(bra_is_use AS BOOL) AS bra_is_use,
  CAST(bra_is_active AS BOOL) AS bra_is_active,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(bra_created_date, 1, 19)) AS bra_created_date,
  NULLIF(CAST(TRIM(bra_created_by) AS STRING), '') AS bra_created_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(bra_updated_date, 1, 19)) AS bra_updated_date,
  NULLIF(CAST(TRIM(bra_updated_by) AS STRING), '') AS bra_updated_by,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
