config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["category"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["category"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(TRIM(cat_id) AS STRING) AS cat_id,
  CAST(TRIM(cat_code) AS STRING) AS cat_code,
  CAST(TRIM(cat_name) AS STRING) AS cat_name,
  CAST(TRIM(cat_d365_code) AS STRING) AS cat_d365_code,
  CAST(TRIM(cat_description) AS STRING) AS cat_description,
  CAST(TRIM(cat_tag) AS STRING) AS cat_tag,
  CAST(TRIM(cat_parent_id) AS STRING) AS cat_parent_id,
  CAST(cat_level AS INT64) AS cat_level,
  CAST(TRIM(cat_img_name) AS STRING) AS cat_img_name,
  CAST(TRIM(cat_img_path) AS STRING) AS cat_img_path,
  CAST(TRIM(cat_vendor_id) AS STRING) AS cat_vendor_id,
  CAST(cat_is_active AS BOOL) AS cat_is_active,
  CAST(cat_is_use AS BOOL) AS cat_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cat_created_date, 1, 19)) AS cat_created_date,
  CAST(TRIM(cat_created_by) AS STRING) AS cat_created_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cat_updated_date, 1, 19)) AS cat_updated_date,
  CAST(TRIM(cat_updated_by) AS STRING) AS cat_updated_by,
  CAST(TRIM(cat_specific_field) AS STRING) AS cat_specific_field,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
