config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: ["validated_schema_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product_detail"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product_detail"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(pd_id) AS STRING), '') AS pd_id,
  NULLIF(CAST(TRIM(pd_prd_id) AS STRING), '') AS pd_prd_id,
  NULLIF(CAST(TRIM(pd_url_video) AS STRING), '') AS pd_url_video,
  NULLIF(CAST(TRIM(pd_detail) AS STRING), '') AS pd_detail,
  NULLIF(CAST(TRIM(pd_series) AS STRING), '') AS pd_series,
  NULLIF(CAST(TRIM(pd_model) AS STRING), '') AS pd_model,
  NULLIF(CAST(TRIM(pd_material) AS STRING), '') AS pd_material,
  NULLIF(CAST(TRIM(pd_certificate) AS STRING), '') AS pd_certificate,
  NULLIF(CAST(TRIM(pd_garantee) AS STRING), '') AS pd_garantee,
  NULLIF(CAST(TRIM(pd_garantee_detail) AS STRING), '') AS pd_garantee_detail,
  NULLIF(CAST(TRIM(pd_shape) AS STRING), '') AS pd_shape,
  NULLIF(CAST(TRIM(pd_supplier_country) AS STRING), '') AS pd_supplier_country,
  CAST(pd_package_wide AS FLOAT64) AS pd_package_wide,
  CAST(pd_package_long AS FLOAT64) AS pd_package_long,
  CAST(pd_package_hight AS FLOAT64) AS pd_package_hight,
  CAST(pd_size_wide AS FLOAT64) AS pd_size_wide,
  CAST(pd_size_long AS FLOAT64) AS pd_size_long,
  NULLIF(CAST(TRIM(pd_sl_id) AS STRING), '') AS pd_sl_id,
  CAST(pd_size_hight AS FLOAT64) AS pd_size_hight,
  NULLIF(CAST(TRIM(pd_sh_id) AS STRING), '') AS pd_sh_id,
  CAST(pd_net_weight AS FLOAT64) AS pd_net_weight,
  CAST(pd_gross_weight AS FLOAT64) AS pd_gross_weight,
  NULLIF(CAST(TRIM(pd_uw_id) AS STRING), '') AS pd_uw_id,
  NULLIF(CAST(TRIM(pd_ul_id) AS STRING), '') AS pd_ul_id,
  NULLIF(CAST(TRIM(pd_uh_id) AS STRING), '') AS pd_uh_id,
  NULLIF(CAST(TRIM(pd_sw_id) AS STRING), '') AS pd_sw_id,
  NULLIF(CAST(TRIM(pd_net_unit_id) AS STRING), '') AS pd_net_unit_id,
  NULLIF(CAST(TRIM(pd_gross_unit_id) AS STRING), '') AS pd_gross_unit_id,
  NULLIF(CAST(TRIM(pd_how_to) AS STRING), '') AS pd_how_to,
  NULLIF(CAST(TRIM(pd_how_to_url) AS STRING), '') AS pd_how_to_url,
  NULLIF(CAST(TRIM(pd_how_to_path) AS STRING), '') AS pd_how_to_path,
  NULLIF(CAST(TRIM(pd_suggest) AS STRING), '') AS pd_suggest,
  NULLIF(CAST(TRIM(pd_suggest_url) AS STRING), '') AS pd_suggest_url,
  NULLIF(CAST(TRIM(pd_suggest_path) AS STRING), '') AS pd_suggest_path,
  NULLIF(CAST(TRIM(pd_caution) AS STRING), '') AS pd_caution,
  NULLIF(CAST(TRIM(pd_caution_url) AS STRING), '') AS pd_caution_url,
  NULLIF(CAST(TRIM(pd_caution_path) AS STRING), '') AS pd_caution_path,
  NULLIF(CAST(TRIM(pd_file_name) AS STRING), '') AS pd_file_name,
  NULLIF(CAST(TRIM(pd_file_path) AS STRING), '') AS pd_file_path,
  CAST(pd_is_system AS BOOL) AS pd_is_system,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pd_created_date, 1, 19)) AS pd_created_date,
  NULLIF(CAST(TRIM(pd_created_by) AS STRING), '') AS pd_created_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pd_updated_date, 1, 19)) AS pd_updated_date,
  NULLIF(CAST(TRIM(pd_updated_by) AS STRING), '') AS pd_updated_by,
  NULLIF(CAST(TRIM(pd_product_name) AS STRING), '') AS pd_product_name,
  NULLIF(CAST(TRIM(pd_vendor_code) AS STRING), '') AS pd_vendor_code,
  NULLIF(CAST(TRIM(pd_barcode) AS STRING), '') AS pd_barcode,
  NULLIF(CAST(TRIM(pd_sale_unit) AS STRING), '') AS pd_sale_unit,
  NULLIF(CAST(TRIM(pd_spacific_fields) AS STRING), '') AS pd_spacific_fields,
  NULLIF(CAST(TRIM(pd_remark_inactive) AS STRING), '') AS pd_remark_inactive,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
