config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = "product"
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(TRIM(prd_id) AS STRING) AS prd_id,
  CAST(TRIM(prd_sku) AS STRING) AS prd_sku,
  CAST(TRIM(prd_description) AS STRING) AS prd_description,
  CAST(TRIM(prd_d365_sku) AS STRING) AS prd_d365_sku,
  CAST(TRIM(prd_item_text) AS STRING) AS prd_item_text,
  CAST(TRIM(prd_item_code) AS STRING) AS prd_item_code,
  CAST(TRIM(prd_stopped_sate) AS STRING) AS prd_stopped_sate,
  CAST(TRIM(prd_made_to_order) AS STRING) AS prd_made_to_order,
  CAST(TRIM(prd_sale_unite) AS STRING) AS prd_sale_unite,
  CAST(TRIM(prd_tag) AS STRING) AS prd_tag,
  CAST(TRIM(prd_universal_barcode) AS STRING) AS prd_universal_barcode,
  CAST(TRIM(prd_internal_barcode) AS STRING) AS prd_internal_barcode,
  CAST(TRIM(prd_cat_id) AS STRING) AS prd_cat_id,
  CAST(TRIM(prd_filter1) AS STRING) AS prd_filter1,
  CAST(TRIM(prd_filter2) AS STRING) AS prd_filter2,
  CAST(TRIM(prd_brand_id) AS STRING) AS prd_brand_id,
  CAST(TRIM(prd_size) AS STRING) AS prd_size,
  CAST(TRIM(prd_line) AS STRING) AS prd_line,
  CAST(TRIM(prd_color) AS STRING) AS prd_color,
  CAST(TRIM(prd_model) AS STRING) AS prd_model,
  CAST(TRIM(prd_dimension1) AS STRING) AS prd_dimension1,
  CAST(TRIM(prd_dimension2) AS STRING) AS prd_dimension2,
  CAST(TRIM(prd_dimension3) AS STRING) AS prd_dimension3,
  CAST(TRIM(prd_dimension4) AS STRING) AS prd_dimension4,
  CAST(TRIM(prd_vendor_id) AS STRING) AS prd_vendor_id,
  CAST(prd_is_active AS BOOL) AS prd_is_active,
  CAST(prd_is_use AS BOOL) AS prd_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(prd_created_date, 1, 19)) AS prd_created_date,
  CAST(TRIM(prd_created_by) AS STRING) AS prd_created_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(prd_updated_date, 1, 19)) AS prd_updated_date,
  CAST(TRIM(prd_updated_by) AS STRING) AS prd_updated_by,
  CAST(TRIM(prd_pg_id) AS STRING) AS prd_pg_id,
  CAST(TRIM(prd_ps_id) AS STRING) AS prd_ps_id,
  CAST(TRIM(prd_id_source) AS STRING) AS prd_id_source,
  CAST(TRIM(prd_mc_id) AS STRING) AS prd_mc_id,
  CAST(TRIM(prd_diminsion_data) AS STRING) AS prd_diminsion_data,
  CAST(TRIM(prd_pas_id) AS STRING) AS prd_pas_id,
  CAST(TRIM(prd_barcode) AS STRING) AS prd_barcode,
  CAST(TRIM(prd_reject_remark) AS STRING) AS prd_reject_remark,
  CAST(TRIM(prd_ref_mp_id) AS STRING) AS prd_ref_mp_id,
  CAST(prd_is_combo AS BOOL) AS prd_is_combo,
  CAST(prd_combo_price AS FLOAT64) AS prd_combo_price,
  CAST(prd_is_time AS BOOL) AS prd_is_time,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(prd_combo_start, 1, 19)) AS prd_combo_start,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(prd_combo_end, 1, 19)) AS prd_combo_end,
  CAST(prd_total_combo_price AS FLOAT64) AS prd_total_combo_price,
  CAST(prd_total_cost_combo_price AS FLOAT64) AS prd_total_cost_combo_price,
  CAST(TRIM(prd_barcode_format) AS STRING) AS prd_barcode_format,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
