config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: ["validated_schema_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["pg_id"],
    bigquery: {
        partitionBy : "asatdate",
        clusterBy: ["pg_id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = ["pg_id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    -- Retry loop
    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            -- ลอง ALTER TABLE
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            -- ถ้า error ให้ retry
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(pg_id) AS STRING), '') AS pg_id,
  NULLIF(CAST(TRIM(pg_description) AS STRING), '') AS pg_description,
  NULLIF(CAST(TRIM(pg_dimension1) AS STRING), '') AS pg_dimension1,
  NULLIF(CAST(TRIM(pg_dimension2) AS STRING), '') AS pg_dimension2,
  NULLIF(CAST(TRIM(pg_dimension3) AS STRING), '') AS pg_dimension3,
  NULLIF(CAST(TRIM(pg_dimension4) AS STRING), '') AS pg_dimension4,
  NULLIF(CAST(TRIM(pg_dimension_d365_1) AS STRING), '') AS pg_dimension_d365_1,
  NULLIF(CAST(TRIM(pg_dimension_d365_2) AS STRING), '') AS pg_dimension_d365_2,
  NULLIF(CAST(TRIM(pg_dimension_d365_3) AS STRING), '') AS pg_dimension_d365_3,
  NULLIF(CAST(TRIM(pg_dimension_d365_4) AS STRING), '') AS pg_dimension_d365_4,
  NULLIF(CAST(TRIM(pg_vendor_id) AS STRING), '') AS pg_vendor_id,
  CAST(pg_is_system AS BOOL) AS pg_is_system,
  CAST(pg_is_active AS BOOL) AS pg_is_active,
  CAST(pg_is_use AS BOOL) AS pg_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pg_created_date, 1, 19)) AS pg_created_date,
  NULLIF(CAST(TRIM(pg_created_by) AS STRING), '') AS pg_created_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pg_updated_date, 1, 19)) AS pg_updated_date,
  NULLIF(CAST(TRIM(pg_updated_by) AS STRING), '') AS pg_updated_by,
  NULLIF(CAST(TRIM(pg_brand_id) AS STRING), '') AS pg_brand_id,
  NULLIF(CAST(TRIM(pg_code) AS STRING), '') AS pg_code,
  NULLIF(CAST(TRIM(pg_name) AS STRING), '') AS pg_name,
  NULLIF(CAST(TRIM(pg_sku) AS STRING), '') AS pg_sku,
  NULLIF(CAST(TRIM(pg_barcode) AS STRING), '') AS pg_barcode,
  NULLIF(CAST(TRIM(pg_er_source) AS STRING), '') AS pg_er_source,
  NULLIF(CAST(TRIM(pg_tag) AS STRING), '') AS pg_tag,
  NULLIF(CAST(TRIM(pg_file_name) AS STRING), '') AS pg_file_name,
  NULLIF(CAST(TRIM(pg_cg_id) AS STRING), '') AS pg_cg_id,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
