config {
    type: "incremental",
    schema: databuffet.VALIDATED_MASTERSKU,
    dependencies: ["validated_schema_mastersku", "create_all_table_raw_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["ps_id"],
    bigquery: {
        partitionBy : "asatdate",
        clusterBy: ["ps_id"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MASTERSKU,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["ps_id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  ${databuffet.functionData.cleanString('ps_id')} AS ps_id,
  ${databuffet.functionData.cleanString('ps_name')} AS ps_name,
  CAST(ps_is_use AS BOOL) as ps_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(ps_created_date, 1, 19)) as ps_created_date,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(ps_updated_date, 1, 19)) as ps_updated_date,
  ${databuffet.functionData.parseAsatDate()} as asatdate,

FROM
  `${sourceTableRef}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
