config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: ["validated_schema_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["ps_id"],
    bigquery: {
        partitionBy : "asatdate",
        clusterBy: ["ps_id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = ["ps_id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(ps_id) AS STRING), '') AS ps_id,
  NULLIF(CAST(TRIM(ps_name) AS STRING), '') AS ps_name,
  CAST(ps_is_use AS BOOL) as ps_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(ps_created_date, 1, 19)) as ps_created_date,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(ps_updated_date, 1, 19)) as ps_updated_date,
  PARSE_DATE('%Y%m%d', ASATDATE) as asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
