config {
    type: "incremental",
    schema: databuffet.VALIDATED_MASTERSKU,
    dependencies: ["validated_schema_mastersku", "create_all_table_raw_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["pas_id"],
    bigquery: {
        partitionBy : "asatdate",
        clusterBy: ["pas_id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_MASTERSKU
    const table_id = name()
    const pk_key = ["pas_id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(pas_id) AS STRING), '') AS pas_id,
  NULLIF(CAST(TRIM(pas_name) AS STRING), '') AS pas_name,
  CAST(pas_is_use AS BOOL) as pas_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pas_created_date, 1, 19)) as pas_created_date,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pas_updated_date, 1, 19)) as pas_updated_date,
  PARSE_DATE('%Y%m%d', ASATDATE) as asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
