config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: ["validated_schema_mastersku"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["vd_id"],
    bigquery: {
        partitionBy : "asatdate",
        clusterBy: ["vd_id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = ["vd_id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    -- Retry loop
    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            -- ลอง ALTER TABLE
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            -- ถ้า error ให้ retry
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(vd_id) AS STRING), '') AS vd_id,
  NULLIF(CAST(TRIM(vd_api_id) AS STRING), '') AS vd_api_id,
  NULLIF(CAST(TRIM(vd_code) AS STRING), '') AS vd_code,
  NULLIF(CAST(TRIM(vd_name) AS STRING), '') AS vd_name,
  NULLIF(CAST(TRIM(vd_coporate_no) AS STRING), '') AS vd_coporate_no,
  NULLIF(CAST(TRIM(vd_tel) AS STRING), '') AS vd_tel,
  NULLIF(CAST(TRIM(vd_country_name) AS STRING), '') AS vd_country_name,
  NULLIF(CAST(TRIM(vd_province_name) AS STRING), '') AS vd_province_name,
  NULLIF(CAST(TRIM(vd_district_name) AS STRING), '') AS vd_district_name,
  NULLIF(CAST(TRIM(vd_sub_district_name) AS STRING), '') AS vd_sub_district_name,
  NULLIF(CAST(TRIM(vd_zipcode) AS STRING), '') AS vd_zipcode,
  NULLIF(CAST(TRIM(vd_email) AS STRING), '') AS vd_email,
  NULLIF(CAST(TRIM(vd_address) AS STRING), '') AS vd_address,
  NULLIF(CAST(TRIM(vd_organize_name) AS STRING), '') AS vd_organize_name,
  NULLIF(CAST(TRIM(vd_business_type_name) AS STRING), '') AS vd_business_type_name,
  NULLIF(CAST(TRIM(vd_document_id) AS STRING), '') AS vd_document_id,
  NULLIF(CAST(TRIM(vd_document_path) AS STRING), '') AS vd_document_path,
  CAST(vd_is_dbd AS BOOL) AS vd_is_dbd,
  NULLIF(CAST(TRIM(vd_account_type) AS STRING), '') AS vd_account_type,
  NULLIF(CAST(TRIM(vd_kyc_status) AS STRING), '') AS vd_kyc_status,
  CAST(vd_is_active AS BOOL) AS vd_is_active,
  CAST(vd_is_use AS BOOL) AS vd_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(vd_created_date, 1, 19)) AS vd_created_date,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(vd_updated_date, 1, 19)) AS vd_updated_date,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
