config {
    type: "incremental",
    schema: databuffet.VALIDATED_MASTERSKU_SCHEMA,
    // dependencies: [],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys["MASTERSKU"]["brand"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: [...databuffet.primaryKeys["MASTERSKU"]["brand"]],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_MASTERSKU_SCHEMA
    const table_id = name()
    const pk_key = databuffet.primaryKeys["MASTERSKU"]["brand"]

}

SELECT
  CAST(bra_id AS STRING) AS bra_id,
  CAST(bra_name AS STRING) AS bra_name,
  CAST(bra_name_th AS STRING) AS bra_name_th,
  CAST(bra_detail AS STRING) AS bra_detail,
  CAST(bra_vendor_id AS STRING) AS bra_vendor_id,
  CAST(bra_logo_name AS STRING) AS bra_logo_name,
  CAST(bra_logo_path AS STRING) AS bra_logo_path,
  CAST(bra_is_use AS BOOL) AS bra_is_use,
  CAST(bra_is_active AS BOOL) AS bra_is_active,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(bra_created_date, 1, 19)) AS bra_created_date,
  CAST(bra_created_by AS STRING) AS bra_created_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(bra_updated_date, 1, 19)) AS bra_updated_date,
  CAST(bra_updated_by AS STRING) AS bra_updated_by,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,
  
FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1

  -- pre_operations {}
  -- post_operations {}
