config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product_category"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product_category"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(pc_id AS STRING) AS pc_id,
  CAST(pc_prod_id AS STRING) AS pc_prod_id,
  CAST(pc_cat_id AS STRING) AS pc_cat_id,
  CAST(pc_is_ise AS BOOL) AS pc_is_ise,
  CAST(pc_is_active AS BOOL) AS pc_is_active,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pc_created_date, 1, 19)) AS pc_created_date,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pc_updated_date, 1, 19)) AS pc_updated_date,
  CAST(pc_created_by AS STRING) AS pc_created_by,
  CAST(pc_updated_by AS STRING) AS pc_updated_by,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
