config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product_group_cost_group"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MASTERSKU
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MASTERSKU]["product_group_cost_group"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(pgcg_id AS STRING) AS pgcg_id,
  CAST(pgcg_pg_id AS STRING) AS pgcg_pg_id,
  CAST(pgcg_cost_group_detail AS STRING) AS pgcg_cost_group_detail,
  CAST(pgcg_is_use AS BOOL) AS pgcg_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pgcg_create_date, 1, 19)) AS pgcg_create_date,
  CAST(pgcg_create_by AS STRING) AS pgcg_create_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pgcg_update_date, 1, 19)) AS pgcg_update_date,
  CAST(pgcg_update_by AS STRING) AS pgcg_update_by,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

  -- pre_operations {}
post_operations {
    ${post_operations_statement}
}
