config {
    type: "incremental",
    schema: databuffet.VALIDATED_MASTERSKU_SCHEMA,
    // dependencies: [],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys["MASTERSKU"]["product_group_cost_group"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: [...databuffet.primaryKeys["MASTERSKU"]["product_group_cost_group"]],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_MASTERSKU_SCHEMA
    const table_id = name()
    const pk_key = databuffet.primaryKeys["MASTERSKU"]["product_group_cost_group"]

}

SELECT
  CAST(pgcg_id AS STRING) AS pgcg_id,
  CAST(pgcg_pg_id AS STRING) AS pgcg_pg_id,
  CAST(pgcg_cost_group_detail AS STRING) AS pgcg_cost_group_detail,
  CAST(pgcg_is_use AS BOOL) AS pgcg_is_use,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pgcg_create_date, 1, 19)) AS pgcg_create_date,
  CAST(pgcg_create_by AS STRING) AS pgcg_create_by,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pgcg_update_date, 1, 19)) AS pgcg_update_date,
  CAST(pgcg_update_by AS STRING) AS pgcg_update_by,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1

  -- pre_operations {}
  -- post_operations {}
