config {
    type: "incremental",
    schema: databuffet.VALIDATED_MASTERSKU_SCHEMA,
    // dependencies: [],
    tags: [databuffet.TAG_VALIDATED],
    uniqueKey: databuffet.primaryKeys["MASTERSKU"]["product_category"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: [...databuffet.primaryKeys["MASTERSKU"]["product_category"]],
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_MASTERSKU_SCHEMA
    const table_id = name()
    const pk_key = databuffet.primaryKeys["MASTERSKU"]["product_category"]

}

SELECT
  CAST(pc_id AS STRING) AS pc_id,
  CAST(pc_prod_id AS STRING) AS pc_prod_id,
  CAST(pc_cat_id AS STRING) AS pc_cat_id,
  CAST(pc_is_ise AS BOOL) AS pc_is_ise,
  CAST(pc_is_active AS BOOL) AS pc_is_active,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pc_created_date, 1, 19)) AS pc_created_date,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(pc_updated_date, 1, 19)) AS pc_updated_date,
  CAST(pc_created_by AS STRING) AS pc_created_by,
  CAST(pc_updated_by AS STRING) AS pc_updated_by,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate,

FROM
  `${project_id}.${dataset_id}.${table_id}`
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1

  -- pre_operations {}
  -- post_operations {}
