config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5", "create_all_table_raw_mac5_aa05", "create_all_table_raw_mac5_ab01", "create_all_table_raw_mac5_ac02", "create_all_table_raw_mac5_ak02"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "ar_scode"],
    bigquery: {
        clusterBy: ["company_id", "ar_scode"]
    },
}

js {
    const pk_key = ["company_id", "ar_scode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ar_snamet desc, ar_snamee desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT
    'ag01' AS company_id,
    ${databuffet.functionData.castInt64('ar_scode')} as ar_scode,
    ${databuffet.functionData.cleanString('ar_snamet')} as ar_snamet,
    ${databuffet.functionData.cleanString('ar_snamee')} as ar_snamee,
    ${databuffet.functionData.castInt64('ar_scolf')} as ar_scolf,
    ${databuffet.functionData.castInt64('ar_scolb')} as ar_scolb
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.ar_s`

  UNION ALL

  SELECT
    'aa05' AS company_id,
    ${databuffet.functionData.castInt64('ar_scode')} as ar_scode,
    ${databuffet.functionData.cleanString('ar_snamet')} as ar_snamet,
    ${databuffet.functionData.cleanString('ar_snamee')} as ar_snamee,
    ${databuffet.functionData.castInt64('ar_scolf')} as ar_scolf,
    ${databuffet.functionData.castInt64('ar_scolb')} as ar_scolb
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.ar_s`

  UNION ALL

  SELECT
    'ab01' AS company_id,
    ${databuffet.functionData.castInt64('ar_scode')} as ar_scode,
    ${databuffet.functionData.cleanString('ar_snamet')} as ar_snamet,
    ${databuffet.functionData.cleanString('ar_snamee')} as ar_snamee,
    ${databuffet.functionData.castInt64('ar_scolf')} as ar_scolf,
    ${databuffet.functionData.castInt64('ar_scolb')} as ar_scolb
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.ar_s`

  UNION ALL

  SELECT
    'ac02' AS company_id,
    ${databuffet.functionData.castInt64('ar_scode')} as ar_scode,
    ${databuffet.functionData.cleanString('ar_snamet')} as ar_snamet,
    ${databuffet.functionData.cleanString('ar_snamee')} as ar_snamee,
    ${databuffet.functionData.castInt64('ar_scolf')} as ar_scolf,
    ${databuffet.functionData.castInt64('ar_scolb')} as ar_scolb
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.ar_s`

  UNION ALL

  SELECT
    'ak02' AS company_id,
    ${databuffet.functionData.castInt64('ar_scode')} as ar_scode,
    ${databuffet.functionData.cleanString('ar_snamet')} as ar_snamet,
    ${databuffet.functionData.cleanString('ar_snamee')} as ar_snamee,
    ${databuffet.functionData.castInt64('ar_scolf')} as ar_scolf,
    ${databuffet.functionData.castInt64('ar_scolb')} as ar_scolb
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.ar_s`
)

SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
