config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cfs"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cfs"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cfsdateid desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(cfsvnosid) AS STRING) as cfsvnosid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cfsdateid, 1, 19)) AS cfsdateid,
    CAST(TRIM(cfscusid) AS STRING) as cfscusid,
    CAST(TRIM(cfstypeid) AS STRING) as cfstypeid,
    CAST(TRIM(cfsjob) AS STRING) as cfsjob,
    CAST(TRIM(cfsdep) AS STRING) as cfsdep,
    CAST(TRIM(cfsper) AS STRING) as cfsper,
    CAST(TRIM(cfsdoc) AS STRING) as cfsdoc,
    CAST(TRIM(cfsmec) AS STRING) as cfsmec,
    CAST(cfssumreq AS FLOAT64) as cfssumreq,
    CAST(cfssumcut1 AS FLOAT64) as cfssumcut1,
    CAST(cfssumcut2 AS FLOAT64) as cfssumcut2,
    CAST(cfsclearsum AS INT64) as cfsclearsum,
    CAST(cfsclearuser AS INT64) as cfsclearuser,
    CAST(cfsclearall AS INT64) as cfsclearall,
    CAST(cfscurc AS INT64) as cfscurc,
    CAST(cfsexchg AS FLOAT64) as cfsexchg,
    CAST(cfsbillcut AS FLOAT64) as cfsbillcut,
    CAST(cfsbillclr AS INT64) as cfsbillclr,
    CAST(TRIM(rowguid) AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
