config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "cfsvnosid","cfsdateid","cfscusid","cfstypeid"],
    bigquery: {
        clusterBy: ["company_id", "cfsvnosid"]
    },
}

js {
    const pk_key = ["company_id", "cfsvnosid","cfsdateid","cfscusid","cfstypeid"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY company_id, cfsvnosid,cfsdateid,cfscusid,cfstypeid ORDER BY cfsdateid desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.functionData.cleanString('cfsvnosid')} as cfsvnosid,
    ${databuffet.functionData.parseFlexibleDatetime('cfsdateid')} AS cfsdateid,
    ${databuffet.functionData.cleanString('cfscusid')} as cfscusid,
    ${databuffet.functionData.cleanString('cfstypeid')} as cfstypeid,
    ${databuffet.functionData.cleanString('cfsjob')} as cfsjob,
    ${databuffet.functionData.cleanString('cfsdep')} as cfsdep,
    ${databuffet.functionData.cleanString('cfsper')} as cfsper,
    ${databuffet.functionData.cleanString('cfsdoc')} as cfsdoc,
    ${databuffet.functionData.cleanString('cfsmec')} as cfsmec,
    ${databuffet.functionData.castFloat64('cfssumreq')} as cfssumreq,
    ${databuffet.functionData.castFloat64('cfssumcut1')} as cfssumcut1,
    ${databuffet.functionData.castFloat64('cfssumcut2')} as cfssumcut2,
    ${databuffet.functionData.castInt64('cfsclearsum')} as cfsclearsum,
    ${databuffet.functionData.castInt64('cfsclearuser')} as cfsclearuser,
    ${databuffet.functionData.castInt64('cfsclearall')} as cfsclearall,
    ${databuffet.functionData.castInt64('cfscurc')} as cfscurc,
    ${databuffet.functionData.castFloat64('cfsexchg')} as cfsexchg,
    ${databuffet.functionData.castFloat64('cfsbillcut')} as cfsbillcut,
    ${databuffet.functionData.castInt64('cfsbillclr')} as cfsbillclr
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.cfs`

  UNION ALL
  SELECT 'aa05' AS company_id,
    ${databuffet.functionData.cleanString('cfsvnosid')} as cfsvnosid,
    ${databuffet.functionData.parseFlexibleDatetime('cfsdateid')} AS cfsdateid,
    ${databuffet.functionData.cleanString('cfscusid')} as cfscusid,
    ${databuffet.functionData.cleanString('cfstypeid')} as cfstypeid,
    ${databuffet.functionData.cleanString('cfsjob')} as cfsjob,
    ${databuffet.functionData.cleanString('cfsdep')} as cfsdep,
    ${databuffet.functionData.cleanString('cfsper')} as cfsper,
    ${databuffet.functionData.cleanString('cfsdoc')} as cfsdoc,
    ${databuffet.functionData.cleanString('cfsmec')} as cfsmec,
    ${databuffet.functionData.castFloat64('cfssumreq')} as cfssumreq,
    ${databuffet.functionData.castFloat64('cfssumcut1')} as cfssumcut1,
    ${databuffet.functionData.castFloat64('cfssumcut2')} as cfssumcut2,
    ${databuffet.functionData.castInt64('cfsclearsum')} as cfsclearsum,
    ${databuffet.functionData.castInt64('cfsclearuser')} as cfsclearuser,
    ${databuffet.functionData.castInt64('cfsclearall')} as cfsclearall,
    ${databuffet.functionData.castInt64('cfscurc')} as cfscurc,
    ${databuffet.functionData.castFloat64('cfsexchg')} as cfsexchg,
    ${databuffet.functionData.castFloat64('cfsbillcut')} as cfsbillcut,
    ${databuffet.functionData.castInt64('cfsbillclr')} as cfsbillclr
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.cfs`

  UNION ALL
  SELECT 'ab01' AS company_id,
    ${databuffet.functionData.cleanString('cfsvnosid')} as cfsvnosid,
    ${databuffet.functionData.parseFlexibleDatetime('cfsdateid')} AS cfsdateid,
    ${databuffet.functionData.cleanString('cfscusid')} as cfscusid,
    ${databuffet.functionData.cleanString('cfstypeid')} as cfstypeid,
    ${databuffet.functionData.cleanString('cfsjob')} as cfsjob,
    ${databuffet.functionData.cleanString('cfsdep')} as cfsdep,
    ${databuffet.functionData.cleanString('cfsper')} as cfsper,
    ${databuffet.functionData.cleanString('cfsdoc')} as cfsdoc,
    ${databuffet.functionData.cleanString('cfsmec')} as cfsmec,
    ${databuffet.functionData.castFloat64('cfssumreq')} as cfssumreq,
    ${databuffet.functionData.castFloat64('cfssumcut1')} as cfssumcut1,
    ${databuffet.functionData.castFloat64('cfssumcut2')} as cfssumcut2,
    ${databuffet.functionData.castInt64('cfsclearsum')} as cfsclearsum,
    ${databuffet.functionData.castInt64('cfsclearuser')} as cfsclearuser,
    ${databuffet.functionData.castInt64('cfsclearall')} as cfsclearall,
    ${databuffet.functionData.castInt64('cfscurc')} as cfscurc,
    ${databuffet.functionData.castFloat64('cfsexchg')} as cfsexchg,
    ${databuffet.functionData.castFloat64('cfsbillcut')} as cfsbillcut,
    ${databuffet.functionData.castInt64('cfsbillclr')} as cfsbillclr
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.cfs`

  UNION ALL
  SELECT 'ac02' AS company_id,
    ${databuffet.functionData.cleanString('cfsvnosid')} as cfsvnosid,
    ${databuffet.functionData.parseFlexibleDatetime('cfsdateid')} AS cfsdateid,
    ${databuffet.functionData.cleanString('cfscusid')} as cfscusid,
    ${databuffet.functionData.cleanString('cfstypeid')} as cfstypeid,
    ${databuffet.functionData.cleanString('cfsjob')} as cfsjob,
    ${databuffet.functionData.cleanString('cfsdep')} as cfsdep,
    ${databuffet.functionData.cleanString('cfsper')} as cfsper,
    ${databuffet.functionData.cleanString('cfsdoc')} as cfsdoc,
    ${databuffet.functionData.cleanString('cfsmec')} as cfsmec,
    ${databuffet.functionData.castFloat64('cfssumreq')} as cfssumreq,
    ${databuffet.functionData.castFloat64('cfssumcut1')} as cfssumcut1,
    ${databuffet.functionData.castFloat64('cfssumcut2')} as cfssumcut2,
    ${databuffet.functionData.castInt64('cfsclearsum')} as cfsclearsum,
    ${databuffet.functionData.castInt64('cfsclearuser')} as cfsclearuser,
    ${databuffet.functionData.castInt64('cfsclearall')} as cfsclearall,
    ${databuffet.functionData.castInt64('cfscurc')} as cfscurc,
    ${databuffet.functionData.castFloat64('cfsexchg')} as cfsexchg,
    ${databuffet.functionData.castFloat64('cfsbillcut')} as cfsbillcut,
    ${databuffet.functionData.castInt64('cfsbillclr')} as cfsbillclr
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.cfs`
  
  UNION ALL
  SELECT 'ak02' AS company_id,
    ${databuffet.functionData.cleanString('cfsvnosid')} as cfsvnosid,
    ${databuffet.functionData.parseFlexibleDatetime('cfsdateid')} AS cfsdateid,
    ${databuffet.functionData.cleanString('cfscusid')} as cfscusid,
    ${databuffet.functionData.cleanString('cfstypeid')} as cfstypeid,
    ${databuffet.functionData.cleanString('cfsjob')} as cfsjob,
    ${databuffet.functionData.cleanString('cfsdep')} as cfsdep,
    ${databuffet.functionData.cleanString('cfsper')} as cfsper,
    ${databuffet.functionData.cleanString('cfsdoc')} as cfsdoc,
    ${databuffet.functionData.cleanString('cfsmec')} as cfsmec,
    ${databuffet.functionData.castFloat64('cfssumreq')} as cfssumreq,
    ${databuffet.functionData.castFloat64('cfssumcut1')} as cfssumcut1,
    ${databuffet.functionData.castFloat64('cfssumcut2')} as cfssumcut2,
    ${databuffet.functionData.castInt64('cfsclearsum')} as cfsclearsum,
    ${databuffet.functionData.castInt64('cfsclearuser')} as cfsclearuser,
    ${databuffet.functionData.castInt64('cfsclearall')} as cfsclearall,
    ${databuffet.functionData.castInt64('cfscurc')} as cfscurc,
    ${databuffet.functionData.castFloat64('cfsexchg')} as cfsexchg,
    ${databuffet.functionData.castFloat64('cfsbillcut')} as cfsbillcut,
    ${databuffet.functionData.castInt64('cfsbillclr')} as cfsbillclr
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.cfs`

)
SELECT * FROM all_sources
QUALIFY ROW_NUMBER() OVER(PARTITION BY company_id, cfsvnosid,cfsdateid,cfscusid,cfstypeid ORDER BY cfsdateid desc) = 1

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
