config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["chq"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY chqkeydate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(chqno) AS STRING), '') as chqno,
    NULLIF(CAST(TRIM(chqbank) AS STRING), '') as chqbank,
    NULLIF(CAST(TRIM(chqacode) AS STRING), '') as chqacode,
    NULLIF(CAST(TRIM(chqcus) AS STRING), '') as chqcus,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19)) AS chqdatec,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19)) AS chqdater,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19)) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    NULLIF(CAST(TRIM(chqmemo) AS STRING), '') as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    NULLIF(CAST(TRIM(chqjob) AS STRING), '') as chqjob,
    NULLIF(CAST(TRIM(chqdep) AS STRING), '') as chqdep,
    NULLIF(CAST(TRIM(chqper) AS STRING), '') as chqper,
    NULLIF(CAST(TRIM(chqzon) AS STRING), '') as chqzon,
    NULLIF(CAST(TRIM(chqrcode) AS STRING), '') as chqrcode,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19)) AS chqeditlk,
    NULLIF(CAST(TRIM(chqkeyuser) AS STRING), '') as chqkeyuser,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19)) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    NULLIF(CAST(TRIM(chqecode) AS STRING), '') as chqecode,
    NULLIF(CAST(TRIM(chqbranch) AS STRING), '') as chqbranch,
    NULLIF(CAST(TRIM(chqmec) AS STRING), '') as chqmec,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19)) AS chqdatev

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
