config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5", "create_all_table_raw_mac5_aa05", "create_all_table_raw_mac5_ab01", "create_all_table_raw_mac5_ac02", "create_all_table_raw_mac5_ak02", "create_all_function"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "chqno", "chqbank", "chqdatec", "chqtag"],
    bigquery: {
        clusterBy: ["company_id", "chqno"]
    },
}

js {
    const pk_key = ["company_id", "chqno", "chqbank", "chqdatec", "chqtag"]

    let deduplicate_statement = "";
    let post_operations_statement = "";
    
    if (pk_key && pk_key.length > 0) {
        deduplicate_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY chqkeydate desc) = 1`;
        
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;
    DECLARE loop_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

    WHILE retry_count < max_retries AND NOT success DO
        IF TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), loop_start, MINUTE) >= 5 THEN
            BREAK;
        END IF;

        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;

    IF NOT success THEN
        INSERT INTO monitoring_dataset.dataform_all_logs (
            process_name, data_layer, action_name, status, start_time, end_time, error_message, executed_by
        )
        SELECT 
            'Dataform Pipeline', 'VALIDATED', '${name()}', 'FAILED', (SELECT start_ts FROM temp_start_${name()}), NULL, 'Timeout 5 Minutes or Max Retries Reached', SESSION_USER();

        RAISE USING MESSAGE = 'Process Failed: Timeout 5 Minutes or Max Retries Reached';
    END IF;
END;`;
    }
}

pre_operations {
}

WITH raw_sources AS (
  SELECT
    'ag01' AS company_id,
    NULLIF(CAST(TRIM(chqno) AS STRING), '') as chqno,
    NULLIF(CAST(TRIM(chqbank) AS STRING), '') as chqbank,
    NULLIF(CAST(TRIM(chqacode) AS STRING), '') as chqacode,
    NULLIF(CAST(TRIM(chqcus) AS STRING), '') as chqcus,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatec, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19))
    ) AS chqdatec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdater, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19))
    ) AS chqdater,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatep, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19))
    ) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    NULLIF(CAST(TRIM(chqmemo) AS STRING), '') as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    NULLIF(CAST(TRIM(chqjob) AS STRING), '') as chqjob,
    NULLIF(CAST(TRIM(chqdep) AS STRING), '') as chqdep,
    NULLIF(CAST(TRIM(chqper) AS STRING), '') as chqper,
    NULLIF(CAST(TRIM(chqzon) AS STRING), '') as chqzon,
    NULLIF(CAST(TRIM(chqrcode) AS STRING), '') as chqrcode,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqeditlk, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19))
    ) AS chqeditlk,
    NULLIF(CAST(TRIM(chqkeyuser) AS STRING), '') as chqkeyuser,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqkeydate, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19))
    ) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    NULLIF(CAST(TRIM(chqecode) AS STRING), '') as chqecode,
    NULLIF(CAST(TRIM(chqbranch) AS STRING), '') as chqbranch,
    NULLIF(CAST(TRIM(chqmec) AS STRING), '') as chqmec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatev, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19))
    ) AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.chq`

  UNION ALL

  SELECT
    'aa05' AS company_id,
    NULLIF(CAST(TRIM(chqno) AS STRING), '') as chqno,
    NULLIF(CAST(TRIM(chqbank) AS STRING), '') as chqbank,
    NULLIF(CAST(TRIM(chqacode) AS STRING), '') as chqacode,
    NULLIF(CAST(TRIM(chqcus) AS STRING), '') as chqcus,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatec, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19))
    ) AS chqdatec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdater, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19))
    ) AS chqdater,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatep, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19))
    ) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    NULLIF(CAST(TRIM(chqmemo) AS STRING), '') as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    NULLIF(CAST(TRIM(chqjob) AS STRING), '') as chqjob,
    NULLIF(CAST(TRIM(chqdep) AS STRING), '') as chqdep,
    NULLIF(CAST(TRIM(chqper) AS STRING), '') as chqper,
    NULLIF(CAST(TRIM(chqzon) AS STRING), '') as chqzon,
    NULLIF(CAST(TRIM(chqrcode) AS STRING), '') as chqrcode,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqeditlk, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19))
    ) AS chqeditlk,
    NULLIF(CAST(TRIM(chqkeyuser) AS STRING), '') as chqkeyuser,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqkeydate, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19))
    ) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    NULLIF(CAST(TRIM(chqecode) AS STRING), '') as chqecode,
    NULLIF(CAST(TRIM(chqbranch) AS STRING), '') as chqbranch,
    NULLIF(CAST(TRIM(chqmec) AS STRING), '') as chqmec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatev, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19))
    ) AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.chq`

  UNION ALL

  SELECT
    'ab01' AS company_id,
    NULLIF(CAST(TRIM(chqno) AS STRING), '') as chqno,
    NULLIF(CAST(TRIM(chqbank) AS STRING), '') as chqbank,
    NULLIF(CAST(TRIM(chqacode) AS STRING), '') as chqacode,
    NULLIF(CAST(TRIM(chqcus) AS STRING), '') as chqcus,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatec, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19))
    ) AS chqdatec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdater, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19))
    ) AS chqdater,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatep, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19))
    ) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    NULLIF(CAST(TRIM(chqmemo) AS STRING), '') as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    NULLIF(CAST(TRIM(chqjob) AS STRING), '') as chqjob,
    NULLIF(CAST(TRIM(chqdep) AS STRING), '') as chqdep,
    NULLIF(CAST(TRIM(chqper) AS STRING), '') as chqper,
    NULLIF(CAST(TRIM(chqzon) AS STRING), '') as chqzon,
    NULLIF(CAST(TRIM(chqrcode) AS STRING), '') as chqrcode,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqeditlk, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19))
    ) AS chqeditlk,
    NULLIF(CAST(TRIM(chqkeyuser) AS STRING), '') as chqkeyuser,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqkeydate, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19))
    ) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    NULLIF(CAST(TRIM(chqecode) AS STRING), '') as chqecode,
    NULLIF(CAST(TRIM(chqbranch) AS STRING), '') as chqbranch,
    NULLIF(CAST(TRIM(chqmec) AS STRING), '') as chqmec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatev, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19))
    ) AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.chq`

  UNION ALL

  SELECT
    'ac02' AS company_id,
    NULLIF(CAST(TRIM(chqno) AS STRING), '') as chqno,
    NULLIF(CAST(TRIM(chqbank) AS STRING), '') as chqbank,
    NULLIF(CAST(TRIM(chqacode) AS STRING), '') as chqacode,
    NULLIF(CAST(TRIM(chqcus) AS STRING), '') as chqcus,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatec, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19))
    ) AS chqdatec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdater, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19))
    ) AS chqdater,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatep, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19))
    ) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    NULLIF(CAST(TRIM(chqmemo) AS STRING), '') as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    NULLIF(CAST(TRIM(chqjob) AS STRING), '') as chqjob,
    NULLIF(CAST(TRIM(chqdep) AS STRING), '') as chqdep,
    NULLIF(CAST(TRIM(chqper) AS STRING), '') as chqper,
    NULLIF(CAST(TRIM(chqzon) AS STRING), '') as chqzon,
    NULLIF(CAST(TRIM(chqrcode) AS STRING), '') as chqrcode,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqeditlk, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19))
    ) AS chqeditlk,
    NULLIF(CAST(TRIM(chqkeyuser) AS STRING), '') as chqkeyuser,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqkeydate, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19))
    ) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    NULLIF(CAST(TRIM(chqecode) AS STRING), '') as chqecode,
    NULLIF(CAST(TRIM(chqbranch) AS STRING), '') as chqbranch,
    NULLIF(CAST(TRIM(chqmec) AS STRING), '') as chqmec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatev, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19))
    ) AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.chq`

  UNION ALL

  SELECT
    'ak02' AS company_id,
    NULLIF(CAST(TRIM(chqno) AS STRING), '') as chqno,
    NULLIF(CAST(TRIM(chqbank) AS STRING), '') as chqbank,
    NULLIF(CAST(TRIM(chqacode) AS STRING), '') as chqacode,
    NULLIF(CAST(TRIM(chqcus) AS STRING), '') as chqcus,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatec, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatec, 1, 19))
    ) AS chqdatec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdater, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdater, 1, 19))
    ) AS chqdater,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatep, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatep, 1, 19))
    ) AS chqdatep,
    CAST(chqtype AS INT64) as chqtype,
    CAST(chqstatus AS INT64) as chqstatus,
    CAST(chqtotal AS FLOAT64) as chqtotal,
    NULLIF(CAST(TRIM(chqmemo) AS STRING), '') as chqmemo,
    CAST(chqgl AS INT64) as chqgl,
    CAST(chqmi AS INT64) as chqmi,
    CAST(chqown AS INT64) as chqown,
    CAST(chqtag AS INT64) as chqtag,
    CAST(chqstatusn AS INT64) as chqstatusn,
    CAST(chqlock AS INT64) as chqlock,
    CAST(chqpassgl AS INT64) as chqpassgl,
    NULLIF(CAST(TRIM(chqjob) AS STRING), '') as chqjob,
    NULLIF(CAST(TRIM(chqdep) AS STRING), '') as chqdep,
    NULLIF(CAST(TRIM(chqper) AS STRING), '') as chqper,
    NULLIF(CAST(TRIM(chqzon) AS STRING), '') as chqzon,
    NULLIF(CAST(TRIM(chqrcode) AS STRING), '') as chqrcode,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqeditlk, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqeditlk, 1, 19))
    ) AS chqeditlk,
    NULLIF(CAST(TRIM(chqkeyuser) AS STRING), '') as chqkeyuser,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqkeydate, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqkeydate, 1, 19))
    ) AS chqkeydate,
    CAST(chqdeduct AS FLOAT64) as chqdeduct,
    NULLIF(CAST(TRIM(chqecode) AS STRING), '') as chqecode,
    NULLIF(CAST(TRIM(chqbranch) AS STRING), '') as chqbranch,
    NULLIF(CAST(TRIM(chqmec) AS STRING), '') as chqmec,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(chqdatev, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(chqdatev, 1, 19))
    ) AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.chq`
),

all_sources AS (
  SELECT * FROM raw_sources
  ${deduplicate_statement}
)

-------------------------------------------------------------------------
-- โจ เน€เธฃเธตเธขเธเนเธเน UDF เธ—เธตเนเน€เธฃเธฒเธฃเธฑเธ Parameter เน€เธเนเธฒเนเธ เธชเธฑเนเธเธเธฃเธดเนเธ! โจ
-------------------------------------------------------------------------
SELECT 
  * EXCEPT(chqmemo, extracted_data),
  chqmemo AS chqmemo_raw,               -- ๐‘ เธ”เธถเธเธเธญเธฅเธฑเธกเธเนเธ”เธดเธเธเธฅเธฑเธเธกเธฒ เนเธฅเนเธงเธ•เธฑเนเธเธเธทเนเธญเน€เธเนเธ _raw
  extracted_data.chqmemo AS chqmemo,    -- ๐‘ เน€เธญเธฒเธเนเธญเธเธงเธฒเธกเธ—เธตเนเธ•เธฑเธ”เนเธฅเนเธง (clean) เธกเธฒเนเธเนเน€เธเนเธ chqmemo เนเธ—เธ
  extracted_data.extract_text,
  extracted_data.extract_value
FROM (
  SELECT 
    *,
    -- เนเธขเธ 3 Parameters เนเธซเน UDF เธ•เธฒเธกเนเธเธฃเธเธชเธฃเนเธฒเธเธ—เธตเนเน€เธฃเธฒเธ•เธฑเนเธเนเธงเนเน€เธฅเธขเธเธฃเธฑเธ
    `${databuffet.DATABASE}.${databuffet.FUNCTION_DATASET}.EXTRACT_CHQ_DATA`(chqmemo, chqdatec, chqtotal) AS extracted_data
  FROM all_sources
)

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}