config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5", "create_all_table_raw_mac5_aa05", "create_all_table_raw_mac5_ab01", "create_all_table_raw_mac5_ac02", "create_all_table_raw_mac5_ak02", "create_all_function"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "chqno", "chqbank", "chqdatec", "chqtag"],
    bigquery: {
        clusterBy: ["company_id", "chqno"]
    },
}

js {
    const pk_key = ["company_id", "chqno", "chqbank", "chqdatec", "chqtag"]

    let deduplicate_statement = "";
    let post_operations_statement = "";
    
    if (pk_key && pk_key.length > 0) {
        deduplicate_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY chqkeydate desc) = 1`;
        
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;
    DECLARE loop_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

    WHILE retry_count < max_retries AND NOT success DO
        IF TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), loop_start, MINUTE) >= 5 THEN
            BREAK;
        END IF;

        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;

    IF NOT success THEN
        INSERT INTO monitoring_dataset.dataform_all_logs (
            process_name, data_layer, action_name, status, start_time, end_time, error_message, executed_by
        )
        SELECT 
            'Dataform Pipeline', 'VALIDATED', '${name()}', 'FAILED', (SELECT start_ts FROM temp_start_${name()}), NULL, 'Timeout 5 Minutes or Max Retries Reached', SESSION_USER();

        RAISE USING MESSAGE = 'Process Failed: Timeout 5 Minutes or Max Retries Reached';
    END IF;
END;`;
    }
}

pre_operations {
}

WITH raw_sources AS (
  SELECT
    'ag01' AS company_id,
    ${databuffet.functionData.cleanString('chqno')} as chqno,
    ${databuffet.functionData.cleanString('chqbank')} as chqbank,
    ${databuffet.functionData.cleanString('chqacode')} as chqacode,
    ${databuffet.functionData.cleanString('chqcus')} as chqcus,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatec')} AS chqdatec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdater')} AS chqdater,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatep')} AS chqdatep,
    ${databuffet.functionData.castInt64('chqtype')} as chqtype,
    ${databuffet.functionData.castInt64('chqstatus')} as chqstatus,
    ${databuffet.functionData.castFloat64('chqtotal')} as chqtotal,
    ${databuffet.functionData.cleanString('chqmemo')} as chqmemo,
    ${databuffet.functionData.castInt64('chqgl')} as chqgl,
    ${databuffet.functionData.castInt64('chqmi')} as chqmi,
    ${databuffet.functionData.castInt64('chqown')} as chqown,
    ${databuffet.functionData.castInt64('chqtag')} as chqtag,
    ${databuffet.functionData.castInt64('chqstatusn')} as chqstatusn,
    ${databuffet.functionData.castInt64('chqlock')} as chqlock,
    ${databuffet.functionData.castInt64('chqpassgl')} as chqpassgl,
    ${databuffet.functionData.cleanString('chqjob')} as chqjob,
    ${databuffet.functionData.cleanString('chqdep')} as chqdep,
    ${databuffet.functionData.cleanString('chqper')} as chqper,
    ${databuffet.functionData.cleanString('chqzon')} as chqzon,
    ${databuffet.functionData.cleanString('chqrcode')} as chqrcode,
    ${databuffet.functionData.parseFlexibleDatetime('chqeditlk')} AS chqeditlk,
    ${databuffet.functionData.cleanString('chqkeyuser')} as chqkeyuser,
    ${databuffet.functionData.parseFlexibleDatetime('chqkeydate')} AS chqkeydate,
    ${databuffet.functionData.castFloat64('chqdeduct')} as chqdeduct,
    ${databuffet.functionData.cleanString('chqecode')} as chqecode,
    ${databuffet.functionData.cleanString('chqbranch')} as chqbranch,
    ${databuffet.functionData.cleanString('chqmec')} as chqmec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatev')} AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.chq`

  UNION ALL

  SELECT
    'aa05' AS company_id,
    ${databuffet.functionData.cleanString('chqno')} as chqno,
    ${databuffet.functionData.cleanString('chqbank')} as chqbank,
    ${databuffet.functionData.cleanString('chqacode')} as chqacode,
    ${databuffet.functionData.cleanString('chqcus')} as chqcus,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatec')} AS chqdatec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdater')} AS chqdater,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatep')} AS chqdatep,
    ${databuffet.functionData.castInt64('chqtype')} as chqtype,
    ${databuffet.functionData.castInt64('chqstatus')} as chqstatus,
    ${databuffet.functionData.castFloat64('chqtotal')} as chqtotal,
    ${databuffet.functionData.cleanString('chqmemo')} as chqmemo,
    ${databuffet.functionData.castInt64('chqgl')} as chqgl,
    ${databuffet.functionData.castInt64('chqmi')} as chqmi,
    ${databuffet.functionData.castInt64('chqown')} as chqown,
    ${databuffet.functionData.castInt64('chqtag')} as chqtag,
    ${databuffet.functionData.castInt64('chqstatusn')} as chqstatusn,
    ${databuffet.functionData.castInt64('chqlock')} as chqlock,
    ${databuffet.functionData.castInt64('chqpassgl')} as chqpassgl,
    ${databuffet.functionData.cleanString('chqjob')} as chqjob,
    ${databuffet.functionData.cleanString('chqdep')} as chqdep,
    ${databuffet.functionData.cleanString('chqper')} as chqper,
    ${databuffet.functionData.cleanString('chqzon')} as chqzon,
    ${databuffet.functionData.cleanString('chqrcode')} as chqrcode,
    ${databuffet.functionData.parseFlexibleDatetime('chqeditlk')} AS chqeditlk,
    ${databuffet.functionData.cleanString('chqkeyuser')} as chqkeyuser,
    ${databuffet.functionData.parseFlexibleDatetime('chqkeydate')} AS chqkeydate,
    ${databuffet.functionData.castFloat64('chqdeduct')} as chqdeduct,
    ${databuffet.functionData.cleanString('chqecode')} as chqecode,
    ${databuffet.functionData.cleanString('chqbranch')} as chqbranch,
    ${databuffet.functionData.cleanString('chqmec')} as chqmec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatev')} AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.chq`

  UNION ALL

  SELECT
    'ab01' AS company_id,
    ${databuffet.functionData.cleanString('chqno')} as chqno,
    ${databuffet.functionData.cleanString('chqbank')} as chqbank,
    ${databuffet.functionData.cleanString('chqacode')} as chqacode,
    ${databuffet.functionData.cleanString('chqcus')} as chqcus,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatec')} AS chqdatec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdater')} AS chqdater,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatep')} AS chqdatep,
    ${databuffet.functionData.castInt64('chqtype')} as chqtype,
    ${databuffet.functionData.castInt64('chqstatus')} as chqstatus,
    ${databuffet.functionData.castFloat64('chqtotal')} as chqtotal,
    ${databuffet.functionData.cleanString('chqmemo')} as chqmemo,
    ${databuffet.functionData.castInt64('chqgl')} as chqgl,
    ${databuffet.functionData.castInt64('chqmi')} as chqmi,
    ${databuffet.functionData.castInt64('chqown')} as chqown,
    ${databuffet.functionData.castInt64('chqtag')} as chqtag,
    ${databuffet.functionData.castInt64('chqstatusn')} as chqstatusn,
    ${databuffet.functionData.castInt64('chqlock')} as chqlock,
    ${databuffet.functionData.castInt64('chqpassgl')} as chqpassgl,
    ${databuffet.functionData.cleanString('chqjob')} as chqjob,
    ${databuffet.functionData.cleanString('chqdep')} as chqdep,
    ${databuffet.functionData.cleanString('chqper')} as chqper,
    ${databuffet.functionData.cleanString('chqzon')} as chqzon,
    ${databuffet.functionData.cleanString('chqrcode')} as chqrcode,
    ${databuffet.functionData.parseFlexibleDatetime('chqeditlk')} AS chqeditlk,
    ${databuffet.functionData.cleanString('chqkeyuser')} as chqkeyuser,
    ${databuffet.functionData.parseFlexibleDatetime('chqkeydate')} AS chqkeydate,
    ${databuffet.functionData.castFloat64('chqdeduct')} as chqdeduct,
    ${databuffet.functionData.cleanString('chqecode')} as chqecode,
    ${databuffet.functionData.cleanString('chqbranch')} as chqbranch,
    ${databuffet.functionData.cleanString('chqmec')} as chqmec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatev')} AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.chq`

  UNION ALL

  SELECT
    'ac02' AS company_id,
    ${databuffet.functionData.cleanString('chqno')} as chqno,
    ${databuffet.functionData.cleanString('chqbank')} as chqbank,
    ${databuffet.functionData.cleanString('chqacode')} as chqacode,
    ${databuffet.functionData.cleanString('chqcus')} as chqcus,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatec')} AS chqdatec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdater')} AS chqdater,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatep')} AS chqdatep,
    ${databuffet.functionData.castInt64('chqtype')} as chqtype,
    ${databuffet.functionData.castInt64('chqstatus')} as chqstatus,
    ${databuffet.functionData.castFloat64('chqtotal')} as chqtotal,
    ${databuffet.functionData.cleanString('chqmemo')} as chqmemo,
    ${databuffet.functionData.castInt64('chqgl')} as chqgl,
    ${databuffet.functionData.castInt64('chqmi')} as chqmi,
    ${databuffet.functionData.castInt64('chqown')} as chqown,
    ${databuffet.functionData.castInt64('chqtag')} as chqtag,
    ${databuffet.functionData.castInt64('chqstatusn')} as chqstatusn,
    ${databuffet.functionData.castInt64('chqlock')} as chqlock,
    ${databuffet.functionData.castInt64('chqpassgl')} as chqpassgl,
    ${databuffet.functionData.cleanString('chqjob')} as chqjob,
    ${databuffet.functionData.cleanString('chqdep')} as chqdep,
    ${databuffet.functionData.cleanString('chqper')} as chqper,
    ${databuffet.functionData.cleanString('chqzon')} as chqzon,
    ${databuffet.functionData.cleanString('chqrcode')} as chqrcode,
    ${databuffet.functionData.parseFlexibleDatetime('chqeditlk')} AS chqeditlk,
    ${databuffet.functionData.cleanString('chqkeyuser')} as chqkeyuser,
    ${databuffet.functionData.parseFlexibleDatetime('chqkeydate')} AS chqkeydate,
    ${databuffet.functionData.castFloat64('chqdeduct')} as chqdeduct,
    ${databuffet.functionData.cleanString('chqecode')} as chqecode,
    ${databuffet.functionData.cleanString('chqbranch')} as chqbranch,
    ${databuffet.functionData.cleanString('chqmec')} as chqmec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatev')} AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.chq`

  UNION ALL

  SELECT
    'ak02' AS company_id,
    ${databuffet.functionData.cleanString('chqno')} as chqno,
    ${databuffet.functionData.cleanString('chqbank')} as chqbank,
    ${databuffet.functionData.cleanString('chqacode')} as chqacode,
    ${databuffet.functionData.cleanString('chqcus')} as chqcus,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatec')} AS chqdatec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdater')} AS chqdater,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatep')} AS chqdatep,
    ${databuffet.functionData.castInt64('chqtype')} as chqtype,
    ${databuffet.functionData.castInt64('chqstatus')} as chqstatus,
    ${databuffet.functionData.castFloat64('chqtotal')} as chqtotal,
    ${databuffet.functionData.cleanString('chqmemo')} as chqmemo,
    ${databuffet.functionData.castInt64('chqgl')} as chqgl,
    ${databuffet.functionData.castInt64('chqmi')} as chqmi,
    ${databuffet.functionData.castInt64('chqown')} as chqown,
    ${databuffet.functionData.castInt64('chqtag')} as chqtag,
    ${databuffet.functionData.castInt64('chqstatusn')} as chqstatusn,
    ${databuffet.functionData.castInt64('chqlock')} as chqlock,
    ${databuffet.functionData.castInt64('chqpassgl')} as chqpassgl,
    ${databuffet.functionData.cleanString('chqjob')} as chqjob,
    ${databuffet.functionData.cleanString('chqdep')} as chqdep,
    ${databuffet.functionData.cleanString('chqper')} as chqper,
    ${databuffet.functionData.cleanString('chqzon')} as chqzon,
    ${databuffet.functionData.cleanString('chqrcode')} as chqrcode,
    ${databuffet.functionData.parseFlexibleDatetime('chqeditlk')} AS chqeditlk,
    ${databuffet.functionData.cleanString('chqkeyuser')} as chqkeyuser,
    ${databuffet.functionData.parseFlexibleDatetime('chqkeydate')} AS chqkeydate,
    ${databuffet.functionData.castFloat64('chqdeduct')} as chqdeduct,
    ${databuffet.functionData.cleanString('chqecode')} as chqecode,
    ${databuffet.functionData.cleanString('chqbranch')} as chqbranch,
    ${databuffet.functionData.cleanString('chqmec')} as chqmec,
    ${databuffet.functionData.parseFlexibleDatetime('chqdatev')} AS chqdatev
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.chq`
),

all_sources AS (
  SELECT * FROM raw_sources
  ${deduplicate_statement}
)

-------------------------------------------------------------------------
-- โจ เน€เธฃเธตเธขเธเนเธเน UDF เธ—เธตเนเน€เธฃเธฒเธฃเธฑเธ Parameter เน€เธเนเธฒเนเธ เธชเธฑเนเธเธเธฃเธดเนเธ! โจ
-------------------------------------------------------------------------
SELECT 
  * EXCEPT(chqmemo, extracted_data),
  chqmemo AS chqmemo_raw,               -- ๐‘ เธ”เธถเธเธเธญเธฅเธฑเธกเธเนเธ”เธดเธเธเธฅเธฑเธเธกเธฒ เนเธฅเนเธงเธ•เธฑเนเธเธเธทเนเธญเน€เธเนเธ _raw
  extracted_data.chqmemo AS chqmemo,    -- ๐‘ เน€เธญเธฒเธเนเธญเธเธงเธฒเธกเธ—เธตเนเธ•เธฑเธ”เนเธฅเนเธง (clean) เธกเธฒเนเธเนเน€เธเนเธ chqmemo เนเธ—เธ
  extracted_data.extract_text,
  extracted_data.extract_value
FROM (
  SELECT 
    *,
    -- เนเธขเธ 3 Parameters เนเธซเน UDF เธ•เธฒเธกเนเธเธฃเธเธชเธฃเนเธฒเธเธ—เธตเนเน€เธฃเธฒเธ•เธฑเนเธเนเธงเนเน€เธฅเธขเธเธฃเธฑเธ
    `${databuffet.DATABASE}.${databuffet.FUNCTION_DATASET}.EXTRACT_CHQ_DATA`(chqmemo, chqdatec, chqtotal) AS extracted_data
  FROM all_sources
)

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}