config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [],
    bigquery: {
        clusterBy: ["cppstkid"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = []

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cppdateid desc) = 1`;
        post_operations_statement = `BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS';
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED';
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(cppstkid) AS STRING), '') as cppstkid,
    CAST(cpplinkid AS INT64) as cpplinkid,
    NULLIF(CAST(TRIM(cppvnosid) AS STRING), '') as cppvnosid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cppdateid, 1, 19)) AS cppdateid,
    NULLIF(CAST(TRIM(cppcusid) AS STRING), '') as cppcusid,
    NULLIF(CAST(TRIM(cppjob) AS STRING), '') as cppjob,
    NULLIF(CAST(TRIM(cppdep) AS STRING), '') as cppdep,
    NULLIF(CAST(TRIM(cppper) AS STRING), '') as cppper,
    NULLIF(CAST(TRIM(cppdoc) AS STRING), '') as cppdoc,
    NULLIF(CAST(TRIM(cppmec) AS STRING), '') as cppmec,
    NULLIF(CAST(TRIM(cppsto) AS STRING), '') as cppsto,
    CAST(cppstkreq AS FLOAT64) as cppstkreq,
    CAST(cppstkcut1 AS FLOAT64) as cppstkcut1,
    CAST(cppstkcut2 AS FLOAT64) as cppstkcut2,
    CAST(cppsumreq AS FLOAT64) as cppsumreq,
    CAST(cppsumcut1 AS FLOAT64) as cppsumcut1,
    CAST(cppsumcut2 AS FLOAT64) as cppsumcut2,
    CAST(cppclearstk AS INT64) as cppclearstk,
    CAST(cppclearsum AS INT64) as cppclearsum,
    CAST(cppclearuser AS INT64) as cppclearuser,
    CAST(cppclearall AS INT64) as cppclearall,
    CAST(cppcurc AS INT64) as cppcurc,
    CAST(cppexchg AS FLOAT64) as cppexchg,
    CAST(cppcut AS INT64) as cppcut,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cppdelvdate, 1, 19)) AS cppdelvdate,
    CAST(cpplistno AS INT64) as cpplistno,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
