config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["cpsstkid"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = []

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `BEGIN
    ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(CPSstkID) AS STRING), '') AS cpsstkid,
  CAST(CPSlinkID AS INT64) AS cpslinkid,
  NULLIF(CAST(TRIM(CPSvnosID) AS STRING), '') AS cpsvnosid,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(CPSdateID, 1, 19)) AS cpsdateid,
  NULLIF(CAST(TRIM(CPScusID) AS STRING), '') AS cpscusid,
  NULLIF(CAST(TRIM(CPSjob) AS STRING), '') AS cpsjob,
  NULLIF(CAST(TRIM(CPSdep) AS STRING), '') AS cpsdep,
  NULLIF(CAST(TRIM(CPSper) AS STRING), '') AS cpsper,
  NULLIF(CAST(TRIM(CPSdoc) AS STRING), '') AS cpsdoc,
  NULLIF(CAST(TRIM(CPSmec) AS STRING), '') AS cpsmec,
  NULLIF(CAST(TRIM(CPSsto) AS STRING), '') AS cpssto,
  CAST(CPSstkREQ AS FLOAT64) AS cpsstkreq,
  CAST(CPSstkCUT1 AS FLOAT64) AS cpsstkcut1,
  CAST(CPSstkCUT2 AS FLOAT64) AS cpsstkcut2,
  CAST(CPSsumREQ AS FLOAT64) AS cpssumreq,
  CAST(CPSsumCUT1 AS FLOAT64) AS cpssumcut1,
  CAST(CPSsumCUT2 AS FLOAT64) AS cpssumcut2,
  CAST(CPSclearSTK AS INT64) AS cpsclearstk,
  CAST(CPSclearSUM AS INT64) AS cpsclearsum,
  CAST(CPSclearUSER AS INT64) AS cpsclearuser,
  CAST(CPSclearALL AS INT64) AS cpsclearall,
  CAST(CPScurC AS INT64) AS cpscurc,
  CAST(CPSexchg AS FLOAT64) AS cpsexchg,
  CAST(CPScut AS INT64) AS cpscut,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(CPSdelvDate, 1, 19)) AS cpsdelvdate,
  CAST(CPSlistNo AS INT64) AS cpslistno,
  NULLIF(CAST(TRIM(rowguid) AS STRING), '') AS rowguid,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
