config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "cpxstkid","cpxlinkid","cpxvnosid","cpxdateid"],
    bigquery: {
        clusterBy: ["company_id", "cpxstkid"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "cpxstkid","cpxlinkid","cpxvnosid","cpxdateid"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cpxdateid desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.functionData.cleanString('cpxstkid')} as cpxstkid,
    ${databuffet.functionData.castInt64('cpxlinkid')} as cpxlinkid,
    ${databuffet.functionData.cleanString('cpxvnosid')} as cpxvnosid,
    ${databuffet.functionData.parseFlexibleDatetime('cpxdateid')} AS cpxdateid,
    ${databuffet.functionData.cleanString('cpxjob')} as cpxjob,
    ${databuffet.functionData.cleanString('cpxdep')} as cpxdep,
    ${databuffet.functionData.cleanString('cpxper')} as cpxper,
    ${databuffet.functionData.cleanString('cpxdoc')} as cpxdoc,
    ${databuffet.functionData.cleanString('cpxmec')} as cpxmec,
    ${databuffet.functionData.cleanString('cpxsto')} as cpxsto,
    ${databuffet.functionData.castFloat64('cpxstkreq')} as cpxstkreq,
    ${databuffet.functionData.castFloat64('cpxstkcut')} as cpxstkcut,
    ${databuffet.functionData.castInt64('cpxclearstk')} as cpxclearstk,
    ${databuffet.functionData.castInt64('cpxclearuser')} as cpxclearuser,
    ${databuffet.functionData.castInt64('cpxclearall')} as cpxclearall,
    ${databuffet.functionData.castInt64('cpxstatus')} as cpxstatus

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
