config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["cpxstkid","cpxlinkid","cpxvnosid","cpxdateid"],
    bigquery: {
        clusterBy: ["cpxstkid"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["cpxstkid","cpxlinkid","cpxvnosid","cpxdateid"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY cpxdateid desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(cpxstkid) AS STRING), '') as cpxstkid,
    CAST(cpxlinkid AS INT64) as cpxlinkid,
    NULLIF(CAST(TRIM(cpxvnosid) AS STRING), '') as cpxvnosid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(cpxdateid, 1, 19)) AS cpxdateid,
    NULLIF(CAST(TRIM(cpxjob) AS STRING), '') as cpxjob,
    NULLIF(CAST(TRIM(cpxdep) AS STRING), '') as cpxdep,
    NULLIF(CAST(TRIM(cpxper) AS STRING), '') as cpxper,
    NULLIF(CAST(TRIM(cpxdoc) AS STRING), '') as cpxdoc,
    NULLIF(CAST(TRIM(cpxmec) AS STRING), '') as cpxmec,
    NULLIF(CAST(TRIM(cpxsto) AS STRING), '') as cpxsto,
    CAST(cpxstkreq AS FLOAT64) as cpxstkreq,
    CAST(cpxstkcut AS FLOAT64) as cpxstkcut,
    CAST(cpxclearstk AS INT64) as cpxclearstk,
    CAST(cpxclearuser AS INT64) as cpxclearuser,
    CAST(cpxclearall AS INT64) as cpxclearall,
    CAST(cpxstatus AS INT64) as cpxstatus,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${sourceTableRef}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
