config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cre"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["cre"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY crenamet desc, crenamee desc, credate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(crecode) AS STRING) as crecode,
    CAST(TRIM(cregroup) AS STRING) as cregroup,
    CAST(TRIM(crenamet) AS STRING) as crenamet,
    CAST(TRIM(crenamee) AS STRING) as crenamee,
    CAST(TRIM(crecontactt) AS STRING) as crecontactt,
    CAST(TRIM(crecontacte) AS STRING) as crecontacte,
    CAST(TRIM(creadd1at) AS STRING) as creadd1at,
    CAST(TRIM(creadd2at) AS STRING) as creadd2at,
    CAST(TRIM(creadd3at) AS STRING) as creadd3at,
    CAST(TRIM(creadd1ae) AS STRING) as creadd1ae,
    CAST(TRIM(creadd2ae) AS STRING) as creadd2ae,
    CAST(TRIM(creadd3ae) AS STRING) as creadd3ae,
    CAST(TRIM(cretel) AS STRING) as cretel,
    CAST(TRIM(cretaxnos) AS STRING) as cretaxnos,
    CAST(TRIM(crezone) AS STRING) as crezone,
    CAST(TRIM(cregrade) AS STRING) as cregrade,
    CAST(crelimit AS FLOAT64) as crelimit,
    CAST(cretaxclass AS FLOAT64) as cretaxclass,
    CAST(cregoodsdef AS INT64) as cregoodsdef,
    CAST(crecreditterm AS INT64) as crecreditterm,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(credate, 1, 19)) AS credate,
    CAST(crehide AS INT64) as crehide,
    CAST(TRIM(crefax) AS STRING) as crefax,
    CAST(TRIM(creemail) AS STRING) as creemail,
    CAST(cretarget AS FLOAT64) as cretarget,
    CAST(TRIM(crememo) AS STRING) as crememo,
    CAST(TRIM(creac) AS STRING) as creac,
    CAST(crelock AS INT64) as crelock,
    CAST(TRIM(creoname) AS STRING) as creoname,
    CAST(TRIM(creprice) AS STRING) as creprice,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(creeditlk, 1, 19)) AS creeditlk,
    CAST(TRIM(crerefwe) AS STRING) as crerefwe,
    CAST(TRIM(cresortnt) AS STRING) as cresortnt,
    CAST(TRIM(cresortne) AS STRING) as cresortne,
    CAST(TRIM(crecardid) AS STRING) as crecardid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(creeditdt, 1, 19)) AS creeditdt,
    CAST(TRIM(creeditmf) AS STRING) as creeditmf,
    CAST(cretaxtype AS INT64) as cretaxtype,
    CAST(creinex AS INT64) as creinex,
    CAST(TRIM(crebranch) AS STRING) as crebranch

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
