config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["depcode"],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["depcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY depeditdt desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(depcode) AS STRING), '') as depcode,
    NULLIF(CAST(TRIM(depgroup) AS STRING), '') as depgroup,
    NULLIF(CAST(TRIM(depdesct) AS STRING), '') as depdesct,
    NULLIF(CAST(TRIM(depdesce) AS STRING), '') as depdesce,
    CAST(dephide AS INT64) as dephide,
    CAST(deplock AS INT64) as deplock,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(depeditdt, 1, 19)) AS depeditdt,
    NULLIF(CAST(TRIM(depeditmf) AS STRING), '') as depeditmf,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
