config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["id"],
    bigquery: {
        clusterBy: ["id"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY dupdate desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(ref_id AS INT64) as ref_id,
    CAST(qtid AS INT64) as qtid,
    NULLIF(CAST(TRIM(quodeid) AS STRING), '') as quodeid,
    NULLIF(CAST(TRIM(stkcode) AS STRING), '') as stkcode,
    CAST(quantity AS FLOAT64) as quantity,
    CAST(price AS FLOAT64) as price,
    NULLIF(CAST(TRIM(total) AS STRING), '') as total,
    NULLIF(CAST(TRIM(uinsert) AS STRING), '') as uinsert,
    NULLIF(CAST(TRIM(uupdate) AS STRING), '') as uupdate,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) as dinsert,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)) as dupdate,
    NULLIF(CAST(TRIM(status) AS STRING), '') as status,
    NULLIF(CAST(TRIM(link) AS STRING), '') as link,
    NULLIF(CAST(TRIM(type) AS STRING), '') as type,
    NULLIF(CAST(TRIM(fandex) AS STRING), '') as fandex,
    NULLIF(CAST(TRIM(itemsize) AS STRING), '') as itemsize

FROM
  `${sourceTableRef}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
