config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "doccode"],
    bigquery: {
        clusterBy: ["company_id", "doccode"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "doccode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY doceditdt desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    NULLIF(CAST(TRIM(doccode) AS STRING), '') as doccode,
    NULLIF(CAST(TRIM(docgroup) AS STRING), '') as docgroup,
    NULLIF(CAST(TRIM(docdesct) AS STRING), '') as docdesct,
    NULLIF(CAST(TRIM(docdesce) AS STRING), '') as docdesce,
    CAST(doclock AS INT64) as doclock,
    NULLIF(CAST(TRIM(docacc) AS STRING), '') as docacc,
    CAST(docdebit AS INT64) as docdebit,
    NULLIF(CAST(TRIM(docrefwe) AS STRING), '') as docrefwe,
    CAST(dochide AS INT64) as dochide,
    COALESCE(
      SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(doceditdt, 1, 19)),
      SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(doceditdt, 1, 19))
    ) AS doceditdt,
    NULLIF(CAST(TRIM(doceditmf) AS STRING), '') as doceditmf

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
