config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["doccode"],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["doccode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY doceditdt desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(doccode) AS STRING), '') as doccode,
    NULLIF(CAST(TRIM(docgroup) AS STRING), '') as docgroup,
    NULLIF(CAST(TRIM(docdesct) AS STRING), '') as docdesct,
    NULLIF(CAST(TRIM(docdesce) AS STRING), '') as docdesce,
    CAST(doclock AS INT64) as doclock,
    NULLIF(CAST(TRIM(docacc) AS STRING), '') as docacc,
    CAST(docdebit AS INT64) as docdebit,
    NULLIF(CAST(TRIM(docrefwe) AS STRING), '') as docrefwe,
    CAST(dochide AS INT64) as dochide,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(doceditdt, 1, 19)) AS doceditdt,
    NULLIF(CAST(TRIM(doceditmf) AS STRING), '') as doceditmf,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
