config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["main_qtspread"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["main_qtspread"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY projectname desc, dupdate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(ref_id AS INT64) as ref_id,
    CAST(TRIM(qtid) AS STRING) as qtid,
    CAST(TRIM(uinsert) AS STRING) as uinsert,
    CAST(TRIM(uupdate) AS STRING) as uupdate,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) as dinsert,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)) as dupdate,
    CAST(TRIM(atten) AS STRING) as atten,
    CAST(TRIM(lat) AS STRING) as lat,
    CAST(TRIM(long) AS STRING) as long,
    CAST(TRIM(mapnote) AS STRING) as mapnote,
    CAST(TRIM(city) AS STRING) as city,
    CAST(TRIM(ctel) AS STRING) as ctel,
    CAST(TRIM(ctel2) AS STRING) as ctel2,
    CAST(TRIM(road) AS STRING) as road,
    CAST(TRIM(area) AS STRING) as area,
    CAST(TRIM(district) AS STRING) as district,
    CAST(TRIM(postcode) AS STRING) as postcode,
    CAST(TRIM(caddress) AS STRING) as caddress,
    CAST(TRIM(podocno) AS STRING) as podocno,
    CAST(TRIM(rdosend) AS STRING) as rdosend,
    CAST(TRIM(checknote) AS STRING) as checknote,
    CAST(TRIM(checknote2) AS STRING) as checknote2,
    CAST(TRIM(checknote3) AS STRING) as checknote3,
    CAST(TRIM(checknote4) AS STRING) as checknote4,
    CAST(TRIM(checknotemoney) AS STRING) as checknotemoney,
    CAST(TRIM(textnote) AS STRING) as textnote,
    CAST(TRIM(status) AS STRING) as status,
    CAST(TRIM(editnote) AS STRING) as editnote,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(editnotedate, 1, 19)) AS editnotedate,
    CAST(TRIM(delvdate) AS STRING) as delvdate,
    CAST(TRIM(transferfg) AS STRING) as transferfg,
    CAST(TRIM(meccode) AS STRING) as meccode,
    CAST(TRIM(subcontract) AS STRING) as subcontract,
    CAST(TRIM(blueprint) AS STRING) as blueprint,
    CAST(TRIM(projectname) AS STRING) as projectname,
    CAST(TRIM(mihjob) AS STRING) as mihjob,
    CAST(repeatblueprint AS INT64) as repeatblueprint,
    CAST(TRIM(noteblueprint) AS STRING) as noteblueprint,
    CAST(discountthreepercent AS INT64) as discountthreepercent,
    CAST(paybycash AS INT64) as paybycash,
    CAST(creditterm AS INT64) as creditterm,
    CAST(moneydeposit AS FLOAT64) as moneydeposit,
    CAST(extrasum AS INT64) as extrasum,
    CAST(TRIM(agent) AS STRING) as agent,
    CAST(TRIM(termpayment) AS STRING) as termpayment,
    CAST(discountcash AS INT64) as discountcash,
    CAST(TRIM(paytype) AS STRING) as paytype,
    CAST(amount AS FLOAT64) as amount,
    CAST(TRIM(refer_order_allkons_m) AS STRING) as refer_order_allkons_m,
    CAST(etax AS INT64) as etax,
    CAST(TRIM(etax_email) AS STRING) as etax_email

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
