config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "id"],
    bigquery: {
        clusterBy: ["company_id", "id"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY projectname desc, dupdate desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.functionData.castInt64('id')} as id,
    ${databuffet.functionData.castInt64('ref_id')} as ref_id,
    ${databuffet.functionData.cleanString('qtid')} as qtid,
    ${databuffet.functionData.cleanString('uinsert')} as uinsert,
    ${databuffet.functionData.cleanString('uupdate')} as uupdate,
    COALESCE(
        SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)),
        PARSE_DATETIME('%b %d %Y %I:%M%p', TRIM(dinsert))
    ) as dinsert,
    --PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) as dinsert,
    COALESCE(
        SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)),
        PARSE_DATETIME('%b %d %Y %I:%M%p', TRIM(dupdate))
    ) as dupdate,
    --PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)) as dupdate,
    ${databuffet.functionData.cleanString('atten')} as atten,
    ${databuffet.functionData.cleanString('lat')} as lat,
    ${databuffet.functionData.cleanString('long')} as long,
    ${databuffet.functionData.cleanString('mapnote')} as mapnote,
    ${databuffet.functionData.cleanString('city')} as city,
    ${databuffet.functionData.cleanString('ctel')} as ctel,
    ${databuffet.functionData.cleanString('ctel2')} as ctel2,
    ${databuffet.functionData.cleanString('road')} as road,
    ${databuffet.functionData.cleanString('area')} as area,
    ${databuffet.functionData.cleanString('district')} as district,
    ${databuffet.functionData.cleanString('postcode')} as postcode,
    ${databuffet.functionData.cleanString('caddress')} as caddress,
    ${databuffet.functionData.cleanString('podocno')} as podocno,
    ${databuffet.functionData.cleanString('rdosend')} as rdosend,
    ${databuffet.functionData.cleanString('checknote')} as checknote,
    ${databuffet.functionData.cleanString('checknote2')} as checknote2,
    ${databuffet.functionData.cleanString('checknote3')} as checknote3,
    ${databuffet.functionData.cleanString('checknote4')} as checknote4,
    ${databuffet.functionData.cleanString('checknotemoney')} as checknotemoney,
    ${databuffet.functionData.cleanString('textnote')} as textnote,
    ${databuffet.functionData.cleanString('status')} as status,
    ${databuffet.functionData.cleanString('editnote')} as editnote,
    COALESCE(
        SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(editnotedate, 1, 19)),
        PARSE_DATETIME('%b %d %Y %I:%M%p', TRIM(editnotedate))
    ) as editnotedate,
    --PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(editnotedate, 1, 19)) AS editnotedate,
    ${databuffet.functionData.cleanString('delvdate')} as delvdate,
    ${databuffet.functionData.cleanString('transferfg')} as transferfg,
    ${databuffet.functionData.cleanString('meccode')} as meccode,
    ${databuffet.functionData.cleanString('subcontract')} as subcontract,
    ${databuffet.functionData.cleanString('blueprint')} as blueprint,
    ${databuffet.functionData.cleanString('projectname')} as projectname,
    ${databuffet.functionData.cleanString('mihjob')} as mihjob,
    ${databuffet.functionData.castInt64('repeatblueprint')} as repeatblueprint,
    ${databuffet.functionData.cleanString('noteblueprint')} as noteblueprint,
    ${databuffet.functionData.castInt64('discountthreepercent')} as discountthreepercent,
    ${databuffet.functionData.castInt64('paybycash')} as paybycash,
    ${databuffet.functionData.castInt64('creditterm')} as creditterm,
    ${databuffet.functionData.castFloat64('moneydeposit')} as moneydeposit,
    ${databuffet.functionData.castInt64('extrasum')} as extrasum,
    ${databuffet.functionData.cleanString('agent')} as agent,
    ${databuffet.functionData.cleanString('termpayment')} as termpayment,
    ${databuffet.functionData.castInt64('discountcash')} as discountcash,
    ${databuffet.functionData.cleanString('paytype')} as paytype,
    ${databuffet.functionData.castFloat64('amount')} as amount,
    ${databuffet.functionData.cleanString('refer_order_allkons_m')} as refer_order_allkons_m,
    ${databuffet.functionData.castInt64('etax')} as etax,
    ${databuffet.functionData.cleanString('etax_email')} as etax_email

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
