config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mec"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mec"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY meceditdt desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(meccode) AS STRING) as meccode,
    CAST(mectpl AS INT64) as mectpl,
    CAST(mectoctype AS INT64) as mectoctype,
    CAST(TRIM(mectocode) AS STRING) as mectocode,
    CAST(TRIM(mect1) AS STRING) as mect1,
    CAST(TRIM(mect2) AS STRING) as mect2,
    CAST(TRIM(mect3) AS STRING) as mect3,
    CAST(TRIM(mect4) AS STRING) as mect4,
    CAST(TRIM(mect5) AS STRING) as mect5,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mecd1, 1, 19)) AS mecd1,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mecd2, 1, 19)) AS mecd2,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mecd3, 1, 19)) AS mecd3,
    CAST(meci1 AS INT64) as meci1,
    CAST(meci2 AS INT64) as meci2,
    CAST(mecc1 AS FLOAT64) as mecc1,
    CAST(mecc2 AS FLOAT64) as mecc2,
    CAST(mecc3 AS FLOAT64) as mecc3,
    CAST(mecc4 AS FLOAT64) as mecc4,
    CAST(mecc5 AS FLOAT64) as mecc5,
    CAST(TRIM(mecm1) AS STRING) as mecm1,
    CAST(TRIM(mecm2) AS STRING) as mecm2,
    CAST(TRIM(mecm3) AS STRING) as mecm3,
    CAST(TRIM(mecm4) AS STRING) as mecm4,
    CAST(TRIM(mecm5) AS STRING) as mecm5,
    CAST(TRIM(mecm6) AS STRING) as mecm6,
    CAST(TRIM(mecm7) AS STRING) as mecm7,
    CAST(TRIM(mecm8) AS STRING) as mecm8,
    CAST(TRIM(mecm9) AS STRING) as mecm9,
    CAST(TRIM(mecdesc) AS STRING) as mecdesc,
    CAST(mechide AS INT64) as mechide,
    CAST(meclock AS INT64) as meclock,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(meceditlk, 1, 19)) AS meceditlk,
    CAST(TRIM(mecrefwe) AS STRING) as mecrefwe,
    CAST(TRIM(mecsortn) AS STRING) as mecsortn,
    CAST(TRIM(mect6) AS STRING) as mect6,
    CAST(TRIM(mect7) AS STRING) as mect7,
    CAST(TRIM(mect8) AS STRING) as mect8,
    CAST(TRIM(mect9) AS STRING) as mect9,
    CAST(TRIM(mect10) AS STRING) as mect10,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(meceditdt, 1, 19)) AS meceditdt,
    CAST(TRIM(meceditmf) AS STRING) as meceditmf,
    CAST(TRIM(rowguid) AS STRING) as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
