config {
    type: "incremental",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["company_id", "MIEday","MIEmonth","MIEyear","MIEtype","MIEvnos","MIEcus"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["company_id", "mietype", "mievnos", "miecus"]
    },
}

js {
    const pk_key = ["company_id", "MIEday","MIEmonth","MIEyear","MIEtype","MIEvnos","MIEcus"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.castInt64('MIEday')} AS mieday,
    ${databuffet.castInt64('MIEmonth')} AS miemonth,
    ${databuffet.castInt64('MIEyear')} AS mieyear,
    ${databuffet.cleanString('MIEtype')} AS mietype,
    ${databuffet.cleanString('MIEvnos')} AS mievnos,
    ${databuffet.cleanString('MIEcus')} AS miecus,
    ${databuffet.castFloat64('MIErecDT3')} AS mierecdt3,
    ${databuffet.castFloat64('MIErecDT53')} AS mierecdt53,
    ${databuffet.castFloat64('MIErecDRND')} AS mierecdrnd,
    ${databuffet.castFloat64('MIErecDEXG')} AS mierecdexg,
    ${databuffet.castFloat64('MIErecDCSH')} AS mierecdcsh,
    ${databuffet.castFloat64('MIErecDOTH')} AS mierecdoth,
    ${databuffet.castFloat64('MIErecPLUS')} AS mierecplus,
    ${databuffet.castFloat64('MIErecCASH')} AS miereccash,
    ${databuffet.castFloat64('MIErecCQRD')} AS miereccqrd,
    ${databuffet.cleanString('MIEctermCX')} AS miectermcx,
    ${databuffet.cleanString('MIEctermPX')} AS miectermpx,
    ${databuffet.cleanString('MIEctermAX')} AS miectermax,
    ${databuffet.cleanString('MIEctermDX')} AS miectermdx,
    ${databuffet.castInt64('MIEtag')} AS mietag,
    ${databuffet.castFloat64('MIEbaseDT3')} AS miebasedt3,
    ${databuffet.castFloat64('MIEbaseDT53')} AS miebasedt53,
    ${databuffet.cleanString('MIEdescDT3')} AS miedescdt3,
    ${databuffet.cleanString('MIEdescDT53')} AS miedescdt53,
    ${databuffet.castInt64('MIEconDT3')} AS miecondt3,
    ${databuffet.castInt64('MIEconDT53')} AS miecondt53,
    ${databuffet.cleanString('MIErecFC')} AS mierecfc,
    ${databuffet.castFloat64('MIErecDT32')} AS mierecdt32,
    ${databuffet.castFloat64('MIErecDT532')} AS mierecdt532,
    ${databuffet.castFloat64('MIEbaseDT32')} AS miebasedt32,
    ${databuffet.castFloat64('MIEbaseDT532')} AS miebasedt532,
    ${databuffet.cleanString('MIEdescDT32')} AS miedescdt32,
    ${databuffet.cleanString('MIEdescDT532')} AS miedescdt532,
    ${databuffet.castInt64('MIEconDT32')} AS miecondt32,
    ${databuffet.castInt64('MIEconDT532')} AS miecondt532,
    ${databuffet.castFloat64('MIEperDT3')} AS mieperdt3,
    ${databuffet.castFloat64('MIEperDT32')} AS mieperdt32,
    ${databuffet.castFloat64('MIEperDT53')} AS mieperdt53,
    ${databuffet.castFloat64('MIEperDT532')} AS mieperdt532,
    ${databuffet.cleanString('MIEtaxpayNo')} AS mietaxpayno,
    ${databuffet.parseAsatDate()} AS asatdate
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.mie`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL
  SELECT 'aa05' AS company_id,
    ${databuffet.castInt64('MIEday')} AS mieday,
    ${databuffet.castInt64('MIEmonth')} AS miemonth,
    ${databuffet.castInt64('MIEyear')} AS mieyear,
    ${databuffet.cleanString('MIEtype')} AS mietype,
    ${databuffet.cleanString('MIEvnos')} AS mievnos,
    ${databuffet.cleanString('MIEcus')} AS miecus,
    ${databuffet.castFloat64('MIErecDT3')} AS mierecdt3,
    ${databuffet.castFloat64('MIErecDT53')} AS mierecdt53,
    ${databuffet.castFloat64('MIErecDRND')} AS mierecdrnd,
    ${databuffet.castFloat64('MIErecDEXG')} AS mierecdexg,
    ${databuffet.castFloat64('MIErecDCSH')} AS mierecdcsh,
    ${databuffet.castFloat64('MIErecDOTH')} AS mierecdoth,
    ${databuffet.castFloat64('MIErecPLUS')} AS mierecplus,
    ${databuffet.castFloat64('MIErecCASH')} AS miereccash,
    ${databuffet.castFloat64('MIErecCQRD')} AS miereccqrd,
    ${databuffet.cleanString('MIEctermCX')} AS miectermcx,
    ${databuffet.cleanString('MIEctermPX')} AS miectermpx,
    ${databuffet.cleanString('MIEctermAX')} AS miectermax,
    ${databuffet.cleanString('MIEctermDX')} AS miectermdx,
    ${databuffet.castInt64('MIEtag')} AS mietag,
    ${databuffet.castFloat64('MIEbaseDT3')} AS miebasedt3,
    ${databuffet.castFloat64('MIEbaseDT53')} AS miebasedt53,
    ${databuffet.cleanString('MIEdescDT3')} AS miedescdt3,
    ${databuffet.cleanString('MIEdescDT53')} AS miedescdt53,
    ${databuffet.castInt64('MIEconDT3')} AS miecondt3,
    ${databuffet.castInt64('MIEconDT53')} AS miecondt53,
    ${databuffet.cleanString('MIErecFC')} AS mierecfc,
    ${databuffet.castFloat64('MIErecDT32')} AS mierecdt32,
    ${databuffet.castFloat64('MIErecDT532')} AS mierecdt532,
    ${databuffet.castFloat64('MIEbaseDT32')} AS miebasedt32,
    ${databuffet.castFloat64('MIEbaseDT532')} AS miebasedt532,
    ${databuffet.cleanString('MIEdescDT32')} AS miedescdt32,
    ${databuffet.cleanString('MIEdescDT532')} AS miedescdt532,
    ${databuffet.castInt64('MIEconDT32')} AS miecondt32,
    ${databuffet.castInt64('MIEconDT532')} AS miecondt532,
    ${databuffet.castFloat64('MIEperDT3')} AS mieperdt3,
    ${databuffet.castFloat64('MIEperDT32')} AS mieperdt32,
    ${databuffet.castFloat64('MIEperDT53')} AS mieperdt53,
    ${databuffet.castFloat64('MIEperDT532')} AS mieperdt532,
    ${databuffet.cleanString('MIEtaxpayNo')} AS mietaxpayno,
    ${databuffet.parseAsatDate()} AS asatdate
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.mie`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL
  SELECT 'ab01' AS company_id,
    ${databuffet.castInt64('MIEday')} AS mieday,
    ${databuffet.castInt64('MIEmonth')} AS miemonth,
    ${databuffet.castInt64('MIEyear')} AS mieyear,
    ${databuffet.cleanString('MIEtype')} AS mietype,
    ${databuffet.cleanString('MIEvnos')} AS mievnos,
    ${databuffet.cleanString('MIEcus')} AS miecus,
    ${databuffet.castFloat64('MIErecDT3')} AS mierecdt3,
    ${databuffet.castFloat64('MIErecDT53')} AS mierecdt53,
    ${databuffet.castFloat64('MIErecDRND')} AS mierecdrnd,
    ${databuffet.castFloat64('MIErecDEXG')} AS mierecdexg,
    ${databuffet.castFloat64('MIErecDCSH')} AS mierecdcsh,
    ${databuffet.castFloat64('MIErecDOTH')} AS mierecdoth,
    ${databuffet.castFloat64('MIErecPLUS')} AS mierecplus,
    ${databuffet.castFloat64('MIErecCASH')} AS miereccash,
    ${databuffet.castFloat64('MIErecCQRD')} AS miereccqrd,
    ${databuffet.cleanString('MIEctermCX')} AS miectermcx,
    ${databuffet.cleanString('MIEctermPX')} AS miectermpx,
    ${databuffet.cleanString('MIEctermAX')} AS miectermax,
    ${databuffet.cleanString('MIEctermDX')} AS miectermdx,
    ${databuffet.castInt64('MIEtag')} AS mietag,
    ${databuffet.castFloat64('MIEbaseDT3')} AS miebasedt3,
    ${databuffet.castFloat64('MIEbaseDT53')} AS miebasedt53,
    ${databuffet.cleanString('MIEdescDT3')} AS miedescdt3,
    ${databuffet.cleanString('MIEdescDT53')} AS miedescdt53,
    ${databuffet.castInt64('MIEconDT3')} AS miecondt3,
    ${databuffet.castInt64('MIEconDT53')} AS miecondt53,
    ${databuffet.cleanString('MIErecFC')} AS mierecfc,
    ${databuffet.castFloat64('MIErecDT32')} AS mierecdt32,
    ${databuffet.castFloat64('MIErecDT532')} AS mierecdt532,
    ${databuffet.castFloat64('MIEbaseDT32')} AS miebasedt32,
    ${databuffet.castFloat64('MIEbaseDT532')} AS miebasedt532,
    ${databuffet.cleanString('MIEdescDT32')} AS miedescdt32,
    ${databuffet.cleanString('MIEdescDT532')} AS miedescdt532,
    ${databuffet.castInt64('MIEconDT32')} AS miecondt32,
    ${databuffet.castInt64('MIEconDT532')} AS miecondt532,
    ${databuffet.castFloat64('MIEperDT3')} AS mieperdt3,
    ${databuffet.castFloat64('MIEperDT32')} AS mieperdt32,
    ${databuffet.castFloat64('MIEperDT53')} AS mieperdt53,
    ${databuffet.castFloat64('MIEperDT532')} AS mieperdt532,
    ${databuffet.cleanString('MIEtaxpayNo')} AS mietaxpayno,
    ${databuffet.parseAsatDate()} AS asatdate
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mie`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL
  SELECT 'ac02' AS company_id,
    ${databuffet.castInt64('MIEday')} AS mieday,
    ${databuffet.castInt64('MIEmonth')} AS miemonth,
    ${databuffet.castInt64('MIEyear')} AS mieyear,
    ${databuffet.cleanString('MIEtype')} AS mietype,
    ${databuffet.cleanString('MIEvnos')} AS mievnos,
    ${databuffet.cleanString('MIEcus')} AS miecus,
    ${databuffet.castFloat64('MIErecDT3')} AS mierecdt3,
    ${databuffet.castFloat64('MIErecDT53')} AS mierecdt53,
    ${databuffet.castFloat64('MIErecDRND')} AS mierecdrnd,
    ${databuffet.castFloat64('MIErecDEXG')} AS mierecdexg,
    ${databuffet.castFloat64('MIErecDCSH')} AS mierecdcsh,
    ${databuffet.castFloat64('MIErecDOTH')} AS mierecdoth,
    ${databuffet.castFloat64('MIErecPLUS')} AS mierecplus,
    ${databuffet.castFloat64('MIErecCASH')} AS miereccash,
    ${databuffet.castFloat64('MIErecCQRD')} AS miereccqrd,
    ${databuffet.cleanString('MIEctermCX')} AS miectermcx,
    ${databuffet.cleanString('MIEctermPX')} AS miectermpx,
    ${databuffet.cleanString('MIEctermAX')} AS miectermax,
    ${databuffet.cleanString('MIEctermDX')} AS miectermdx,
    ${databuffet.castInt64('MIEtag')} AS mietag,
    ${databuffet.castFloat64('MIEbaseDT3')} AS miebasedt3,
    ${databuffet.castFloat64('MIEbaseDT53')} AS miebasedt53,
    ${databuffet.cleanString('MIEdescDT3')} AS miedescdt3,
    ${databuffet.cleanString('MIEdescDT53')} AS miedescdt53,
    ${databuffet.castInt64('MIEconDT3')} AS miecondt3,
    ${databuffet.castInt64('MIEconDT53')} AS miecondt53,
    ${databuffet.cleanString('MIErecFC')} AS mierecfc,
    ${databuffet.castFloat64('MIErecDT32')} AS mierecdt32,
    ${databuffet.castFloat64('MIErecDT532')} AS mierecdt532,
    ${databuffet.castFloat64('MIEbaseDT32')} AS miebasedt32,
    ${databuffet.castFloat64('MIEbaseDT532')} AS miebasedt532,
    ${databuffet.cleanString('MIEdescDT32')} AS miedescdt32,
    ${databuffet.cleanString('MIEdescDT532')} AS miedescdt532,
    ${databuffet.castInt64('MIEconDT32')} AS miecondt32,
    ${databuffet.castInt64('MIEconDT532')} AS miecondt532,
    ${databuffet.castFloat64('MIEperDT3')} AS mieperdt3,
    ${databuffet.castFloat64('MIEperDT32')} AS mieperdt32,
    ${databuffet.castFloat64('MIEperDT53')} AS mieperdt53,
    ${databuffet.castFloat64('MIEperDT532')} AS mieperdt532,
    ${databuffet.cleanString('MIEtaxpayNo')} AS mietaxpayno,
    ${databuffet.parseAsatDate()} AS asatdate
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.mie`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }
  
  UNION ALL
  SELECT 'ak02' AS company_id,
    ${databuffet.castInt64('MIEday')} AS mieday,
    ${databuffet.castInt64('MIEmonth')} AS miemonth,
    ${databuffet.castInt64('MIEyear')} AS mieyear,
    ${databuffet.cleanString('MIEtype')} AS mietype,
    ${databuffet.cleanString('MIEvnos')} AS mievnos,
    ${databuffet.cleanString('MIEcus')} AS miecus,
    ${databuffet.castFloat64('MIErecDT3')} AS mierecdt3,
    ${databuffet.castFloat64('MIErecDT53')} AS mierecdt53,
    ${databuffet.castFloat64('MIErecDRND')} AS mierecdrnd,
    ${databuffet.castFloat64('MIErecDEXG')} AS mierecdexg,
    ${databuffet.castFloat64('MIErecDCSH')} AS mierecdcsh,
    ${databuffet.castFloat64('MIErecDOTH')} AS mierecdoth,
    ${databuffet.castFloat64('MIErecPLUS')} AS mierecplus,
    ${databuffet.castFloat64('MIErecCASH')} AS miereccash,
    ${databuffet.castFloat64('MIErecCQRD')} AS miereccqrd,
    ${databuffet.cleanString('MIEctermCX')} AS miectermcx,
    ${databuffet.cleanString('MIEctermPX')} AS miectermpx,
    ${databuffet.cleanString('MIEctermAX')} AS miectermax,
    ${databuffet.cleanString('MIEctermDX')} AS miectermdx,
    ${databuffet.castInt64('MIEtag')} AS mietag,
    ${databuffet.castFloat64('MIEbaseDT3')} AS miebasedt3,
    ${databuffet.castFloat64('MIEbaseDT53')} AS miebasedt53,
    ${databuffet.cleanString('MIEdescDT3')} AS miedescdt3,
    ${databuffet.cleanString('MIEdescDT53')} AS miedescdt53,
    ${databuffet.castInt64('MIEconDT3')} AS miecondt3,
    ${databuffet.castInt64('MIEconDT53')} AS miecondt53,
    ${databuffet.cleanString('MIErecFC')} AS mierecfc,
    ${databuffet.castFloat64('MIErecDT32')} AS mierecdt32,
    ${databuffet.castFloat64('MIErecDT532')} AS mierecdt532,
    ${databuffet.castFloat64('MIEbaseDT32')} AS miebasedt32,
    ${databuffet.castFloat64('MIEbaseDT532')} AS miebasedt532,
    ${databuffet.cleanString('MIEdescDT32')} AS miedescdt32,
    ${databuffet.cleanString('MIEdescDT532')} AS miedescdt532,
    ${databuffet.castInt64('MIEconDT32')} AS miecondt32,
    ${databuffet.castInt64('MIEconDT532')} AS miecondt532,
    ${databuffet.castFloat64('MIEperDT3')} AS mieperdt3,
    ${databuffet.castFloat64('MIEperDT32')} AS mieperdt32,
    ${databuffet.castFloat64('MIEperDT53')} AS mieperdt53,
    ${databuffet.castFloat64('MIEperDT532')} AS mieperdt532,
    ${databuffet.cleanString('MIEtaxpayNo')} AS mietaxpayno,
    ${databuffet.parseAsatDate()} AS asatdate
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.mie`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
