config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mih_billing"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mih_billing"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY mihkeydate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(mihday AS INT64) as mihday,
    CAST(mihmonth AS INT64) as mihmonth,
    CAST(mihyear AS INT64) as mihyear,
    NULLIF(CAST(TRIM(mihtype) AS STRING), '') as mihtype,
    NULLIF(CAST(TRIM(mihvnos) AS STRING), '') as mihvnos,
    NULLIF(CAST(TRIM(mihcus) AS STRING), '') as mihcus,
    NULLIF(CAST(TRIM(mihjob) AS STRING), '') as mihjob,
    NULLIF(CAST(TRIM(mihdep) AS STRING), '') as mihdep,
    NULLIF(CAST(TRIM(mihper) AS STRING), '') as mihper,
    NULLIF(CAST(TRIM(mihdoc) AS STRING), '') as mihdoc,
    NULLIF(CAST(TRIM(mihmec) AS STRING), '') as mihmec,
    NULLIF(CAST(TRIM(mihvatno) AS STRING), '') as mihvatno,
    NULLIF(CAST(TRIM(mihdesc) AS STRING), '') as mihdesc,
    NULLIF(CAST(TRIM(mihmemo) AS STRING), '') as mihmemo,
    NULLIF(CAST(TRIM(mihnotes) AS STRING), '') as mihnotes,
    NULLIF(CAST(TRIM(mihref1) AS STRING), '') as mihref1,
    NULLIF(CAST(TRIM(mihref2) AS STRING), '') as mihref2,
    NULLIF(CAST(TRIM(mihref3) AS STRING), '') as mihref3,
    NULLIF(CAST(TRIM(mihdischt1) AS STRING), '') as mihdischt1,
    NULLIF(CAST(TRIM(mihdischt2) AS STRING), '') as mihdischt2,
    NULLIF(CAST(TRIM(mihdelvsite) AS STRING), '') as mihdelvsite,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihdelvdate, 1, 19)) AS mihdelvdate,
    CAST(mihstanding AS INT64) as mihstanding,
    CAST(mihlinkgl AS INT64) as mihlinkgl,
    CAST(mihnouplink AS INT64) as mihnouplink,
    CAST(mihnolist AS INT64) as mihnolist,
    CAST(mihcurc AS INT64) as mihcurc,
    CAST(mihvatinlist AS INT64) as mihvatinlist,
    CAST(mihlock AS INT64) as mihlock,
    CAST(mihprintn AS INT64) as mihprintn,
    CAST(mihcheque AS INT64) as mihcheque,
    CAST(mihcancel AS INT64) as mihcancel,
    CAST(mihstatus AS INT64) as mihstatus,
    CAST(mihclearum AS INT64) as mihclearum,
    CAST(mihctermno AS INT64) as mihctermno,
    CAST(mihcog AS FLOAT64) as mihcog,
    CAST(mihvatsum AS FLOAT64) as mihvatsum,
    CAST(mihnetsum AS FLOAT64) as mihnetsum,
    CAST(mihdisclst AS FLOAT64) as mihdisclst,
    CAST(mihdischf1 AS FLOAT64) as mihdischf1,
    CAST(mihdischf2 AS FLOAT64) as mihdischf2,
    CAST(mihexchg AS FLOAT64) as mihexchg,
    CAST(mihextrasum AS FLOAT64) as mihextrasum,
    CAST(mihextravat AS FLOAT64) as mihextravat,
    CAST(mihextracut AS INT64) as mihextracut,
    NULLIF(CAST(TRIM(mihextramem) AS STRING), '') as mihextramem,
    NULLIF(CAST(TRIM(mihrecno) AS STRING), '') as mihrecno,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihrecdate, 1, 19)) AS mihrecdate,
    NULLIF(CAST(TRIM(mihsavetag) AS STRING), '') as mihsavetag,
    NULLIF(CAST(TRIM(mihkeyuser) AS STRING), '') as mihkeyuser,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihkeydate, 1, 19)) AS mihkeydate,
    NULLIF(CAST(TRIM(mihdocrunno) AS STRING), '') as mihdocrunno,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihdategl, 1, 19)) AS mihdategl,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihduepo, 1, 19)) AS mihduepo,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(miheditlk, 1, 19)) AS miheditlk,
    CAST(mihiscf AS INT64) as mihiscf,
    CAST(mihissp AS INT64) as mihissp,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihdates1, 1, 19)) AS mihdates1,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihdates2, 1, 19)) AS mihdates2,
    CAST(mihnumsi AS INT64) as mihnumsi,
    CAST(mihnumsc AS FLOAT64) as mihnumsc,
    CAST(mihvatpc AS FLOAT64) as mihvatpc,
    CAST(mihincluded AS INT64) as mihincluded,
    NULLIF(CAST(TRIM(mihtaxvnos) AS STRING), '') as mihtaxvnos,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihtaxdate, 1, 19)) AS mihtaxdate,
    CAST(mihtaxsum AS FLOAT64) as mihtaxsum,
    CAST(mihload AS INT64) as mihload,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihpaiddate, 1, 19)) AS mihpaiddate,
    NULLIF(CAST(TRIM(mihbookordernum) AS STRING), '') as mihbookordernum,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mihsenddate, 1, 19)) AS mihsenddate,
    CAST(mihbl AS INT64) as mihbl,
    CAST(mihrpv AS INT64) as mihrpv,
    CAST(mihclearcut AS INT64) as mihclearcut,
    CAST(mihsettlecut AS INT64) as mihsettlecut,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid,
    NULLIF(CAST(TRIM(mihdebbranch) AS STRING), '') as mihdebbranch,
    NULLIF(CAST(TRIM(mihdebtaxnos) AS STRING), '') as mihdebtaxnos

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
