config {
    type: "incremental",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["MIHday","MIHmonth","MIHyear","MIHtype","MIHvnos","MIHcus"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["mihtype", "mihvnos", "mihcus"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["MIHday","MIHmonth","MIHyear","MIHtype","MIHvnos","MIHcus"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(MIHday AS INT64) AS mihday,
  CAST(MIHmonth AS INT64) AS mihmonth,
  CAST(MIHyear AS INT64) AS mihyear,
  NULLIF(CAST(TRIM(MIHtype) AS STRING), '') AS mihtype,
  NULLIF(CAST(TRIM(MIHvnos) AS STRING), '') AS mihvnos,
  NULLIF(CAST(TRIM(MIHcus) AS STRING), '') AS mihcus,
  NULLIF(CAST(TRIM(MIHjob) AS STRING), '') AS mihjob,
  NULLIF(CAST(TRIM(MIHdep) AS STRING), '') AS mihdep,
  NULLIF(CAST(TRIM(MIHper) AS STRING), '') AS mihper,
  NULLIF(CAST(TRIM(MIHdoc) AS STRING), '') AS mihdoc,
  NULLIF(CAST(TRIM(MIHmec) AS STRING), '') AS mihmec,
  NULLIF(CAST(TRIM(MIHvatNO) AS STRING), '') AS mihvatno,
  NULLIF(CAST(TRIM(MIHdesc) AS STRING), '') AS mihdesc,
  NULLIF(CAST(TRIM(MIHmemo) AS STRING), '') AS mihmemo,
  NULLIF(CAST(TRIM(MIHnotes) AS STRING), '') AS mihnotes,
  NULLIF(CAST(TRIM(MIHref1) AS STRING), '') AS mihref1,
  NULLIF(CAST(TRIM(MIHref2) AS STRING), '') AS mihref2,
  NULLIF(CAST(TRIM(MIHref3) AS STRING), '') AS mihref3,
  NULLIF(CAST(TRIM(MIHdiscHT1) AS STRING), '') AS mihdischt1,
  NULLIF(CAST(TRIM(MIHdiscHT2) AS STRING), '') AS mihdischt2,
  NULLIF(CAST(TRIM(MIHdelvSite) AS STRING), '') AS mihdelvsite,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHdelvDate, 1, 19)) AS mihdelvdate,
  CAST(MIHstanding AS INT64) AS mihstanding,
  CAST(MIHlinkGL AS INT64) AS mihlinkgl,
  CAST(MIHnoUPLINK AS INT64) AS mihnouplink,
  CAST(MIHnolist AS INT64) AS mihnolist,
  CAST(MIHcurC AS INT64) AS mihcurc,
  CAST(MIHvatInList AS INT64) AS mihvatinlist,
  CAST(MIHlock AS INT64) AS mihlock,
  CAST(MIHprintN AS INT64) AS mihprintn,
  CAST(MIHcheque AS INT64) AS mihcheque,
  CAST(MIHcancel AS INT64) AS mihcancel,
  CAST(MIHstatus AS INT64) AS mihstatus,
  CAST(MIHclearUM AS INT64) AS mihclearum,
  CAST(MIHctermNO AS INT64) AS mihctermno,
  CAST(MIHcog AS FLOAT64) AS mihcog,
  CAST(MIHvatSUM AS FLOAT64) AS mihvatsum,
  CAST(MIHnetSUM AS FLOAT64) AS mihnetsum,
  CAST(MIHdiscLST AS FLOAT64) AS mihdisclst,
  CAST(MIHdiscHF1 AS FLOAT64) AS mihdischf1,
  CAST(MIHdiscHF2 AS FLOAT64) AS mihdischf2,
  CAST(MIHexchg AS FLOAT64) AS mihexchg,
  CAST(MIHextraSUM AS FLOAT64) AS mihextrasum,
  CAST(MIHextraVAT AS FLOAT64) AS mihextravat,
  CAST(MIHextraCUT AS INT64) AS mihextracut,
  NULLIF(CAST(TRIM(MIHextraMEM) AS STRING), '') AS mihextramem,
  NULLIF(CAST(TRIM(MIHrecNO) AS STRING), '') AS mihrecno,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHrecDATE, 1, 19)) AS mihrecdate,
  NULLIF(CAST(TRIM(MIHsaveTAG) AS STRING), '') AS mihsavetag,
  NULLIF(CAST(TRIM(MIHkeyUser) AS STRING), '') AS mihkeyuser,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHkeyDate, 1, 19)) AS mihkeydate,
  NULLIF(CAST(TRIM(MIHdocRunNo) AS STRING), '') AS mihdocrunno,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHdateGL, 1, 19)) AS mihdategl,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHduePO, 1, 19)) AS mihduepo,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHeditLK, 1, 19)) AS miheditlk,
  CAST(MIHisCF AS INT64) AS mihiscf,
  CAST(MIHisSP AS INT64) AS mihissp,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHdateS1, 1, 19)) AS mihdates1,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHdateS2, 1, 19)) AS mihdates2,
  CAST(MIHnumSI AS INT64) AS mihnumsi,
  CAST(MIHnumSC AS FLOAT64) AS mihnumsc,
  CAST(MIHvatPC AS FLOAT64) AS mihvatpc,
  CAST(MIHincluded AS INT64) AS mihincluded,
  NULLIF(CAST(TRIM(MIHtaxvnos) AS STRING), '') AS mihtaxvnos,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHtaxdate, 1, 19)) AS mihtaxdate,
  CAST(MIHtaxsum AS FLOAT64) AS mihtaxsum,
  CAST(MIHload AS INT64) AS mihload,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHpaidDate, 1, 19)) AS mihpaiddate,
  NULLIF(CAST(TRIM(MIHbookOrderNum) AS STRING), '') AS mihbookordernum,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MIHsendDate, 1, 19)) AS mihsenddate,
  CAST(MIHbl AS INT64) AS mihbl,
  CAST(MIHrpv AS INT64) AS mihrpv,
  CAST(MIHclearCUT AS INT64) AS mihclearcut,
  CAST(MIHsettleCUT AS INT64) AS mihsettlecut,
  NULLIF(CAST(TRIM(rowguid) AS STRING), '') AS rowguid,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${sourceTableRef}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
