config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mil"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["mil"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  CAST(MILday AS INT64) AS milday,
  CAST(MILmonth AS INT64) AS milmonth,
  CAST(MILyear AS INT64) AS milyear,
  CAST(TRIM(MILtype) AS STRING) AS miltype,
  CAST(TRIM(MILvnos) AS STRING) AS milvnos,
  CAST(TRIM(MILcus) AS STRING) AS milcus,
  CAST(TRIM(MILstk) AS STRING) AS milstk,
  CAST(TRIM(MILjob) AS STRING) AS miljob,
  CAST(TRIM(MILdep) AS STRING) AS mildep,
  CAST(TRIM(MILper) AS STRING) AS milper,
  CAST(TRIM(MILdoc) AS STRING) AS mildoc,
  CAST(TRIM(MILmec) AS STRING) AS milmec,
  CAST(TRIM(MILsto) AS STRING) AS milsto,
  CAST(TRIM(MILstoMT) AS STRING) AS milstomt,
  CAST(MILlistNo AS INT64) AS millistno,

  (CASE 
    WHEN LEFT(CAST(TRIM(MILvnos) AS STRING), 2) = 'CN' THEN CAST(MILquan AS FLOAT64) * -1
    ELSE CAST(MILquan AS FLOAT64) 
  END) AS milquan,
  CAST(MILquan AS FLOAT64) AS milquan_raw,

  CAST(MILquanP2 AS FLOAT64) AS milquanp2,

  (CASE 
    WHEN LEFT(CAST(TRIM(MILvnos) AS STRING), 2) = 'CN' THEN CAST(MILadisc AS FLOAT64) * -1
    ELSE CAST(MILadisc AS FLOAT64)
  END) AS miladisc,
  CAST(MILadisc AS FLOAT64) AS miladisc_raw,

  (CASE 
    WHEN LEFT(CAST(TRIM(MILvnos) AS STRING), 2) = 'CN' THEN CAST(MILcog AS FLOAT64) * -1
    ELSE CAST(MILcog AS FLOAT64)
  END) AS milcog,
  CAST(MILcog AS FLOAT64) AS milcog_raw,
  
  CAST(MILconv AS FLOAT64) AS milconv,

  (CASE 
    WHEN LEFT(CAST(TRIM(MILvnos) AS STRING), 2) = 'CN' THEN CAST(MILdiscA AS FLOAT64) * -1
    ELSE CAST(MILdiscA AS FLOAT64)
  END) AS mildisca,
  CAST(MILdiscA AS FLOAT64) AS mildisca_raw,

  CAST(TRIM(MILdiscT) AS STRING) AS mildisct,
  (CASE 
    WHEN LEFT(CAST(TRIM(MILvnos) AS STRING), 2) = 'CN' THEN CAST(MILvat AS FLOAT64) * -1
    ELSE CAST(MILvat AS FLOAT64)
  END) AS milvat,
  CAST(MILvat AS FLOAT64) AS milvat_raw,

  (CASE 
    WHEN LEFT(CAST(TRIM(MILvnos) AS STRING), 2) = 'CN' THEN CAST(MILsum AS FLOAT64) * -1
    ELSE CAST(MILsum AS FLOAT64)
  END) AS milsum,
  CAST(MILsum AS FLOAT64) AS milsum_raw,

  CAST(MILcut AS INT64) AS milcut,
  CAST(MILstype AS INT64) AS milstype,
  CAST(TRIM(MILuname) AS STRING) AS miluname,
  CAST(TRIM(MILdesc) AS STRING) AS mildesc,
  CAST(TRIM(MILvCol1) AS STRING) AS milvcol1,
  CAST(TRIM(MILvCol2) AS STRING) AS milvcol2,
  CAST(TRIM(MILvCol3) AS STRING) AS milvcol3,
  CAST(TRIM(MILvCol4) AS STRING) AS milvcol4,
  CAST(MILcurC AS INT64) AS milcurc,
  CAST(MILexchg AS FLOAT64) AS milexchg,
  CAST(MILacost AS FLOAT64) AS milacost,
  CAST(MILpqm AS INT64) AS milpqm,
  CAST(MILpmFrom AS INT64) AS milpmfrom,
  CAST(MILpmTo AS INT64) AS milpmto,
  CAST(MILtag AS INT64) AS miltag,
  CAST(TRIM(MILlinkVCno) AS STRING) AS millinkvcno,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILlinkVCdate, 1, 19)) AS millinkvcdate,
  CAST(TRIM(MILlinkVCtype) AS STRING) AS millinkvctype,
  CAST(TRIM(MILlinkVCdeposit) AS STRING) AS millinkvcdeposit,
  CAST(MILlinkVCid AS INT64) AS millinkvcid,
  CAST(MILclearUM AS INT64) AS milclearum,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILexpDATE, 1, 19)) AS milexpdate,
  CAST(TRIM(MILnotes) AS STRING) AS milnotes,
  CAST(MILnotKL AS INT64) AS milnotkl,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILdelvDT, 1, 19)) AS mildelvdt,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILdateSP, 1, 19)) AS mildatesp,
  CAST(MILnumCSP AS FLOAT64) AS milnumcsp,
  CAST(MILnumISP AS INT64) AS milnumisp,
  CAST(MILcost AS FLOAT64) AS milcost,
  CAST(MILucost AS FLOAT64) AS milucost,
  CAST(MILuprice AS FLOAT64) AS miluprice,
  CAST(MILuseQuanP AS INT64) AS milusequanp,
  CAST(TRIM(MILvCol5) AS STRING) AS milvcol5,
  CAST(MILfitem AS INT64) AS milfitem,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
