config {
    type: "incremental",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5", "create_all_table_raw_mac5_aa05", "create_all_table_raw_mac5_ab01", "create_all_table_raw_mac5_ac02", "create_all_table_raw_mac5_ak02", "mih"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["company_id", "MILtype","MILvnos","MILlistNo"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["company_id", "miltype", "milvnos"]
    },
}

js {
    const pk_key = ["company_id", "MILtype","MILvnos","MILlistNo"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH cte_mil as (
  SELECT 'ag01' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'aa05' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'ab01' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'ac02' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'ak02' AS company_id,
    milday, milmonth, milyear, miltype, milvnos, milcus, milstk,
    miljob, mildep, milper, mildoc, milmec,
    milsto, milstomt, millistno, milquan, milquanp2, miladisc, milcog, milconv,
    mildisca, mildisct, milvat, milsum, milcut, milstype, miluname, mildesc,
    milvcol1, milvcol2, milvcol3, milvcol4,
    milcurc, milexchg, milacost, milpqm, milpmfrom, milpmto, miltag,
    millinkvcno, millinkvcdate, millinkvctype, millinkvcdeposit, millinkvcid,
    milclearum, milexpdate, milnotes, milnotkl, mildelvdt, mildatesp,
    milnumcsp, milnumisp, milcost, milucost, miluprice, milusequanp,
    milvcol5, milfitem, ASATDATE
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

), cte_mih as (
  select
    t1.company_id,
    t1.mihyear,
    t1.mihmonth,
    t1.mihday,
    t1.mihtype,
    t1.mihvnos,
    t1.mihcus,
    t1.mihdischf1

  from ${ref("mih")} as t1
  inner join (
    select distinct company_id, milyear, milmonth, milday, miltype, milvnos, milcus
    from cte_mil
  ) as t2
    on t1.company_id = t2.company_id
    and t1.mihyear = t2.milyear
    and t1.mihmonth = t2.milmonth
    and t1.mihday = t2.milday
    and t1.mihtype = t2.miltype
    and t1.mihvnos = t2.milvnos
    and t1.mihcus = t2.milcus

)
SELECT
  mil.company_id,
  ${databuffet.functionData.castInt64('MILday')} AS milday,
  ${databuffet.functionData.castInt64('MILmonth')} AS milmonth,
  ${databuffet.functionData.castInt64('MILyear')} AS milyear,
  ${databuffet.functionData.cleanString('MILtype')} AS miltype,
  ${databuffet.functionData.cleanString('MILvnos')} AS milvnos,
  ${databuffet.functionData.cleanString('MILcus')} AS milcus,
  ${databuffet.functionData.cleanCode('MILstk')} AS milstk,
  ${databuffet.functionData.cleanString('MILjob')} AS miljob,
  ${databuffet.functionData.cleanString('MILdep')} AS mildep,
  ${databuffet.functionData.cleanString('MILper')} AS milper,
  ${databuffet.functionData.cleanString('MILdoc')} AS mildoc,
  ${databuffet.functionData.cleanString('MILmec')} AS milmec,
  ${databuffet.functionData.cleanString('MILsto')} AS milsto,
  ${databuffet.functionData.cleanString('MILstoMT')} AS milstomt,
  ${databuffet.functionData.castInt64('MILlistNo')} AS millistno,

  (CASE
    WHEN ${databuffet.functionData.cleanString('MILtype')} = 'BS' THEN ${databuffet.functionData.castFloat64('MILquan')} * -1
    ELSE ${databuffet.functionData.castFloat64('MILquan')}
  END) AS milquan,
  ${databuffet.functionData.castFloat64('MILquan')} AS milquan_raw,

  ${databuffet.functionData.castFloat64('MILquanP2')} AS milquanp2,

  (CASE
    WHEN ${databuffet.functionData.cleanString('MILtype')} = 'BS' THEN ${databuffet.functionData.castFloat64('MILadisc')} * -1
    ELSE ${databuffet.functionData.castFloat64('MILadisc')}
  END) AS miladisc,
  ${databuffet.functionData.castFloat64('MILadisc')} AS miladisc_raw,

  (CASE
    WHEN ${databuffet.functionData.cleanString('MILtype')} = 'BS' THEN ${databuffet.functionData.castFloat64('MILcog')} * -1
    ELSE ${databuffet.functionData.castFloat64('MILcog')}
  END) AS milcog,
  ${databuffet.functionData.castFloat64('MILcog')} AS milcog_raw,

  ${databuffet.functionData.castFloat64('MILconv')} AS milconv,

  (CASE
    WHEN ${databuffet.functionData.cleanString('MILtype')} = 'BS' THEN ${databuffet.functionData.castFloat64('MILdiscA')} * -1
    ELSE ${databuffet.functionData.castFloat64('MILdiscA')}
  END) AS mildisca,
  ${databuffet.functionData.castFloat64('MILdiscA')} AS mildisca_raw,

  ${databuffet.functionData.cleanString('MILdiscT')} AS mildisct,
  (CASE
    WHEN ${databuffet.functionData.cleanString('MILtype')} = 'BS' THEN ${databuffet.functionData.castFloat64('MILvat')} * -1
    ELSE ${databuffet.functionData.castFloat64('MILvat')}
  END) AS milvat,
  ${databuffet.functionData.castFloat64('MILvat')} AS milvat_raw,

  (CASE
    WHEN ${databuffet.functionData.cleanString('MILtype')} = 'BS' THEN CAST(IF( (MILsum - (mihdischf1*-1)) < 0, 0, CAST((MILsum - MILadisc) AS FLOAT64)) * -1 AS FLOAT64)
    ELSE CAST((MILsum - MILadisc) AS FLOAT64)
  END) AS milsum,
  ${databuffet.functionData.castFloat64('MILsum')} AS milsum_raw,

  ${databuffet.functionData.castInt64('MILcut')} AS milcut,
  ${databuffet.functionData.castInt64('MILstype')} AS milstype,
  ${databuffet.functionData.cleanString('MILuname')} AS miluname,
  ${databuffet.functionData.cleanString('MILdesc')} AS mildesc,
  ${databuffet.functionData.cleanString('MILvCol1')} AS milvcol1,
  ${databuffet.functionData.cleanString('MILvCol2')} AS milvcol2,
  ${databuffet.functionData.cleanString('MILvCol3')} AS milvcol3,
  ${databuffet.functionData.cleanString('MILvCol4')} AS milvcol4,
  ${databuffet.functionData.castInt64('MILcurC')} AS milcurc,
  ${databuffet.functionData.castFloat64('MILexchg')} AS milexchg,
  ${databuffet.functionData.castFloat64('MILacost')} AS milacost,
  ${databuffet.functionData.castInt64('MILpqm')} AS milpqm,
  ${databuffet.functionData.castInt64('MILpmFrom')} AS milpmfrom,
  ${databuffet.functionData.castInt64('MILpmTo')} AS milpmto,
  ${databuffet.functionData.castInt64('MILtag')} AS miltag,
  ${databuffet.functionData.cleanString('MILlinkVCno')} AS millinkvcno,
  ${databuffet.functionData.parseFlexibleDatetime('MILlinkVCdate')} AS millinkvcdate,
  ${databuffet.functionData.cleanString('MILlinkVCtype')} AS millinkvctype,
  ${databuffet.functionData.cleanString('MILlinkVCdeposit')} AS millinkvcdeposit,
  ${databuffet.functionData.castInt64('MILlinkVCid')} AS millinkvcid,
  ${databuffet.functionData.castInt64('MILclearUM')} AS milclearum,
  ${databuffet.functionData.parseFlexibleDatetime('MILexpDATE')} AS milexpdate,
  ${databuffet.functionData.cleanString('MILnotes')} AS milnotes,
  ${databuffet.functionData.castInt64('MILnotKL')} AS milnotkl,
  ${databuffet.functionData.parseFlexibleDatetime('MILdelvDT')} AS mildelvdt,
  ${databuffet.functionData.parseFlexibleDatetime('MILdateSP')} AS mildatesp,
  ${databuffet.functionData.castFloat64('MILnumCSP')} AS milnumcsp,
  ${databuffet.functionData.castInt64('MILnumISP')} AS milnumisp,
  ${databuffet.functionData.castFloat64('MILcost')} AS milcost,
  ${databuffet.functionData.castFloat64('MILucost')} AS milucost,
  ${databuffet.functionData.castFloat64('MILuprice')} AS miluprice,
  ${databuffet.functionData.castInt64('MILuseQuanP')} AS milusequanp,
  ${databuffet.functionData.cleanString('MILvCol5')} AS milvcol5,
  ${databuffet.functionData.castInt64('MILfitem')} AS milfitem,
  ${databuffet.functionData.parseAsatDate()} AS asatdate
FROM cte_mil as mil
LEFT JOIN cte_mih as mih
  on mil.company_id = mih.company_id
  and mil.milyear = mih.mihyear
  and mil.milmonth = mih.mihmonth
  and mil.milday = mih.mihday
  and mil.miltype = mih.mihtype
  and mil.milvnos = mih.mihvnos
  and mil.milcus = mih.mihcus
WHERE IFNULL(${databuffet.functionData.cleanString('MILvnos')}, '') != ''
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
