config {
    type: "incremental",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5", "create_all_table_raw_mac5_aa05", "create_all_table_raw_mac5_ab01", "create_all_table_raw_mac5_ac02", "create_all_table_raw_mac5_ak02", "mih"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["company_id", "MILtype","MILvnos","MILlistNo"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["company_id", "miltype", "milvnos"]
    },
}

js {
    const pk_key = ["company_id", "MILtype","MILvnos","MILlistNo"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY asatdate DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH cte_mil as (
  SELECT 'ag01' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'aa05' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'ab01' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'ac02' AS company_id, * FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

  UNION ALL

  SELECT 'ak02' AS company_id,
    milday, milmonth, milyear, miltype, milvnos, milcus, milstk,
    miljob, mildep, milper, mildoc, milmec,
    milsto, milstomt, millistno, milquan, milquanp2, miladisc, milcog, milconv,
    mildisca, mildisct, milvat, milsum, milcut, milstype, miluname, mildesc,
    milvcol1, milvcol2, milvcol3, milvcol4,
    milcurc, milexchg, milacost, milpqm, milpmfrom, milpmto, miltag,
    millinkvcno, millinkvcdate, millinkvctype, millinkvcdeposit, millinkvcid,
    milclearum, milexpdate, milnotes, milnotkl, mildelvdt, mildatesp,
    milnumcsp, milnumisp, milcost, milucost, miluprice, milusequanp,
    milvcol5, milfitem, ASATDATE
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.mil`
  ${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE('Asia/Bangkok')-1)`) }

), cte_mih as (
  select
    t1.company_id,
    t1.mihyear,
    t1.mihmonth,
    t1.mihday,
    t1.mihtype,
    t1.mihvnos,
    t1.mihcus,
    t1.mihdischf1

  from ${ref("mih")} as t1
  inner join (
    select distinct company_id, milyear, milmonth, milday, miltype, milvnos, milcus
    from cte_mil
  ) as t2
    on t1.company_id = t2.company_id
    and t1.mihyear = t2.milyear
    and t1.mihmonth = t2.milmonth
    and t1.mihday = t2.milday
    and t1.mihtype = t2.miltype
    and t1.mihvnos = t2.milvnos
    and t1.mihcus = t2.milcus

)
SELECT
  mil.company_id,
  CAST(MILday AS INT64) AS milday,
  CAST(MILmonth AS INT64) AS milmonth,
  CAST(MILyear AS INT64) AS milyear,
  NULLIF(CAST(TRIM(MILtype) AS STRING), '') AS miltype,
  NULLIF(CAST(TRIM(MILvnos) AS STRING), '') AS milvnos,
  NULLIF(CAST(TRIM(MILcus) AS STRING), '') AS milcus,
  NULLIF(CAST(TRIM(REGEXP_REPLACE(MILstk, r'[\n\r\t]', '')) AS STRING), '') AS milstk,
  NULLIF(CAST(TRIM(MILjob) AS STRING), '') AS miljob,
  NULLIF(CAST(TRIM(MILdep) AS STRING), '') AS mildep,
  NULLIF(CAST(TRIM(MILper) AS STRING), '') AS milper,
  NULLIF(CAST(TRIM(MILdoc) AS STRING), '') AS mildoc,
  NULLIF(CAST(TRIM(MILmec) AS STRING), '') AS milmec,
  NULLIF(CAST(TRIM(MILsto) AS STRING), '') AS milsto,
  NULLIF(CAST(TRIM(MILstoMT) AS STRING), '') AS milstomt,
  CAST(MILlistNo AS INT64) AS millistno,

  (CASE
    WHEN NULLIF(CAST(TRIM(MILtype) AS STRING), '') = 'BS' THEN CAST(MILquan AS FLOAT64) * -1
    ELSE CAST(MILquan AS FLOAT64)
  END) AS milquan,
  CAST(MILquan AS FLOAT64) AS milquan_raw,

  CAST(MILquanP2 AS FLOAT64) AS milquanp2,

  (CASE
    WHEN NULLIF(CAST(TRIM(MILtype) AS STRING), '') = 'BS' THEN CAST(MILadisc AS FLOAT64) * -1
    ELSE CAST(MILadisc AS FLOAT64)
  END) AS miladisc,
  CAST(MILadisc AS FLOAT64) AS miladisc_raw,

  (CASE
    WHEN NULLIF(CAST(TRIM(MILtype) AS STRING), '') = 'BS' THEN CAST(MILcog AS FLOAT64) * -1
    ELSE CAST(MILcog AS FLOAT64)
  END) AS milcog,
  CAST(MILcog AS FLOAT64) AS milcog_raw,

  CAST(MILconv AS FLOAT64) AS milconv,

  (CASE
    WHEN NULLIF(CAST(TRIM(MILtype) AS STRING), '') = 'BS' THEN CAST(MILdiscA AS FLOAT64) * -1
    ELSE CAST(MILdiscA AS FLOAT64)
  END) AS mildisca,
  CAST(MILdiscA AS FLOAT64) AS mildisca_raw,

  NULLIF(CAST(TRIM(MILdiscT) AS STRING), '') AS mildisct,
  (CASE
    WHEN NULLIF(CAST(TRIM(MILtype) AS STRING), '') = 'BS' THEN CAST(MILvat AS FLOAT64) * -1
    ELSE CAST(MILvat AS FLOAT64)
  END) AS milvat,
  CAST(MILvat AS FLOAT64) AS milvat_raw,

  (CASE
    WHEN NULLIF(CAST(TRIM(MILtype) AS STRING), '') = 'BS' THEN CAST(IF( (MILsum - (mihdischf1*-1)) < 0, 0, CAST((MILsum - MILadisc) AS FLOAT64)) * -1 AS FLOAT64)
    ELSE CAST((MILsum - MILadisc) AS FLOAT64)
  END) AS milsum,
  CAST(MILsum AS FLOAT64) AS milsum_raw,

  CAST(MILcut AS INT64) AS milcut,
  CAST(MILstype AS INT64) AS milstype,
  NULLIF(CAST(TRIM(MILuname) AS STRING), '') AS miluname,
  NULLIF(CAST(TRIM(MILdesc) AS STRING), '') AS mildesc,
  NULLIF(CAST(TRIM(MILvCol1) AS STRING), '') AS milvcol1,
  NULLIF(CAST(TRIM(MILvCol2) AS STRING), '') AS milvcol2,
  NULLIF(CAST(TRIM(MILvCol3) AS STRING), '') AS milvcol3,
  NULLIF(CAST(TRIM(MILvCol4) AS STRING), '') AS milvcol4,
  CAST(MILcurC AS INT64) AS milcurc,
  CAST(MILexchg AS FLOAT64) AS milexchg,
  CAST(MILacost AS FLOAT64) AS milacost,
  CAST(MILpqm AS INT64) AS milpqm,
  CAST(MILpmFrom AS INT64) AS milpmfrom,
  CAST(MILpmTo AS INT64) AS milpmto,
  CAST(MILtag AS INT64) AS miltag,
  NULLIF(CAST(TRIM(MILlinkVCno) AS STRING), '') AS millinkvcno,
  COALESCE(
    SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(MILlinkVCdate, 1, 19)),
    SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILlinkVCdate, 1, 19))
  ) AS millinkvcdate,
  NULLIF(CAST(TRIM(MILlinkVCtype) AS STRING), '') AS millinkvctype,
  NULLIF(CAST(TRIM(MILlinkVCdeposit) AS STRING), '') AS millinkvcdeposit,
  CAST(MILlinkVCid AS INT64) AS millinkvcid,
  CAST(MILclearUM AS INT64) AS milclearum,
  COALESCE(
    SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(MILexpDATE, 1, 19)),
    SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILexpDATE, 1, 19))
  ) AS milexpdate,
  NULLIF(CAST(TRIM(MILnotes) AS STRING), '') AS milnotes,
  CAST(MILnotKL AS INT64) AS milnotkl,
  COALESCE(
    SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(MILdelvDT, 1, 19)),
    SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILdelvDT, 1, 19))
  ) AS mildelvdt,
  COALESCE(
    SAFE.PARSE_DATETIME('%b %d %Y %I:%M%p', SUBSTR(MILdateSP, 1, 19)),
    SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(MILdateSP, 1, 19))
  ) AS mildatesp,
  CAST(MILnumCSP AS FLOAT64) AS milnumcsp,
  CAST(MILnumISP AS INT64) AS milnumisp,
  CAST(MILcost AS FLOAT64) AS milcost,
  CAST(MILucost AS FLOAT64) AS milucost,
  CAST(MILuprice AS FLOAT64) AS miluprice,
  CAST(MILuseQuanP AS INT64) AS milusequanp,
  NULLIF(CAST(TRIM(MILvCol5) AS STRING), '') AS milvcol5,
  CAST(MILfitem AS INT64) AS milfitem,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM cte_mil as mil
LEFT JOIN cte_mih as mih
  on mil.company_id = mih.company_id
  and mil.milyear = mih.mihyear
  and mil.milmonth = mih.mihmonth
  and mil.milday = mih.mihday
  and mil.miltype = mih.mihtype
  and mil.milvnos = mih.mihvnos
  and mil.milcus = mih.mihcus

${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
