config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [],
    bigquery: {
        clusterBy: ["miltype", "milvnos", "milcus", "millistno"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = []

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY miluname desc, mildesc desc) = 1`;
        post_operations_statement = `BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS';
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED';
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(milday AS INT64) as milday,
    CAST(milmonth AS INT64) as milmonth,
    CAST(milyear AS INT64) as milyear,
    NULLIF(CAST(TRIM(miltype) AS STRING), '') as miltype,
    NULLIF(CAST(TRIM(milvnos) AS STRING), '') as milvnos,
    NULLIF(CAST(TRIM(milcus) AS STRING), '') as milcus,
    NULLIF(CAST(TRIM(milstk) AS STRING), '') as milstk,
    NULLIF(CAST(TRIM(miljob) AS STRING), '') as miljob,
    NULLIF(CAST(TRIM(mildep) AS STRING), '') as mildep,
    NULLIF(CAST(TRIM(milper) AS STRING), '') as milper,
    NULLIF(CAST(TRIM(mildoc) AS STRING), '') as mildoc,
    NULLIF(CAST(TRIM(milmec) AS STRING), '') as milmec,
    NULLIF(CAST(TRIM(milsto) AS STRING), '') as milsto,
    NULLIF(CAST(TRIM(milstomt) AS STRING), '') as milstomt,
    CAST(millistno AS INT64) as millistno,
    CAST(milquan AS FLOAT64) as milquan,
    CAST(milquanp2 AS FLOAT64) as milquanp2,
    CAST(miladisc AS FLOAT64) as miladisc,
    CAST(milcog AS FLOAT64) as milcog,
    CAST(milconv AS FLOAT64) as milconv,
    CAST(mildisca AS FLOAT64) as mildisca,
    NULLIF(CAST(TRIM(mildisct) AS STRING), '') as mildisct,
    CAST(milvat AS FLOAT64) as milvat,
    CAST(milsum AS FLOAT64) as milsum,
    CAST(milcut AS INT64) as milcut,
    CAST(milstype AS INT64) as milstype,
    NULLIF(CAST(TRIM(miluname) AS STRING), '') as miluname,
    NULLIF(CAST(TRIM(mildesc) AS STRING), '') as mildesc,
    NULLIF(CAST(TRIM(milvcol1) AS STRING), '') as milvcol1,
    NULLIF(CAST(TRIM(milvcol2) AS STRING), '') as milvcol2,
    NULLIF(CAST(TRIM(milvcol3) AS STRING), '') as milvcol3,
    NULLIF(CAST(TRIM(milvcol4) AS STRING), '') as milvcol4,
    CAST(milcurc AS INT64) as milcurc,
    CAST(milexchg AS FLOAT64) as milexchg,
    CAST(milacost AS FLOAT64) as milacost,
    CAST(milpqm AS INT64) as milpqm,
    CAST(milpmfrom AS INT64) as milpmfrom,
    CAST(milpmto AS INT64) as milpmto,
    CAST(miltag AS INT64) as miltag,
    NULLIF(CAST(TRIM(millinkvcno) AS STRING), '') as millinkvcno,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(millinkvcdate, 1, 19)) AS millinkvcdate,
    NULLIF(CAST(TRIM(millinkvctype) AS STRING), '') as millinkvctype,
    NULLIF(CAST(TRIM(millinkvcdeposit) AS STRING), '') as millinkvcdeposit,
    CAST(millinkvcid AS INT64) as millinkvcid,
    CAST(milclearum AS INT64) as milclearum,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(milexpdate, 1, 19)) AS milexpdate,
    NULLIF(CAST(TRIM(milnotes) AS STRING), '') as milnotes,
    CAST(milnotkl AS INT64) as milnotkl,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mildelvdt, 1, 19)) AS mildelvdt,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mildatesp, 1, 19)) AS mildatesp,
    CAST(milnumcsp AS FLOAT64) as milnumcsp,
    CAST(milnumisp AS INT64) as milnumisp,
    CAST(milcost AS FLOAT64) as milcost,
    CAST(milucost AS FLOAT64) as milucost,
    CAST(miluprice AS FLOAT64) as miluprice,
    CAST(milusequanp AS INT64) as milusequanp,
    NULLIF(CAST(TRIM(milvcol5) AS STRING), '') as milvcol5,
    CAST(milfitem AS INT64) as milfitem

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
