config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["id"],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY update_date desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    NULLIF(CAST(TRIM(order_no) AS STRING), '') as order_no,
    NULLIF(CAST(TRIM(status) AS STRING), '') as status,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(create_date, 1, 19)) AS create_date,
    NULLIF(CAST(TRIM(promotion_type) AS STRING), '') as promotion_type,
    NULLIF(CAST(TRIM(notes) AS STRING), '') as notes,
    NULLIF(CAST(TRIM(sub_order) AS STRING), '') as sub_order,
    NULLIF(CAST(TRIM(made_from) AS STRING), '') as made_from,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(datetime, 1, 19)) AS datetime,
    NULLIF(CAST(TRIM(deliverystatus) AS STRING), '') as deliverystatus,
    NULLIF(CAST(TRIM(cancelstatus) AS STRING), '') as cancelstatus,
    NULLIF(CAST(TRIM(confirmstatus) AS STRING), '') as confirmstatus,
    NULLIF(CAST(TRIM(order_source) AS STRING), '') as order_source,
    CAST(is_complete AS INT64) as is_complete,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(update_date, 1, 19)) AS update_date

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
