config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["id"],
    bigquery: {
        clusterBy: ["id"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_MAC5
    const table_id = name()
    const pk_key = ["id"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY datepayinadmin desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(mainqtid AS INT64) as mainqtid,
    NULLIF(CAST(TRIM(preorderno) AS STRING), '') as preorderno,
    NULLIF(CAST(TRIM(orderno) AS STRING), '') as orderno,
    NULLIF(CAST(TRIM(type) AS STRING), '') as type,
    NULLIF(CAST(TRIM(path212) AS STRING), '') as path212,
    NULLIF(CAST(TRIM(path10acc) AS STRING), '') as path10acc,
    NULLIF(CAST(TRIM(path10fac) AS STRING), '') as path10fac,
    NULLIF(CAST(TRIM(filename) AS STRING), '') as filename,
    NULLIF(CAST(TRIM(uinsert) AS STRING), '') as uinsert,
    NULLIF(CAST(TRIM(date) AS STRING), '') as date,
    CAST(status AS INT64) as status,
    NULLIF(CAST(TRIM(pathqtid) AS STRING), '') as pathqtid,
    NULLIF(CAST(TRIM(note) AS STRING), '') as note,
    PARSE_DATE('%Y-%m-%d', SUBSTR(datepayinadmin, 1, 19)) as datepayinadmin,
    NULLIF(CAST(TRIM(refpo) AS STRING), '') as refpo

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
