config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["proagid","proagstkcode"],
    bigquery: {
        clusterBy: ["proagid","proagstkcode"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["proagid","proagstkcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY proagenddate desc, proagstrdate desc) = 1`;
        post_operations_statement = `BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS';
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED';
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(proagid AS INT64) as proagid,
    NULLIF(CAST(TRIM(proagstkcode) AS STRING), '') as proagstkcode,
    NULLIF(CAST(TRIM(proagsttcode) AS STRING), '') as proagsttcode,
    NULLIF(CAST(TRIM(proagstt) AS STRING), '') as proagstt,
    PARSE_DATE('%Y-%m-%d', SUBSTR(proagstrdate, 1, 10)) AS proagstrdate,
    PARSE_DATE('%Y-%m-%d', SUBSTR(proagenddate, 1, 10)) AS proagenddate,
    NULLIF(CAST(TRIM(proagregion) AS STRING), '') as proagregion,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
