config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "proagid","proagstkcode"],
    bigquery: {
        clusterBy: ["company_id", "proagid","proagstkcode"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "proagid","proagstkcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY proagenddate desc, proagstrdate desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    CAST(proagid AS INT64) as proagid,
    NULLIF(CAST(TRIM(proagstkcode) AS STRING), '') as proagstkcode,
    NULLIF(CAST(TRIM(proagsttcode) AS STRING), '') as proagsttcode,
    NULLIF(CAST(TRIM(proagstt) AS STRING), '') as proagstt,
    PARSE_DATE('%Y-%m-%d', SUBSTR(proagstrdate, 1, 10)) AS proagstrdate,
    PARSE_DATE('%Y-%m-%d', SUBSTR(proagenddate, 1, 10)) AS proagenddate,
    NULLIF(CAST(TRIM(proagregion) AS STRING), '') as proagregion,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
