config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["id","procrcstkcode"],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["id","procrcstkcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY procrcenddate desc, procrcstrdate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    NULLIF(CAST(TRIM(procrcstkcode) AS STRING), '') as procrcstkcode,
    NULLIF(CAST(TRIM(procrcsttcode) AS STRING), '') as procrcsttcode,
    NULLIF(CAST(TRIM(procrcstt) AS STRING), '') as procrcstt,
    PARSE_DATE('%Y-%m-%d', SUBSTR(procrcstrdate, 1, 10)) AS procrcstrdate,
    PARSE_DATE('%Y-%m-%d', SUBSTR(procrcenddate, 1, 10)) AS procrcenddate,
    NULLIF(CAST(TRIM(procrcregion) AS STRING), '') as procrcregion,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
