config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["proreid","prorestkcode"],
    bigquery: {
        clusterBy: ["proreid","prorestkcode"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["proreid","prorestkcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY proreenddate desc, prorestrdate desc) = 1`;
        post_operations_statement = `EXECUTE IMMEDIATE '''
    ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
    ''';`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(proreid AS INT64) as proreid,
    NULLIF(CAST(TRIM(prorestkcode) AS STRING), '') as prorestkcode,
    NULLIF(CAST(TRIM(proresttcode) AS STRING), '') as proresttcode,
    NULLIF(CAST(TRIM(prorestt) AS STRING), '') as prorestt,
    PARSE_DATE('%Y-%m-%d', SUBSTR(prorestrdate, 1, 10)) AS prorestrdate,
    PARSE_DATE('%Y-%m-%d', SUBSTR(proreenddate, 1, 10)) AS proreenddate,
    NULLIF(CAST(TRIM(proreregion) AS STRING), '') as proreregion,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
