config {
    type: "incremental",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_INCREMENTAL],
    uniqueKey: ["serial"],
    bigquery: {
        partitionBy: "asatdate",
        clusterBy: ["serial"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["serial"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY ASATDATE DESC) = 1`;
        post_operations_statement = `EXECUTE IMMEDIATE '''
    ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
    ''';`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
  NULLIF(CAST(TRIM(serial) AS STRING), '') AS serial,
  NULLIF(CAST(TRIM(rcvdate) AS STRING), '') AS rcvdate,
  CAST(rcvtype AS INT64) AS rcvtype,
  NULLIF(CAST(TRIM(rcvvnos) AS STRING), '') AS rcvvnos,
  NULLIF(CAST(TRIM(rcvstk) AS STRING), '') AS rcvstk,
  NULLIF(CAST(TRIM(descT1) AS STRING), '') AS desct1,
  NULLIF(CAST(TRIM(qty) AS STRING), '') AS qty,
  NULLIF(CAST(TRIM(unit) AS STRING), '') AS unit,
  NULLIF(CAST(TRIM(rcvsto) AS STRING), '') AS rcvsto,
  NULLIF(CAST(TRIM(username) AS STRING), '') AS username,
  NULLIF(CAST(TRIM(remark) AS STRING), '') AS remark,
  NULLIF(CAST(TRIM(rcvtime) AS STRING), '') AS rcvtime,
  NULLIF(CAST(TRIM(Fdatetime2) AS STRING), '') AS fdatetime2,
  NULLIF(CAST(TRIM(rcvStatus) AS STRING), '') AS rcvstatus,
  NULLIF(CAST(TRIM(rcvtypeFG) AS STRING), '') AS rcvtypefg,
  NULLIF(CAST(TRIM(rcvstatusMR) AS STRING), '') AS rcvstatusmr,
  NULLIF(CAST(TRIM(rcvzone) AS STRING), '') AS rcvzone,
  NULLIF(CAST(TRIM(rcvOrder) AS STRING), '') AS rcvorder,
  NULLIF(CAST(TRIM(rcvCommand) AS STRING), '') AS rcvcommand,
  NULLIF(CAST(TRIM(rcvExtCode) AS STRING), '') AS rcvextcode,
  NULLIF(CAST(TRIM(mixVnos) AS STRING), '') AS mixvnos,
  PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(mixDate, 1, 19)) AS mixdate,
  NULLIF(CAST(TRIM(rcvTranCode) AS STRING), '') AS rcvtrancode,
  CAST(rcvCancel AS INT64) AS rcvcancel,
  NULLIF(CAST(TRIM(rcvOrder_Pack) AS STRING), '') AS rcvorder_pack,
  NULLIF(CAST(TRIM(adjVnos) AS STRING), '') AS adjvnos,
  NULLIF(CAST(TRIM(PackDate) AS STRING), '') AS packdate,
  NULLIF(CAST(TRIM(PackTime) AS STRING), '') AS packtime,
  CAST(rcvConvert AS INT64) AS rcvconvert,
  NULLIF(CAST(TRIM(Odate) AS STRING), '') AS odate,
  NULLIF(CAST(TRIM(Ouser) AS STRING), '') AS ouser,
  CAST(FMIL2LISTNO AS INT64) AS fmil2listno,
  NULLIF(CAST(TRIM(Ostatus) AS STRING), '') AS ostatus,
  PARSE_DATE('%Y%m%d', ASATDATE) AS asatdate
FROM
  `${project_id}.${dataset_id}.${table_id}`
${ when(incremental(), `WHERE ASATDATE >= FORMAT_DATE("%Y%m%d", CURRENT_DATE(\'Asia/Bangkok\')-1)`) }
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
