config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["stdautono"],
    bigquery: {
        clusterBy: ["stdautono"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["stdautono"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stddesct1 desc, stddesce1 desc) = 1`;
        post_operations_statement = `EXECUTE IMMEDIATE '''
    ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
    ''';`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(stdcode) AS STRING), '') as stdcode,
    CAST(stdtype AS INT64) as stdtype,
    NULLIF(CAST(TRIM(stddebtor) AS STRING), '') as stddebtor,
    NULLIF(CAST(TRIM(stdstkcode) AS STRING), '') as stdstkcode,
    NULLIF(CAST(TRIM(stddesct1) AS STRING), '') as stddesct1,
    NULLIF(CAST(TRIM(stddesce1) AS STRING), '') as stddesce1,
    CAST(stdautono AS INT64) as stdautono,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
