config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5", "create_all_table_raw_mac5_aa05", "create_all_table_raw_mac5_ab01", "create_all_table_raw_mac5_ac02", "create_all_table_raw_mac5_ak02", "stgacc", "stg_report"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "stgcode"],
    bigquery: {
        clusterBy: ["company_id", "stgcode"]
    },
}

js {
    const pk_key = ["company_id", "stgcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stgdesct desc, stgdesce desc, rowguid desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }

}
WITH stgacc AS (
    SELECT stgcode, gacccode, gaccname
    FROM ${ref("stgacc")} as stgacc
    LEFT JOIN ${ref("stg_report")} as stg_report
        ON stgacc.gacccode = stg_report.stgacccode
    QUALIFY row_number() over(partition by stgcode order by gacccode desc) = 1
),
all_sources AS (
  SELECT
    'ag01' AS company_id,
    NULLIF(CAST(TRIM(REGEXP_REPLACE(stg.stgcode, r'[\n\r\t-.]', '')) AS STRING), '') as stgcode,
    NULLIF(CAST(TRIM(stg.stgdesct) AS STRING), '') as stgdesct,
    NULLIF(CAST(TRIM(stg.stgdesce) AS STRING), '') as stgdesce,
    NULLIF(CAST(TRIM(stg.rowguid) AS STRING), '') as rowguid,
    NULLIF(CAST(TRIM(stgacc.gacccode) AS STRING), '') as gacccode,
    NULLIF(CAST(TRIM(stgacc.gaccname) AS STRING), '') as gaccname
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AG01}.stg` as stg
  LEFT JOIN stgacc as stgacc ON stg.stgcode = stgacc.stgcode

  UNION ALL

  SELECT
    'aa05' AS company_id,
    NULLIF(CAST(TRIM(REGEXP_REPLACE(stg.stgcode, r'[\n\r\t-.]', '')) AS STRING), '') as stgcode,
    NULLIF(CAST(TRIM(stg.stgdesct) AS STRING), '') as stgdesct,
    NULLIF(CAST(TRIM(stg.stgdesce) AS STRING), '') as stgdesce,
    NULLIF(CAST(TRIM(stg.rowguid) AS STRING), '') as rowguid,
    NULLIF(CAST(TRIM(stgacc.gacccode) AS STRING), '') as gacccode,
    NULLIF(CAST(TRIM(stgacc.gaccname) AS STRING), '') as gaccname
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AA05}.stg` as stg
  LEFT JOIN stgacc as stgacc ON stg.stgcode = stgacc.stgcode

  UNION ALL

  SELECT
    'ab01' AS company_id,
    NULLIF(CAST(TRIM(REGEXP_REPLACE(stg.stgcode, r'[\n\r\t-.]', '')) AS STRING), '') as stgcode,
    NULLIF(CAST(TRIM(stg.stgdesct) AS STRING), '') as stgdesct,
    NULLIF(CAST(TRIM(stg.stgdesce) AS STRING), '') as stgdesce,
    CAST(NULL AS STRING) as rowguid,
    NULLIF(CAST(TRIM(stgacc.gacccode) AS STRING), '') as gacccode,
    NULLIF(CAST(TRIM(stgacc.gaccname) AS STRING), '') as gaccname
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AB01}.stg` as stg
  LEFT JOIN stgacc as stgacc ON stg.stgcode = stgacc.stgcode

  UNION ALL

  SELECT
    'ac02' AS company_id,
    NULLIF(CAST(TRIM(REGEXP_REPLACE(stg.stgcode, r'[\n\r\t-.]', '')) AS STRING), '') as stgcode,
    NULLIF(CAST(TRIM(stg.stgdesct) AS STRING), '') as stgdesct,
    NULLIF(CAST(TRIM(stg.stgdesce) AS STRING), '') as stgdesce,
    NULLIF(CAST(TRIM(stg.rowguid) AS STRING), '') as rowguid,
    NULLIF(CAST(TRIM(stgacc.gacccode) AS STRING), '') as gacccode,
    NULLIF(CAST(TRIM(stgacc.gaccname) AS STRING), '') as gaccname
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AC02}.stg` as stg
  LEFT JOIN stgacc as stgacc ON stg.stgcode = stgacc.stgcode

  UNION ALL

  SELECT
    'ak02' AS company_id,
    NULLIF(CAST(TRIM(REGEXP_REPLACE(stg.stgcode, r'[\n\r\t-.]', '')) AS STRING), '') as stgcode,
    NULLIF(CAST(TRIM(stg.stgdesct) AS STRING), '') as stgdesct,
    NULLIF(CAST(TRIM(stg.stgdesce) AS STRING), '') as stgdesce,
    CAST(NULL AS STRING) as rowguid,
    NULLIF(CAST(TRIM(stgacc.gacccode) AS STRING), '') as gacccode,
    NULLIF(CAST(TRIM(stgacc.gaccname) AS STRING), '') as gaccname
  FROM `${databuffet.DATABASE}.${databuffet.RAW_MAC5_AK02}.stg` as stg
  LEFT JOIN stgacc as stgacc ON stg.stgcode = stgacc.stgcode
)

SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
