config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["stk"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["stk"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stkeditdt desc, stkdesct1 desc, stkdesct2 desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(stkcode) AS STRING) as stkcode,
    CAST(TRIM(stkgroup) AS STRING) as stkgroup,
    CAST(TRIM(stkcode2) AS STRING) as stkcode2,
    CAST(TRIM(stkdesct1) AS STRING) as stkdesct1,
    CAST(TRIM(stkdesct2) AS STRING) as stkdesct2,
    CAST(TRIM(stkdesct3) AS STRING) as stkdesct3,
    CAST(TRIM(stkdesce1) AS STRING) as stkdesce1,
    CAST(TRIM(stkdesce2) AS STRING) as stkdesce2,
    CAST(TRIM(stkdesce3) AS STRING) as stkdesce3,
    CAST(stkmax AS FLOAT64) as stkmax,
    CAST(stkmin AS FLOAT64) as stkmin,
    CAST(stkunit1 AS INT64) as stkunit1,
    CAST(stkunit2 AS INT64) as stkunit2,
    CAST(stkconv1 AS FLOAT64) as stkconv1,
    CAST(stkconv2 AS FLOAT64) as stkconv2,
    CAST(stksnsv AS INT64) as stksnsv,
    CAST(TRIM(stkuname0) AS STRING) as stkuname0,
    CAST(TRIM(stkuname1) AS STRING) as stkuname1,
    CAST(TRIM(stkuname2) AS STRING) as stkuname2,
    CAST(TRIM(stkuname3) AS STRING) as stkuname3,
    CAST(TRIM(stkuname4) AS STRING) as stkuname4,
    CAST(TRIM(stkuname5) AS STRING) as stkuname5,
    CAST(stkqu1 AS FLOAT64) as stkqu1,
    CAST(stkqu2 AS FLOAT64) as stkqu2,
    CAST(stkqu3 AS FLOAT64) as stkqu3,
    CAST(stkqu4 AS FLOAT64) as stkqu4,
    CAST(stkqu5 AS FLOAT64) as stkqu5,
    CAST(stkqe1 AS FLOAT64) as stkqe1,
    CAST(stkqe2 AS FLOAT64) as stkqe2,
    CAST(stkqe3 AS FLOAT64) as stkqe3,
    CAST(stkqe4 AS FLOAT64) as stkqe4,
    CAST(stkqe5 AS FLOAT64) as stkqe5,
    CAST(stkqn1 AS INT64) as stkqn1,
    CAST(stkqn2 AS INT64) as stkqn2,
    CAST(stkqn3 AS INT64) as stkqn3,
    CAST(stkqn4 AS INT64) as stkqn4,
    CAST(stkqn5 AS INT64) as stkqn5,
    CAST(stkvat AS FLOAT64) as stkvat,
    CAST(stkexpire AS INT64) as stkexpire,
    CAST(stkhide AS INT64) as stkhide,
    CAST(stkuse2 AS INT64) as stkuse2,
    CAST(TRIM(stku2name) AS STRING) as stku2name,
    CAST(stkfx AS INT64) as stkfx,
    CAST(TRIM(stkacp) AS STRING) as stkacp,
    CAST(TRIM(stkacs) AS STRING) as stkacs,
    CAST(TRIM(stkacc) AS STRING) as stkacc,
    CAST(stklock AS INT64) as stklock,
    CAST(TRIM(stkmemo) AS STRING) as stkmemo,
    CAST(TRIM(stkacc1) AS STRING) as stkacc1,
    CAST(TRIM(stkacc2) AS STRING) as stkacc2,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(stkeditlk, 1, 19)) AS stkeditlk,
    CAST(TRIM(stkrefwe) AS STRING) as stkrefwe,
    CAST(TRIM(stkbarc1) AS STRING) as stkbarc1,
    CAST(TRIM(stkbarc2) AS STRING) as stkbarc2,
    CAST(TRIM(stkbarc3) AS STRING) as stkbarc3,
    CAST(TRIM(stksortnt) AS STRING) as stksortnt,
    CAST(TRIM(stksortne) AS STRING) as stksortne,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(stkeditdt, 1, 19)) AS stkeditdt,
    CAST(stkstatus AS INT64) as stkstatus,
    CAST(TRIM(stksto) AS STRING) as stksto,
    CAST(TRIM(stkeditmf) AS STRING) as stkeditmf,
    CAST(TRIM(rowguid) AS STRING) as rowguid,
    CAST(TRIM(stkcode885) AS STRING) as stkcode885,
    CAST(TRIM(stktype) AS STRING) as stktype,
    CAST(TRIM(stksalegrp) AS STRING) as stksalegrp,
    CAST(TRIM(stksaletype) AS STRING) as stksaletype,
    CAST(TRIM(stksalesup) AS STRING) as stksalesup,
    CAST(TRIM(stksalegrps1) AS STRING) as stksalegrps1,
    CAST(TRIM(stksalegrps2) AS STRING) as stksalegrps2,
    CAST(TRIM(stksub1) AS STRING) as stksub1,
    CAST(TRIM(stksub2) AS STRING) as stksub2,
    CAST(TRIM(stksub3) AS STRING) as stksub3,
    CAST(TRIM(stkbrand) AS STRING) as stkbrand,
    CAST(TRIM(stkexpand) AS STRING) as stkexpand,
    CAST(TRIM(stklggrp) AS STRING) as stklggrp,
    CAST(TRIM(stkgroup_dge) AS STRING) as stkgroup_dge,
    CAST(TRIM(stkgroup1_dge_report) AS STRING) as stkgroup1_dge_report,
    CAST(TRIM(stkgroup2_dge_report) AS STRING) as stkgroup2_dge_report,
    CAST(TRIM(stkgroup3_dge_report) AS STRING) as stkgroup3_dge_report,
    CAST(TRIM(part_dge) AS STRING) as part_dge,
    CAST(TRIM(stkfpass) AS STRING) as stkfpass

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
