config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["stk_mkt"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["stk_mkt"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stkdesct1 DESC) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(stkcode) AS STRING), '') as stkcode,
    NULLIF(CAST(TRIM(stkgroup) AS STRING), '') as stkgroup,
    NULLIF(CAST(TRIM(stkdesct1) AS STRING), '') as stkdesct1,
    NULLIF(CAST(TRIM(zgroup1) AS STRING), '') as zgroup1,
    NULLIF(CAST(TRIM(zgroup2) AS STRING), '') as zgroup2,
    NULLIF(CAST(TRIM(zsize) AS STRING), '') as zsize,
    NULLIF(CAST(TRIM(zcolor) AS STRING), '') as zcolor,
    NULLIF(CAST(TRIM(zgroup3) AS STRING), '') as zgroup3,
    NULLIF(CAST(TRIM(zgroup4) AS STRING), '') as zgroup4,
    NULLIF(CAST(TRIM(zgroup5) AS STRING), '') as zgroup5,
    NULLIF(CAST(TRIM(zgroup6) AS STRING), '') as zgroup6,
    NULLIF(CAST(TRIM(zgroup7) AS STRING), '') as zgroup7
FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
