config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "stkcode"],
    bigquery: {
        clusterBy: ["company_id", "stkcode"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "stkcode"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stkdesct1 DESC) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.functionData.cleanString('stkcode')} as stkcode,
    ${databuffet.functionData.cleanString('stkgroup')} as stkgroup,
    ${databuffet.functionData.cleanString('stkdesct1')} as stkdesct1,
    ${databuffet.functionData.cleanString('zgroup1')} as zgroup1,
    ${databuffet.functionData.cleanString('zgroup2')} as zgroup2,
    ${databuffet.functionData.cleanString('zsize')} as zsize,
    ${databuffet.functionData.cleanString('zcolor')} as zcolor,
    ${databuffet.functionData.cleanString('zgroup3')} as zgroup3,
    ${databuffet.functionData.cleanString('zgroup4')} as zgroup4,
    ${databuffet.functionData.cleanString('zgroup5')} as zgroup5,
    ${databuffet.functionData.cleanString('zgroup6')} as zgroup6,
    ${databuffet.functionData.cleanString('zgroup7')} as zgroup7
  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
