config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["sto"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["sto"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stoeditdt desc, stodesct desc, stodesce desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(stocode) AS STRING), '') as stocode,
    NULLIF(CAST(TRIM(stogroup) AS STRING), '') as stogroup,
    NULLIF(CAST(TRIM(stodesct) AS STRING), '') as stodesct,
    NULLIF(CAST(TRIM(stodesce) AS STRING), '') as stodesce,
    CAST(stolock AS INT64) as stolock,
    CAST(stohide AS INT64) as stohide,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(stoeditdt, 1, 19)) AS stoeditdt,
    NULLIF(CAST(TRIM(stoeditmf) AS STRING), '') as stoeditmf,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
