config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["tabvnosid","tabdateid","tabcusid","tabtypeid","tablistno"],
    bigquery: {
        clusterBy: ["tabvnosid","tabdateid","tabcusid"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["tabvnosid","tabdateid","tabcusid","tabtypeid","tablistno"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY tabdateid desc) = 1`;
        post_operations_statement = `BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS';
    EXECUTE IMMEDIATE 'ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED';
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(tabvnosid) AS STRING), '') as tabvnosid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(tabdateid, 1, 19)) AS tabdateid,
    NULLIF(CAST(TRIM(tabcusid) AS STRING), '') as tabcusid,
    NULLIF(CAST(TRIM(tabtypeid) AS STRING), '') as tabtypeid,
    NULLIF(CAST(TRIM(tablinktype) AS STRING), '') as tablinktype,
    NULLIF(CAST(TRIM(tablinkvno) AS STRING), '') as tablinkvno,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(tablinkvdate, 1, 19)) AS tablinkvdate,
    NULLIF(CAST(TRIM(tablinkvcus) AS STRING), '') as tablinkvcus,
    NULLIF(CAST(TRIM(tablinkvtype) AS STRING), '') as tablinkvtype,
    CAST(tablinkvid AS INT64) as tablinkvid,
    NULLIF(CAST(TRIM(tabstk) AS STRING), '') as tabstk,
    CAST(tabquan AS FLOAT64) as tabquan,
    CAST(tabquanp2 AS FLOAT64) as tabquanp2,
    CAST(tabsum AS FLOAT64) as tabsum,
    CAST(tabcurc AS INT64) as tabcurc,
    CAST(tabexchg AS FLOAT64) as tabexchg,
    CAST(tablistno AS INT64) as tablistno,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
