config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "tabvnosid","tabdateid","tabcusid","tabtypeid","tablistno"],
    bigquery: {
        clusterBy: ["company_id", "tabvnosid","tabdateid","tabcusid"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "tabvnosid","tabdateid","tabcusid","tabtypeid","tablistno"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY tabdateid desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.cleanString('tabvnosid')} as tabvnosid,
    ${databuffet.parseFlexibleDatetime('tabdateid')} AS tabdateid,
    ${databuffet.cleanString('tabcusid')} as tabcusid,
    ${databuffet.cleanString('tabtypeid')} as tabtypeid,
    ${databuffet.cleanString('tablinktype')} as tablinktype,
    ${databuffet.cleanString('tablinkvno')} as tablinkvno,
    ${databuffet.parseFlexibleDatetime('tablinkvdate')} AS tablinkvdate,
    ${databuffet.cleanString('tablinkvcus')} as tablinkvcus,
    ${databuffet.cleanString('tablinkvtype')} as tablinkvtype,
    ${databuffet.castInt64('tablinkvid')} as tablinkvid,
    ${databuffet.cleanString('tabstk')} as tabstk,
    ${databuffet.castFloat64('tabquan')} as tabquan,
    ${databuffet.castFloat64('tabquanp2')} as tabquanp2,
    ${databuffet.castFloat64('tabsum')} as tabsum,
    ${databuffet.castInt64('tabcurc')} as tabcurc,
    ${databuffet.castFloat64('tabexchg')} as tabexchg,
    ${databuffet.castInt64('tablistno')} as tablistno

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
