config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "tabvnosid","tabdateid","tabcusid","tabtypeid","tablistno"],
    bigquery: {
        clusterBy: ["company_id", "tabvnosid","tabdateid","tabcusid"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "tabvnosid","tabdateid","tabcusid","tabtypeid","tablistno"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY tabdateid desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    NULLIF(CAST(TRIM(tabvnosid) AS STRING), '') as tabvnosid,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(tabdateid, 1, 19)) AS tabdateid,
    NULLIF(CAST(TRIM(tabcusid) AS STRING), '') as tabcusid,
    NULLIF(CAST(TRIM(tabtypeid) AS STRING), '') as tabtypeid,
    NULLIF(CAST(TRIM(tablinktype) AS STRING), '') as tablinktype,
    NULLIF(CAST(TRIM(tablinkvno) AS STRING), '') as tablinkvno,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(tablinkvdate, 1, 19)) AS tablinkvdate,
    NULLIF(CAST(TRIM(tablinkvcus) AS STRING), '') as tablinkvcus,
    NULLIF(CAST(TRIM(tablinkvtype) AS STRING), '') as tablinkvtype,
    CAST(tablinkvid AS INT64) as tablinkvid,
    NULLIF(CAST(TRIM(tabstk) AS STRING), '') as tabstk,
    CAST(tabquan AS FLOAT64) as tabquan,
    CAST(tabquanp2 AS FLOAT64) as tabquanp2,
    CAST(tabsum AS FLOAT64) as tabsum,
    CAST(tabcurc AS INT64) as tabcurc,
    CAST(tabexchg AS FLOAT64) as tabexchg,
    CAST(tablistno AS INT64) as tablistno,
    NULLIF(CAST(TRIM(rowguid) AS STRING), '') as rowguid

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
