config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbcontact"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbcontact"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY contactname desc, contactdesc desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(id) AS STRING) as id,
    CAST(TRIM(contactpersonal) AS STRING) as contactpersonal,
    CAST(TRIM(contactcompany) AS STRING) as contactcompany,
    CAST(TRIM(contactcop) AS STRING) as contactcop,
    CAST(TRIM(contactsegment) AS STRING) as contactsegment,
    CAST(TRIM(contactchannel) AS STRING) as contactchannel,
    CAST(TRIM(contactstatus) AS STRING) as contactstatus,
    CAST(TRIM(contacttitle) AS STRING) as contacttitle,
    CAST(TRIM(contactname) AS STRING) as contactname,
    CAST(TRIM(contactnick) AS STRING) as contactnick,
    CAST(TRIM(contactaddress) AS STRING) as contactaddress,
    CAST(TRIM(contactaddress1) AS STRING) as contactaddress1,
    CAST(TRIM(contactaddress2) AS STRING) as contactaddress2,
    CAST(TRIM(contactaddress3) AS STRING) as contactaddress3,
    CAST(TRIM(contactaddress4) AS STRING) as contactaddress4,
    CAST(TRIM(contactaddress5) AS STRING) as contactaddress5,
    CAST(TRIM(contactaddress6) AS STRING) as contactaddress6,
    CAST(TRIM(contacttel) AS STRING) as contacttel,
    CAST(TRIM(contactmail) AS STRING) as contactmail,
    CAST(TRIM(contacttype) AS STRING) as contacttype,
    PARSE_DATE('%Y-%m-%d', SUBSTR(contactbday, 1, 10)) AS contactbday,
    CAST(TRIM(contactage) AS STRING) as contactage,
    CAST(TRIM(contactbyear) AS STRING) as contactbyear,
    CAST(TRIM(contacthob) AS STRING) as contacthob,
    CAST(TRIM(contactstudy) AS STRING) as contactstudy,
    CAST(TRIM(contactmag) AS STRING) as contactmag,
    CAST(TRIM(contactme) AS STRING) as contactme,
    CAST(TRIM(contactcolor) AS STRING) as contactcolor,
    CAST(TRIM(contactfood) AS STRING) as contactfood,
    CAST(TRIM(contactlife) AS STRING) as contactlife,
    CAST(TRIM(contactact) AS STRING) as contactact,
    CAST(TRIM(contactsday) AS STRING) as contactsday,
    CAST(TRIM(contactdesc) AS STRING) as contactdesc,
    CAST(TRIM(contactlove) AS STRING) as contactlove,
    CAST(TRIM(contactson) AS STRING) as contactson,
    CAST(TRIM(contactcntson) AS STRING) as contactcntson,
    CAST(TRIM(contactcntgirl) AS STRING) as contactcntgirl,
    CAST(TRIM(contactsonname1) AS STRING) as contactsonname1,
    CAST(TRIM(contactsonage1) AS STRING) as contactsonage1,
    CAST(TRIM(contactsonstudy1) AS STRING) as contactsonstudy1,
    CAST(TRIM(contactsonname2) AS STRING) as contactsonname2,
    CAST(TRIM(contactsonage2) AS STRING) as contactsonage2,
    CAST(TRIM(contactsonstudy2) AS STRING) as contactsonstudy2,
    CAST(TRIM(contactsonname3) AS STRING) as contactsonname3,
    CAST(TRIM(contactsonage3) AS STRING) as contactsonage3,
    CAST(TRIM(contactsonstudy3) AS STRING) as contactsonstudy3,
    CAST(TRIM(contactposition) AS STRING) as contactposition,
    CAST(TRIM(contactpower) AS STRING) as contactpower,
    CAST(TRIM(projectcode) AS STRING) as projectcode,
    CAST(TRIM(contactpp1) AS STRING) as contactpp1,
    CAST(TRIM(contactpp2) AS STRING) as contactpp2,
    CAST(TRIM(contactpp3) AS STRING) as contactpp3,
    CAST(TRIM(contactpp4) AS STRING) as contactpp4,
    CAST(TRIM(contactpp5) AS STRING) as contactpp5,
    CAST(TRIM(contactpp6) AS STRING) as contactpp6,
    CAST(TRIM(insertby) AS STRING) as insertby,
    CAST(TRIM(insertwhen) AS STRING) as insertwhen,
    CAST(TRIM(lastupdate) AS STRING) as lastupdate,
    CAST(TRIM(contactpath20) AS STRING) as contactpath20,
    CAST(TRIM(contactdebcode) AS STRING) as contactdebcode,
    CAST(activestatus AS INT64) as activestatus,
    CAST(TRIM(lineidcorp) AS STRING) as lineidcorp

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
