config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [],
    bigquery: {
        clusterBy: ["docno"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = []

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY dupdate desc) = 1`;
        post_operations_statement = `BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    -- Retry loop
    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            -- ลอง ALTER TABLE
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            -- ถ้า error ให้ retry
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(docno AS INT64) as docno,
    CAST(projectcode AS INT64) as projectcode,
    NULLIF(CAST(TRIM(projectname) AS STRING), '') as projectname,
    NULLIF(CAST(TRIM(statuscomp) AS STRING), '') as statuscomp,
    NULLIF(CAST(TRIM(compname) AS STRING), '') as compname,
    NULLIF(CAST(TRIM(register) AS STRING), '') as register,
    NULLIF(CAST(TRIM(addresscomp) AS STRING), '') as addresscomp,
    NULLIF(CAST(TRIM(province) AS STRING), '') as province,
    NULLIF(CAST(TRIM(district) AS STRING), '') as district,
    NULLIF(CAST(TRIM(country) AS STRING), '') as country,
    NULLIF(CAST(TRIM(status) AS STRING), '') as status,
    NULLIF(CAST(TRIM(capital) AS STRING), '') as capital,
    NULLIF(CAST(TRIM(place) AS STRING), '') as place,
    NULLIF(CAST(TRIM(tel) AS STRING), '') as tel,
    NULLIF(CAST(TRIM(mobile) AS STRING), '') as mobile,
    NULLIF(CAST(TRIM(fax) AS STRING), '') as fax,
    NULLIF(CAST(TRIM(mail) AS STRING), '') as mail,
    NULLIF(CAST(TRIM(namedirector) AS STRING), '') as namedirector,
    NULLIF(CAST(TRIM(nickname) AS STRING), '') as nickname,
    NULLIF(CAST(TRIM(teldirector) AS STRING), '') as teldirector,
    NULLIF(CAST(TRIM(profilecomp) AS STRING), '') as profilecomp,
    NULLIF(CAST(TRIM(typecomp) AS STRING), '') as typecomp,
    NULLIF(CAST(TRIM(startdate) AS STRING), '') as startdate,
    NULLIF(CAST(TRIM(history) AS STRING), '') as history,
    NULLIF(CAST(TRIM(pjstart) AS STRING), '') as pjstart,
    NULLIF(CAST(TRIM(pjend) AS STRING), '') as pjend,
    NULLIF(CAST(TRIM(pjval) AS STRING), '') as pjval,
    NULLIF(CAST(TRIM(pjfor) AS STRING), '') as pjfor,
    NULLIF(CAST(TRIM(compgroup) AS STRING), '') as compgroup,
    NULLIF(CAST(TRIM(acccode) AS STRING), '') as acccode,
    NULLIF(CAST(TRIM(accname) AS STRING), '') as accname,
    NULLIF(CAST(TRIM(closedby) AS STRING), '') as closedby,
    NULLIF(CAST(TRIM(projectfrom) AS STRING), '') as projectfrom,
    NULLIF(CAST(TRIM(ptype) AS STRING), '') as ptype,
    NULLIF(CAST(TRIM(ppc) AS STRING), '') as ppc,
    NULLIF(CAST(TRIM(pecom) AS STRING), '') as pecom,
    NULLIF(CAST(TRIM(uinsert) AS STRING), '') as uinsert,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert,
    NULLIF(CAST(TRIM(insertby) AS STRING), '') as insertby,
    NULLIF(CAST(TRIM(uupdate) AS STRING), '') as uupdate,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)) AS dupdate,
    NULLIF(CAST(TRIM(meccode) AS STRING), '') as meccode,
    NULLIF(CAST(TRIM(contactdebcode) AS STRING), '') as contactdebcode,
    NULLIF(CAST(TRIM(refallkon) AS STRING), '') as refallkon

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
