config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_profilecomp"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_profilecomp"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY dupdate desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(docno AS INT64) as docno,
    CAST(projectcode AS INT64) as projectcode,
    CAST(TRIM(projectname) AS STRING) as projectname,
    CAST(TRIM(statuscomp) AS STRING) as statuscomp,
    CAST(TRIM(compname) AS STRING) as compname,
    CAST(TRIM(register) AS STRING) as register,
    CAST(TRIM(addresscomp) AS STRING) as addresscomp,
    CAST(TRIM(province) AS STRING) as province,
    CAST(TRIM(district) AS STRING) as district,
    CAST(TRIM(country) AS STRING) as country,
    CAST(TRIM(status) AS STRING) as status,
    CAST(TRIM(capital) AS STRING) as capital,
    CAST(TRIM(place) AS STRING) as place,
    CAST(TRIM(tel) AS STRING) as tel,
    CAST(TRIM(mobile) AS STRING) as mobile,
    CAST(TRIM(fax) AS STRING) as fax,
    CAST(TRIM(mail) AS STRING) as mail,
    CAST(TRIM(namedirector) AS STRING) as namedirector,
    CAST(TRIM(nickname) AS STRING) as nickname,
    CAST(TRIM(teldirector) AS STRING) as teldirector,
    CAST(TRIM(profilecomp) AS STRING) as profilecomp,
    CAST(TRIM(typecomp) AS STRING) as typecomp,
    CAST(TRIM(startdate) AS STRING) as startdate,
    CAST(TRIM(history) AS STRING) as history,
    CAST(TRIM(pjstart) AS STRING) as pjstart,
    CAST(TRIM(pjend) AS STRING) as pjend,
    CAST(TRIM(pjval) AS STRING) as pjval,
    CAST(TRIM(pjfor) AS STRING) as pjfor,
    CAST(TRIM(compgroup) AS STRING) as compgroup,
    CAST(TRIM(acccode) AS STRING) as acccode,
    CAST(TRIM(accname) AS STRING) as accname,
    CAST(TRIM(closedby) AS STRING) as closedby,
    CAST(TRIM(projectfrom) AS STRING) as projectfrom,
    CAST(TRIM(ptype) AS STRING) as ptype,
    CAST(TRIM(ppc) AS STRING) as ppc,
    CAST(TRIM(pecom) AS STRING) as pecom,
    CAST(TRIM(uinsert) AS STRING) as uinsert,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) AS dinsert,
    CAST(TRIM(insertby) AS STRING) as insertby,
    CAST(TRIM(uupdate) AS STRING) as uupdate,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dupdate, 1, 19)) AS dupdate,
    CAST(TRIM(meccode) AS STRING) as meccode,
    CAST(TRIM(contactdebcode) AS STRING) as contactdebcode,
    CAST(TRIM(refallkon) AS STRING) as refallkon

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
