config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quotation"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quotation"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY extradesc desc, cname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(TRIM(running) AS STRING) as running,
    CAST(TRIM(atten) AS STRING) as atten,
    CAST(TRIM(address) AS STRING) as address,
    CAST(TRIM(sdate) AS STRING) as sdate,
    CAST(TRIM(project) AS STRING) as project,
    CAST(TRIM(tel) AS STRING) as tel,
    CAST(TRIM(sale) AS STRING) as sale,
    CAST(TRIM(price_validity) AS STRING) as price_validity,
    CAST(TRIM(termdelivery) AS STRING) as termdelivery,
    CAST(TRIM(termpayment) AS STRING) as termpayment,
    CAST(TRIM(uinsert) AS STRING) as uinsert,
    CAST(TRIM(dinsert) AS STRING) as dinsert,
    CAST(TRIM(uupdate) AS STRING) as uupdate,
    CAST(TRIM(dupdate) AS STRING) as dupdate,
    CAST(TRIM(agent1) AS STRING) as agent1,
    CAST(TRIM(agent2) AS STRING) as agent2,
    CAST(TRIM(period) AS STRING) as period,
    CAST(TRIM(pos) AS STRING) as pos,
    CAST(vat AS INT64) as vat,
    CAST(disc AS INT64) as disc,
    CAST(extrasum AS INT64) as extrasum,
    CAST(TRIM(extradesc) AS STRING) as extradesc,
    CAST(TRIM(date1st) AS STRING) as date1st,
    CAST(TRIM(date1end) AS STRING) as date1end,
    CAST(TRIM(date2st) AS STRING) as date2st,
    CAST(TRIM(date2end) AS STRING) as date2end,
    CAST(cashstatus AS INT64) as cashstatus,
    CAST(TRIM(note) AS STRING) as note,
    CAST(TRIM(noteforapp) AS STRING) as noteforapp,
    CAST(TRIM(memoforapp) AS STRING) as memoforapp,
    CAST(rev AS INT64) as rev,
    CAST(typecus AS INT64) as typecus,
    CAST(TRIM(channel) AS STRING) as channel,
    CAST(TRIM(channel2) AS STRING) as channel2,
    CAST(typeprice AS INT64) as typeprice,
    CAST(fob AS INT64) as fob,
    CAST(cancel AS INT64) as cancel,
    CAST(apptype AS INT64) as apptype,
    CAST(TRIM(typedeb) AS STRING) as typedeb,
    CAST(TRIM(saledep) AS STRING) as saledep,
    CAST(TRIM(typeproject) AS STRING) as typeproject,
    CAST(selectstatus AS INT64) as selectstatus,
    CAST(conpostatus AS INT64) as conpostatus,
    CAST(TRIM(lat) AS STRING) as lat,
    CAST(TRIM(long) AS STRING) as long,
    CAST(TRIM(mapnote) AS STRING) as mapnote,
    CAST(TRIM(fileupload) AS STRING) as fileupload,
    CAST(TRIM(city) AS STRING) as city,
    CAST(rdosend AS INT64) as rdosend,
    CAST(TRIM(cname) AS STRING) as cname,
    CAST(TRIM(ctel) AS STRING) as ctel,
    CAST(TRIM(caddress) AS STRING) as caddress,
    CAST(TRIM(checknote) AS STRING) as checknote,
    CAST(TRIM(textnote) AS STRING) as textnote,
    CAST(statusspread AS INT64) as statusspread,
    CAST(chkbox AS INT64) as chkbox,
    CAST(fobstt AS INT64) as fobstt,
    CAST(quotation_ref AS INT64) as quotation_ref,
    CAST(customer_id AS INT64) as customer_id,
    CAST(customer_group AS INT64) as customer_group,
    CAST(quotation_id AS INT64) as quotation_id,
    CAST(estatus AS INT64) as estatus,
    CAST(TRIM(area) AS STRING) as area,
    CAST(TRIM(district) AS STRING) as district,
    CAST(TRIM(postcode) AS STRING) as postcode,
    CAST(qtstepprice AS INT64) as qtstepprice,
    CAST(TRIM(extradis) AS STRING) as extradis

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
