config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quodetail"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbook_quodetail"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY stkdesc desc, cname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(linkid AS INT64) as linkid,
    CAST(TRIM(stkcode) AS STRING) as stkcode,
    CAST(TRIM(stkdesc) AS STRING) as stkdesc,
    CAST(quantity AS FLOAT64) as quantity,
    CAST(lp AS FLOAT64) as lp,
    CAST(nd AS FLOAT64) as nd,
    CAST(sd1 AS FLOAT64) as sd1,
    CAST(sd2 AS FLOAT64) as sd2,
    CAST(sd3 AS FLOAT64) as sd3,
    CAST(dispercent AS FLOAT64) as dispercent,
    CAST(crc AS FLOAT64) as crc,
    CAST(price AS FLOAT64) as price,
    CAST(total AS FLOAT64) as total,
    CAST(priceforag AS FLOAT64) as priceforag,
    CAST(com AS FLOAT64) as com,
    CAST(setcb AS INT64) as setcb,
    CAST(TRIM(type) AS STRING) as type,
    CAST(TRIM(status) AS STRING) as status,
    CAST(TRIM(sent) AS STRING) as sent,
    CAST(TRIM(datepart) AS STRING) as datepart,
    CAST(TRIM(fg) AS STRING) as fg,
    CAST(TRIM(pic) AS STRING) as pic,
    CAST(TRIM(productcp) AS STRING) as productcp,
    CAST(pricecp AS FLOAT64) as pricecp,
    CAST(TRIM(uinsert) AS STRING) as uinsert,
    CAST(TRIM(uupdate) AS STRING) as uupdate,
    CAST(TRIM(dinsert) AS STRING) as dinsert,
    CAST(TRIM(dupdate) AS STRING) as dupdate,
    CAST(TRIM(giveaway) AS STRING) as giveaway,
    CAST(TRIM(givestk) AS STRING) as givestk,
    CAST(bgcount AS FLOAT64) as bgcount,
    CAST(orderno AS INT64) as orderno,
    CAST(TRIM(lat) AS STRING) as lat,
    CAST(TRIM(long) AS STRING) as long,
    CAST(TRIM(mapnote) AS STRING) as mapnote,
    CAST(TRIM(fileupload) AS STRING) as fileupload,
    CAST(TRIM(city) AS STRING) as city,
    CAST(rdosend AS INT64) as rdosend,
    CAST(TRIM(cname) AS STRING) as cname,
    CAST(TRIM(ctel) AS STRING) as ctel,
    CAST(TRIM(caddress) AS STRING) as caddress,
    CAST(TRIM(checknote) AS STRING) as checknote,
    CAST(TRIM(textnote) AS STRING) as textnote,
    CAST(ref_quodetail AS INT64) as ref_quodetail,
    CAST(productgrade AS INT64) as productgrade,
    CAST(fobprice AS FLOAT64) as fobprice,
    CAST(isshow AS INT64) as isshow

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
