config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tbpjaddacc"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY insertdate desc, accname desc, conname desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    CAST(TRIM(pjid) AS STRING) as pjid,
    CAST(TRIM(accid) AS STRING) as accid,
    CAST(TRIM(accname) AS STRING) as accname,
    CAST(TRIM(acctype) AS STRING) as acctype,
    CAST(TRIM(acctype2) AS STRING) as acctype2,
    CAST(TRIM(accpow) AS STRING) as accpow,
    CAST(TRIM(conid) AS STRING) as conid,
    CAST(TRIM(conname) AS STRING) as conname,
    CAST(TRIM(contel) AS STRING) as contel,
    CAST(TRIM(condetail) AS STRING) as condetail,
    CAST(TRIM(uinsert) AS STRING) as uinsert,
    PARSE_DATE('%Y-%m-%d', SUBSTR(insertdate, 1, 10)) AS insertdate,
    CAST(TRIM(textnote) AS STRING) as textnote,
    CAST(TRIM(nickname) AS STRING) as nickname,
    CAST(TRIM(religion) AS STRING) as religion,
    PARSE_DATE('%Y-%m-%d', SUBSTR(birthdate, 1, 10)) AS birthdate,
    CAST(TRIM(lineidper) AS STRING) as lineidper,
    CAST(TRIM(emailper) AS STRING) as emailper,
    CAST(TRIM(idcardper) AS STRING) as idcardper,
    CAST(TRIM(addressper) AS STRING) as addressper,
    CAST(TRIM(country) AS STRING) as country,
    CAST(TRIM(province) AS STRING) as province,
    CAST(TRIM(district) AS STRING) as district,
    CAST(TRIM(sub_district) AS STRING) as sub_district,
    CAST(TRIM(zipcode) AS STRING) as zipcode,
    CAST(TRIM(spousefullname) AS STRING) as spousefullname,
    PARSE_DATE('%Y-%m-%d', SUBSTR(birthdatespouse, 1, 10)) AS birthdatespouse,
    CAST(TRIM(numberofchildren) AS STRING) as numberofchildren,
    CAST(TRIM(favoriteactivity) AS STRING) as favoriteactivity,
    CAST(TRIM(unfavoriteactivity) AS STRING) as unfavoriteactivity,
    CAST(TRIM(trait) AS STRING) as trait

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
