config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tdis_mail"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tdis_mail"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY salename desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(saleid) AS STRING) as saleid,
    CAST(TRIM(spass) AS STRING) as spass,
    CAST(TRIM(salename) AS STRING) as salename,
    CAST(TRIM(salemail) AS STRING) as salemail,
    CAST(TRIM(mail1) AS STRING) as mail1,
    CAST(TRIM(mail2) AS STRING) as mail2,
    CAST(TRIM(mail3) AS STRING) as mail3,
    CAST(TRIM(mail4) AS STRING) as mail4,
    CAST(TRIM(lv) AS STRING) as lv,
    CAST(TRIM(cc1) AS STRING) as cc1,
    CAST(TRIM(cc2) AS STRING) as cc2,
    CAST(TRIM(cc3) AS STRING) as cc3,
    CAST(TRIM(cc4) AS STRING) as cc4,
    CAST(TRIM(cc5) AS STRING) as cc5,
    CAST(TRIM(cc6) AS STRING) as cc6,
    CAST(TRIM(cc7) AS STRING) as cc7,
    CAST(TRIM(cc8) AS STRING) as cc8,
    CAST(TRIM(cc9) AS STRING) as cc9,
    CAST(TRIM(passlv1) AS STRING) as passlv1,
    CAST(TRIM(passlv2) AS STRING) as passlv2,
    CAST(TRIM(passlv3) AS STRING) as passlv3,
    CAST(TRIM(passlv4) AS STRING) as passlv4,
    CAST(TRIM(f1) AS STRING) as f1,
    CAST(TRIM(f2) AS STRING) as f2,
    CAST(TRIM(f3) AS STRING) as f3,
    CAST(TRIM(f4) AS STRING) as f4,
    CAST(TRIM(f5) AS STRING) as f5,
    CAST(TRIM(f6) AS STRING) as f6,
    CAST(TRIM(f7) AS STRING) as f7,
    CAST(TRIM(f8) AS STRING) as f8,
    CAST(TRIM(f9) AS STRING) as f9,
    CAST(TRIM(f10) AS STRING) as f10,
    CAST(TRIM(pum1) AS STRING) as pum1,
    CAST(TRIM(pum2) AS STRING) as pum2,
    CAST(TRIM(pum3) AS STRING) as pum3,
    CAST(TRIM(ppass1) AS STRING) as ppass1,
    CAST(TRIM(ppass2) AS STRING) as ppass2,
    CAST(TRIM(ppass3) AS STRING) as ppass3,
    CAST(TRIM(ma) AS STRING) as ma,
    CAST(TRIM(ta) AS STRING) as ta,
    CAST(TRIM(ceo) AS STRING) as ceo,
    CAST(TRIM(app) AS STRING) as app,
    CAST(TRIM(lv_pum) AS STRING) as lv_pum,
    CAST(TRIM(lv_rp) AS STRING) as lv_rp,
    CAST(TRIM(rp1) AS STRING) as rp1,
    CAST(TRIM(rp2) AS STRING) as rp2,
    CAST(TRIM(rp3) AS STRING) as rp3,
    CAST(TRIM(rpass1) AS STRING) as rpass1,
    CAST(TRIM(rpass2) AS STRING) as rpass2,
    CAST(TRIM(rpass3) AS STRING) as rpass3,
    CAST(TRIM(lv_ele) AS STRING) as lv_ele,
    CAST(TRIM(ele1) AS STRING) as ele1,
    CAST(TRIM(ele2) AS STRING) as ele2,
    CAST(TRIM(ele3) AS STRING) as ele3,
    CAST(TRIM(epass1) AS STRING) as epass1,
    CAST(TRIM(epass2) AS STRING) as epass2,
    CAST(TRIM(epass3) AS STRING) as epass3,
    CAST(TRIM(type) AS STRING) as type,
    CAST(TRIM(menu1) AS STRING) as menu1,
    CAST(TRIM(download) AS STRING) as download,
    CAST(TRIM(pic) AS STRING) as pic,
    CAST(TRIM(lv_boq_lyn) AS STRING) as lv_boq_lyn,
    CAST(active AS INT64) as active

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
