config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["docno","stktype"],
    bigquery: {
        clusterBy: ["docno"]
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = ["docno","stktype"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY sendtime desc) = 1`;
        post_operations_statement = `BEGIN
    ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    NULLIF(CAST(TRIM(docno) AS STRING), '') as docno,
    NULLIF(CAST(TRIM(lv1) AS STRING), '') as lv1,
    NULLIF(CAST(TRIM(lv2) AS STRING), '') as lv2,
    NULLIF(CAST(TRIM(lv3) AS STRING), '') as lv3,
    NULLIF(CAST(TRIM(note1) AS STRING), '') as note1,
    NULLIF(CAST(TRIM(note2) AS STRING), '') as note2,
    NULLIF(CAST(TRIM(note3) AS STRING), '') as note3,
    NULLIF(CAST(TRIM(u1) AS STRING), '') as u1,
    NULLIF(CAST(TRIM(u2) AS STRING), '') as u2,
    NULLIF(CAST(TRIM(u3) AS STRING), '') as u3,
    NULLIF(CAST(TRIM(d1) AS STRING), '') as d1,
    NULLIF(CAST(TRIM(d2) AS STRING), '') as d2,
    NULLIF(CAST(TRIM(d3) AS STRING), '') as d3,
    NULLIF(CAST(TRIM(sendto) AS STRING), '') as sendto,
    NULLIF(CAST(TRIM(sendtime) AS STRING), '') as sendtime,
    NULLIF(CAST(TRIM(comment) AS STRING), '') as comment,
    NULLIF(CAST(TRIM(stktype) AS STRING), '') as stktype

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
