config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: ["company_id", "docno","stktype"],
    bigquery: {
        clusterBy: ["company_id", "docno"]
    },
}

js {
    // Define table references
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    // Build source table reference
    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    // Keep existing logic
    const pk_key = ["company_id", "docno","stktype"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY sendtime desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.cleanString('docno')} as docno,
    ${databuffet.cleanString('lv1')} as lv1,
    ${databuffet.cleanString('lv2')} as lv2,
    ${databuffet.cleanString('lv3')} as lv3,
    ${databuffet.cleanString('note1')} as note1,
    ${databuffet.cleanString('note2')} as note2,
    ${databuffet.cleanString('note3')} as note3,
    ${databuffet.cleanString('u1')} as u1,
    ${databuffet.cleanString('u2')} as u2,
    ${databuffet.cleanString('u3')} as u3,
    ${databuffet.cleanString('d1')} as d1,
    ${databuffet.cleanString('d2')} as d2,
    ${databuffet.cleanString('d3')} as d3,
    ${databuffet.cleanString('sendto')} as sendto,
    ${databuffet.cleanString('sendtime')} as sendtime,
    ${databuffet.cleanString('comment')} as comment,
    ${databuffet.cleanString('stktype')} as stktype

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
