config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tdis_approveqt"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tdis_approveqt"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY sendtime desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(docno) AS STRING) as docno,
    CAST(TRIM(lv1) AS STRING) as lv1,
    CAST(TRIM(lv2) AS STRING) as lv2,
    CAST(TRIM(lv3) AS STRING) as lv3,
    CAST(TRIM(note1) AS STRING) as note1,
    CAST(TRIM(note2) AS STRING) as note2,
    CAST(TRIM(note3) AS STRING) as note3,
    CAST(TRIM(u1) AS STRING) as u1,
    CAST(TRIM(u2) AS STRING) as u2,
    CAST(TRIM(u3) AS STRING) as u3,
    CAST(TRIM(d1) AS STRING) as d1,
    CAST(TRIM(d2) AS STRING) as d2,
    CAST(TRIM(d3) AS STRING) as d3,
    CAST(TRIM(sendto) AS STRING) as sendto,
    CAST(TRIM(sendtime) AS STRING) as sendtime,
    CAST(TRIM(comment) AS STRING) as comment,
    CAST(TRIM(stktype) AS STRING) as stktype

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
