config {
    type: "table",
    schema: databuffet.VALIDATED_MAC5,
    dependencies: ["validated_schema_mac5", "create_all_table_raw_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [],
    bigquery: {
        clusterBy: ["company_id"]
    },
}

js {
    const sourceTable = {
        database: databuffet.DATABASE,
        schema: databuffet.RAW_MAC5_AG01,
        name: name(),
    };

    const sourceTableRef = `${sourceTable.database}.${sourceTable.schema}.${sourceTable.name}`;

    const pk_key = []

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY file_load_datetime desc) = 1`;
        post_operations_statement = `
BEGIN
    DECLARE retry_count INT64 DEFAULT 0;
    DECLARE max_retries INT64 DEFAULT 10;
    DECLARE success BOOL DEFAULT FALSE;

    WHILE retry_count < max_retries AND NOT success DO
        BEGIN
            ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
            ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;
            SET success = TRUE;
        EXCEPTION WHEN ERROR THEN
            SET retry_count = retry_count + 1;
        END;
    END WHILE;
END;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

WITH all_sources AS (
  SELECT 'ag01' AS company_id,
    ${databuffet.functionData.cleanString('fdocument')} as fdocument,
    ${databuffet.functionData.cleanString('fserial_no')} as fserial_no,
    ${databuffet.functionData.cleanString('fcode')} as fcode,
    ${databuffet.functionData.cleanString('fvehicle')} as fvehicle,
    ${databuffet.functionData.cleanString('fitem')} as fitem,
    ${databuffet.functionData.cleanString('fitem2')} as fitem2,
    qty2,
    ${databuffet.functionData.cleanString('s1')} as s1,
    ${databuffet.functionData.cleanString('s2')} as s2,
    ${databuffet.functionData.cleanString('s3')} as s3,
    ${databuffet.functionData.cleanString('stt')} as stt,
    ${databuffet.functionData.cleanString('username')} as username

  FROM
    `${sourceTableRef}`
)
SELECT * FROM all_sources
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
