config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: [...databuffet.dependencies[databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5]],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tmp_pdf_sansiri"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["tmp_pdf_sansiri"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY vendorname desc, sitename desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(TRIM(crdate) AS STRING) as crdate,
    CAST(TRIM(vendorno) AS STRING) as vendorno,
    CAST(TRIM(vendorname) AS STRING) as vendorname,
    CAST(TRIM(newpo) AS STRING) as newpo,
    CAST(TRIM(pono) AS STRING) as pono,
    CAST(TRIM(podate) AS STRING) as podate,
    CAST(TRIM(potype) AS STRING) as potype,
    CAST(TRIM(deliverydate) AS STRING) as deliverydate,
    CAST(TRIM(siteno) AS STRING) as siteno,
    CAST(TRIM(sitename) AS STRING) as sitename,
    CAST(TRIM(siteaddress) AS STRING) as siteaddress,
    CAST(TRIM(totalqty) AS STRING) as totalqty,
    CAST(TRIM(totalamount) AS STRING) as totalamount,
    CAST(TRIM(totalitem) AS STRING) as totalitem,
    CAST(TRIM(cancelpo) AS STRING) as cancelpo,
    CAST(TRIM(termcode) AS STRING) as termcode,
    CAST(TRIM(poremark) AS STRING) as poremark,
    CAST(TRIM(quotationno) AS STRING) as quotationno,
    CAST(TRIM(quotationdate) AS STRING) as quotationdate,
    CAST(TRIM(poitemno) AS STRING) as poitemno,
    CAST(TRIM(artno) AS STRING) as artno,
    CAST(TRIM(artdesc) AS STRING) as artdesc,
    CAST(TRIM(hpeancode) AS STRING) as hpeancode,
    CAST(TRIM(vdeancode) AS STRING) as vdeancode,
    CAST(TRIM(vdproductname) AS STRING) as vdproductname,
    CAST(TRIM(qty) AS STRING) as qty,
    CAST(TRIM(purchunit) AS STRING) as purchunit,
    CAST(TRIM(price) AS STRING) as price,
    CAST(TRIM(qtyperunit) AS STRING) as qtyperunit,
    CAST(TRIM(priceperunit) AS STRING) as priceperunit,
    CAST(TRIM(priceunit) AS STRING) as priceunit,
    CAST(TRIM(packsize) AS STRING) as packsize,
    CAST(TRIM(articleremark) AS STRING) as articleremark,
    CAST(TRIM(freegoodsflag) AS STRING) as freegoodsflag,
    CAST(TRIM(stk) AS STRING) as stk,
    CAST(TRIM(novat) AS STRING) as novat,
    CAST(TRIM(attfile) AS STRING) as attfile,
    CAST(TRIM(statusticket) AS STRING) as statusticket,
    CAST(TRIM(duedate) AS STRING) as duedate,
    CAST(TRIM(reciver) AS STRING) as reciver,
    CAST(TRIM(deladd) AS STRING) as deladd,
    CAST(TRIM(que) AS STRING) as que,
    CAST(TRIM(delvname) AS STRING) as delvname,
    CAST(TRIM(delvtel) AS STRING) as delvtel,
    CAST(TRIM(credit) AS STRING) as credit,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(dinsert, 1, 19)) as dinsert,
    CAST(TRIM(status) AS STRING) as status

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
