config {
    type: "table",
    schema: databuffet.VALIDATED_SCHEMA + "_" + databuffet.SOURCE_MAC5,
    dependencies: ["validated_schema_mac5"],
    tags: [databuffet.TAG_VALIDATED, databuffet.TAG_VALIDATED_FULL],
    uniqueKey: [...databuffet.primaryKeys[databuffet.SOURCE_MAC5]["userloginanyprogram"]],
    bigquery: {
        clusterBy: []
    },
}

js {
    const project_id = databuffet.DATABASE
    const dataset_id = databuffet.RAW_SCHEMA + "_" + databuffet.SOURCE_MAC5
    const table_id = name()
    const pk_key = databuffet.primaryKeys[databuffet.SOURCE_MAC5]["userloginanyprogram"]

    let partition_statement, post_operations_statement;

    if (pk_key && pk_key.length > 0) {
        partition_statement = `QUALIFY ROW_NUMBER() OVER(PARTITION BY ${pk_key} ORDER BY username desc, name desc) = 1`;
        post_operations_statement = `ALTER TABLE ${self()} DROP PRIMARY KEY IF EXISTS;
    ALTER TABLE ${self()} ADD PRIMARY KEY (${pk_key}) NOT ENFORCED;`;

    } else {
        partition_statement = "";
        post_operations_statement = "";
    }
}

SELECT
    CAST(id AS INT64) as id,
    NULLIF(CAST(TRIM(username) AS STRING), '') as username,
    NULLIF(CAST(TRIM(password) AS STRING), '') as password,
    NULLIF(CAST(TRIM(actionapp) AS STRING), '') as actionapp,
    NULLIF(CAST(TRIM(name) AS STRING), '') as name,
    NULLIF(CAST(TRIM(notes) AS STRING), '') as notes,
    NULLIF(CAST(TRIM(department) AS STRING), '') as department,
    NULLIF(CAST(TRIM(levelaction) AS STRING), '') as levelaction,
    NULLIF(CAST(TRIM(email) AS STRING), '') as email,
    NULLIF(CAST(TRIM(token) AS STRING), '') as token,
    PARSE_DATETIME('%Y-%m-%d %H:%M:%S', SUBSTR(tokenexpiry, 1, 19)) AS tokenexpiry,
    CAST(istokenvalid AS INT64) as istokenvalid

FROM
  `${project_id}.${dataset_id}.${table_id}`
${partition_statement}

pre_operations {
}

post_operations {
    ${ when(!incremental(), post_operations_statement) }
}
